export const timelineEvents = [
  {
    year: 1960,
    era: "early",
    title: "Military Career & Early EM Research",
    type: "career",
    description: "Lt. Col. Thomas E. Bearden begins his military career, developing early interest in electromagnetic theory and Soviet weapons research. His background in nuclear engineering and systems analysis shapes his unorthodox theoretical approach.",
    concepts: [],
    color: "#6b7280",
  },
  {
    year: 1970,
    era: "early",
    title: "Discovery of Scalar EM Principles",
    type: "theory",
    description: "Bearden begins formulating extensions to Maxwell's equations, proposing that longitudinal 'scalar' waves in the vacuum potential carry structured information. He argues these were deliberately removed from classical EM theory in the 1880s.",
    concepts: ["scalar_em", "maxwell_equations"],
    color: "#3b82f6",
  },
  {
    year: 1975,
    era: "development",
    title: "Soviet Scalar Weapons Intelligence",
    type: "geopolitical",
    description: "Bearden catalogues alleged Soviet scalar EM weapons programs, claiming the USSR achieved practical scalar weaponry. He links anomalous radar returns and unexplained phenomena over the Pacific to Soviet scalar transmitters.",
    concepts: ["weather_warfare", "scalar_em"],
    color: "#ef4444",
  },
  {
    year: 1978,
    era: "development",
    title: "Kaznacheyev Experiments Referenced",
    type: "theory",
    description: "Bearden integrates Soviet biophysicist Vlail Kaznacheyev's cytopathogenic effect experiments into his scalar EM framework, arguing they prove disease is fundamentally electromagnetic and can be transmitted at a distance through UV photon emission.",
    concepts: ["kaznacheyev", "biological_warfare"],
    color: "#22c55e",
  },
  {
    year: 1980,
    era: "development",
    title: "Rife Technology & Frequency Medicine",
    type: "history",
    description: "Bearden connects Royal Raymond Rife's 1930s prismatic microscope work and mortal oscillatory rate research to scalar EM principles, arguing Rife had independently discovered bio-scalar resonance decades earlier.",
    concepts: ["rife_microscope", "kindling"],
    color: "#f59e0b",
  },
  {
    year: 1981,
    era: "publication",
    title: "Gravitobiology & Kindling Theory",
    type: "publication",
    description: "Bearden formalizes the 'kindling' concept — charging atomic nuclei with dynamically structured biopotentials. He links this to negentropy in living systems, proposing life itself is a self-kindling bioelectromagnetic phenomenon.",
    concepts: ["kindling", "negentropy"],
    color: "#22c55e",
  },
  {
    year: 1982,
    era: "publication",
    title: "Comments on the New Tesla Electromagnetics, Part II (1982)",
    type: "publication",
    description: "Bearden formalizes the scalar wave / vacuum potential framework. He argues the vacuum has an absolute electrical potential of ~200 million volts and is composed of pure massless charge. A 'scalar wave' can propagate through this vacuum with no E-field or H-field — only a scalar phi-field difference. He distinguishes massless charge flow (no work done, no V=IR) from conventional mass-current electricity, and shows that the mechanical spin of electrons 'couples' independent scalar phi-fields into vector EM waves.",
    concepts: ["scalar_em", "maxwell_equations", "negentropy"],
    color: "#3b82f6",
  },
  {
    year: 1982,
    era: "publication",
    title: "Dirac Sea & Vacuum Oscillation — Free Energy Mechanism",
    type: "theory",
    description: "In Part II, Bearden proposes a concrete free-energy extraction mechanism: oscillating the vacuum potential itself causes partial 'unstripping' of Dirac sea negative-energy wells, lifting electrons into the circuit. The resulting voltage and current are 'essentially limitless' if proper vacuum oscillation is maintained. Standard EM theory fails to recognize this because it assumes vacuum potential is zero and conflates massless charge with charged mass.",
    concepts: ["scalar_em", "negentropy", "maxwell_equations"],
    color: "#3b82f6",
  },
  {
    year: 1982,
    era: "development",
    title: "Global Free Energy Research Survey (Schaffranke / Toronto)",
    type: "geopolitical",
    description: "Dr. Rolf Schaffranke's 'Overture to a New Age Technology' (included in the 1984 Tesla Book Co. volume) surveys international scalar/gravity-field energy prototypes: a West German flux-motor motorcycle running 20,000 km fuellessly; the French-German-Swiss Kromrey G-field generator delivering 700W at >100% efficiency; Japan's tachion beam research (Prof. Seike / Hitachi); Denmark's 300%-efficient 5-coil transformer; and the Searl Levity Disc. Bearden integrates these as independent corroboration of vacuum energy engineering.",
    concepts: ["scalar_em", "negentropy"],
    color: "#f59e0b",
  },
  {
    year: 1984,
    era: "publication",
    title: "The New Tesla Electromagnetics & Secrets of Electrical Free Energy (Tesla Book Co.)",
    type: "publication",
    description: "Published by Tesla Book Company (1984), this volume collects Bearden's scalar EM and free-energy papers including 'Comments on the New Tesla Electromagnetics Parts I & II' (1982). Contents include: Historical Background of Scalar EM Weapons, Phase Conjugate Wave characteristics, and Schaffranke's global survey of over-unity prototypes. The book argues present EM theory is a restricted special case of a more fundamental electromagnetics discovered by Tesla, and that the vacuum's massless charge is an untapped energy source.",
    concepts: ["scalar_em", "maxwell_equations", "negentropy"],
    color: "#3b82f6",
  },
  {
    year: 1984,
    era: "publication",
    title: "AIDS: Biological Warfare (Tesla Book Co.)",
    type: "publication",
    description: "Publication of Bearden's controversial book arguing AIDS was deliberately engineered using scalar EM techniques applied to viral DNA. ISBN 0-914119-04-4. Bearden claims the kindling effect can 'program' viruses with electromagnetically transmissible cytopathogenic patterns.",
    concepts: ["biological_warfare", "kindling", "kaznacheyev"],
    color: "#ef4444",
  },
  {
    year: 1986,
    era: "publication",
    title: "Chernobyl & Scalar EM Weapons",
    type: "geopolitical",
    description: "Following the Chernobyl nuclear disaster, Bearden alleges the accident was caused by the tail-end discharge of a giant standing scalar EM wave, claiming Soviet safety circuits were bypassed electromagnetically.",
    concepts: ["scalar_em", "weather_warfare"],
    color: "#ef4444",
  },
  {
    year: 1988,
    era: "publication",
    title: "Analysis of Scalar/EM Technology (1990 ed.)",
    type: "publication",
    description: "Bearden's comprehensive technical analysis covering historical background of scalar EM weapons, phase conjugate wave characteristics, and the nested modulation hierarchy (L³→L²→LT→T). Published by Tesla Book Company.",
    concepts: ["scalar_em", "maxwell_equations", "neutrino_field", "mind_field"],
    color: "#3b82f6",
  },
  {
    year: 1990,
    era: "mature",
    title: "Hyperspatial Engineering & Bioframe Theory",
    type: "theory",
    description: "Bearden elaborates the bioframe / orthorotation model, describing living systems as existing across multiple higher-dimensional reference frames. He proposes that mind exists in the T (time) dimension, only three orthorotations from ordinary physical reality.",
    concepts: ["bioframe", "mind_field", "neutrino_field"],
    color: "#a855f7",
  },
  {
    year: 1993,
    era: "mature",
    title: "Consciousness Hierarchy & Temporal Logic",
    type: "theory",
    description: "Bearden extends Aristotelian logic with temporal accounting to describe consciousness layers from the personal unconscious through family, city, race, and species to the universal. He proposes a fifth law of logic integrating 'oneness' with classical identity.",
    concepts: ["consciousness", "aristotle_logic"],
    color: "#06b6d4",
  },
  {
    year: 2002,
    era: "mature",
    title: "Energy from the Vacuum",
    type: "publication",
    description: "Major synthesis work connecting scalar EM theory to free energy extraction from the vacuum. Bearden argues the vacuum is a vast reservoir of ordered scalar EM energy that can be tapped via resonant scalar transmitters — unifying his physics, biology, and consciousness models.",
    concepts: ["scalar_em", "negentropy", "mind_field"],
    color: "#3b82f6",
  },
];

export const eraLabels = {
  early: { label: "Early Work", color: "#6b7280" },
  development: { label: "Framework Development", color: "#3b82f6" },
  publication: { label: "Key Publications", color: "#f59e0b" },
  mature: { label: "Mature Theory", color: "#a855f7" },
};

export const typeIcons = {
  career: "🎖️",
  theory: "🔬",
  geopolitical: "⚡",
  publication: "📖",
  history: "🔭",
};