export const timelineEvents = [
  {
    year: 1960,
    era: "early",
    title: "Military Career & Early EM Research",
    type: "career",
    description: "Lt. Col. Thomas E. Bearden begins his military career, developing early interest in electromagnetic theory and Soviet weapons research. His background in nuclear engineering and systems analysis shapes his unorthodox theoretical approach.",
    concepts: [],
    color: "#6b7280",
  },
  {
    year: 1970,
    era: "early",
    title: "Discovery of Scalar EM Principles",
    type: "theory",
    description: "Bearden begins formulating extensions to Maxwell's equations, proposing that longitudinal 'scalar' waves in the vacuum potential carry structured information. He argues these were deliberately removed from classical EM theory in the 1880s.",
    concepts: ["scalar_em", "maxwell_equations"],
    color: "#3b82f6",
  },
  {
    year: 1975,
    era: "development",
    title: "Soviet Scalar Weapons Intelligence",
    type: "geopolitical",
    description: "Bearden catalogues alleged Soviet scalar EM weapons programs, claiming the USSR achieved practical scalar weaponry. He links anomalous radar returns and unexplained phenomena over the Pacific to Soviet scalar transmitters.",
    concepts: ["weather_warfare", "scalar_em"],
    color: "#ef4444",
  },
  {
    year: 1978,
    era: "development",
    title: "Kaznacheyev Experiments Referenced",
    type: "theory",
    description: "Bearden integrates Soviet biophysicist Vlail Kaznacheyev's cytopathogenic effect experiments into his scalar EM framework, arguing they prove disease is fundamentally electromagnetic and can be transmitted at a distance through UV photon emission.",
    concepts: ["kaznacheyev", "biological_warfare"],
    color: "#22c55e",
  },
  {
    year: 1980,
    era: "development",
    title: "Rife Technology & Frequency Medicine",
    type: "history",
    description: "Bearden connects Royal Raymond Rife's 1930s prismatic microscope work and mortal oscillatory rate research to scalar EM principles, arguing Rife had independently discovered bio-scalar resonance decades earlier.",
    concepts: ["rife_microscope", "kindling"],
    color: "#f59e0b",
  },
  {
    year: 1981,
    era: "publication",
    title: "Gravitobiology & Kindling Theory",
    type: "publication",
    description: "Bearden formalizes the 'kindling' concept — charging atomic nuclei with dynamically structured biopotentials. He links this to negentropy in living systems, proposing life itself is a self-kindling bioelectromagnetic phenomenon.",
    concepts: ["kindling", "negentropy"],
    color: "#22c55e",
  },
  {
    year: 1984,
    era: "publication",
    title: "AIDS: Biological Warfare (Tesla Book Co.)",
    type: "publication",
    description: "Publication of Bearden's controversial book arguing AIDS was deliberately engineered using scalar EM techniques applied to viral DNA. ISBN 0-914119-04-4. Bearden claims the kindling effect can 'program' viruses with electromagnetically transmissible cytopathogenic patterns.",
    concepts: ["biological_warfare", "kindling", "kaznacheyev"],
    color: "#ef4444",
  },
  {
    year: 1986,
    era: "publication",
    title: "Chernobyl & Scalar EM Weapons",
    type: "geopolitical",
    description: "Following the Chernobyl nuclear disaster, Bearden alleges the accident was caused by the tail-end discharge of a giant standing scalar EM wave, claiming Soviet safety circuits were bypassed electromagnetically.",
    concepts: ["scalar_em", "weather_warfare"],
    color: "#ef4444",
  },
  {
    year: 1988,
    era: "publication",
    title: "Analysis of Scalar/EM Technology (1990 ed.)",
    type: "publication",
    description: "Bearden's comprehensive technical analysis covering historical background of scalar EM weapons, phase conjugate wave characteristics, and the nested modulation hierarchy (L³→L²→LT→T). Published by Tesla Book Company.",
    concepts: ["scalar_em", "maxwell_equations", "neutrino_field", "mind_field"],
    color: "#3b82f6",
  },
  {
    year: 1990,
    era: "mature",
    title: "Hyperspatial Engineering & Bioframe Theory",
    type: "theory",
    description: "Bearden elaborates the bioframe / orthorotation model, describing living systems as existing across multiple higher-dimensional reference frames. He proposes that mind exists in the T (time) dimension, only three orthorotations from ordinary physical reality.",
    concepts: ["bioframe", "mind_field", "neutrino_field"],
    color: "#a855f7",
  },
  {
    year: 1993,
    era: "mature",
    title: "Consciousness Hierarchy & Temporal Logic",
    type: "theory",
    description: "Bearden extends Aristotelian logic with temporal accounting to describe consciousness layers from the personal unconscious through family, city, race, and species to the universal. He proposes a fifth law of logic integrating 'oneness' with classical identity.",
    concepts: ["consciousness", "aristotle_logic"],
    color: "#06b6d4",
  },
  {
    year: 2002,
    era: "mature",
    title: "Energy from the Vacuum",
    type: "publication",
    description: "Major synthesis work connecting scalar EM theory to free energy extraction from the vacuum. Bearden argues the vacuum is a vast reservoir of ordered scalar EM energy that can be tapped via resonant scalar transmitters — unifying his physics, biology, and consciousness models.",
    concepts: ["scalar_em", "negentropy", "mind_field"],
    color: "#3b82f6",
  },
];

export const eraLabels = {
  early: { label: "Early Work", color: "#6b7280" },
  development: { label: "Framework Development", color: "#3b82f6" },
  publication: { label: "Key Publications", color: "#f59e0b" },
  mature: { label: "Mature Theory", color: "#a855f7" },
};

export const typeIcons = {
  career: "🎖️",
  theory: "🔬",
  geopolitical: "⚡",
  publication: "📖",
  history: "🔭",
};