export const timelineEvents = [
  {
    year: 1960,
    era: "early",
    title: "Military Career & Early EM Research",
    type: "career",
    description: "Lt. Col. Thomas E. Bearden begins his military career, developing early interest in electromagnetic theory and Soviet weapons research. His background in nuclear engineering and systems analysis shapes his unorthodox theoretical approach.",
    concepts: [],
    color: "#6b7280",
  },
  {
    year: 1970,
    era: "early",
    title: "Discovery of Scalar EM Principles",
    type: "theory",
    description: "Bearden begins formulating extensions to Maxwell's equations, proposing that longitudinal 'scalar' waves in the vacuum potential carry structured information. He argues these were deliberately removed from classical EM theory in the 1880s.",
    concepts: ["scalar_em", "maxwell_equations"],
    color: "#3b82f6",
  },
  {
    year: 1975,
    era: "development",
    title: "Soviet Scalar Weapons Intelligence",
    type: "geopolitical",
    description: "Bearden catalogues alleged Soviet scalar EM weapons programs, claiming the USSR achieved practical scalar weaponry. He links anomalous radar returns and unexplained phenomena over the Pacific to Soviet scalar transmitters.",
    concepts: ["weather_warfare", "scalar_em"],
    color: "#ef4444",
  },
  {
    year: 1978,
    era: "development",
    title: "Kaznacheyev Experiments Referenced",
    type: "theory",
    description: "Bearden integrates Soviet biophysicist Vlail Kaznacheyev's cytopathogenic effect experiments into his scalar EM framework, arguing they prove disease is fundamentally electromagnetic and can be transmitted at a distance through UV photon emission.",
    concepts: ["kaznacheyev", "biological_warfare"],
    color: "#22c55e",
  },
  {
    year: 1980,
    era: "development",
    title: "Rife Technology & Frequency Medicine",
    type: "history",
    description: "Bearden connects Royal Raymond Rife's 1930s prismatic microscope work and mortal oscillatory rate research to scalar EM principles, arguing Rife had independently discovered bio-scalar resonance decades earlier.",
    concepts: ["rife_microscope", "kindling"],
    color: "#f59e0b",
  },
  {
    year: 1981,
    era: "publication",
    title: "Gravitobiology & Kindling Theory",
    type: "publication",
    description: "Bearden formalizes the 'kindling' concept — charging atomic nuclei with dynamically structured biopotentials. He links this to negentropy in living systems, proposing life itself is a self-kindling bioelectromagnetic phenomenon.",
    concepts: ["kindling", "negentropy"],
    color: "#22c55e",
  },
  {
    year: 1982,
    era: "publication",
    title: "Comments on the New Tesla Electromagnetics, Part II (1982)",
    type: "publication",
    description: "Bearden formalizes the scalar wave / vacuum potential framework. He argues the vacuum has an absolute electrical potential of ~200 million volts and is composed of pure massless charge. A 'scalar wave' can propagate through this vacuum with no E-field or H-field — only a scalar phi-field difference. He distinguishes massless charge flow (no work done, no V=IR) from conventional mass-current electricity, and shows that the mechanical spin of electrons 'couples' independent scalar phi-fields into vector EM waves.",
    concepts: ["scalar_em", "maxwell_equations", "negentropy"],
    color: "#3b82f6",
  },
  {
    year: 1982,
    era: "publication",
    title: "Dirac Sea & Vacuum Oscillation — Free Energy Mechanism",
    type: "theory",
    description: "In Part II, Bearden proposes a concrete free-energy extraction mechanism: oscillating the vacuum potential itself causes partial 'unstripping' of Dirac sea negative-energy wells, lifting electrons into the circuit. The resulting voltage and current are 'essentially limitless' if proper vacuum oscillation is maintained. Standard EM theory fails to recognize this because it assumes vacuum potential is zero and conflates massless charge with charged mass.",
    concepts: ["scalar_em", "negentropy", "maxwell_equations"],
    color: "#3b82f6",
  },
  {
    year: 1982,
    era: "development",
    title: "Global Free Energy Research Survey (Schaffranke / Toronto)",
    type: "geopolitical",
    description: "Dr. Rolf Schaffranke's 'Overture to a New Age Technology' (included in the 1984 Tesla Book Co. volume) surveys international scalar/gravity-field energy prototypes: a West German flux-motor motorcycle running 20,000 km fuellessly; the French-German-Swiss Kromrey G-field generator delivering 700W at >100% efficiency; Japan's tachion beam research (Prof. Seike / Hitachi); Denmark's 300%-efficient 5-coil transformer; and the Searl Levity Disc. Bearden integrates these as independent corroboration of vacuum energy engineering.",
    concepts: ["scalar_em", "negentropy"],
    color: "#f59e0b",
  },
  {
    year: 1983,
    era: "publication",
    title: "Toward a New Electromagnetics Part 3: Clarifying the Vector Concept",
    type: "publication",
    description: "Bearden publishes Part 3, introducing his taxonomy of four distinct vector types: (1) Massless Spatial — the geometer's vector; (2) Mass System — the mechanic's vector; (3) Charged Mass System — the electrician's vector; (4) Charged Spatial System — the advanced electrician's vector. He argues that conflating these four types into one symbol is the foundational error of modern physics, responsible for the vacuum energy blind spot. He demonstrates that force is an effect (F ≡ [Mā + ṁv̄]), not a cause, and that neither E-fields nor B-fields exist in the vacuum — only massless charge gradients.",
    concepts: ["vector_concept", "force_as_effect", "scalar_em", "maxwell_equations"],
    color: "#3b82f6",
  },
  {
    year: 1983,
    era: "publication",
    title: "Toward a New Electromagnetics Part 4: Vectors and Mechanisms Clarified",
    type: "publication",
    description: "Part 4 extends the vector taxonomy to practical mechanisms: the anenergy pump (free phi-field energy extraction via trapped charge), the energy bottle (two-transmitter scalar EM interference zone that captures energy with no reflection), scalar longitudinal waves (Ē=0, B̄=0, ∇φ≠−Ē), wave translation between transverse and longitudinal forms via nonlinear media, standing scalar wave patterns in magnetic materials, and scalar pulse radar (range from scalar-vs-Hertz pulse time difference). First systematic treatment of scalar EM weapons architecture with circuit diagrams.",
    concepts: ["anenergy", "energy_bottle", "scalar_longitudinal", "vacuum_structure", "weather_warfare"],
    color: "#3b82f6",
  },
  {
    year: 1984,
    era: "publication",
    title: "The New Tesla Electromagnetics & Secrets of Electrical Free Energy (Tesla Book Co.)",
    type: "publication",
    description: "Published by Tesla Book Company (1984), this volume collects Bearden's scalar EM and free-energy papers including 'Comments on the New Tesla Electromagnetics Parts I & II' (1982). Contents include: Historical Background of Scalar EM Weapons, Phase Conjugate Wave characteristics, and Schaffranke's global survey of over-unity prototypes. The book argues present EM theory is a restricted special case of a more fundamental electromagnetics discovered by Tesla, and that the vacuum's massless charge is an untapped energy source.",
    concepts: ["scalar_em", "maxwell_equations", "negentropy"],
    color: "#3b82f6",
  },
  {
    year: 1984,
    era: "publication",
    title: "AIDS: Biological Warfare (Tesla Book Co.)",
    type: "publication",
    description: "Publication of Bearden's controversial book arguing AIDS was deliberately engineered using scalar EM techniques applied to viral DNA. ISBN 0-914119-04-4. Bearden claims the kindling effect can 'program' viruses with electromagnetically transmissible cytopathogenic patterns.",
    concepts: ["biological_warfare", "kindling", "kaznacheyev"],
    color: "#ef4444",
  },
  {
    year: 1985,
    era: "development",
    title: "Arrow DC-8 / China Airlines 006 — EM Missile Analysis",
    type: "geopolitical",
    description: "Bearden analyzes two 1985 aviation disasters as EM weapon strikes. The Arrow Air DC-8 crash at Gander (Dec 12, 1985): Bearden's annotated flight recorder data shows electrical spikes on two independent sensors consistent with an EM missile strike during liftoff rotation, followed by graviton charging of atomic nuclei, electrostatic cooling of engine combustion, explosive plastics ignition, and graviton radiation decay. China Airlines Flight 006 (Feb 19, 1985): engines disabled in sequence consistent with scalar EM interference, jet drops 30,000 ft. Both are documented with original Figure 21, 22, 23 diagrams.",
    concepts: ["soviet_woodpecker", "em_biological_warfare", "scalar_em", "kindling"],
    color: "#ef4444",
  },
  {
    year: 1986,
    era: "publication",
    title: "Chernobyl & Scalar EM Weapons",
    type: "geopolitical",
    description: "Following the Chernobyl nuclear disaster, Bearden alleges the accident was caused by the tail-end discharge of a giant standing scalar EM wave, claiming Soviet safety circuits were bypassed electromagnetically.",
    concepts: ["scalar_em", "weather_warfare"],
    color: "#ef4444",
  },
  {
    year: 1988,
    era: "publication",
    title: "Gravitobiology First Edition (1988/1991)",
    type: "publication",
    description: "Bearden's landmark synthesis of EM and gravitational field theory applied to living systems. Introduces: gravitons as coupled photon/antiphoton spin-2 pairs; Whittaker standing potential waves as the hidden variable structure of the vacuum; the quantum potential as a non-local EM information carrier; Soviet Woodpecker signals as scalar EM biological warfare delivery systems; EM trigger windows for disease induction; morphogenetic field as species-level quantum potential; and gravitobiological mechanisms for evolution and the Gaia hypothesis. Published by Tesla Book Company; 2019 edition by Energetic Productions / Cheniere Media.",
    concepts: ["gravitobiology", "graviton", "quantum_potential", "soviet_woodpecker", "em_biological_warfare", "morphogenetic_field"],
    color: "#22c55e",
  },
  {
    year: 1988,
    era: "publication",
    title: "Analysis of Scalar/EM Technology (1990 ed.)",
    type: "publication",
    description: "Bearden's comprehensive technical analysis covering historical background of scalar EM weapons, phase conjugate wave characteristics, and the nested modulation hierarchy (L³→L²→LT→T). Published by Tesla Book Company.",
    concepts: ["scalar_em", "maxwell_equations", "neutrino_field", "mind_field"],
    color: "#3b82f6",
  },
  {
    year: 1990,
    era: "mature",
    title: "Hyperspatial Engineering & Bioframe Theory",
    type: "theory",
    description: "Bearden elaborates the bioframe / orthorotation model, describing living systems as existing across multiple higher-dimensional reference frames. He proposes that mind exists in the T (time) dimension, only three orthorotations from ordinary physical reality.",
    concepts: ["bioframe", "mind_field", "neutrino_field"],
    color: "#a855f7",
  },
  {
    year: 1993,
    era: "mature",
    title: "Consciousness Hierarchy & Temporal Logic",
    type: "theory",
    description: "Bearden extends Aristotelian logic with temporal accounting to describe consciousness layers from the personal unconscious through family, city, race, and species to the universal. He proposes a fifth law of logic integrating 'oneness' with classical identity.",
    concepts: ["consciousness", "aristotle_logic"],
    color: "#06b6d4",
  },
  {
    year: 1930,
    era: "early",
    title: "T.H. Moray Sea-of-Energy Device — 50kW Demonstration",
    type: "history",
    description: "Thomas Henry Moray demonstrates his 'Sea-of-Energy' vacuum extraction device in Salt Lake City. Photographs document a compact valve/tube unit powering a panel of ~30 incandescent bulbs (estimated 50kW) with no external power connection. Multiple independent witnesses including engineers sign affidavits. The device is later destroyed by a Soviet agent who infiltrated the lab. Bearden's anenergy pump framework (Part 4, 1983) provides the first rigorous theoretical explanation of the Moray mechanism: oscillated phi-application at resonance produces steady-state Moray emission from the vacuum.",
    concepts: ["anenergy", "vacuum_structure", "negentropy"],
    color: "#f59e0b",
  },
  {
    year: 1965,
    era: "development",
    title: "Prioré Device — French Government-Funded EM Cancer Cure",
    type: "history",
    description: "Antoine Prioré (Bordeaux, France) demonstrates his multichannel EM modulation device to French government scientists. The device reportedly cures terminal cancers in laboratory animals; multiple documented experimental series with official French scientific witnesses. The French Ministry of Defense and CNRS fund research. After Prioré's death the program is terminated. Bearden's Fig. 10 (Excalibur Briefing) documents the exact signal architecture: multichannel modulation F₁/F₂/F₃ → derivative carrier/modulator → primary carrier output Fz, mapped to the S'/S''/S''' hyperspatial hierarchy.",
    concepts: ["kindling", "negentropy", "bioframe"],
    color: "#22c55e",
  },
  {
    year: 1980,
    era: "publication",
    title: "Excalibur Briefing — 1st Edition (1980)",
    type: "publication",
    description: "Bearden publishes his most accessible synthesis: UFO phenomena, cattle mutilations, thought photography, psychic surgery, and paranormal events explained via the clustered orthogonal worlds model (S/S'/S''/S''') and nested modulation hierarchy. Introduces the 4th Law of Logic (binocular identity of exact opposites), the inception/intent mechanics of free will (Fig. 25), the life/death/reincarnation model (Fig. 24), and a rigorous hyperspatial framework for all anomalous phenomena. Published by Strawberry Hill Press; revised and expanded 2nd edition 1988 by Tesla Book Company (ISBN 0-89407-050-4).",
    concepts: ["consciousness", "bioframe", "mind_field", "aristotle_logic"],
    color: "#a855f7",
  },
  {
    year: 1983,
    era: "publication",
    title: "Phi-River & Conservation of Charge Extended — Part 4 Diagrams",
    type: "theory",
    description: "In Part 4, Bearden introduces the phi-river concept: two locked-in phi-sources of different magnitudes create a ∇φ river of virtual particles — a region of curved spacetime where energy is not conserved. He distinguishes the failed standard circuit (electron spray nozzle with losses) from the free anenergy pump (shielded toroid, ∇φ inside = 0, φ > φ₀). Also introduces the extended conservation laws: charge = Mc + AEc (massless + charged), and the new massless charge ↔ energy cycle completing the Massless Charge — Energy — Mass triangle missing from standard physics.",
    concepts: ["anenergy", "vacuum_structure", "scalar_em", "negentropy"],
    color: "#3b82f6",
  },
  {
    year: 1983,
    era: "publication",
    title: "ELF Brain Entrainment Architecture Documented",
    type: "geopolitical",
    description: "Bearden documents the Soviet ELF brain-entrainment mechanism in Excalibur Briefing: multiple carriers in the 5–30 MHz band, each modulated at ≤10 Hz and synchronized in phase. This locks all brains within range into phase with the 10 Hz modulation. With additional detrimental modulations, the locked brain state can be driven into pathological territory. Bearden identifies this as the mechanism behind Soviet Woodpecker transmitter broadcasts and attributes documented Western health anomalies to its deployment. Includes the Prioré device as an inadvertent countermeasure — its hyperspatial EM structure naturally counters ELF entrainment patterns.",
    concepts: ["soviet_woodpecker", "em_biological_warfare", "mind_field", "weather_warfare"],
    color: "#ef4444",
  },
  {
    year: 2001,
    era: "mature",
    title: "Atmospheric Scalar EM Grid Documentation — California Sky Photos",
    type: "geopolitical",
    description: "Bearden's team documents a sustained series of anomalous atmospheric cloud formations along the California coastline (Solvang, Santa Barbara, Palos Verdes) attributed to scalar EM transmitter operations. Photographs from Nov–Dec 2001 and Spring 2002 capture: (1) radial spoke-pattern cirrus formations emanating from a single focus point — the 'boattailed' beam pattern of a scalar EM interference grid; (2) regular rectangular grid-pattern cirrus indicating standing scalar wave interference; (3) circular 'hole-punch' clearings in altocumulus decks — attributed to focused scalar energy bottle zones where the E=0 B=0 interference region suppresses cloud nucleation; (4) the 2-radials diagram (uploaded) showing the exact scalar interference grid pattern with pattern linking and central ring disappearance matching observed cloud signatures. The Woodpecker Grid sound recordings and satellite radar anomaly maps are published alongside the photos on the Tom Bearden Website.",
    concepts: ["soviet_woodpecker", "weather_warfare", "energy_bottle", "scalar_em"],
    color: "#06b6d4",
  },
  {
    year: 2001,
    era: "mature",
    title: "Scalar Interference Grid Pattern — 2-Radials Diagram Published",
    type: "theory",
    description: "Publication of the '2-radials' diagram (reproduced on the Tom Bearden Website) showing the precise far-field structure of a two-source scalar EM interference grid: two 'boattailed' beams from the scalar transmitter pair create an elliptical ground footprint, a 'pattern linking' zone connecting the two radial fans, and 'intense peaks of normal energy' at the beam lobes where destructive phi-interference converts scalar energy back to detectable Hertz radiation. The diagram labels 'central ring disappears' — matching the observed hole-punch cloud signature — and 'scalar interference grid pattern' at the ground ellipse. This is the first published diagram directly correlating a scalar EM transmitter geometry with an observable atmospheric signature, providing a falsifiable prediction for detecting scalar weapon operations via cloud morphology analysis.",
    concepts: ["energy_bottle", "scalar_em", "weather_warfare", "soviet_woodpecker"],
    color: "#06b6d4",
  },
  {
    year: 1976,
    era: "development",
    title: "Soviet Woodpecker Grid — Anomalous Radar Returns Documented",
    type: "geopolitical",
    description: "Starting in 1976, a distinctive low-frequency pulse signal dubbed the 'Woodpecker' (4–30 MHz, 10 Hz pulse rate) is detected worldwide on shortwave radio. Bearden attributes this to over-the-horizon scalar EM transmitters near Chernobyl (Duga-3 array). Beyond standard radar interpretation, he argues the Woodpecker produces a standing scalar wave grid across North America — the atmospheric delivery mechanism for ELF brain entrainment (10 Hz modulation) and biological warfare. The Tom Bearden Website hosts recordings of the Woodpecker sound and satellite radar anomaly maps showing radial cloud interference patterns consistent with a scalar EM grid footprint over the Pacific and US West Coast.",
    concepts: ["soviet_woodpecker", "weather_warfare", "em_biological_warfare", "scalar_em"],
    color: "#ef4444",
  },
  {
    year: 1996,
    era: "mature",
    title: "Energetics / Bioenergetics / Psychoenergetics Framework (1996 Diagram)",
    type: "theory",
    description: "Bearden publishes his unified 'Energetics' diagram dividing all EM interactions into three domains: Energetics (nonliving systems — scalar interferometry, vacuum engines, quantum potential, SWZ effects), Bioenergetics (living bodies — master cell control via Popp, disease induction/remission, cellular spacetime structuring), and Psychoenergetics (living minds — thoughts/memories/emotions, species and biospheric minds, conscious/unconscious spacetime structuring). All three domains share identical underlying mechanisms operating at different substrate levels. This 1996 diagram is the most complete visual synthesis of Bearden's entire framework.",
    concepts: ["energetics_framework", "kindling", "consciousness", "scalar_em", "quantum_potential"],
    color: "#06b6d4",
  },
  {
    year: 1995,
    era: "mature",
    title: "Vacuum Engines & Prioré's Methodology: The True Science of Energy-Medicine (Explore! 1995)",
    type: "publication",
    description: "Bearden publishes 'Vacuum Engines and Prioré's Methodology — The True Science of Energy-Medicine' (Parts I & II) in Explore! Vol. 6, No. 1, 1995. Introduces the two-type engineering framework: Type 1 (using external energy upon quiescent vacuum matter) vs Type 2 (gating and structuring the vacuum flux itself — vacuum engines). Documents Prioré's photographs and laboratory evidence, Kaznacheyev two-chamber cytopathogenic effect apparatus (Figure 3), graviton lattice templates (Figure 4), vacuum engine concept diagram (Figure 2), the photon interaction generating discretized time flow (Figure 7), the SWZ biwave decomposition of the scalar EM potential (Figure 5), and a rigorous table of the Prioré therapy mechanism (Table 4). Introduces asymmetric regauging, the overunity circuit demonstration (Patent Pending), Patterson Power Cell, and Chung's carbon filament negative resistor.",
    concepts: ["vacuum_engine_type2", "priors_device", "kaznacheyev", "asymmetric_regauging", "time_reversal_zone", "kindling"],
    color: "#22c55e",
  },
  {
    year: 1998,
    era: "mature",
    title: "Foundations of Electro-Magnetism Slide Series & Toward a Practical Unified Field Theory",
    type: "publication",
    description: "Bearden releases his comprehensive slide series on Foundations of Electro-Magnetism and 'Toward a Practical Unified Field Theory With Deep Experimental Examples' (CTEC, Inc.). Covers: 32 flaws in classical EM theory (complete enumeration), Maxwell's quaternion theory and its reduction by Heaviside/Gibbs, the missing infolded electrodynamics diagram, ST curvature propagation (mass-to-ST and ST-to-mass transforms), the 7-space EM potential (Figure 8), extension of the Work-Energy Theorem (reaction cross section lambda), absorption and emission reactions comparing energy-density vs time-density excited states, Becker's bone fracture healing experiments, Becker's theoretical DC control system governing regeneration, the Patterson Power Cell (Figure 29), anomalous LW EM emission phenomena at China Lake, time-reversal zones in nuclear and chemical reactions, and the new conservation of energy law: ET = EE + EM + Et.",
    concepts: ["maxwell_equations", "vacuum_engine_type2", "time_reversal_zone", "asymmetric_regauging", "time_as_energy", "mccs_cellular_control"],
    color: "#3b82f6",
  },
  {
    year: 1999,
    era: "mature",
    title: "Mind Control & EM Wave Polarization Transductions (Explore! Magazine, 1999)",
    type: "publication",
    description: "Bearden publishes 'Mind Control and EM Wave Polarization Transductions, Parts I, II & III' in Explore! Magazine (Vol. 9, No. 2, 1999). Introduces t-polarized (scalar) photons as the fourth photon polarization, establishes that time is dense EM energy at 9x10^16 J/second, presents the wave transduction chain (transverse → longitudinal → time-density wave), and formally derives the mind-body coupling loop (Figure 5). Documents Russian KGB psychoenergetics applications for 20+ years. Notes two specific 1997 tests of advanced mind control weapons against US military pilots over central US. Presents the first rigorous physical solution to the problem of intent and free will via coherent 4-space rotations.",
    concepts: ["t_polarized_photons", "wave_transduction", "mind_body_coupling", "time_as_energy", "consciousness", "elf_entrainment"],
    color: "#a855f7",
  },
  {
    year: 2002,
    era: "mature",
    title: "Energy from the Vacuum",
    type: "publication",
    description: "Major synthesis work connecting scalar EM theory to free energy extraction from the vacuum. Bearden argues the vacuum is a vast reservoir of ordered scalar EM energy that can be tapped via resonant scalar transmitters — unifying his physics, biology, and consciousness models.",
    concepts: ["scalar_em", "negentropy", "mind_field"],
    color: "#3b82f6",
  },
];

export const eraLabels = {
  early: { label: "Early Work", color: "#6b7280" },
  development: { label: "Framework Development", color: "#3b82f6" },
  publication: { label: "Key Publications", color: "#f59e0b" },
  mature: { label: "Mature Theory", color: "#a855f7" },
};

export const typeIcons = {
  career: "🎖️",
  theory: "🔬",
  geopolitical: "⚡",
  publication: "📖",
  history: "🔭",
};