// All 33 device build plans — Technical Brief Pack definitions
// Each brief pack maps to one invention from businessItems.js

export const BRIEF_PACKS = [
  {
    id: "bp-001",
    slug: "anenergy-pump-demo",
    title: "Anenergy Pump Demonstration Circuit",
    subtitle: "Phi-Field Extraction & the Moray Mechanism",
    category: "Vacuum Energy",
    price: 27,
    pages: "45–55",
    difficulty: "Advanced",
    color: "#22c55e",
    icon: "🔋",
    tagline: "Physical demonstration of phi-field extraction — the Moray mechanism in a kit",
    theory_basis: "Bearden 'Toward a New Electromagnetics Part 4' (1983)",
    sections: [
      "System Architecture & Operating Principle",
      "Bill of Materials (BOM) with exact part numbers",
      "Shielded Toroidal Coil Winding Specifications",
      "DDS Pulse Controller Circuit Diagram",
      "Phi-Differential Measurement Points & Protocol",
      "Moray-Type Oscillation Cycle Documentation",
      "Safety Guidelines & Lab Setup",
    ],
  },
  {
    id: "bp-002",
    slug: "scalar-energy-bottle",
    title: "Scalar Energy Bottle Interferometer",
    subtitle: "Two-Transmitter Zero-Vector Interference Zone",
    category: "Scalar EM / Defense",
    price: 27,
    pages: "50–60",
    difficulty: "Expert",
    color: "#ef4444",
    icon: "🎯",
    tagline: "Two-transmitter scalar EM system — E=0, B=0 interference zone with scalar pulse radar",
    theory_basis: "Bearden Part 4 (1983) — energy bottle figures, scalar pulse radar diagrams",
    sections: [
      "Zero-Vector Transmitter Topology (balanced push-pull coil)",
      "Interference Zone Geometry & BOM",
      "FPGA Timing Circuit (nanosecond resolution)",
      "Scalar Pulse Radar Timing Protocol",
      "Dual-Detector Assembly (conventional + scalar)",
      "Interference Zone Calculation Software",
      "Safety & Shielding Requirements",
    ],
  },
  {
    id: "bp-003",
    slug: "vacuum-potential-oscillator",
    title: "Vacuum Potential Oscillator (VPO) Circuit",
    subtitle: "Resonant LC Vacuum-Ground Potential Shift",
    category: "Vacuum Energy",
    price: 27,
    pages: "35–45",
    difficulty: "Intermediate",
    color: "#3b82f6",
    icon: "🔧",
    tagline: "Hands-on exploration of scalar phi-field principles using resonant LC circuit",
    theory_basis: "Bearden 1982 'Comments on New Tesla EM Part II' — vacuum oscillation mechanism",
    sections: [
      "Vacuum Potential Oscillation Theory",
      "Resonant LC Circuit Design & BOM",
      "Custom Toroid Winding Specifications",
      "Quartz Resonator Integration",
      "Measurement Protocol Guide",
      "Safety & Operating Procedures",
    ],
  },
  {
    id: "bp-004",
    slug: "biofield-frequency-chamber",
    title: "Biofield Frequency Exposure Chamber",
    subtitle: "Kaznacheyev-Type UV Photon Transmission",
    category: "Bioelectromagnetics",
    price: 27,
    pages: "40–50",
    difficulty: "Intermediate",
    color: "#22c55e",
    icon: "🧪",
    tagline: "Shielded quartz-windowed chamber for cytopathogenic UV photon transmission experiments",
    theory_basis: "Bearden analysis of Kaznacheyev experiments; Rife mortal oscillatory rate research",
    sections: [
      "Kaznacheyev Effect — Operating Principle",
      "Dual-Compartment Chamber Construction (BOM)",
      "UV-Grade Quartz vs Glass Optical Path Specs",
      "Programmable Frequency Driver Circuit",
      "Cell Culture Integration Protocol",
      "Measurement & Documentation Methodology",
      "Regulatory Status (FDA-exempt research instrument)",
    ],
  },
  {
    id: "bp-005",
    slug: "open-system-generator",
    title: "Open-System Magnetic Generator",
    subtitle: "Kromrey/Gray/Searl Design Engineering Plans",
    category: "Free Energy",
    price: 27,
    pages: "55–65",
    difficulty: "Advanced",
    color: "#f59e0b",
    icon: "⚙️",
    tagline: "Engineering plans based on Kromrey, Edwin Gray's patent, and Searl generator principles",
    theory_basis: "Schaffranke 1982; Edwin Gray US Patent #3,890,548; Searl design notes",
    sections: [
      "System Overview & Historical Precedent",
      "Rotating Assembly Engineering Drawings",
      "BOM with Exact Component Specifications",
      "Winding Specifications & Coil Geometry",
      "Switching Control Circuit (MOSFET H-bridge)",
      "Power Output Measurement Methodology",
      "Safety Protocols for Rotating EM Systems",
    ],
  },
  {
    id: "bp-006",
    slug: "quantum-potential-detector",
    title: "Quantum Potential EMI Detector ('Fireflies Sensor')",
    subtitle: "Quartz-Crystal Array Statistical Burst Detector",
    category: "Defense / Detection",
    price: 27,
    pages: "40–50",
    difficulty: "Advanced",
    color: "#ef4444",
    icon: "📡",
    tagline: "Detect scalar EM interference invisible to standard instruments via statistical burst analysis",
    theory_basis: "Bearden Gravitobiology 1991: Table 6, Figure 14, Table 7 (Pentagon EMI studies)",
    sections: [
      "Quantum Potential Detection Theory",
      "Tuned Quartz-Crystal Array Design & BOM",
      "Statistical Burst-Pattern Analysis Firmware",
      "Anomaly Alert System Architecture",
      "Calibration & Baseline Protocol",
      "Comparison vs Standard Spectrum Analyzer",
      "Anomalous Signature Classification Guide",
    ],
  },
  {
    id: "bp-007",
    slug: "em-trigger-window-therapy",
    title: "EM Trigger Window Therapy Device",
    subtitle: "Precision Frequency EM Pulse Generator",
    category: "Bioelectromagnetics",
    price: 27,
    pages: "40–50",
    difficulty: "Intermediate",
    color: "#22c55e",
    icon: "💊",
    tagline: "Programmable EM pulses within documented biological trigger windows (Lisitsyn tables)",
    theory_basis: "Gravitobiology Table 12 (EM trigger windows), Lisitsyn's report (p.41), Beck/Hunt research",
    sections: [
      "Lisitsyn Trigger Window Table — 24 Biological Frequencies",
      "DDS Frequency Generator Design & BOM",
      "Consumer Wristband Form Factor Specifications",
      "Clinical Full-Body Chamber Configuration",
      "Programmable Protocol Software Interface",
      "Safety Limits & Operating Parameters",
      "Regulatory Pathway (non-diagnostic wellness device)",
    ],
  },
  {
    id: "bp-008",
    slug: "morphogenetic-coherence-monitor",
    title: "Morphogenetic Field Coherence Monitor",
    subtitle: "Quantum Potential Coherence Index Measurement",
    category: "AgTech / Biotech",
    price: 27,
    pages: "45–55",
    difficulty: "Expert",
    color: "#22c55e",
    icon: "🌿",
    tagline: "Monitor local graviton lattice coherence around biological samples",
    theory_basis: "Gravitobiology p.45-48 (morphogenetic field), Figure 20 (graviton lattice)",
    sections: [
      "Morphogenetic Field Physics — Whittaker Structure",
      "SQUID Magnetometer Array Specifications & BOM",
      "Coherence Index Calculation Algorithm",
      "Agricultural Deployment Protocol",
      "Cancer Precursor Detection Application",
      "Data Logging & Analysis Software",
      "Shielded Measurement Enclosure Design",
    ],
  },
  {
    id: "bp-009",
    slug: "phase-conjugate-mirror",
    title: "Whittaker Wave Phase Conjugate Mirror (PCM) System",
    subtitle: "Time-Reversed EM Signals via BaTiO₃ Nonlinear Medium",
    category: "Defense / Scalar Comms",
    price: 27,
    pages: "50–60",
    difficulty: "Expert",
    color: "#3b82f6",
    icon: "🔭",
    tagline: "Time-reverse incoming EM waves for self-targeting communications and EM countermeasures",
    theory_basis: "Gravitobiology Figures 10, 11 (phase conjugate mirrors); Whittaker wave decomposition",
    sections: [
      "Phase Conjugation Physics & BaTiO₃ Geometry",
      "PPCM Pumping Configuration & BOM",
      "RF Input/Output Coupling Design",
      "Phase Conjugate Output Verification Protocol",
      "Scalar Communications Application",
      "Therapeutic Pattern Cancellation Setup",
      "Safety & ESD Protection",
    ],
  },
  {
    id: "bp-010",
    slug: "priore-multichannel-em",
    title: "Prioré-Type Multichannel EM Therapy System",
    subtitle: "Modern DDS Implementation of Bearden Fig. 10 Architecture",
    category: "Bioelectromagnetics",
    price: 27,
    pages: "55–65",
    difficulty: "Expert",
    color: "#22c55e",
    icon: "🏥",
    tagline: "S'/S''/S''' hyperspatial layer outputs — DDS signal chain + FPGA modulation",
    theory_basis: "Bearden Excalibur Briefing Fig. 10 (Prioré device); Gravitobiology kindling reversal",
    sections: [
      "Fig. 10 Architecture Decoded (S'/S''/S''' chain)",
      "DDS Signal Generator Configuration & BOM",
      "FPGA Modulation Chain Design",
      "Shielded Applicator Coil Specifications",
      "Treatment Protocol Software",
      "Research vs Clinical Configuration",
      "IRB Approval Pathway Documentation",
    ],
  },
  {
    id: "bp-011",
    slug: "elf-carrier-detector",
    title: "ELF Carrier Lock Detection System ('Psychotronic Detector')",
    subtitle: "SDR Phase-Coherence Scanner — 5–30 MHz Band",
    category: "Defense / Detection",
    price: 27,
    pages: "40–50",
    difficulty: "Advanced",
    color: "#ef4444",
    icon: "📡",
    tagline: "Detect synchronized ≤10 Hz ELF modulation sidebands across multiple carriers",
    theory_basis: "Bearden Excalibur Briefing ELF entrainment diagram; Gravitobiology Table 7",
    sections: [
      "ELF Carrier Phase-Coherence Detection Theory",
      "SDR Hardware Configuration & BOM (HackRF/RTL-SDR)",
      "Cross-Correlation Firmware Architecture",
      "Statistical Phase Anomaly Detection Algorithm",
      "Geographic Direction-Finding Add-On (antenna array)",
      "Timestamp Logging & Reporting System",
      "Correlation with Cloud Morphology Observations",
    ],
  },
  {
    id: "bp-012",
    slug: "phi-river-gradient-sensor",
    title: "Phi-River Gradient Sensor (∇φ Detector)",
    subtitle: "Hall-Effect Bridge Measurement of Massless Charge Flux",
    category: "Vacuum Energy / Instrumentation",
    price: 27,
    pages: "40–50",
    difficulty: "Advanced",
    color: "#ef4444",
    icon: "🌊",
    tagline: "Directly measure the virtual particle flux river between two phi-sources",
    theory_basis: "Bearden Part 4 phi-river figures; phi-source diagrams; anenergy pump geometry",
    sections: [
      "∇φ River vs E-Field — Key Distinction",
      "Matched Shielded Toroidal Coil Pair Specs & BOM",
      "Hall-Effect Bridge Circuit Design",
      "Common-Mode E-Field Rejection Protocol",
      "Calibration Procedure for Virtual Photon Flux",
      "Data Acquisition & Signal Processing",
      "Measurement Interpretation Guide",
    ],
  },
  {
    id: "bp-013",
    slug: "meg-replication-kit",
    title: "MEG Replication Kit (Motionless Electromagnetic Generator)",
    subtitle: "COP>1 Device — Peer-Reviewed & Independently Replicated",
    category: "Free Energy",
    price: 27,
    pages: "60–70",
    difficulty: "Advanced",
    color: "#a855f7",
    icon: "🔮",
    tagline: "Build the Foundations of Physics Letters 2001 device independently replicated by Naudin",
    theory_basis: "Anastasovski et al. Found. Phys. Lett. 14(1), 2001; Naudin replication notes; Bearden CTEC Inc.",
    sections: [
      "O(3) Electrodynamics & MEG Operating Principle",
      "Nanocrystalline Core Toroid Specifications & BOM",
      "Primary/Secondary Coil Winding Ratios",
      "MOSFET H-Bridge Switching Circuit",
      "Naudin Replication Protocol Step-by-Step",
      "COP>1 Measurement Methodology (power analyzer setup)",
      "Common Replication Pitfalls & Solutions",
    ],
  },
  {
    id: "bp-014",
    slug: "asymmetric-regauging-generator",
    title: "Asymmetric Regauging Overunity Generator (Type 2 Power Cell)",
    subtitle: "Two-Loop Asymmetric Self-Regauging Circuit",
    category: "Free Energy",
    price: 27,
    pages: "50–60",
    difficulty: "Expert",
    color: "#ef4444",
    icon: "⚡",
    tagline: "Patent-pending circuit: Source loop A asymmetrically regauges load loop B via bridging conductor",
    theory_basis: "Bearden overunity demonstration circuit (Patent Pending, 1993-1995); Chung carbon filament resistor",
    sections: [
      "Asymmetric Self-Regauging Theory",
      "Spherical Conducting Shell Fabrication & BOM",
      "Two-Loop Bridging Architecture",
      "Power-Free MOSFET Switching Protocol",
      "Chung Carbon Filament Negative Resistor Add-On",
      "S-Flow / dφ/dt / EMF Flow Measurement",
      "Safety Protocols for High-Potential Circuits",
    ],
  },
  {
    id: "bp-015",
    slug: "telomere-regeneration-device",
    title: "Telomere Regeneration Device (TRD-1)",
    subtitle: "AI-Assisted Scalar EM Porthole Therapy System",
    category: "Longevity / Biotech",
    price: 27,
    pages: "65–75",
    difficulty: "Expert",
    color: "#22c55e",
    icon: "🧬",
    tagline: "Three-stage MCCS protocol: spectroscopy → delta computation → porthole reinsertion",
    theory_basis: "Bearden 'Vacuum Engines & Prioré's Methodology' (1995); MCCS telomere regeneration protocol",
    sections: [
      "MCCS Telomere Reduction Correlate Theory",
      "Stage 1: Full-Body TW Emission Spectroscopy (Faraday enclosure BOM)",
      "Stage 2: AI Delta Computation Architecture",
      "Stage 3: DDS Phased Antenna Array — Reinsertion Design",
      "Three-Session Treatment Protocol",
      "Phase Conjugate Replica Generation",
      "Research Device Classification & IRB Pathway",
    ],
  },
  {
    id: "bp-016",
    slug: "portable-porthole-treatment",
    title: "Portable Porthole Disease Treatment System (PPDTS)",
    subtitle: "Suitcase-Sized Delta Spectrum Reinsertion System",
    category: "Emergency Medicine",
    price: 27,
    pages: "60–70",
    difficulty: "Expert",
    color: "#ef4444",
    icon: "🏥",
    tagline: "Assembly-line capable mass casualty treatment — 30-second irradiation per patient",
    theory_basis: "Bearden Explore! 1999; Figure 13 porthole technology",
    sections: [
      "Delta Spectrum Disease Reinsertion Theory",
      "Wire Antenna Blanket Construction & BOM",
      "DDS Frequency Generator Configuration",
      "Laptop-Based Delta Computation System",
      "Patient Baseline Measurement Protocol",
      "Assembly-Line Treatment Sequencing",
      "Emergency Use Authorization Pathway",
    ],
  },
  {
    id: "bp-017",
    slug: "trz-cold-fusion-reactor",
    title: "Time-Reversal Zone Cold Fusion Reactor (TRZ-CFR)",
    subtitle: "Patterson Power Cell Geometry + LW Emission Detection",
    category: "Nuclear / Clean Energy",
    price: 27,
    pages: "60–70",
    difficulty: "Expert",
    color: "#ef4444",
    icon: "⚛️",
    tagline: "Palladium-clad microsphere cathode with TRZ framework — reproduce China Lake 73σ anomalies",
    theory_basis: "Bearden China Lake data; Patterson Power Cell (Figure 29); TRZ nuclear reaction diagrams",
    sections: [
      "TRZ Framework Applied to Cold Fusion",
      "Palladium-Clad Microsphere Cathode Specs & BOM",
      "Heavy Water Electrolytic Cell Configuration",
      "LW Emission Detection Array (GM + scintillation)",
      "Cross-Correlation Detection Firmware",
      "Time-Density Charging Monitoring Protocol",
      "Anomalous Radiation Correlate Analysis",
    ],
  },
  {
    id: "bp-018",
    slug: "t-polarized-em-transducer",
    title: "T-Polarized EM Wave Transducer",
    subtitle: "Two-Stage Transduction Chain: Transverse → Longitudinal → Time-Density",
    category: "Scalar Comms / Research",
    price: 27,
    pages: "50–60",
    difficulty: "Expert",
    color: "#ef4444",
    icon: "⏱️",
    tagline: "Figure 2 implementation — anomalous wave invisibility to standard instruments demonstrated",
    theory_basis: "Bearden 'Mind Control and EM Wave Polarization Transductions' Figure 2 (Explore! 1999)",
    sections: [
      "Two-Stage Transduction Chain Theory (Fig. 2)",
      "Stage 1: BaTiO₃ Phase Conjugate Mirror Specs & BOM",
      "Stage 2: Longitudinal → Time-Density Conversion",
      "SDR Side-by-Side Comparison Setup",
      "Custom Scalar Detector Design",
      "Anomalous Instrument Reading Documentation",
      "Scalar Communications Application Protocol",
    ],
  },
  {
    id: "bp-019",
    slug: "psychoenergetics-cellular-control",
    title: "Psychoenergetics Cellular Control System",
    subtitle: "Coherent Biophoton-Frequency EM + Scalar Interferometry",
    category: "Bioelectromagnetics",
    price: 27,
    pages: "45–55",
    difficulty: "Advanced",
    color: "#22c55e",
    icon: "🧬",
    tagline: "Engineer the bioenergetics domain: master cell control, disease induction/remission",
    theory_basis: "Bearden 1996 Energetics diagram (Bioenergetics domain); Popp biophoton master cell control",
    sections: [
      "Bioenergetics Domain — Popp Master Cell Control Theory",
      "DDS Multi-Frequency Generator Design & BOM",
      "UV LED Biophoton-Range Output Array",
      "Disease Remission vs Enhancement Protocols",
      "Scalar Interferometry Overlay Configuration",
      "Coherent Biophoton Measurement Setup",
      "Safety Parameters & Operating Limits",
    ],
  },
  {
    id: "bp-020",
    slug: "bedini-signal-conditioner",
    title: "Bedini Environmental EM Signal Conditioner (BESC-1)",
    subtitle: "Force-Fit Therapy Signals to Local Vacuum Environment",
    category: "Bioelectromagnetics",
    price: 27,
    pages: "45–55",
    difficulty: "Advanced",
    color: "#ef4444",
    icon: "🎛️",
    tagline: "Eliminate scalar interferometry jamming in Rife, PEMF, and Priore-type devices",
    theory_basis: "Bearden Nov 2002 (Bedini's Discovery); Bedini tube conditioning method",
    sections: [
      "Bedini Environmental Conditioning Theory",
      "Electron Tube Reverse-Mode Circuit Design & BOM",
      "Oscilloscope Conditioning Verification Output",
      "BNC Plug-In Compatibility Configuration",
      "Local Vacuum Environment Sampling Protocol",
      "Before/After Conditioning Comparison Procedure",
      "Integration with Standard Rife/PEMF Outputs",
    ],
  },
  {
    id: "bp-021",
    slug: "waddington-valley-tracer",
    title: "Waddington Valley EM Tracer System (WVTS)",
    subtitle: "Map Infolded EM Fingerprints of Cellular Differentiation Stages",
    category: "Longevity / Epigenetics",
    price: 27,
    pages: "55–65",
    difficulty: "Expert",
    color: "#22c55e",
    icon: "🗺️",
    tagline: "Build a Waddington valley EM database for precision epigenetic reprogramming",
    theory_basis: "Bearden Nov 2002; Waddington 1940; Becker 1967, 1970; Reik & Dean 2002",
    sections: [
      "Waddington Valley EM Fingerprint Theory",
      "Wideband Biophoton Spectroscopy Setup & BOM",
      "Shielded Faraday Enclosure Construction",
      "Cell Culture Differentiation Stage Protocol",
      "EM Emission Spectroscopy Array Design",
      "ML Template-Matching Database (Python pipeline)",
      "Valley Reference Database Architecture",
    ],
  },
  {
    id: "bp-022",
    slug: "cloning-efficiency-system",
    title: "Cloning Efficiency Enhancement System (CEES)",
    subtitle: "Bedini-Conditioned Signals for SCNT Cloning",
    category: "Cloning / Reproductive Biology",
    price: 27,
    pages: "55–65",
    difficulty: "Expert",
    color: "#22c55e",
    icon: "🧬",
    tagline: "Address EM environment mismatch — the root cause of worldwide cloning inefficiency",
    theory_basis: "Bearden Nov 2002; Reik, Dean & Walter, Science 2001; Solter, Nat. Rev. Gen. 2000",
    sections: [
      "EM Mismatch Theory in SCNT Cloning",
      "Local Vacuum EM Environment Mapping Protocol & BOM",
      "Somatic Nucleus / Egg Cell EM Fingerprinting",
      "Bedini-Conditioned Bridging Signal Generation",
      "SCNT Procedure Integration Protocol",
      "Efficiency Measurement Framework",
      "IACUC Approval Documentation Template",
    ],
  },
  {
    id: "bp-023",
    slug: "kaznacheyev-reversal-chamber",
    title: "Kaznacheyev Reversal Cell Imprinting Chamber (KRCIC)",
    subtitle: "Healthy Donor → Diseased Recipient UV Biophoton Template Reversal",
    category: "Bioelectromagnetics",
    price: 27,
    pages: "55–65",
    difficulty: "Advanced",
    color: "#22c55e",
    icon: "🔬",
    tagline: "Reverse the cytopathogenic effect — imprint healthy-cell UV templates onto diseased cells",
    theory_basis: "Kaznacheyev cytopathogenic UV experiments (USSR); Bearden MCCS framework; Popp biophoton coherence",
    sections: [
      "Kaznacheyev Reversal — Operating Theory",
      "Dual-Chamber UV-Grade Fused Silica Construction & BOM",
      "Photomultiplier Tube Array Configuration (Hamamatsu R7400)",
      "Phase-Contrast Microscope Integration",
      "DDS-Programmable UV Template Delivery System",
      "Disease-Specific Frequency Template Selection",
      "Real-Time Morphological Change Monitoring Protocol",
    ],
  },
  {
    id: "bp-024",
    slug: "uv-biophoton-disease-reversal",
    title: "UV Biophoton Disease Reversal Spectrometer (UBDRS)",
    subtitle: "Single-Photon UV Spectroscopy + ML Template Matching",
    category: "Bioelectromagnetics / Diagnostics",
    price: 27,
    pages: "60–70",
    difficulty: "Expert",
    color: "#06b6d4",
    icon: "🧬",
    tagline: "Identify cytopathogenic UV spectra and synthesize matched healthy-tissue templates",
    theory_basis: "Kaznacheyev; Popp biophoton research; Bearden MCCS (Explore! 1995); Gravitobiology 1991",
    sections: [
      "UV Biophoton Disease Template Theory",
      "Single-Photon UV Spectrometer Setup & BOM (200–400nm)",
      "PMT Detector Array Configuration",
      "DDS-Driven UV-LED Template Synthesis Array",
      "ML Template-Matching Pipeline (Python/TensorFlow)",
      "Disease Spectral Database Architecture",
      "PMT-Monitored Feedback Loop & Automated Microscopy",
    ],
  },
  {
    id: "bp-025",
    slug: "morphoyield-trz-array",
    title: "MorphoYield TRZ-Agri Array",
    subtitle: "Phase-Conjugate Scalar Biofield Enhancement for Agriculture",
    category: "AgTech",
    price: 27,
    pages: "50–60",
    difficulty: "Advanced",
    color: "#22c55e",
    icon: "🌾",
    tagline: "Field-deployable antenna array for morphogenetic field enhancement and crop yield improvement",
    theory_basis: "Bearden Gravitobiology (1991) p.45-48 morphogenetic field; TRZ framework (Explore! 1995)",
    sections: [
      "Morphogenetic Field Enhancement Theory",
      "Phase-Conjugate VLF-ELF Antenna Array Design & BOM",
      "GPS-Geo-Referenced Placement Protocol",
      "Soil-Moisture-Coupled Field Strength Optimizer",
      "Seasonal Protocol Library (major crop types)",
      "Field Trial Measurement Framework",
      "Weatherproof Enclosure & Mounting Specifications",
    ],
  },
  {
    id: "bp-026",
    slug: "aegis-sv-shield",
    title: "Aegis-SV Adaptive Scalar Counterphase Shield",
    subtitle: "Phase-Conjugate Vacuum Engineering EM Quiet Zone",
    category: "Defense / EMF Protection",
    price: 27,
    pages: "55–65",
    difficulty: "Expert",
    color: "#3b82f6",
    icon: "🛡️",
    tagline: "Adaptive counterphase generation targeting 10 Hz ELF brain-entrainment signatures",
    theory_basis: "Bearden Gravitobiology (1991) ELF entrainment architecture; Pentagon EMI studies (Table 7)",
    sections: [
      "Adaptive Counterphase Theory (PPCM Architecture)",
      "Wearable Form Factor: SDR Mini + DDS Chip + LiPo BOM",
      "Cabinet Form Factor: Higher-Power PA Stage",
      "Grid-Scale Perimeter Array Configuration",
      "SDR Ambient Sampling + DDS Output Circuit",
      "Varactor Diode Array Nonlinear Medium",
      "Phase-Conjugate Firmware Documentation",
    ],
  },
  {
    id: "bp-027",
    slug: "longitudinal-wave-acoustic",
    title: "Longitudinal Wave Acoustic-EM Transducer (LWAT)",
    subtitle: "Scalar EM → Acoustic Pressure for Non-Destructive Testing",
    category: "Industrial / Defense",
    price: 27,
    pages: "45–55",
    difficulty: "Advanced",
    color: "#06b6d4",
    icon: "🌊",
    tagline: "Convert scalar EM to acoustic pressure — non-contact structural inspection and covert comms",
    theory_basis: "Whittaker E.T. (1903); Bearden Parts 3 & 4 (1983); Aharonov-Bohm (1959)",
    sections: [
      "Whittaker Decomposition & Acoustic Transduction Theory",
      "Piezoelectric Transducer Array Design & BOM",
      "Nonlinear Acoustic Coupling Medium (ferrofluid)",
      "Scalar Interferometry Source Configuration",
      "Phase-Conjugate Return Capture Protocol",
      "Structural Inspection Test Protocol",
      "Covert Acoustic Communications Setup",
    ],
  },
  {
    id: "bp-028",
    slug: "biophoton-coherence-chamber",
    title: "Biophoton Coherence Restoration Chamber (BCRC)",
    subtitle: "Popp Master Cell Control Frequencies — UV Coherent Delivery",
    category: "Longevity / Bioelectromagnetics",
    price: 27,
    pages: "40–50",
    difficulty: "Intermediate",
    color: "#22c55e",
    icon: "🧬",
    tagline: "Restore cellular biophoton coherence using Popp's peer-reviewed master cell control frequencies",
    theory_basis: "Popp F.A. et al. (1992); Chang J.J. et al. (1998); Kaznacheyev (1974–1982); Bearden MCCS (1995)",
    sections: [
      "Popp Biophoton Coherence Theory",
      "Coherent UV LED Source Configuration & BOM (200–400nm)",
      "UV-Grade Quartz Optical Path Specifications",
      "Dual Hamamatsu PMT Monitoring Array",
      "Coherence Index Calculation Protocol",
      "Treatment Frequency Library (Popp master control windows)",
      "Research Instrument Classification Notes",
    ],
  },
  {
    id: "bp-029",
    slug: "asymmetric-flux-gate",
    title: "Asymmetric Flux Gate Induction Generator (AFIG)",
    subtitle: "Aharonov-Bohm Vector Potential Asymmetric Flux Gating",
    category: "Free Energy",
    price: 27,
    pages: "50–60",
    difficulty: "Expert",
    color: "#f59e0b",
    icon: "⚡",
    tagline: "Exploit the experimentally verified AB effect to produce net electron drift without back-EMF",
    theory_basis: "Aharonov Y. & Bohm D. (1959); Bedini switching patents; Bearden asymmetric regauging; Patterson Power Cell",
    sections: [
      "Aharonov-Bohm Effect Applied to Generators",
      "Multi-Pole Flux Gate Array Design & BOM",
      "Ferrite Core Asymmetric Switching Topology",
      "FPGA Asymmetric Timing Control (nanosecond precision)",
      "Patterson-Geometry Output Coil Specifications",
      "Net Electron Drift Measurement Protocol",
      "Back-EMF Suppression Verification",
    ],
  },
  {
    id: "bp-030",
    slug: "atmospheric-electrostatic-harvester",
    title: "Atmospheric Electrostatic Gradient Harvester (AEGH)",
    subtitle: "Schumann-Resonant Antenna Array — Continuous 50–500mW Output",
    category: "Renewable Energy / IoT",
    price: 27,
    pages: "40–50",
    difficulty: "Intermediate",
    color: "#06b6d4",
    icon: "🌍",
    tagline: "Tap Earth's 100 V/m electrostatic gradient via Schumann resonances — battery-free IoT power",
    theory_basis: "Rycroft M.J. et al. (2008); Tesla N. (1901) Wardenclyffe patents; Schumann W.O. (1952); Bearden open-system EM",
    sections: [
      "Atmospheric Electric Circuit Theory (peer-reviewed)",
      "Schumann Resonance Antenna Array Design & BOM",
      "Impedance Matching Network (7.83 Hz target)",
      "Ultra-Low-Loss Rectifier + Supercapacitor Buffer",
      "Power Conditioning Circuit for IoT Applications",
      "Field Deployment & Height Optimization",
      "Output Power Measurement Under Atmospheric Conditions",
    ],
  },
  {
    id: "bp-031",
    slug: "morphogenetic-coherence-synchronizer",
    title: "Morphogenetic Field Coherence Synchronizer (MFCS)",
    subtitle: "Phased ELF Helmholtz Coil Array for Wound Healing Research",
    category: "Regenerative Medicine",
    price: 27,
    pages: "45–55",
    difficulty: "Intermediate",
    color: "#22c55e",
    icon: "🧠",
    tagline: "4-element phased ELF array synchronizing intercellular morphogenetic field coherence",
    theory_basis: "Gurwitsch A.G. (1923); Sheldrake R. (1981); Becker R.O. (1985); Bearden Gravitobiology (1991)",
    sections: [
      "Morphogenetic Coherence Theory (Gurwitsch/Becker)",
      "4-Element Helmholtz Coil Array Design & BOM",
      "FPGA Phase Control Circuit (nanosecond precision)",
      "DDS Frequency Generation (0.1–100 Hz range)",
      "In Vitro Wound Scratch Assay Protocol",
      "Neural Axon Regeneration Setup",
      "IRB-Approved In Vitro Study Protocol Template",
    ],
  },
  {
    id: "bp-032",
    slug: "atmospheric-signature-ai",
    title: "Atmospheric Scalar EM Signature Recognition System (AI Edition)",
    subtitle: "Vision Transformer + All-Sky Camera — Cloud Morphology Classifier",
    category: "Defense Meteorology / AI",
    price: 27,
    pages: "50–60",
    difficulty: "Advanced",
    color: "#06b6d4",
    icon: "🛰️",
    tagline: "AI-powered cloud morphology classifier trained on scalar interference grid signatures",
    theory_basis: "Bearden 2-radials diagram; California coast sky photography series; Bearden Part 4 energy bottle geometry",
    sections: [
      "2-Radials Scalar Interference Geometry Theory",
      "All-Sky Camera Hardware Configuration & BOM",
      "GPS Timestamp & Automated Logging Setup",
      "Vision Transformer Fine-Tuning Pipeline",
      "Ground-Truth Label Protocol (Bearden photo archive)",
      "Anomalous Formation Classification System",
      "Woodpecker Grid Correlation Module",
    ],
  },
  {
    id: "bp-033",
    slug: "woodpecker-grid-detector",
    title: "Woodpecker Grid Standing Wave Detector (HF Scalar Signature Receiver)",
    subtitle: "SDR PRI-Analysis Firmware — 4–30 MHz Woodpecker Pulse Detection",
    category: "Defense / SIGINT",
    price: 27,
    pages: "35–45",
    difficulty: "Intermediate",
    color: "#ef4444",
    icon: "📻",
    tagline: "Detect Soviet-style 10 Hz pulse modulation in HF band with audio output and direction finding",
    theory_basis: "Bearden Website Woodpecker documentation; Soviet Duga-3 analysis; Bearden ELF entrainment architecture",
    sections: [
      "Woodpecker Signature Analysis (10 Hz PRI Theory)",
      "RTL-SDR Dongle Configuration & BOM",
      "PRI-Detection Firmware Architecture",
      "Auto-Scan Band Sweep Configuration",
      "Geographic Direction-Finding Antenna Array (2–4 element)",
      "Cloud Morphology Correlation Log",
      "Audio Output & Acoustic Signature Identification",
    ],
  },
];

export const CATEGORY_COLORS = {
  "Vacuum Energy": "#22c55e",
  "Scalar EM / Defense": "#ef4444",
  "Bioelectromagnetics": "#06b6d4",
  "Free Energy": "#f59e0b",
  "Defense / Detection": "#ef4444",
  "AgTech / Biotech": "#22c55e",
  "Defense / Scalar Comms": "#3b82f6",
  "Longevity / Biotech": "#a855f7",
  "Emergency Medicine": "#ef4444",
  "Nuclear / Clean Energy": "#3b82f6",
  "Scalar Comms / Research": "#3b82f6",
  "Longevity / Epigenetics": "#a855f7",
  "Cloning / Reproductive Biology": "#22c55e",
  "Bioelectromagnetics / Diagnostics": "#06b6d4",
  "Industrial / Defense": "#94a3b8",
  "Longevity / Bioelectromagnetics": "#22c55e",
  "Renewable Energy / IoT": "#06b6d4",
  "Regenerative Medicine": "#22c55e",
  "Defense Meteorology / AI": "#06b6d4",
  "Defense / SIGINT": "#ef4444",
  "Defense / EMF Protection": "#3b82f6",
  "Vacuum Energy / Instrumentation": "#f59e0b",
};

export const MASTER_BUNDLE_PRICE = 197;
export const SINGLE_PACK_PRICE = 27;