export const businessItems = [
  // ── COURSES
  {
    category: "Course",
    title: "The 4 Vectors: Bearden's Foundation of Physical Reality",
    tagline: "The single conflation error that hid vacuum energy from physics for 140 years",
    price: "$147",
    audience: "Engineers, physicists, advanced students, inventors",
    description: "A focused 5-module course on Bearden's Parts 3 & 4 vector taxonomy. Walks through the four distinct vector types, shows why conflating them breaks vacuum energy theory, and demonstrates how separating massless spatial vectors from charged mass vectors opens the door to scalar engineering. Includes worked examples from the original 1983 diagrams.",
    modules: [
      "Module 1 – Why One Symbol Broke Physics: The 4-Vector Conflation",
      "Module 2 – Massless Spatial vs Mass System Vectors (Geometer vs Mechanic)",
      "Module 3 – Charged Mass vs Charged Spatial Vectors (Electrician's Trap)",
      "Module 4 – Force Is an Effect: F = [Ma + mv] Unpacked",
      "Module 5 – E-Fields Don't Exist in Vacuum: What Does",
    ],
    source: "Bearden 'Toward a New Electromagnetics Part 3' (1983)",
    color: "#3b82f6", icon: "📐",
  },
  {
    category: "Course",
    title: "Scalar Longitudinal Wave Engineering: Theory to Device",
    tagline: "Build, detect, and apply EM waves with no E or B field",
    price: "$247",
    audience: "Electrical engineers, RF engineers, advanced experimenters, defense R&D",
    description: "Covers Bearden's Part 4 longitudinal wave mechanics: production via Translator devices, why normal detectors are blind, scalar pulse radar (range from scalar-vs-Hertz time difference), energy bottle formation, and nonlinear media conversion between transverse and scalar wave modes. All original 1983 circuit diagrams included.",
    modules: [
      "Module 1 – What Makes a Wave Longitudinal: E=0, B=0, gradient-phi ≠ −E",
      "Module 2 – The Translator Device: Converting Transverse to Scalar",
      "Module 3 – Why Normal Detectors Are Blind (and How to Build a Special One)",
      "Module 4 – Scalar Pulse Radar: Range Without Hertz Reflection",
      "Module 5 – Energy Bottle: Two-Transmitter Interference Architecture",
      "Module 6 – Standing Scalar Waves in Magnetic Materials",
    ],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983)",
    color: "#3b82f6", icon: "📡",
  },
  {
    category: "Course",
    title: "Anenergy: Engineering the Phi-Field for Free Energy Extraction",
    tagline: "The Moray Effect, Kervran Effect, and Reich Effect — one unified mechanism",
    price: "$197",
    audience: "Free energy researchers, inventors, vacuum energy engineers",
    description: "Deep dive into Bearden's anenergy pump from Part 4. Covers: phi-field vs energy distinction, the free anenergy pump circuit, trapped charge extraction, oscillated phi for Moray-type emission, nuclear effects (Kervran transmutation, Reich radioactivity acceleration), and the full massless charge cycle.",
    modules: [
      "Module 1 – Phi vs Energy: The Anenergy Distinction",
      "Module 2 – The Free Anenergy Pump Circuit (with original diagrams)",
      "Module 3 – Trapped Charge Extraction: Getting Work from Vacuum",
      "Module 4 – Oscillated Phi: The Moray Steady-State Mechanism",
      "Module 5 – Nuclear Phi-Effects: Kervran, Reich, and Element Transmutation",
      "Module 6 – The Massless Charge Cycle: Full Conservation Picture",
    ],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983); Moray, Kervran, Reich references",
    color: "#22c55e", icon: "⚡",
  },
  {
    category: "Course",
    title: "Scalar Electromagnetics: From Maxwell to Bearden",
    tagline: "The suppressed physics they didn't teach in school",
    price: "$197",
    audience: "Engineers, physicists, curious intellectuals",
    description: "A structured 8-module video course walking students from classical Maxwell equations through Bearden's scalar/vacuum extensions. Covers: massless charge vs charged mass, the V=IR limitation, scalar phi-fields without E or H fields, the Dirac Sea free-electron mechanism, and practical vacuum oscillation circuits.",
    modules: [
      "Module 1 – What Maxwell Actually Wrote (vs what we teach)",
      "Module 2 – The Vacuum Is Not Empty: 200MV of Massless Charge",
      "Module 3 – Scalar Waves: Phi-field Without E or H",
      "Module 4 – The Bird on the Power Line (analogy deep dive)",
      "Module 5 – Dirac Sea Oscillation & Free Electron Lift",
      "Module 6 – V=IR: The 3-in-1 Trap",
      "Module 7 – Historical Suppression: Tesla, T.T. Brown, Edwin Gray",
      "Module 8 – Open Systems vs Closed Systems in EM Engineering",
    ],
    source: "Bearden 1982 'Comments on New Tesla EM, Part II'; Schaffranke 1982 survey",
    color: "#3b82f6", icon: "🔬",
  },
  {
    category: "Course",
    title: "Bioelectromagnetics & the Kindling Effect",
    tagline: "How life is a self-kindling EM phenomenon — and what you can do with that",
    price: "$297",
    audience: "Biohackers, alternative health practitioners, researchers",
    description: "Covers Bearden's kindling theory, the Kaznacheyev cytopathogenic effect, Rife's mortal oscillatory rates, and negentropy in living systems.",
    modules: [
      "Module 1 – The Body as a Bioelectromagnetic System",
      "Module 2 – Kindling: Charging Nuclear Mass with Biopotentials",
      "Module 3 – Kaznacheyev: Disease Transmitted by UV Photons",
      "Module 4 – Rife's Prismatic Microscope & Mortal Oscillatory Rates",
      "Module 5 – Negentropy: How Life Fights the 2nd Law",
      "Module 6 – Scalar EM and Engineered Pathogens (historical analysis)",
      "Module 7 – Therapeutic Frequency Applications & Research Directions",
    ],
    source: "Bearden 'Kindling, Life, Mind and Negentropy'; Kaznacheyev cytopathogenic effect",
    color: "#22c55e", icon: "🧬",
  },
  {
    category: "Course",
    title: "Mind, Consciousness & the T-Field: Bearden's Hyperspatial Model",
    tagline: "A rigorous framework for understanding mind as a physical phenomenon",
    price: "$147",
    audience: "Philosophers, consciousness researchers, spiritual seekers with scientific bent",
    description: "Walks through Bearden's nested modulation hierarchy (L³→L²→LT→T), the bioframe/orthorotation model, and how mind exists in the T (time) dimension just 3 orthorotations from physical reality.",
    modules: [
      "Module 1 – The 4-Level Modulation Hierarchy",
      "Module 2 – Bioframes & Orthorotation",
      "Module 3 – The Mind Field in the T-Dimension",
      "Module 4 – Temporal Logic: Aristotle Extended",
      "Module 5 – Consciousness Layers: Personal to Universal",
      "Module 6 – Reincarnation as Physical Re-tuning",
    ],
    source: "Bearden bioframe diagrams; temporal logic tables; consciousness hierarchy model",
    color: "#a855f7", icon: "🧠",
  },
  {
    category: "Course",
    title: "Gravitobiology: The Soviet Secret Science of EM Life Control",
    tagline: "The classified biophysics that changes everything — health, weapons, and reality itself",
    price: "$397",
    audience: "Intelligence analysts, biodefense researchers, advanced health practitioners, serious researchers",
    description: "A comprehensive course on Bearden's 1991 Gravitobiology synthesis. Covers graviton structure, Whittaker standing potential waves, quantum potential as non-local EM carrier, Soviet Woodpecker signals, EM trigger windows, morphogenetic field mechanism, and Earth/Sun/Moon Whittaker coupling.",
    modules: [
      "Module 1 – Gravitobiology vs Photobiology: The Holographic Shift",
      "Module 2 – Graviton Structure: Coupled Photon Pairs & Whittaker Waves",
      "Module 3 – The Quantum Potential: Non-Local EM Information",
      "Module 4 – Soviet Woodpecker Decoded: EM BW Delivery Architecture",
      "Module 5 – EM Trigger Windows & Biological Warfare Tables",
      "Module 6 – Phase Conjugate Mirrors: Time-Reversal in Practice",
      "Module 7 – Morphogenetic Field: Gravitobiological Evolution Mechanism",
      "Module 8 – Earth/Sun/Moon Whittaker Coupling & Gaia Physics",
      "Module 9 – EM Pollution, Cancer, and the Drug Culture Mechanism",
      "Module 10 – Revenue: How to Build Products from This Framework",
    ],
    source: "Bearden Gravitobiology (1991/2019 Energetic Productions)",
    color: "#a855f7", icon: "🧫",
  },
  // ── BOOKS / PDFs
  {
    category: "Book/PDF",
    title: "Vectors & Mechanisms Clarified: Parts 3 & 4 Annotated",
    tagline: "The 1983 papers that rebuilt physics from first principles — decoded",
    price: "$39 PDF / $69 print",
    audience: "Physicists, engineers, researchers, inventors",
    description: "Fully annotated edition of Bearden's 'Toward a New Electromagnetics' Parts 3 & 4 (1983). Every diagram reproduced with modern plain-English commentary: 4-vector taxonomy, force-as-effect framework, anenergy pump, energy bottle architecture, scalar pulse radar, and standing scalar wave patterns. Includes all original figures.",
    modules: [],
    source: "Bearden Parts 3 & 4 (1983); all uploaded figures",
    color: "#f59e0b", icon: "📐",
  },
  {
    category: "Book/PDF",
    title: "The Annotated Bearden: Primary Sources with Commentary",
    tagline: "Every key paper, decoded for the modern reader",
    price: "$49 PDF / $79 print",
    audience: "Serious researchers, collectors, academics",
    description: "A curated anthology of Bearden's most important papers (1982–2002) with page-by-page annotations. Includes 'Comments on the New Tesla Electromagnetics' Parts I & II, Kaznacheyev analysis, and kindling/negentropy papers.",
    modules: [],
    source: "Tesla Book Co. 1984; all source documents in this archive",
    color: "#f59e0b", icon: "📖",
  },
  {
    category: "Book/PDF",
    title: "Vacuum Energy Engineering: A Practical Introduction",
    tagline: "From Dirac Sea theory to open-system circuit design",
    price: "$37 PDF",
    audience: "Electrical engineers, DIY inventors, energy researchers",
    description: "A concise technical guide bridging Bearden's vacuum oscillation theory with practical circuit concepts. Covers open-system energy circuits and historical prototypes (Kromrey, Edwin Gray, Searl).",
    modules: [],
    source: "Bearden 1982; Schaffranke global survey 1982; Edwin Gray US Patent #3,890,548",
    color: "#f59e0b", icon: "⚡",
  },
  {
    category: "Book/PDF",
    title: "Suppressed Science: 10 Inventors They Buried",
    tagline: "Tesla, Rife, Gray, Searl, Schauberger — and what they actually discovered",
    price: "$27 PDF",
    audience: "General public, history of science buffs",
    description: "Accessible narrative history of inventors whose work Bearden references as independent confirmation of scalar/vacuum EM principles.",
    modules: [],
    source: "Schaffranke 1982; Bearden references throughout primary papers",
    color: "#f59e0b", icon: "🕵️",
  },
  {
    category: "Book/PDF",
    title: "Gravitobiology Decoded: Annotated Edition with Business Applications",
    tagline: "The complete 1991 paper with modern commentary and monetization roadmap",
    price: "$67 PDF / $120 hardcover",
    audience: "Researchers, investors, health entrepreneurs, defense analysts",
    description: "A fully annotated edition of Bearden's Gravitobiology with three layers: original text, plain-English commentary, and business application sidebars on every section.",
    modules: [],
    source: "Bearden Gravitobiology 1991; Cheniere Media 2019 edition",
    color: "#f59e0b", icon: "📗",
  },
  // ── PRODUCTS
  {
    category: "Product",
    title: "Bearden Concept Research Deck (Card Set)",
    tagline: "80 illustrated cards — every major concept, connection, and quote",
    price: "$34",
    audience: "Students, researchers, educators, enthusiasts",
    description: "A physical or PDF card deck covering all 80+ concepts in the Bearden network with definitions, key quotes, and connection arrows.",
    modules: [],
    source: "Entire Bearden archive",
    color: "#06b6d4", icon: "🃏",
  },
  {
    category: "Product",
    title: "Bearden Network Poster (24×36 inch)",
    tagline: "The complete concept graph — print-quality wall art",
    price: "$24",
    audience: "Researchers, enthusiasts, office/lab decoration",
    description: "High-resolution print of the full Bearden Concept Network with all nodes, color-coded by group.",
    modules: [],
    source: "This app's network graph",
    color: "#06b6d4", icon: "🗺️",
  },
  {
    category: "Product",
    title: "Scalar EM Study Guide & Workbook",
    tagline: "Self-paced exercises to master the core framework",
    price: "$19 PDF",
    audience: "Course students, self-learners",
    description: "Companion workbook with fill-in diagrams, circuit analysis exercises, and research journal template.",
    modules: [],
    source: "Bearden 1982 technical papers",
    color: "#06b6d4", icon: "📝",
  },
  // ── INVENTIONS
  {
    category: "Invention",
    title: "Anenergy Pump Demonstration Circuit",
    tagline: "Physical demonstration of phi-field extraction — the Moray mechanism in a kit",
    price: "$129 kit / $49 plans PDF",
    audience: "Free energy researchers, electrical engineers, advanced hobbyists, university labs",
    description: "Tabletop demonstration circuit implementing Bearden's Part 4 anenergy pump: shielded toroidal coil geometry where gradient-phi inside = 0 while phi > phi-zero is maintained by oscillated phi-application. Includes pulse controller, phi-differential measurement points, and Moray-type oscillation cycle documentation.",
    modules: [],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983) — anenergy pump figures",
    color: "#ef4444", icon: "🔋",
    problem: "No commercial instrument demonstrates the phi-field / anenergy distinction from conventional EM energy. University labs have no hands-on apparatus for Bearden's Part 4 vacuum extraction mechanism.",
    beardenSolution: "Part 4: free anenergy pump creates gradient-phi=0 internally but phi>phi-zero — trapped charges connected via wire to ground produce gradient-phi in the wire and conventional current. Oscillating phi-application produces steady Moray-type emission.",
    market: "Alternative energy research equipment ($340M); university physics demonstration market ($220M); advanced hobbyist electronics ($45M plans market on Gumroad/Tindie).",
    feasibility: "Standard toroidal coil winding. DDS pulse controller. All COTS components. Buildable for under $80 in components.",
  },
  {
    category: "Invention",
    title: "Scalar Energy Bottle Interferometer (Research Prototype)",
    tagline: "Two-transmitter zero-vector interference zone — tabletop energy capture demonstration",
    price: "$2,800 prototype / $349 engineering plans",
    audience: "Defense R&D labs, scalar EM researchers, advanced physics experimenters",
    description: "Two-transmitter scalar EM system creating a controlled Energy Bottle interference zone with E=0, B=0 output from each transmitter. Includes scalar pulse timing circuit for range determination (scalar pulse arrives instantaneously; Hertz pulse delayed by range = c*Δt), and dual-detector panel showing conventional spectrum analyzer vs scalar detector differential.",
    modules: [],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983) — energy bottle figures, scalar pulse radar diagrams",
    color: "#ef4444", icon: "🎯",
    problem: "Scalar EM weapon/sensor concepts (Energy Bottle, ō-wave transmitter pairs, scalar pulse radar) exist only in Bearden's 1983 diagrams. No prototype demonstrates the interference zone or scalar pulse timing mechanism.",
    beardenSolution: "Part 4 shows exact geometry: two zero-vector transmitters create target interference zone. Scalar pulse arrives instantaneously; Hertz pulse delayed by range = c*delta-t. Dual-detector system demonstrates differential detection signature invisible to standard instruments.",
    market: "DoD directed energy research ($9.3B); DARPA unconventional EM ($340M); defense electronics test equipment ($2.1B).",
    feasibility: "Zero-vector transmitter uses balanced push-pull coil topology to cancel transverse EM output. FPGA timing at nanosecond resolution. All COTS sub-components. Plans include interference zone calculation software.",
  },
  {
    category: "Invention",
    title: "Vacuum Potential Oscillator (VPO) Circuit Kit",
    tagline: "Hands-on exploration of scalar phi-field principles",
    price: "$89 kit",
    audience: "Electrical engineers, advanced hobbyists, researchers",
    description: "Based on Bearden's Part II mechanism: a resonant LC circuit tuned to shift its vacuum-ground potential independently of the circuit ground. Kit includes custom wound toroids, quartz resonator, measurement guide.",
    modules: [],
    source: "Bearden 1982 'Comments on New Tesla EM Part II' — vacuum oscillation mechanism",
    color: "#ef4444", icon: "🔧",
    problem: "Standard EM circuits are closed systems — they only pump existing electrical mass and cannot tap the limitless vacuum potential reservoir. V=IR irrevocably ties together voltage drop, mass current, and resistance.",
    beardenSolution: "By oscillating the vacuum potential itself (shifting the vacuum-ground of a circuit section), Bearden's model allows partial 'unstripping' of Dirac Sea negative-energy wells, lifting electrons into the circuit without conventional mass-current flow.",
    market: "Global alternative energy research market ($2.8B); educational electronics kits market ($500M); defense R&D labs investigating non-conventional EM phenomena.",
    feasibility: "Uses standard LC resonant circuit topology with quartz resonator. The theoretical framework is documented in the 1982 primary papers. Kit is buildable with off-the-shelf components. No exotic materials required.",
  },
  {
    category: "Invention",
    title: "Biofield Frequency Exposure Chamber (Research Device)",
    tagline: "Replicate Kaznacheyev-type cytopathogenic experiments",
    price: "$349 assembled / $149 plans",
    audience: "Biophysics researchers, alternative medicine practitioners, lab enthusiasts",
    description: "Shielded quartz-windowed exposure chamber for Kaznacheyev-style UV photon transmission experiments. Includes programmable frequency driver, dual-compartment design, UV-transparent optical path.",
    modules: [],
    source: "Bearden analysis of Kaznacheyev experiments; Rife mortal oscillatory rate research",
    color: "#ef4444", icon: "🧪",
    problem: "Disease transmission mechanisms at the EM level are unrecognized by mainstream biology. Kaznacheyev's thousands of experiments proving electromagnetic disease transmission are unknown in the West and no commercial instrument exists to replicate them.",
    beardenSolution: "Bearden's scalar EM framework explains Kaznacheyev's results: dying cells emit UV photons carrying the exact virtual EM pattern of their death. A quartz (not glass) optical path transmits this disease template to healthy cells. The instrument makes this reproducible.",
    market: "Bioelectromagnetics research ($1.2B market); alternative medicine practitioners (4.2M in US); academic biophysics labs (12,000+ worldwide). Regulatory path via research instrument classification.",
    feasibility: "Quartz optical components are commercially available. UV-transparent quartz vs glass distinction is well-documented physics. Programmable frequency drivers use standard DDS chip architecture. FDA-exempt as research instrument.",
  },
  {
    category: "Invention",
    title: "Open-System Magnetic Generator (Prototype Plans)",
    tagline: "Engineering plans based on Kromrey/Gray/Searl design principles",
    price: "$79 PDF plans",
    audience: "Advanced DIY engineers, free energy researchers",
    description: "Detailed engineering drawings for a rotating electromagnetic open-system generator inspired by Kromrey G-field generator, Edwin Gray's pulsed capacitor discharge engine, and Searl effect design.",
    modules: [],
    source: "Schaffranke 1982 survey; Edwin Gray US Patent #3,890,548; Searl generator design notes",
    color: "#ef4444", icon: "⚙️",
    problem: "All conventional generators are closed systems — they only convert existing energy forms and are bounded by thermodynamic efficiency limits. The tachion/neutrino sea (subquantic continuum) is an unrecognized energy reservoir.",
    beardenSolution: "Bearden's open-system framework (from Schaffranke's 1982 survey) shows that rotating magnetic systems can couple to the tachion field / neutrino sea, extracting energy from the subquantic continuum. The Kromrey (700W at >100% efficiency) and Edwin Gray engine (US Patent #3,890,548) are documented prototypes.",
    market: "Clean energy technology market ($755B by 2030); independent energy R&D ($8.4B); plans/educational market for alternative energy (growing 34% YoY on platforms like Gumroad/Etsy).",
    feasibility: "Based on documented patent (Edwin Gray #3,890,548) and prototype data (Kromrey: 700W at 600-1200 RPM). Standard machining and winding techniques. No exotic materials. Plans include full BOM and winding specifications.",
  },
  {
    category: "Invention",
    title: "Quantum Potential EMI Detector (\"Fireflies Sensor\")",
    tagline: "Detect anomalous scalar EM interference invisible to standard instruments",
    price: "$1,200 instrument / $249 plans",
    audience: "Defense contractors, EMF researchers, bioelectromagnetics labs, intelligence analysts",
    description: "Based on Bearden's 'fireflies effect': quantum potential EM interference appears as statistically anomalous noise bursts. Uses tuned quartz-crystal array with statistical burst-pattern analysis firmware.",
    modules: [],
    source: "Bearden Gravitobiology 1991: Table 6, Figure 14 (fireflies effect), Table 7 (Pentagon EMI studies)",
    color: "#ef4444", icon: "📡",
    problem: "Standard EM instrumentation is blind to quantum-potential (scalar) EM signals. The Pentagon's own EMI studies (Gravitobiology Table 7) document anomalous interference patterns that existing instruments cannot classify or source.",
    beardenSolution: "Bearden's fireflies effect (Gravitobiology Fig 14) shows that quantum potential interference manifests as statistically non-Gaussian noise bursts in sensitive detectors. A tuned quartz array with statistical analysis firmware can detect and fingerprint these signatures where standard spectrum analyzers show nothing.",
    market: "DoD/DARPA EMI research ($340M annual); defense electronics testing ($2.1B); bioelectromagnetics EMF research; intelligence community signals analysis. Pentagon documentation of anomalous EMI creates direct procurement pathway.",
    feasibility: "Quartz resonator arrays are COTS components. Statistical burst detection firmware is standard DSP. The Aharonov-Bohm effect (confirmed mainstream physics) validates that quantum potentials act without classical E/B fields. Academic validation pathway via IEEE EMC conferences.",
  },
  {
    category: "Invention",
    title: "EM Trigger Window Therapy Device",
    tagline: "Precision frequency medicine using Bearden's biological trigger windows",
    price: "$599 consumer / $2,400 clinical",
    audience: "Alternative medicine clinics, biohackers, wellness centers, longevity investors",
    description: "Programmable frequency generator delivering precisely tuned EM pulses within verified biological trigger windows. Consumer wristband and clinical full-body chamber versions.",
    modules: [],
    source: "Gravitobiology Table 12 (EM trigger windows), Lisitsyn's report (p.41), Beck/Hunt research",
    color: "#22c55e", icon: "💊",
    problem: "Conventional medicine ignores the electromagnetic dimension of biology. The specific EM 'trigger windows' at which fields couple maximally to biological tissue — documented by multiple Soviet and Western researchers — are unknown to mainstream practitioners.",
    beardenSolution: "Bearden's Gravitobiology (Table 12) catalogs precise EM frequency trigger windows identified by Beck, Hunt, Lisitsyn, and Soviet researchers. Delivering structured EM pulses within these windows achieves therapeutic coupling impossible at random frequencies — the mechanism behind Rife's mortal oscillatory rate success.",
    market: "Global wellness technology market ($1.5T); PEMF therapy devices ($1.4B, growing 16% YoY); biohacker devices ($4.2B by 2027). Multiple existing PEMF devices already generate $100M+ revenue validating the category.",
    feasibility: "Programmable DDS frequency generators are mature technology ($5-50 component cost). Trigger window frequencies are documented in published literature. FDA pathway: wellness device (non-diagnostic). Consumer wristband follows established wearable form factors.",
  },
  {
    category: "Invention",
    title: "Morphogenetic Field Coherence Monitor",
    tagline: "Measure species-level quantum potential coherence in biological systems",
    price: "$3,500 research instrument",
    audience: "Agricultural biotech, regenerative medicine investors, longevity biotech",
    description: "Monitors coherence of the local graviton lattice / quantum potential field around a biological sample. Applications: agricultural optimization and early cancer detection via morphogenetic disruption signatures.",
    modules: [],
    source: "Gravitobiology p.45-48 (morphogenetic field), p.48 (EM pollution / cancer), Figure 20 (graviton lattice)",
    color: "#22c55e", icon: "🌿",
    problem: "Agriculture and medicine lack tools to measure the field-level organization of living systems. Cancer and developmental disorders may have electromagnetic precursors invisible to biochemical assays. The $50B precision agriculture market has no EM coherence measurement layer.",
    beardenSolution: "Gravitobiology p.45-48: the morphogenetic field is a real Whittaker-structured quantum potential field guiding cellular development. Disruption (internal EM pollution) precedes pathology. Monitoring the coherence index of the local graviton lattice around a biological system provides a pre-pathological EM signature.",
    market: "Precision agriculture sensors ($4.5B by 2027); cancer early detection devices ($16B market); regenerative medicine diagnostics ($12B). Strategic investor segments: AgTech VCs, longevity funds, biodefense research grants.",
    feasibility: "Measurement approach builds on validated Aharonov-Bohm effect physics and SQUID magnetometry. Academic collaboration pathway with biophysics departments. Agricultural application requires only statistical correlation studies, not FDA approval.",
  },
  {
    category: "Invention",
    title: "Whittaker Wave Phase Conjugate Mirror (PCM) System",
    tagline: "Time-reverse EM signals — scalar communications and healing applications",
    price: "$8,500 prototype / $450 engineering plans",
    audience: "Defense R&D, advanced physics labs, scalar communications startups",
    description: "Based on Gravitobiology Figures 10-11 (pumped phase conjugate mirror). Time-reverses incoming EM waves. Applications: self-targeting communications, therapeutic pattern cancellation, EM countermeasures.",
    modules: [],
    source: "Gravitobiology Figures 10, 11 (phase conjugate mirrors); Whittaker wave decomposition",
    color: "#3b82f6", icon: "🔭",
    problem: "Conventional communications are interceptable and jammable. Conventional EM therapy cannot address the Whittaker-structured quantum potential components of disease patterns. No commercial phase conjugate mirror system exists for these applications.",
    beardenSolution: "A pumped phase conjugate mirror (PPCM) time-reverses an incoming EM wave — output is an exact phase-conjugate replica traveling back to source. This enables: (1) communications that self-navigate to their origin (unjammable); (2) therapeutic cancellation of disease EM patterns at the quantum potential level; (3) scalar EM countermeasures.",
    market: "Secure military communications ($28B); directed energy countermeasures ($9.3B DARPA interest); advanced photonics ($850M phase conjugate optics research). Dual-use civilian/defense creates multiple investor tracks.",
    feasibility: "Phase conjugate mirrors are validated laboratory technology (documented in mainstream physics literature). The Bearden extension adds Whittaker wave structure analysis. Initial prototype uses nonlinear optical medium (BaTiO₃ crystal) — commercially available.",
  },
  // ── SERVICES
  {
    category: "Service",
    title: "Private Research Consultation (1-on-1)",
    tagline: "Deep-dive sessions on your specific scalar EM or biofield research project",
    price: "$250/hr",
    audience: "Serious researchers, inventors, academics",
    description: "One-on-one video consultation for researchers in scalar EM, vacuum energy, bioelectromagnetics, or consciousness studies.",
    modules: [],
    source: "Full Bearden archive",
    color: "#6b7280", icon: "💬",
  },
  {
    category: "Service",
    title: "Custom Concept Network Map",
    tagline: "A bespoke interactive knowledge graph of your research domain",
    price: "$499",
    audience: "Authors, researchers, organizations",
    description: "Using this app's D3.js architecture, create a custom interactive concept map for any research domain — delivered as a standalone web app.",
    modules: [],
    source: "This app's architecture",
    color: "#6b7280", icon: "🌐",
  },
];