export const businessItems = [
  // ── COURSES
  {
    category: "Course",
    title: "The 4 Vectors: Bearden's Foundation of Physical Reality",
    tagline: "The single conflation error that hid vacuum energy from physics for 140 years",
    price: "$147",
    audience: "Engineers, physicists, advanced students, inventors",
    description: "A focused 5-module course on Bearden's Parts 3 & 4 vector taxonomy. Walks through the four distinct vector types, shows why conflating them breaks vacuum energy theory, and demonstrates how separating massless spatial vectors from charged mass vectors opens the door to scalar engineering. Includes worked examples from the original 1983 diagrams.",
    modules: [
      "Module 1 – Why One Symbol Broke Physics: The 4-Vector Conflation",
      "Module 2 – Massless Spatial vs Mass System Vectors (Geometer vs Mechanic)",
      "Module 3 – Charged Mass vs Charged Spatial Vectors (Electrician's Trap)",
      "Module 4 – Force Is an Effect: F = [Ma + mv] Unpacked",
      "Module 5 – E-Fields Don't Exist in Vacuum: What Does",
    ],
    source: "Bearden 'Toward a New Electromagnetics Part 3' (1983)",
    color: "#3b82f6", icon: "📐",
  },
  {
    category: "Course",
    title: "Scalar Longitudinal Wave Engineering: Theory to Device",
    tagline: "Build, detect, and apply EM waves with no E or B field",
    price: "$247",
    audience: "Electrical engineers, RF engineers, advanced experimenters, defense R&D",
    description: "Covers Bearden's Part 4 longitudinal wave mechanics: production via Translator devices, why normal detectors are blind, scalar pulse radar (range from scalar-vs-Hertz time difference), energy bottle formation, and nonlinear media conversion between transverse and scalar wave modes. All original 1983 circuit diagrams included.",
    modules: [
      "Module 1 – What Makes a Wave Longitudinal: E=0, B=0, gradient-phi ≠ −E",
      "Module 2 – The Translator Device: Converting Transverse to Scalar",
      "Module 3 – Why Normal Detectors Are Blind (and How to Build a Special One)",
      "Module 4 – Scalar Pulse Radar: Range Without Hertz Reflection",
      "Module 5 – Energy Bottle: Two-Transmitter Interference Architecture",
      "Module 6 – Standing Scalar Waves in Magnetic Materials",
    ],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983)",
    color: "#3b82f6", icon: "📡",
  },
  {
    category: "Course",
    title: "Anenergy: Engineering the Phi-Field for Free Energy Extraction",
    tagline: "The Moray Effect, Kervran Effect, and Reich Effect — one unified mechanism",
    price: "$197",
    audience: "Free energy researchers, inventors, vacuum energy engineers",
    description: "Deep dive into Bearden's anenergy pump from Part 4. Covers: phi-field vs energy distinction, the free anenergy pump circuit, trapped charge extraction, oscillated phi for Moray-type emission, nuclear effects (Kervran transmutation, Reich radioactivity acceleration), and the full massless charge cycle.",
    modules: [
      "Module 1 – Phi vs Energy: The Anenergy Distinction",
      "Module 2 – The Free Anenergy Pump Circuit (with original diagrams)",
      "Module 3 – Trapped Charge Extraction: Getting Work from Vacuum",
      "Module 4 – Oscillated Phi: The Moray Steady-State Mechanism",
      "Module 5 – Nuclear Phi-Effects: Kervran, Reich, and Element Transmutation",
      "Module 6 – The Massless Charge Cycle: Full Conservation Picture",
    ],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983); Moray, Kervran, Reich references",
    color: "#22c55e", icon: "⚡",
  },
  {
    category: "Course",
    title: "Scalar Electromagnetics: From Maxwell to Bearden",
    tagline: "The suppressed physics they didn't teach in school",
    price: "$197",
    audience: "Engineers, physicists, curious intellectuals",
    description: "A structured 8-module video course walking students from classical Maxwell equations through Bearden's scalar/vacuum extensions. Covers: massless charge vs charged mass, the V=IR limitation, scalar phi-fields without E or H fields, the Dirac Sea free-electron mechanism, and practical vacuum oscillation circuits.",
    modules: [
      "Module 1 – What Maxwell Actually Wrote (vs what we teach)",
      "Module 2 – The Vacuum Is Not Empty: 200MV of Massless Charge",
      "Module 3 – Scalar Waves: Phi-field Without E or H",
      "Module 4 – The Bird on the Power Line (analogy deep dive)",
      "Module 5 – Dirac Sea Oscillation & Free Electron Lift",
      "Module 6 – V=IR: The 3-in-1 Trap",
      "Module 7 – Historical Suppression: Tesla, T.T. Brown, Edwin Gray",
      "Module 8 – Open Systems vs Closed Systems in EM Engineering",
    ],
    source: "Bearden 1982 'Comments on New Tesla EM, Part II'; Schaffranke 1982 survey",
    color: "#3b82f6", icon: "🔬",
  },
  {
    category: "Course",
    title: "Bioelectromagnetics & the Kindling Effect",
    tagline: "How life is a self-kindling EM phenomenon — and what you can do with that",
    price: "$297",
    audience: "Biohackers, alternative health practitioners, researchers",
    description: "Covers Bearden's kindling theory, the Kaznacheyev cytopathogenic effect, Rife's mortal oscillatory rates, and negentropy in living systems.",
    modules: [
      "Module 1 – The Body as a Bioelectromagnetic System",
      "Module 2 – Kindling: Charging Nuclear Mass with Biopotentials",
      "Module 3 – Kaznacheyev: Disease Transmitted by UV Photons",
      "Module 4 – Rife's Prismatic Microscope & Mortal Oscillatory Rates",
      "Module 5 – Negentropy: How Life Fights the 2nd Law",
      "Module 6 – Scalar EM and Engineered Pathogens (historical analysis)",
      "Module 7 – Therapeutic Frequency Applications & Research Directions",
    ],
    source: "Bearden 'Kindling, Life, Mind and Negentropy'; Kaznacheyev cytopathogenic effect",
    color: "#22c55e", icon: "🧬",
  },
  {
    category: "Course",
    title: "Mind, Consciousness & the T-Field: Bearden's Hyperspatial Model",
    tagline: "A rigorous framework for understanding mind as a physical phenomenon",
    price: "$147",
    audience: "Philosophers, consciousness researchers, spiritual seekers with scientific bent",
    description: "Walks through Bearden's nested modulation hierarchy (L³→L²→LT→T), the bioframe/orthorotation model, and how mind exists in the T (time) dimension just 3 orthorotations from physical reality.",
    modules: [
      "Module 1 – The 4-Level Modulation Hierarchy",
      "Module 2 – Bioframes & Orthorotation",
      "Module 3 – The Mind Field in the T-Dimension",
      "Module 4 – Temporal Logic: Aristotle Extended",
      "Module 5 – Consciousness Layers: Personal to Universal",
      "Module 6 – Reincarnation as Physical Re-tuning",
    ],
    source: "Bearden bioframe diagrams; temporal logic tables; consciousness hierarchy model",
    color: "#a855f7", icon: "🧠",
  },
  {
    category: "Course",
    title: "Gravitobiology: The Soviet Secret Science of EM Life Control",
    tagline: "The classified biophysics that changes everything — health, weapons, and reality itself",
    price: "$397",
    audience: "Intelligence analysts, biodefense researchers, advanced health practitioners, serious researchers",
    description: "A comprehensive course on Bearden's 1991 Gravitobiology synthesis. Covers graviton structure, Whittaker standing potential waves, quantum potential as non-local EM carrier, Soviet Woodpecker signals, EM trigger windows, morphogenetic field mechanism, and Earth/Sun/Moon Whittaker coupling.",
    modules: [
      "Module 1 – Gravitobiology vs Photobiology: The Holographic Shift",
      "Module 2 – Graviton Structure: Coupled Photon Pairs & Whittaker Waves",
      "Module 3 – The Quantum Potential: Non-Local EM Information",
      "Module 4 – Soviet Woodpecker Decoded: EM BW Delivery Architecture",
      "Module 5 – EM Trigger Windows & Biological Warfare Tables",
      "Module 6 – Phase Conjugate Mirrors: Time-Reversal in Practice",
      "Module 7 – Morphogenetic Field: Gravitobiological Evolution Mechanism",
      "Module 8 – Earth/Sun/Moon Whittaker Coupling & Gaia Physics",
      "Module 9 – EM Pollution, Cancer, and the Drug Culture Mechanism",
      "Module 10 – Revenue: How to Build Products from This Framework",
    ],
    source: "Bearden Gravitobiology (1991/2019 Energetic Productions)",
    color: "#a855f7", icon: "🧫",
  },
  // ── BOOKS / PDFs
  {
    category: "Book/PDF",
    title: "Vectors & Mechanisms Clarified: Parts 3 & 4 Annotated",
    tagline: "The 1983 papers that rebuilt physics from first principles — decoded",
    price: "$39 PDF / $69 print",
    audience: "Physicists, engineers, researchers, inventors",
    description: "Fully annotated edition of Bearden's 'Toward a New Electromagnetics' Parts 3 & 4 (1983). Every diagram reproduced with modern plain-English commentary: 4-vector taxonomy, force-as-effect framework, anenergy pump, energy bottle architecture, scalar pulse radar, and standing scalar wave patterns. Includes all original figures.",
    modules: [],
    source: "Bearden Parts 3 & 4 (1983); all uploaded figures",
    color: "#f59e0b", icon: "📐",
  },
  {
    category: "Book/PDF",
    title: "The Annotated Bearden: Primary Sources with Commentary",
    tagline: "Every key paper, decoded for the modern reader",
    price: "$49 PDF / $79 print",
    audience: "Serious researchers, collectors, academics",
    description: "A curated anthology of Bearden's most important papers (1982–2002) with page-by-page annotations. Includes 'Comments on the New Tesla Electromagnetics' Parts I & II, Kaznacheyev analysis, and kindling/negentropy papers.",
    modules: [],
    source: "Tesla Book Co. 1984; all source documents in this archive",
    color: "#f59e0b", icon: "📖",
  },
  {
    category: "Book/PDF",
    title: "Vacuum Energy Engineering: A Practical Introduction",
    tagline: "From Dirac Sea theory to open-system circuit design",
    price: "$37 PDF",
    audience: "Electrical engineers, DIY inventors, energy researchers",
    description: "A concise technical guide bridging Bearden's vacuum oscillation theory with practical circuit concepts. Covers open-system energy circuits and historical prototypes (Kromrey, Edwin Gray, Searl).",
    modules: [],
    source: "Bearden 1982; Schaffranke global survey 1982; Edwin Gray US Patent #3,890,548",
    color: "#f59e0b", icon: "⚡",
  },
  {
    category: "Book/PDF",
    title: "Suppressed Science: 10 Inventors They Buried",
    tagline: "Tesla, Rife, Gray, Searl, Schauberger — and what they actually discovered",
    price: "$27 PDF",
    audience: "General public, history of science buffs",
    description: "Accessible narrative history of inventors whose work Bearden references as independent confirmation of scalar/vacuum EM principles.",
    modules: [],
    source: "Schaffranke 1982; Bearden references throughout primary papers",
    color: "#f59e0b", icon: "🕵️",
  },
  {
    category: "Book/PDF",
    title: "Gravitobiology Decoded: Annotated Edition with Business Applications",
    tagline: "The complete 1991 paper with modern commentary and monetization roadmap",
    price: "$67 PDF / $120 hardcover",
    audience: "Researchers, investors, health entrepreneurs, defense analysts",
    description: "A fully annotated edition of Bearden's Gravitobiology with three layers: original text, plain-English commentary, and business application sidebars on every section.",
    modules: [],
    source: "Bearden Gravitobiology 1991; Cheniere Media 2019 edition",
    color: "#f59e0b", icon: "📗",
  },
  // ── PRODUCTS
  {
    category: "Product",
    title: "Bearden Concept Research Deck (Card Set)",
    tagline: "80 illustrated cards — every major concept, connection, and quote",
    price: "$34",
    audience: "Students, researchers, educators, enthusiasts",
    description: "A physical or PDF card deck covering all 80+ concepts in the Bearden network with definitions, key quotes, and connection arrows.",
    modules: [],
    source: "Entire Bearden archive",
    color: "#06b6d4", icon: "🃏",
  },
  {
    category: "Product",
    title: "Bearden Network Poster (24×36 inch)",
    tagline: "The complete concept graph — print-quality wall art",
    price: "$24",
    audience: "Researchers, enthusiasts, office/lab decoration",
    description: "High-resolution print of the full Bearden Concept Network with all nodes, color-coded by group.",
    modules: [],
    source: "This app's network graph",
    color: "#06b6d4", icon: "🗺️",
  },
  {
    category: "Product",
    title: "Scalar EM Study Guide & Workbook",
    tagline: "Self-paced exercises to master the core framework",
    price: "$19 PDF",
    audience: "Course students, self-learners",
    description: "Companion workbook with fill-in diagrams, circuit analysis exercises, and research journal template.",
    modules: [],
    source: "Bearden 1982 technical papers",
    color: "#06b6d4", icon: "📝",
  },
  // ── INVENTIONS
  {
    category: "Invention",
    title: "Anenergy Pump Demonstration Circuit",
    tagline: "Physical demonstration of phi-field extraction — the Moray mechanism in a kit",
    price: "$129 kit / $49 plans PDF",
    audience: "Free energy researchers, electrical engineers, advanced hobbyists, university labs",
    description: "Tabletop demonstration circuit implementing Bearden's Part 4 anenergy pump: shielded toroidal coil geometry where gradient-phi inside = 0 while phi > phi-zero is maintained by oscillated phi-application. Includes pulse controller, phi-differential measurement points, and Moray-type oscillation cycle documentation.",
    modules: [],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983) — anenergy pump figures",
    color: "#ef4444", icon: "🔋",
    problem: "No commercial instrument demonstrates the phi-field / anenergy distinction from conventional EM energy. University labs have no hands-on apparatus for Bearden's Part 4 vacuum extraction mechanism.",
    beardenSolution: "Part 4: free anenergy pump creates gradient-phi=0 internally but phi>phi-zero — trapped charges connected via wire to ground produce gradient-phi in the wire and conventional current. Oscillating phi-application produces steady Moray-type emission.",
    market: "Alternative energy research equipment ($340M); university physics demonstration market ($220M); advanced hobbyist electronics ($45M plans market on Gumroad/Tindie).",
    feasibility: "Standard toroidal coil winding. DDS pulse controller. All COTS components. Buildable for under $80 in components.",
  },
  {
    category: "Invention",
    title: "Scalar Energy Bottle Interferometer (Research Prototype)",
    tagline: "Two-transmitter zero-vector interference zone — tabletop energy capture demonstration",
    price: "$2,800 prototype / $349 engineering plans",
    audience: "Defense R&D labs, scalar EM researchers, advanced physics experimenters",
    description: "Two-transmitter scalar EM system creating a controlled Energy Bottle interference zone with E=0, B=0 output from each transmitter. Includes scalar pulse timing circuit for range determination (scalar pulse arrives instantaneously; Hertz pulse delayed by range = c*Δt), and dual-detector panel showing conventional spectrum analyzer vs scalar detector differential.",
    modules: [],
    source: "Bearden 'Toward a New Electromagnetics Part 4' (1983) — energy bottle figures, scalar pulse radar diagrams",
    color: "#ef4444", icon: "🎯",
    problem: "Scalar EM weapon/sensor concepts (Energy Bottle, ō-wave transmitter pairs, scalar pulse radar) exist only in Bearden's 1983 diagrams. No prototype demonstrates the interference zone or scalar pulse timing mechanism.",
    beardenSolution: "Part 4 shows exact geometry: two zero-vector transmitters create target interference zone. Scalar pulse arrives instantaneously; Hertz pulse delayed by range = c*delta-t. Dual-detector system demonstrates differential detection signature invisible to standard instruments.",
    market: "DoD directed energy research ($9.3B); DARPA unconventional EM ($340M); defense electronics test equipment ($2.1B).",
    feasibility: "Zero-vector transmitter uses balanced push-pull coil topology to cancel transverse EM output. FPGA timing at nanosecond resolution. All COTS sub-components. Plans include interference zone calculation software.",
  },
  {
    category: "Invention",
    title: "Vacuum Potential Oscillator (VPO) Circuit Kit",
    tagline: "Hands-on exploration of scalar phi-field principles",
    price: "$89 kit",
    audience: "Electrical engineers, advanced hobbyists, researchers",
    description: "Based on Bearden's Part II mechanism: a resonant LC circuit tuned to shift its vacuum-ground potential independently of the circuit ground. Kit includes custom wound toroids, quartz resonator, measurement guide.",
    modules: [],
    source: "Bearden 1982 'Comments on New Tesla EM Part II' — vacuum oscillation mechanism",
    color: "#ef4444", icon: "🔧",
    problem: "Standard EM circuits are closed systems — they only pump existing electrical mass and cannot tap the limitless vacuum potential reservoir. V=IR irrevocably ties together voltage drop, mass current, and resistance.",
    beardenSolution: "By oscillating the vacuum potential itself (shifting the vacuum-ground of a circuit section), Bearden's model allows partial 'unstripping' of Dirac Sea negative-energy wells, lifting electrons into the circuit without conventional mass-current flow.",
    market: "Global alternative energy research market ($2.8B); educational electronics kits market ($500M); defense R&D labs investigating non-conventional EM phenomena.",
    feasibility: "Uses standard LC resonant circuit topology with quartz resonator. The theoretical framework is documented in the 1982 primary papers. Kit is buildable with off-the-shelf components. No exotic materials required.",
  },
  {
    category: "Invention",
    title: "Biofield Frequency Exposure Chamber (Research Device)",
    tagline: "Replicate Kaznacheyev-type cytopathogenic experiments",
    price: "$349 assembled / $149 plans",
    audience: "Biophysics researchers, alternative medicine practitioners, lab enthusiasts",
    description: "Shielded quartz-windowed exposure chamber for Kaznacheyev-style UV photon transmission experiments. Includes programmable frequency driver, dual-compartment design, UV-transparent optical path.",
    modules: [],
    source: "Bearden analysis of Kaznacheyev experiments; Rife mortal oscillatory rate research",
    color: "#ef4444", icon: "🧪",
    problem: "Disease transmission mechanisms at the EM level are unrecognized by mainstream biology. Kaznacheyev's thousands of experiments proving electromagnetic disease transmission are unknown in the West and no commercial instrument exists to replicate them.",
    beardenSolution: "Bearden's scalar EM framework explains Kaznacheyev's results: dying cells emit UV photons carrying the exact virtual EM pattern of their death. A quartz (not glass) optical path transmits this disease template to healthy cells. The instrument makes this reproducible.",
    market: "Bioelectromagnetics research ($1.2B market); alternative medicine practitioners (4.2M in US); academic biophysics labs (12,000+ worldwide). Regulatory path via research instrument classification.",
    feasibility: "Quartz optical components are commercially available. UV-transparent quartz vs glass distinction is well-documented physics. Programmable frequency drivers use standard DDS chip architecture. FDA-exempt as research instrument.",
  },
  {
    category: "Invention",
    title: "Open-System Magnetic Generator (Prototype Plans)",
    tagline: "Engineering plans based on Kromrey/Gray/Searl design principles",
    price: "$79 PDF plans",
    audience: "Advanced DIY engineers, free energy researchers",
    description: "Detailed engineering drawings for a rotating electromagnetic open-system generator inspired by Kromrey G-field generator, Edwin Gray's pulsed capacitor discharge engine, and Searl effect design.",
    modules: [],
    source: "Schaffranke 1982 survey; Edwin Gray US Patent #3,890,548; Searl generator design notes",
    color: "#ef4444", icon: "⚙️",
    problem: "All conventional generators are closed systems — they only convert existing energy forms and are bounded by thermodynamic efficiency limits. The tachion/neutrino sea (subquantic continuum) is an unrecognized energy reservoir.",
    beardenSolution: "Bearden's open-system framework (from Schaffranke's 1982 survey) shows that rotating magnetic systems can couple to the tachion field / neutrino sea, extracting energy from the subquantic continuum. The Kromrey (700W at >100% efficiency) and Edwin Gray engine (US Patent #3,890,548) are documented prototypes.",
    market: "Clean energy technology market ($755B by 2030); independent energy R&D ($8.4B); plans/educational market for alternative energy (growing 34% YoY on platforms like Gumroad/Etsy).",
    feasibility: "Based on documented patent (Edwin Gray #3,890,548) and prototype data (Kromrey: 700W at 600-1200 RPM). Standard machining and winding techniques. No exotic materials. Plans include full BOM and winding specifications.",
  },
  {
    category: "Invention",
    title: "Quantum Potential EMI Detector (\"Fireflies Sensor\")",
    tagline: "Detect anomalous scalar EM interference invisible to standard instruments",
    price: "$1,200 instrument / $249 plans",
    audience: "Defense contractors, EMF researchers, bioelectromagnetics labs, intelligence analysts",
    description: "Based on Bearden's 'fireflies effect': quantum potential EM interference appears as statistically anomalous noise bursts. Uses tuned quartz-crystal array with statistical burst-pattern analysis firmware.",
    modules: [],
    source: "Bearden Gravitobiology 1991: Table 6, Figure 14 (fireflies effect), Table 7 (Pentagon EMI studies)",
    color: "#ef4444", icon: "📡",
    problem: "Standard EM instrumentation is blind to quantum-potential (scalar) EM signals. The Pentagon's own EMI studies (Gravitobiology Table 7) document anomalous interference patterns that existing instruments cannot classify or source.",
    beardenSolution: "Bearden's fireflies effect (Gravitobiology Fig 14) shows that quantum potential interference manifests as statistically non-Gaussian noise bursts in sensitive detectors. A tuned quartz array with statistical analysis firmware can detect and fingerprint these signatures where standard spectrum analyzers show nothing.",
    market: "DoD/DARPA EMI research ($340M annual); defense electronics testing ($2.1B); bioelectromagnetics EMF research; intelligence community signals analysis. Pentagon documentation of anomalous EMI creates direct procurement pathway.",
    feasibility: "Quartz resonator arrays are COTS components. Statistical burst detection firmware is standard DSP. The Aharonov-Bohm effect (confirmed mainstream physics) validates that quantum potentials act without classical E/B fields. Academic validation pathway via IEEE EMC conferences.",
  },
  {
    category: "Invention",
    title: "EM Trigger Window Therapy Device",
    tagline: "Precision frequency medicine using Bearden's biological trigger windows",
    price: "$599 consumer / $2,400 clinical",
    audience: "Alternative medicine clinics, biohackers, wellness centers, longevity investors",
    description: "Programmable frequency generator delivering precisely tuned EM pulses within verified biological trigger windows. Consumer wristband and clinical full-body chamber versions.",
    modules: [],
    source: "Gravitobiology Table 12 (EM trigger windows), Lisitsyn's report (p.41), Beck/Hunt research",
    color: "#22c55e", icon: "💊",
    problem: "Conventional medicine ignores the electromagnetic dimension of biology. The specific EM 'trigger windows' at which fields couple maximally to biological tissue — documented by multiple Soviet and Western researchers — are unknown to mainstream practitioners.",
    beardenSolution: "Bearden's Gravitobiology (Table 12) catalogs precise EM frequency trigger windows identified by Beck, Hunt, Lisitsyn, and Soviet researchers. Delivering structured EM pulses within these windows achieves therapeutic coupling impossible at random frequencies — the mechanism behind Rife's mortal oscillatory rate success.",
    market: "Global wellness technology market ($1.5T); PEMF therapy devices ($1.4B, growing 16% YoY); biohacker devices ($4.2B by 2027). Multiple existing PEMF devices already generate $100M+ revenue validating the category.",
    feasibility: "Programmable DDS frequency generators are mature technology ($5-50 component cost). Trigger window frequencies are documented in published literature. FDA pathway: wellness device (non-diagnostic). Consumer wristband follows established wearable form factors.",
  },
  {
    category: "Invention",
    title: "Morphogenetic Field Coherence Monitor",
    tagline: "Measure species-level quantum potential coherence in biological systems",
    price: "$3,500 research instrument",
    audience: "Agricultural biotech, regenerative medicine investors, longevity biotech",
    description: "Monitors coherence of the local graviton lattice / quantum potential field around a biological sample. Applications: agricultural optimization and early cancer detection via morphogenetic disruption signatures.",
    modules: [],
    source: "Gravitobiology p.45-48 (morphogenetic field), p.48 (EM pollution / cancer), Figure 20 (graviton lattice)",
    color: "#22c55e", icon: "🌿",
    problem: "Agriculture and medicine lack tools to measure the field-level organization of living systems. Cancer and developmental disorders may have electromagnetic precursors invisible to biochemical assays. The $50B precision agriculture market has no EM coherence measurement layer.",
    beardenSolution: "Gravitobiology p.45-48: the morphogenetic field is a real Whittaker-structured quantum potential field guiding cellular development. Disruption (internal EM pollution) precedes pathology. Monitoring the coherence index of the local graviton lattice around a biological system provides a pre-pathological EM signature.",
    market: "Precision agriculture sensors ($4.5B by 2027); cancer early detection devices ($16B market); regenerative medicine diagnostics ($12B). Strategic investor segments: AgTech VCs, longevity funds, biodefense research grants.",
    feasibility: "Measurement approach builds on validated Aharonov-Bohm effect physics and SQUID magnetometry. Academic collaboration pathway with biophysics departments. Agricultural application requires only statistical correlation studies, not FDA approval.",
  },
  {
    category: "Invention",
    title: "Whittaker Wave Phase Conjugate Mirror (PCM) System",
    tagline: "Time-reverse EM signals — scalar communications and healing applications",
    price: "$8,500 prototype / $450 engineering plans",
    audience: "Defense R&D, advanced physics labs, scalar communications startups",
    description: "Based on Gravitobiology Figures 10-11 (pumped phase conjugate mirror). Time-reverses incoming EM waves. Applications: self-targeting communications, therapeutic pattern cancellation, EM countermeasures.",
    modules: [],
    source: "Gravitobiology Figures 10, 11 (phase conjugate mirrors); Whittaker wave decomposition",
    color: "#3b82f6", icon: "🔭",
    problem: "Conventional communications are interceptable and jammable. Conventional EM therapy cannot address the Whittaker-structured quantum potential components of disease patterns. No commercial phase conjugate mirror system exists for these applications.",
    beardenSolution: "A pumped phase conjugate mirror (PPCM) time-reverses an incoming EM wave — output is an exact phase-conjugate replica traveling back to source. This enables: (1) communications that self-navigate to their origin (unjammable); (2) therapeutic cancellation of disease EM patterns at the quantum potential level; (3) scalar EM countermeasures.",
    market: "Secure military communications ($28B); directed energy countermeasures ($9.3B DARPA interest); advanced photonics ($850M phase conjugate optics research). Dual-use civilian/defense creates multiple investor tracks.",
    feasibility: "Phase conjugate mirrors are validated laboratory technology (documented in mainstream physics literature). The Bearden extension adds Whittaker wave structure analysis. Initial prototype uses nonlinear optical medium (BaTiO₃ crystal) — commercially available.",
  },
  // ── NEW COURSES (from Excalibur Briefing + Part 4 figures)
  {
    category: "Course",
    title: "Excalibur Briefing Decoded: UFOs, Psychokinesis & Scalar EM",
    tagline: "The book that connects paranormal phenomena to hard physics — decoded module by module",
    price: "$197",
    audience: "UFO researchers, consciousness investigators, scalar EM students, curious intellectuals",
    description: "A structured walkthrough of Bearden's Excalibur Briefing (1980/1988): UFO formation mechanics, cattle mutilation explanations, thought photography, psychic surgery, ghost rockets, and contactee reports — all derived from the clustered orthogonal worlds model and the nested modulation hierarchy. Includes full analysis of Figs. 4, 20, 21, 24, 25.",
    modules: [
      "Module 1 – The Clustered Orthogonal Worlds Model (Fig. 20): S/S'/S''/S''' frames",
      "Module 2 – Crosstalk Between Realities (Fig. 21): How mind influences matter",
      "Module 3 – Life, Death & Reincarnation as Physics (Fig. 24)",
      "Module 4 – Consciousness, Intent & Free Will Mechanics (Fig. 25)",
      "Module 5 – UFO Formation: Hyperspatial Frame Intrusion into S-frame",
      "Module 6 – Cattle Mutilations, Thought Photography & Psychic Surgery Explained",
      "Module 7 – The 4th Law of Logic: Binocular Perception & Quantum Superposition (Fig. 4)",
    ],
    source: "Bearden Excalibur Briefing (1988 2nd ed.); ISBN 0-89407-050-4",
    color: "#a855f7", icon: "🛸",
  },
  {
    category: "Course",
    title: "The Prioré Device: Cancer Cure Suppressed — Engineering the Cure",
    tagline: "The French government paid for it. It worked. Then it vanished. Here's how to rebuild it.",
    price: "$297",
    audience: "Biomedical engineers, alternative health investors, cancer researchers, energy medicine practitioners",
    description: "Complete technical analysis of Antoine Prioré's multichannel EM modulation device (Bordeaux, 1960s–1980s), funded by the French government and documented to cure terminal cancers in animals. Covers: Bearden's Fig. 10 architecture (multichannel modulation → derivative carrier → primary carrier), the S'/S''/S''' hyperspatial mapping, the kindling reversal mechanism, and a modern implementation roadmap using DDS signal generators.",
    modules: [
      "Module 1 – The Prioré Story: French Government, Witnesses, and Suppression",
      "Module 2 – Fig. 10 Architecture: Multichannel Modulation Decoded",
      "Module 3 – Hyperspatial Frame Mapping: S' / S'' / S''' Correspondence",
      "Module 4 – The Kindling Reversal Mechanism: Time-Reversing Disease",
      "Module 5 – Modern Implementation: DDS Generators, Modulation Chains, Output Coupling",
      "Module 6 – Regulatory Pathway: Research Device Classification & Clinical Trials",
    ],
    source: "Bearden Excalibur Briefing Fig. 10; Gravitobiology; Prioré documented experiments",
    color: "#22c55e", icon: "💉",
  },
  {
    category: "Course",
    title: "T.H. Moray's Sea-of-Energy Device: Historical Analysis & Replication",
    tagline: "50kW from the vacuum — photographed, witnessed, and destroyed. Rebuild it from first principles.",
    price: "$247",
    audience: "Free energy engineers, electrical engineers, advanced hobbyists, vacuum energy researchers",
    description: "A forensic engineering course on T.H. Moray's documented vacuum energy device (1930s). Uses original Moray photographs plus Bearden's anenergy pump framework to reverse-engineer the device architecture. Covers the tube/valve circuit, the bulb output panel, the phi-oscillation mechanism, and a modern solid-state equivalent design.",
    modules: [
      "Module 1 – Moray: Biography, Witnesses, and the Soviet Sabotage",
      "Module 2 – Photo Analysis: Device Architecture from Original Images",
      "Module 3 – Anenergy Pump as Theoretical Framework for the Moray Device",
      "Module 4 – The Oscillated Phi-Application Mechanism: Moray Effect Explained",
      "Module 5 – Modern Solid-State Equivalent: From Tubes to DDS + MOSFET",
      "Module 6 – Output Verification: Measuring Massless Charge Conversion",
    ],
    source: "Moray photographs (1930s); Bearden Part 4 anenergy pump figures; Schaffranke 1982",
    color: "#f59e0b", icon: "💡",
  },
  {
    category: "Course",
    title: "ELF Brain Entrainment & Mass Mind Control: The Physics of Psychotronics",
    tagline: "10 Hz + 5–30 MHz = locked minds. The Soviet mechanism decoded.",
    price: "$247",
    audience: "Intelligence analysts, neuroscientists, biodefense researchers, EMF activists, journalists",
    description: "Technical decoding of Bearden's ELF brain entrainment mechanism: synchronized 10 Hz modulation on multiple 5–30 MHz carriers locking all brains in range into phase. Covers the Soviet Woodpecker delivery system, the nested modulation hierarchy for virtual-state nervous system interference, documented Pentagon EMI studies, and countermeasure design.",
    modules: [
      "Module 1 – The 10 Hz Brain Lock: Diagram Analysis and Mechanism",
      "Module 2 – Soviet Woodpecker Frequency Analysis and ELF Signature",
      "Module 3 – Nested Modulation: How S'/S''/S''' Targets the Nervous System",
      "Module 4 – Pentagon EMI Studies (Gravitobiology Table 7): Anomalous Data",
      "Module 5 – Mass Psychotronic Events: Historical Case Studies",
      "Module 6 – Countermeasures: Shielding, Detection, and Frequency Jamming",
    ],
    source: "Bearden Excalibur Briefing; Gravitobiology Table 7; Soviet Woodpecker documentation",
    color: "#ef4444", icon: "🧠",
  },
  {
    category: "Course",
    title: "The 4th Law of Logic: Bearden's Correction to Classical Thought",
    tagline: "Aristotle had 3 laws. Bearden found the 4th. It changes everything about physics and consciousness.",
    price: "$147",
    audience: "Philosophers, logicians, quantum physicists, consciousness researchers",
    description: "A rigorous walkthrough of Bearden's temporal logic extension (Excalibur Briefing Fig. 4). Covers: why Aristotle's 3 laws are incomplete for quantum phenomena, the perception operator □ as a decision algorithm, the 4th law (binocular identity of exact opposites), its application to the double-slit experiment, and its role in explaining consciousness as a permanent 4th-law operation.",
    modules: [
      "Module 1 – Aristotle's 3 Laws and Their Hidden Assumption",
      "Module 2 – The Perception Operator: Finite Time and the Decision Algorithm",
      "Module 3 – Monocular vs Binocular Perception in Time",
      "Module 4 – The 4th Law: Boundary Identity of Exact Opposites",
      "Module 5 – Double-Slit Experiment as 4th Law Operation (Fig. 7)",
      "Module 6 – Consciousness as Permanent 4th-Law State",
    ],
    source: "Bearden Excalibur Briefing Figs. 4, 5, 6, 7",
    color: "#06b6d4", icon: "⚖️",
  },
  {
    category: "Course",
    title: "Phi-River Engineering: Virtual Particle Flux & the Curved Spacetime Circuit",
    tagline: "The gradient-phi river is a region of curved spacetime — and you can engineer it",
    price: "$197",
    audience: "Advanced EM engineers, vacuum energy researchers, theoretical physicists",
    description: "Deep dive into Bearden's phi-river concept from Part 4: two locked-in phi-sources of different magnitudes create a virtual particle flow (∇φ river) that curves spacetime locally. Covers the failed standard circuit (electron spray nozzle), the free anenergy pump solution, spinning charged particle / phi-flux coupling, and the massless charge cycle.",
    modules: [
      "Module 1 – The ∇φ River: Virtual Particle Flow Between Two Phi-Sources",
      "Module 2 – Curved Spacetime at the Circuit Level: Why Energy Is Not Conserved",
      "Module 3 – The Spray Nozzle Problem: Why Standard Circuits Fail",
      "Module 4 – Spinning Charged Particle Coupled to Phi-Flux (Figures Analysis)",
      "Module 5 – The Free Anenergy Pump: Eliminating the Spray Nozzle",
      "Module 6 – Conservation of Charge Extended: K₁+K₂=K₃ and the New Cycle",
    ],
    source: "Bearden Part 4 phi-river figures; conservation of charge diagrams; vacuum structure papers",
    color: "#3b82f6", icon: "🌊",
  },
  // ── NEW BOOKS / PDFs
  {
    category: "Book/PDF",
    title: "Excalibur Briefing: Annotated & Illustrated Edition",
    tagline: "The complete 1988 2nd edition with modern commentary, figure analysis, and business applications",
    price: "$59 PDF / $99 hardcover",
    audience: "General public, UFO researchers, consciousness students, Bearden collectors",
    description: "Fully annotated edition of Bearden's most accessible book. Every figure decoded with plain-English commentary. Includes the complete paranormal/UFO analysis, Prioré device architecture, consciousness/life/death mechanics, 4th law of logic, and Moray references — with sidebars connecting each concept to modern research and business opportunity.",
    modules: [],
    source: "Bearden Excalibur Briefing 2nd ed. (1988); ISBN 0-89407-050-4",
    color: "#f59e0b", icon: "🛸",
  },
  {
    category: "Book/PDF",
    title: "The Prioré Device: Complete Technical Dossier",
    tagline: "Everything documented about the French government's funded EM cancer cure",
    price: "$47 PDF",
    audience: "Biomedical investors, energy medicine practitioners, cancer researchers",
    description: "A complete research dossier on Antoine Prioré's multichannel EM device: historical timeline, French government funding documentation, witness accounts, Bearden's Fig. 10 architecture analysis, kindling reversal mechanism, and modern implementation pathway.",
    modules: [],
    source: "Bearden Excalibur Briefing Fig. 10; Gravitobiology; documented Prioré experiments",
    color: "#f59e0b", icon: "💉",
  },
  {
    category: "Book/PDF",
    title: "T.H. Moray: The Complete Photo & Engineering Analysis",
    tagline: "Original photographs + anenergy pump theory + modern replication guide",
    price: "$37 PDF",
    audience: "Free energy researchers, electrical engineers, history of science readers",
    description: "A photographic and engineering analysis of T.H. Moray's Sea-of-Energy device. Includes all known Moray photographs, device architecture reverse-engineering from visual inspection, Bearden's anenergy pump as theoretical framework, and a parts list for a modern equivalent circuit.",
    modules: [],
    source: "Moray photographs (uploaded); Bearden Part 4 anenergy pump",
    color: "#f59e0b", icon: "📷",
  },
  {
    category: "Book/PDF",
    title: "Phi-River & Curved Spacetime: A Visual Engineering Guide",
    tagline: "Every Part 4 phi-diagram reproduced and explained — the missing textbook",
    price: "$29 PDF",
    audience: "Electrical engineers, advanced students, vacuum energy researchers",
    description: "A visual companion to Bearden's Part 4 phi-field mechanics: every phi-river, phi-source, gradient-phi, spray-nozzle, and anenergy pump figure reproduced with step-by-step engineering commentary. Includes the massless charge conservation triangle and the ∇φ river spacetime curvature implications.",
    modules: [],
    source: "Bearden Part 4 (1983) — all phi-field figures",
    color: "#f59e0b", icon: "🌊",
  },
  // ── NEW INVENTIONS
  {
    category: "Invention",
    title: "Prioré-Type Multichannel EM Therapy System",
    tagline: "A modern DDS implementation of the Prioré multichannel modulation architecture",
    price: "$2,400 clinical / $599 research",
    audience: "Biomedical engineers, alternative medicine clinics, longevity investors, cancer research labs",
    description: "Modern solid-state implementation of Bearden's Fig. 10 Prioré device architecture using DDS (direct digital synthesis) signal generators, FPGA modulation chain, and programmable hyperspatial layer outputs (S'/S''/S'''). Research version outputs programmable multichannel modulated EM fields for biological research. Clinical version adds shielded applicator coils and treatment protocol software.",
    modules: [],
    source: "Bearden Excalibur Briefing Fig. 10 (Prioré device); Gravitobiology kindling reversal",
    color: "#ef4444", icon: "🏥",
    problem: "No commercial implementation of the documented Prioré multichannel EM architecture exists. Cancer researchers, energy medicine practitioners, and longevity investors have no device to test Bearden's kindling-reversal hypothesis.",
    beardenSolution: "Fig. 10 shows the exact signal chain: multichannel inputs → derivative carrier/modulator → primary carrier output. Mapped to S'/S''/S''' hierarchy, this impresses a structured virtual-state template onto the target organism — reversing disease patterns via kindling-reversal mechanism.",
    market: "Energy medicine device market ($3.8B); longevity biotech ($85B by 2030); alternative cancer research ($12B). French government documentation provides unique credibility anchor for investor pitches.",
    feasibility: "DDS chips (AD9910) generate arbitrary waveforms with sub-Hz resolution. FPGA modulation chains are standard. All COTS components. Research device exempts from FDA approval. Clinical version pursues IRB approval pathway.",
  },
  {
    category: "Invention",
    title: "ELF Carrier Lock Detection System (\"Psychotronic Detector\")",
    tagline: "Detect Soviet-style ELF brain-entrainment carriers in the 5–30 MHz band",
    price: "$1,800 instrument",
    audience: "Intelligence analysts, biodefense contractors, EMF researchers, government labs",
    description: "A precision RF spectrum analyzer tuned to detect synchronized ELF (≤10 Hz) modulation sidebands on carriers in the 5–30 MHz band — the signature of Bearden's documented ELF brain-entrainment architecture. Includes statistical phase-coherence detection across multiple carriers, timestamp logging, and anomaly alert system.",
    modules: [],
    source: "Bearden Excalibur Briefing ELF entrainment diagram; Gravitobiology Table 7 (Pentagon EMI studies)",
    color: "#ef4444", icon: "📡",
    problem: "Standard spectrum analyzers display amplitude vs frequency but cannot detect synchronized phase-locked ELF modulation across multiple carriers — the specific signature of psychotronic EM broadcast architecture.",
    beardenSolution: "A multi-channel SDR (software-defined radio) receiver with cross-correlation firmware detects statistically anomalous phase coherence of ELF sidebands across multiple unrelated carriers — the smoking-gun signature of the Bearden ELF entrainment architecture.",
    market: "DoD/DARPA EW research ($9.3B); EMF safety monitoring ($2.1B); intelligence community SIGINT tools; academic bioelectromagnetics research. Pentagon EMI studies (Gravitobiology Table 7) create direct government procurement pathway.",
    feasibility: "SDR hardware (RTL-SDR, HackRF) is COTS and costs under $300. Phase-coherence firmware is standard DSP. The anomalous ELF signatures are documented in published literature. Academic validation via IEEE EMC or Nature journals.",
  },
  {
    category: "Invention",
    title: "Phi-River Gradient Sensor (∇φ Detector)",
    tagline: "Directly measure the virtual particle flux river between two phi-sources",
    price: "$950 research instrument / $195 plans",
    audience: "Vacuum energy researchers, scalar EM experimenters, advanced physics labs",
    description: "A differential phi-potential measurement instrument using two matched shielded toroidal coils as phi-source references, with a sensitive Hall-effect bridge circuit measuring the gradient-phi field between them. Designed to detect the 'river' of virtual particle flux in Bearden's phi-river circuit — invisible to conventional voltmeters but detectable via anomalous Hall differential.",
    modules: [],
    source: "Bearden Part 4 phi-river figures; phi-source diagrams; anenergy pump geometry",
    color: "#ef4444", icon: "🌊",
    problem: "No instrument exists to measure gradient-phi directly as distinct from E-field. Standard voltmeters measure ∇φ only as E-field in the presence of charged mass, making the massless-charge / charged-mass distinction unmeasurable with existing equipment.",
    beardenSolution: "Two matched shielded toroidal coils (∇φ inside = 0, φ > φ₀) create a controlled phi-differential. A Hall-effect bridge sensitive to virtual photon flux density between the toroids measures ∇φ without coupling to E-field — the first direct massless-charge measurement instrument.",
    market: "Vacuum energy research equipment; scalar EM laboratory instruments; university physics demonstration market ($220M). Patent-defensible measurement methodology creates licensing opportunity.",
    feasibility: "Matched toroidal coil winding is precision but achievable. Hall sensors at nT sensitivity are COTS. Differential bridge eliminates common-mode E-field pickup. Buildable under $400 in components. Plans include full calibration procedure.",
  },
  // ── NEW SERVICES
  {
    category: "Service",
    title: "Investor Due Diligence Package",
    tagline: "Everything a serious investor needs to evaluate the Bearden IP portfolio",
    price: "$2,500",
    audience: "Angel investors, family offices, deep tech VCs, defense-adjacent funds",
    description: "A comprehensive investor package: IP inventory and valuation framework, market sizing for 8 invention categories, competitive landscape analysis, regulatory pathway summary, risk matrix, and a 30-minute private briefing with the platform operator. Includes access to all primary source documents and a curated list of independent corroborating research.",
    modules: [],
    source: "Full Bearden archive; business models; invention IP analysis",
    color: "#6b7280", icon: "💼",
  },
  {
    category: "Service",
    title: "IP Licensing Package",
    tagline: "License the Bearden framework for your product, course, or research program",
    price: "$5,000–$50,000 (tiered)",
    audience: "Energy companies, biotech startups, defense contractors, academic institutions",
    description: "Tiered IP licensing for commercial use of the Bearden scalar EM framework, device architectures, and course content. Includes: rights to use documented device architectures (anenergy pump, energy bottle, Prioré-type), access to full annotated source archive, co-branding options, and ongoing research collaboration.",
    modules: [],
    source: "Full Bearden IP portfolio",
    color: "#6b7280", icon: "📜",
  },
  {
    category: "Service",
    title: "Research Lab Setup Consultation",
    tagline: "Turn your garage or lab into a functioning scalar EM research facility",
    price: "$1,500 (3-session package)",
    audience: "Independent researchers, university labs, inventor-entrepreneurs",
    description: "Three-session video consultation series covering: equipment selection and procurement (all COTS), lab safety protocols for scalar EM experiments, measurement instrument calibration, experimental protocol design for anenergy pump / phi-river / biofield trigger window experiments, and documentation standards for publishable results.",
    modules: [],
    source: "Full Bearden technical archive; Part 4 device figures",
    color: "#6b7280", icon: "🔬",
  },
  {
    category: "Service",
    title: "Membership: Bearden Research Network (Monthly)",
    tagline: "Monthly deep-dives, live Q&A, new document releases, and member invention reviews",
    price: "$47/month",
    audience: "Serious researchers, students, inventors, investors — all levels",
    description: "Monthly membership including: new annotated document releases from the Bearden archive, live monthly webinar with Q&A, member-submitted invention/experiment reviews, private Discord community access, and early access to new courses and PDF releases. Cancel anytime.",
    modules: [],
    source: "Full Bearden archive; ongoing research",
    color: "#6b7280", icon: "🔐",
  },
  // ── SERVICES (original)
  {
    category: "Service",
    title: "Private Research Consultation (1-on-1)",
    tagline: "Deep-dive sessions on your specific scalar EM or biofield research project",
    price: "$250/hr",
    audience: "Serious researchers, inventors, academics",
    description: "One-on-one video consultation for researchers in scalar EM, vacuum energy, bioelectromagnetics, or consciousness studies.",
    modules: [],
    source: "Full Bearden archive",
    color: "#6b7280", icon: "💬",
  },
  // ── ATMOSPHERIC SCALAR EM — new items from 2-radials diagram + cloud photo documentation
  {
    category: "Course",
    title: "Reading the Sky: Scalar EM Interference in Atmospheric Phenomena",
    tagline: "Radial spokes, grid clouds, hole-punch clearings — the scalar EM signature field guide",
    price: "$197",
    audience: "Weather researchers, geophysical analysts, intelligence analysts, scalar EM students, citizen scientists",
    description: "A structured photographic and theoretical course analyzing the observable atmospheric signatures of scalar EM transmitter operations. Based on Tom Bearden's documented California coast sky photography series (Nov 2001–Spring 2002) and the '2-radials' scalar interference grid diagram. Covers: the boattailed beam pattern geometry, radial spoke cirrus formation mechanism, hole-punch cloud as energy bottle signature, rectangular grid cirrus as standing scalar wave, and how to correlate observed formations with known transmitter geometries.",
    modules: [
      "Module 1 – The 2-Radials Diagram: Scalar Interference Grid Geometry Decoded",
      "Module 2 – Boattailed Beam Pattern: Why the Central Ring Disappears",
      "Module 3 – Radial Spoke Clouds: Far-Field Scalar EM Fan Formation Mechanism",
      "Module 4 – Hole-Punch Clouds as Energy Bottle Signatures (E=0 B=0 Zone)",
      "Module 5 – Grid-Pattern Cirrus: Standing Scalar Wave Interference in the Atmosphere",
      "Module 6 – Soviet Woodpecker Grid: Correlating Duga-3 Geometry with Cloud Observations",
      "Module 7 – Field Protocol: How to Photograph, Timestamp, and Analyze Sky Evidence",
    ],
    source: "Tom Bearden Website atmospheric documentation; 2-radials diagram; Bearden Part 4 energy bottle; Soviet Woodpecker Duga-3 geometry",
    color: "#06b6d4", icon: "☁️",
  },
  {
    category: "Book/PDF",
    title: "Atmospheric Scalar EM: The Cloud Evidence — Annotated Photo Analysis",
    tagline: "29 timestamped photographs + the 2-radials diagram + scalar EM theory — the complete atmospheric evidence file",
    price: "$37 PDF",
    audience: "Researchers, intelligence analysts, weather modification investigators, scalar EM students",
    description: "A fully annotated reference document correlating Bearden's California coast sky photography (29 images, Nov 2001–May 2004) with the scalar EM interference grid model. Each image annotated with: cloud morphology classification, scalar EM signature type (radial spoke / hole-punch / grid / fan), theoretical mechanism, and the 2-radials diagram overlay showing predicted vs observed geometry. Includes the complete Woodpecker Grid audio description and Pacific satellite radar anomaly analysis.",
    modules: [],
    source: "Tom Bearden Website sky photography archive; 2-radials scalar interference grid diagram; Duga-3 Woodpecker documentation",
    color: "#f59e0b", icon: "☁️",
  },
  {
    category: "Invention",
    title: "Atmospheric Scalar EM Signature Recognition System (AI Edition)",
    tagline: "AI-powered cloud morphology classifier trained on scalar interference grid signatures",
    price: "$3,200 instrument + software / $499 software-only",
    audience: "Defense meteorology contractors, weather modification researchers, geophysical intelligence analysts, scalar EM labs",
    description: "A machine vision + AI system trained to identify scalar EM interference signatures in sky photographs and satellite imagery: radial spoke patterns, hole-punch/fallstreak clearings correlated with energy bottle geometry, rectangular grid cirrus matching standing scalar wave spacing, and boattailed beam patterns consistent with two-source scalar transmitter pairs. Software runs on standard GPU hardware; instrument package adds a calibrated all-sky camera with GPS timestamp and automated logging.",
    modules: [],
    source: "Tom Bearden Website 2-radials diagram; California coast sky photography series; Bearden Part 4 energy bottle geometry; Duga-3 transmitter geometry",
    color: "#06b6d4", icon: "🛰️",
    problem: "No systematic tool exists to identify scalar EM atmospheric interference signatures in cloud imagery. Weather modification research, defense meteorology, and scalar EM research all lack automated morphological classification of anomalous cloud formations.",
    beardenSolution: "The 2-radials diagram specifies exact geometric predictions for scalar EM interference in the atmosphere: elliptical ground footprint, radial fan beams, central hole (E=0 zone), pattern-linking arcs. These are measurable morphological features trainable in a vision model using Bearden's documented photo archive as ground-truth labels.",
    market: "Weather modification detection ($4.2B geospatial intelligence market); DoD atmospheric sensing ($2.8B); climate monitoring and geoengineering accountability tools (emerging $500M+ advocacy-funded sector); academic atmospheric physics.",
    feasibility: "Vision transformer fine-tuning on cloud morphology is standard ML pipeline. All-sky cameras are COTS ($200–800). GPS timestamping and automated alert system is standard IoT. Training dataset seeded from Bearden's 29+ documented photographs plus augmentation.",
  },
  {
    category: "Invention",
    title: "Woodpecker Grid Standing Wave Detector (HF Scalar Signature Receiver)",
    tagline: "Monitor the 4–30 MHz band for the 10 Hz pulse Woodpecker signature — the scalar weapon's acoustic fingerprint",
    price: "$750 instrument / $180 plans",
    audience: "Shortwave radio operators, biodefense researchers, scalar EM analysts, citizen scientists, intelligence analysts",
    description: "A purpose-built software-defined radio (SDR) receiver and analysis package tuned to detect the Soviet Woodpecker-style 10 Hz pulse modulation signature in the 4–30 MHz HF band. Features: auto-scan across band, pulse-repetition-interval (PRI) analysis to identify ≤10 Hz modulation, geographic direction-finding via antenna array option, and cloud morphology correlation log (cross-reference atmospheric observations with signal detections). Includes audio output so users can hear the Woodpecker pulse directly (as documented on the Tom Bearden Website).",
    modules: [],
    source: "Tom Bearden Website Woodpecker documentation; Soviet Duga-3 Woodpecker signal analysis; Bearden ELF entrainment architecture",
    color: "#ef4444", icon: "📻",
    problem: "The Woodpecker-style scalar EM broadcast signal — documented on shortwave since 1976 — has no dedicated consumer detection instrument. Existing SDR setups require expert configuration; no off-the-shelf receiver packages the PRI-analysis firmware needed to identify the signature.",
    beardenSolution: "The Woodpecker signature is a distinctive 10 Hz pulse modulation on HF carriers — documentable with standard SDR hardware and custom PRI-detection firmware. Cross-referencing signal detections with simultaneous sky photography creates a correlated evidence record connecting RF emissions to atmospheric morphology changes.",
    market: "Shortwave/SDR hobbyist market (12M+ active operators worldwide); citizen science monitoring tools ($340M); defense/intelligence SIGINT education; academic ELF research. Low price point creates high volume sales + community data network effect.",
    feasibility: "RTL-SDR dongle ($30) + custom PRI firmware. Direction-finding add-on uses 2–4 element antenna array. Cloud correlation logging is a simple smartphone app. Full instrument BOM under $200. Plans cover firmware, antenna design, and calibration procedure.",
  },
  // ── ENERGETICS / PSYCHOENERGETICS / MIND CONTROL PAPER — new items
  {
    category: "Course",
    title: "Energetics, Bioenergetics & Psychoenergetics: Bearden's 1996 Unified Framework",
    tagline: "One diagram. Three domains. The most complete synthesis Bearden ever drew.",
    price: "$197",
    audience: "Physicists, biohackers, consciousness researchers, energy medicine practitioners, advanced students",
    description: "A structured course walking through Bearden's 1996 Energetics diagram — his most complete unified visual framework. Covers all three domains: Energetics (nonliving systems: scalar interferometry, vacuum engines, quantum potential, SWZ effects), Bioenergetics (living bodies: master cell control via Popp, disease induction/remission, spacetime structuring), and Psychoenergetics (living minds: thoughts, memories, emotions, species and biospheric minds). Shows how identical underlying mechanisms operate across all three substrate levels and how to engineer each domain.",
    modules: [
      "Module 1 – The Energetics Diagram: Three Domains, One Unified Mechanism",
      "Module 2 – Energetics (Nonliving): Scalar Interferometry, Vacuum Engines, QP, SWZ",
      "Module 3 – Bioenergetics: Master Cell Control (Popp), Disease Induction, Spacetime Structuring",
      "Module 4 – Psychoenergetics: Engineering Thoughts, Memories, Emotions",
      "Module 5 – Species & Biospheric Minds: The Collective Psychoenergetic Field",
      "Module 6 – Bridging All Three: The SWZ / Scalar Interferometry Cross-Layer",
      "Module 7 – Applications: Products, Devices & Research Pathways from Each Domain",
    ],
    source: "Bearden 1996 Energetics diagram; Gravitobiology; Psychoenergetics papers",
    color: "#06b6d4", icon: "🧠",
  },
  {
    category: "Course",
    title: "T-Polarized Photons & Time as Energy: The Rarest EM Domain",
    tagline: "The 4th photon polarization Western physics ignores — and why it is 9x10^16 times more powerful than force",
    price: "$247",
    audience: "Quantum physicists, EM engineers, consciousness researchers, advanced scalar EM students",
    description: "A rigorous course on Bearden's t-polarized (scalar) photon framework from the 1999 Explore! paper. Covers: the four polarizations of photons (x, y, z, t), why Western physics discards the t-polarization, time as compressed EM energy at 9x10^16 J/second, the Time Density Wave (oscillating rate of flow of time), and how t-polarized EM provides 10^40x amplification over weak G-force for spacetime curvature. Shows why Russian psychoenergetics researchers have been 20+ years ahead of Western science.",
    modules: [
      "Module 1 – The Four Photon Polarizations: x, y, z, and t",
      "Module 2 – Why Western Physics Discards the t-Polarization",
      "Module 3 – Time as Energy: 9x10^16 J per Second",
      "Module 4 – The Time Density Wave (Figure 2): Oscillating Rate of Time",
      "Module 5 – Spacetime Curvature Amplification: 10^40 vs G-Force",
      "Module 6 – Russian KGB Psychoenergetics: What They Knew and When",
    ],
    source: "Bearden 'Mind Control and EM Wave Polarization Transductions' (Explore! Vol. 9, No. 2, 1999)",
    color: "#a855f7", icon: "⏱️",
  },
  {
    category: "Course",
    title: "EM Wave Transduction Mastery: From Transverse to Longitudinal to Time",
    tagline: "Figure 2 decoded: how ordinary EM waves become mind-engineering tools via successive phase conjugate pairing",
    price: "$297",
    audience: "RF engineers, scalar EM researchers, bioelectromagnetics practitioners, psychotronics analysts",
    description: "Deep technical course on Bearden's wave transduction chain from the 1999 paper. Covers Figure 2 in detail: transverse EM + phase conjugate replica → longitudinal EM surge wave; longitudinal EM + phase conjugate replica → time density wave. Explains why transduction produces anomalous instrument readings invisible to standard detectors, why UPWs (undistorted progressive waves) penetrate water and mass with minimal loss, and how the KGB 'brute force' TW method differs from Bearden's fine control transduction approach. Includes replication protocol for each transduction stage.",
    modules: [
      "Module 1 – The Three EM Wave Domains: Transverse, Longitudinal, Time-Density",
      "Module 2 – Figure 2 Decoded: Phase Conjugate Pairing Chain",
      "Module 3 – Why Transduced Waves Are Invisible to Standard Instruments",
      "Module 4 – UPWs (Undistorted Progressive Waves): Penetration Through Mass",
      "Module 5 – KGB Brute Force TW vs Bearden Fine Control Transduction",
      "Module 6 – Replication Protocol: Building a Two-Stage Transduction Chain",
      "Module 7 – Applications: Mind Engineering, Healing, and EM Countermeasures",
    ],
    source: "Bearden 'Mind Control and EM Wave Polarization Transductions' (Explore! 1999) Figure 2",
    color: "#3b82f6", icon: "🌀",
  },
  {
    category: "Course",
    title: "The Mind-Body Coupling Loop: Figure 5 Engineering",
    tagline: "The first rigorous physical solution to intent, free will, and mind-over-matter",
    price: "$197",
    audience: "Consciousness researchers, biohackers, quantum biology students, meditation practitioners, philosophers",
    description: "A course built entirely around Bearden's Figure 5 from the 1999 Explore! paper: the closed-loop mind-body coupling mechanism. Covers the START/DIFFER/ZERO flowchart, coherent mind changes as 4-space rotations projecting into 3-space, virtual ST curvature engines in the brain/body, the body-to-mind sensory feedback loop, and what this means for intent, prayer, meditation, and psychosomatic healing. Provides the first physics-grounded explanation of placebo effect, psychosomatic disease, and intentional self-healing.",
    modules: [
      "Module 1 – Figure 5 Walkthrough: The Complete Mind-Body Coupling Diagram",
      "Module 2 – Coherent Mind Changes as 4-Space Rotations",
      "Module 3 – Virtual ST Curvature Engines in the Brain",
      "Module 4 – The Body Feedback Loop: How Body Changes Report Back to Mind",
      "Module 5 – Intent, Prayer, and Meditation as 4-Space Rotation Engineering",
      "Module 6 – Psychosomatic Disease and Healing: Physics Explanation",
    ],
    source: "Bearden 'Mind Control and EM Wave Polarization Transductions' Figure 5 (Explore! 1999)",
    color: "#a855f7", icon: "🧠",
  },
  {
    category: "Book/PDF",
    title: "Mind Control & EM Wave Polarization Transductions: Annotated Technical Edition",
    tagline: "The complete 1999 Explore! three-part series with diagram analysis and modern commentary",
    price: "$49 PDF",
    audience: "Scalar EM researchers, intelligence analysts, consciousness scientists, psychotronics students",
    description: "Fully annotated edition of Bearden's three-part 1999 Explore! series. All figures decoded: Figure 2 (transduction chain), Figure 4 (general relativity spacetime curvature engine), Figure 5 (mind-body coupling loop), Figure 7 (Russian weapons deployment). Plain-English commentary alongside original technical text. Includes sidebar analysis of the 1997 US military pilot incidents, the KGB 20-year advantage assessment, and a modern replication roadmap.",
    modules: [],
    source: "Bearden 'Mind Control and EM Wave Polarization Transductions, Parts I, II, III' (Explore! Vol. 9, No. 2, 1999)",
    color: "#f59e0b", icon: "🧠",
  },
  {
    category: "Invention",
    title: "T-Polarized EM Wave Transducer (Time-Domain EM Engineering System)",
    tagline: "The first commercial implementation of the Bearden two-stage transduction chain — transverse to longitudinal to time-density wave",
    price: "$4,800 research prototype / $650 engineering plans",
    audience: "Scalar EM researchers, defense R&D labs, consciousness technology startups, bioelectromagnetics experimenters",
    description: "Research prototype implementing Bearden's Figure 2 two-stage EM wave transduction chain: Stage 1 converts transverse EM to longitudinal surge wave via phase conjugate mirror pairing; Stage 2 converts longitudinal to time-density wave (oscillating rate of time). Includes standard spectrum analyzer alongside specialized scalar detector to demonstrate the anomalous invisibility of transduced waves to conventional instruments. Applications: scalar communications, psychoenergetics research, biofield therapeutic research.",
    modules: [],
    source: "Bearden 'Mind Control and EM Wave Polarization Transductions' Figure 2 (Explore! 1999)",
    color: "#ef4444", icon: "⏱️",
    problem: "No commercial instrument implements the Bearden transduction chain from the 1999 paper. Psychoenergetics and scalar EM researchers have no laboratory apparatus to explore t-polarized EM wave generation and detection.",
    beardenSolution: "Figure 2 specifies the exact transduction architecture: transverse EM + phase conjugate replica → longitudinal surge wave; longitudinal + phase conjugate replica → Time Density Wave. Each stage uses a nonlinear medium (BaTiO3 crystal or ferrofluid) as the phase conjugate mirror. Standard SDR detects nothing; custom scalar sensor shows anomalous signal.",
    market: "Psychoenergetics research instruments ($500M); defense DARPA unconventional EM ($340M); consciousness technology startups (emerging $2B category); bioelectromagnetics labs.",
    feasibility: "Phase conjugate mirrors in BaTiO3 crystals are validated physics. DDS signal generators provide the input wave. Two-stage cascading is straightforward RF engineering. Plans include full BOM, crystal specifications, and custom scalar detector design.",
  },
  {
    category: "Invention",
    title: "Psychoenergetics Cellular Control System (Bioenergetics Layer Device)",
    tagline: "Engineer the Bioenergetics domain: master cell control, disease induction/remission, cellular spacetime structuring",
    price: "$3,200 clinical / $780 research",
    audience: "Biomedical engineers, longevity investors, alternative medicine clinics, cancer research labs",
    description: "Based on Bearden's 1996 Bioenergetics domain (master cell control via Popp coherent biophoton emission, spacetime structuring at cellular level, disease induction and remission via scalar interferometry). Delivers programmable coherent biophoton-frequency EM fields tuned to Popp's master cell control windows, with simultaneous scalar interferometry output for cellular spacetime structuring. Dual-mode: Disease Remission Protocol (restoring coherent biophoton emission patterns) and Enhancement Protocol (optimizing cellular coherence for longevity).",
    modules: [],
    source: "Bearden 1996 Energetics diagram (Bioenergetics domain); Popp biophoton master cell control; Gravitobiology",
    color: "#22c55e", icon: "🧬",
    problem: "No commercial device addresses the Bioenergetics layer of Bearden's 1996 diagram simultaneously: master cell control (Popp biophoton frequencies), spacetime structuring at cellular level, and disease induction/remission via scalar interferometry. Existing PEMF devices operate only in the Energetics (nonliving) domain.",
    beardenSolution: "The 1996 diagram specifies the Bioenergetics mechanisms: master cell control (coherent biophoton emission, Popp), spacetime structuring, and disease induction/remission via the same scalar interferometry used in nonliving systems but tuned to living tissue resonances. A DDS-based multi-frequency system with coherent biophoton-range UV output addresses all three simultaneously.",
    market: "Longevity biotech ($85B by 2030); PEMF therapy devices ($1.4B, growing 16% YoY); biophoton therapy ($800M); cancer research instruments ($16B). Popp biophoton research provides mainstream academic validation pathway.",
    feasibility: "Popp's biophoton master cell control frequencies are published in peer-reviewed literature. DDS multi-frequency generation is COTS. UV LED arrays for biophoton-range output are commercially available. FDA pathway: wellness research instrument.",
  },
  {
    category: "Service",
    title: "Custom Concept Network Map",
    tagline: "A bespoke interactive knowledge graph of your research domain",
    price: "$499",
    audience: "Authors, researchers, organizations",
    description: "Using this app's D3.js architecture, create a custom interactive concept map for any research domain — delivered as a standalone web app.",
    modules: [],
    source: "This app's architecture",
    color: "#6b7280", icon: "🌐",
  },
];