export const BUYERS = [
  {
    tier: "Defense / Intelligence",
    color: "#ef4444",
    icon: "🛡️",
    contacts: [
      {
        org: "In-Q-Tel (CIA Venture Arm)",
        contact: "Investments Team",
        email: "info@iqt.org",
        web: "https://www.iqt.org",
        rationale: "Direct mandate for scalar EM analysis, TRZ documentation, Gulf War QP weapon records. In-Q-Tel funds pre-commercial technology with intelligence applications.",
        ask: "$4.5M–$8M exclusive acquisition",
      },
      {
        org: "DARPA Biological Technologies Office",
        contact: "Program Manager — Bioelectromagnetics",
        email: "OUSDRandE@mail.mil",
        web: "https://www.darpa.mil/work-with-us/heilmeier-catechism",
        rationale: "Priore ONR documentation, MCCS telomere regeneration, Porthole disease treatment for mass casualty scenarios. DARPA funds impossible-seeming technologies.",
        ask: "$3M–$6M research license + development contract",
      },
      {
        org: "Battelle Memorial Institute",
        contact: "Chief Research Officer",
        email: "communications@battelle.org",
        web: "https://www.battelle.org",
        rationale: "Applied physics R&D acquisition history. Prior involvement with ONR bioelectromagnetics. Full scalar weapons + Priore archive acquisition candidate.",
        ask: "$2M–$5M portfolio license",
      },
      {
        org: "Leidos (formerly SAIC)",
        contact: "Corporate Development",
        email: "ir@leidos.com",
        web: "https://www.leidos.com",
        rationale: "Defense advanced programs. Baghdad M1A1 anomaly documentation + scalar EM weapons architecture for classified program support.",
        ask: "$3M–$7M acquisition",
      },
    ],
  },
  {
    tier: "Longevity / Biotech",
    color: "#22c55e",
    icon: "🧬",
    contacts: [
      {
        org: "Altos Labs (Jeff Bezos / Yuri Milner)",
        contact: "Chief Scientific Officer — Rick Klausner",
        email: "info@altoslabs.com",
        web: "https://www.altoslabs.com",
        rationale: "Cellular rejuvenation mandate. MCCS telomere regeneration framework, TRD-1 device plans, Priore immune restoration data, and porthole healing process represent the most complete electromagnetic cellular rejuvenation IP available.",
        ask: "$8M–$15M exclusive biotech acquisition",
      },
      {
        org: "Calico Life Sciences (Alphabet/Google)",
        contact: "VP Business Development",
        email: "contact@calicolabs.com",
        web: "https://www.calicolabs.com",
        rationale: "Aging reversal R&D with unlimited capital. Telomere regeneration via MCCS antiengine protocol is directly on-mandate. ONR Priore validation gives mainstream defensibility.",
        ask: "$6M–$12M acquisition or JV",
      },
      {
        org: "Hevolution Foundation (Saudi Sovereign Wealth)",
        contact: "Chief Scientific Officer — Felipe Sierra",
        email: "info@hevolution.com",
        web: "https://www.hevolution.com",
        rationale: "$1B/year longevity mandate, no profit requirement. Electromagnetic medicine framework, Priore cure archive, telomere device plans, and mass casualty treatment system.",
        ask: "$5M–$10M research grant + IP license",
      },
      {
        org: "Breakout Labs (Peter Thiel Foundation)",
        contact: "Hemai Parthasarathy — Scientific Director",
        email: "info@breakoutlabs.org",
        web: "https://www.breakoutlabs.org",
        rationale: "Explicitly funds 'too radical for traditional funding' science. Suppressed technology framing is perfect. Thiel's contrarian thesis + longevity interest.",
        ask: "$1M–$3M seed + equity JV",
      },
    ],
  },
  {
    tier: "Clean Energy / Free Energy",
    color: "#f59e0b",
    icon: "⚡",
    contacts: [
      {
        org: "Breakthrough Energy Ventures (Bill Gates)",
        contact: "Investment Team",
        email: "info@breakthroughenergy.org",
        web: "https://www.breakthroughenergy.org",
        rationale: "MEG COP>1 device plans, asymmetric regauging circuits, TRZ cold fusion reactor, Kawai motor IP, and the full O(3) electrodynamics / Sachs curved spacetime theoretical framework.",
        ask: "$4M–$9M acquisition",
      },
      {
        org: "Founders Fund (Peter Thiel / Blake Masters)",
        contact: "Partnership",
        email: "info@foundersfund.com",
        web: "https://foundersfund.com",
        rationale: "'Secrets the rest of the world doesn't know' thesis. MEG peer-reviewed COP>1, Bohren 1983 mainstream proof, full scalar EM weapons + free energy IP portfolio.",
        ask: "$5M–$12M strategic acquisition",
      },
      {
        org: "Saudi Aramco Energy Ventures",
        contact: "Managing Director",
        email: "saev@aramco.com",
        web: "https://www.aramco.com",
        rationale: "Energy disruption hedge acquisitions. COP>1 clean energy technology — MEG, TRZ reactor, asymmetric regauging — as sovereign energy alternative IP.",
        ask: "$6M–$14M exclusive license",
      },
      {
        org: "SoftBank Vision Fund",
        contact: "Deep Technology Investment Team",
        email: "info@softbank.com",
        web: "https://visionfund.com",
        rationale: "Technology platform + IP portfolio acquisitions at scale. Full Zenith Apex platform (tech + IP + courses + shop + CRM) as going-concern acquisition.",
        ask: "$10M–$20M full platform acquisition",
      },
    ],
  },
  {
    tier: "Academic / Media / Publishing",
    color: "#a855f7",
    icon: "📡",
    contacts: [
      {
        org: "Springer Nature (Scientific Publishing)",
        contact: "VP Acquisitions — Physical Sciences",
        email: "submissions@springernature.com",
        web: "https://www.springernature.com",
        rationale: "Suppressed science archive + annotated research platform. Primary source fragments, ONR documents, Priore records, Brush papers.",
        ask: "$800K–$2M content license",
      },
      {
        org: "Netflix Documentary Division",
        contact: "Original Documentary Pitches",
        email: "documentary@netflix.com",
        web: "https://media.netflix.com",
        rationale: "Priore cancer cure suppression story, Gulf War QP weapons, Baghdad scalar penetrator — three compelling documentary narratives with primary source documentation.",
        ask: "$500K–$2M documentary rights",
      },
    ],
  },
];

export const STAGES = [
  { id: "not_contacted", label: "Not Contacted", color: "#4b5563" },
  { id: "contacted", label: "Contacted", color: "#3b82f6" },
  { id: "nda_sent", label: "NDA Sent", color: "#f59e0b" },
  { id: "nda_signed", label: "NDA Signed", color: "#a855f7" },
  { id: "diligence", label: "In Diligence", color: "#06b6d4" },
  { id: "term_sheet", label: "Term Sheet", color: "#22c55e" },
  { id: "negotiating", label: "Negotiating", color: "#f97316" },
  { id: "closed", label: "Closed / Won", color: "#10b981" },
  { id: "passed", label: "Passed", color: "#ef4444" },
];