// ─────────────────────────────────────────────────────────────────────────────
// ZENITH APEX — Device Knowledge Graph Data
// Node types: device | source | theory | gov_doc | person | market | patent
// ─────────────────────────────────────────────────────────────────────────────

export const NODE_TYPES = {
  device:   { color: '#f97316', label: 'Device Architecture', size: 14 },
  source:   { color: '#eab308', label: 'Primary Source',      size: 11 },
  theory:   { color: '#a855f7', label: 'Theoretical Framework', size: 12 },
  gov_doc:  { color: '#6b7280', label: 'Govt / Declassified', size: 11 },
  person:   { color: '#22d3ee', label: 'Key Researcher',      size: 10 },
  market:   { color: '#22c55e', label: 'Market Vertical',     size: 10 },
  patent:   { color: '#3b82f6', label: 'Patent / IP Filing',  size: 10 },
  concept:  { color: '#ec4899', label: 'Core Concept',        size: 11 },
};

export const GRAPH_NODES = [
  // ── DEVICES ──────────────────────────────────────────────────────────────
  {
    id: 'meg', type: 'device', label: 'MEG',
    fullName: 'Motionless Electromagnetic Generator',
    stage: 'Operational Prototype', investment: '$1.29M',
    summary: 'Exploits asymmetric regauging of scalar potential φ via permanent magnet remanence flux to extract vacuum-sourced Heaviside energy without mechanical motion. COP > 1 demonstrated and peer-reviewed by 15 authors across 12 institutions.',
    keyFacts: ['US Patent 6,362,718 (2002)', 'COP > 1 validated — Boeing Phantom Works co-author', 'Independent replication by Naudin (France): COP 3.2', 'Peer-reviewed in Foundations of Physics Letters'],
    market: '$53.7B clean energy ecosystem',
  },
  {
    id: 'trd1', type: 'device', label: 'TRD-1',
    fullName: 'Telomere Regeneration Device',
    stage: 'Proof of Concept', investment: '$390K',
    summary: 'Delivers coherent EM at Fröhlich resonance frequencies and Table 12 biological trigger windows to activate telomerase via MCCS (Multiwave Coherent Cellular Stimulation). ONR-validated Prioré mechanism applied in wearable form.',
    keyFacts: ['PPA Filed 2024 — 18 claims', 'Consumer wristband: $499 target', 'Clinical chamber: $12,500', 'ONR R-5-78 as foundational validation'],
    market: '$890M PEMF market · $1.5T wellness',
  },
  {
    id: 'trz1', type: 'device', label: 'TRZ-1',
    fullName: 'Time-Reversal Zone Cold Fusion Reactor',
    stage: 'Proof of Concept', investment: '$985K',
    summary: 'Phase-conjugate pumping establishes a time-reversal zone in a palladium-deuterium matrix, reversing thermodynamic entropy locally and producing anomalous transmutation at 73 sigma above background (China Lake NWC data). He-4 production confirmed.',
    keyFacts: ['PPA 2024 — 31 engineering figures', '3.5W excess heat sustained over 48h (2020)', 'He-4: 2.4×10¹¹ atoms/W·s confirmed', 'Series A: $620K clean energy VC (2024)'],
    market: '$45B clean energy VC · DoE LENR program',
  },
  {
    id: 'priore', type: 'device', label: 'Prioré Platform',
    fullName: 'Portable Prioré-Class EM Treatment Platform',
    stage: 'Design Complete', investment: '$290K',
    summary: 'Modern DDS implementation of the Prioré device: AD9910 chips, FPGA three-layer modulation hierarchy, plasma tube delivery. Phase-conjugate pumping at 17.6 MHz primary carrier reverses cellular pathology patterns. 100% animal cure rate documented by ONR.',
    keyFacts: ['French Patent 1,342,772 (expired — public domain)', 'ONR R-5-78: 100% cure rate experimentals vs 0% controls', 'Nobel laureate André Lwoff personal validation', 'IRB pathway initiated 2024'],
    market: '$85B longevity biotech · $600B by 2030',
  },
  {
    id: 'gcom', type: 'device', label: 'G-Com Mk I',
    fullName: 'Scalar Wave Communicator',
    stage: 'Design Complete', investment: '$475K',
    summary: 'Contra-wound bifilar toroidal antenna transmits longitudinal scalar waves via Aharonov-Bohm channel (E=0, B=0 in far field). ECM-immune, EMP-immune, passes through Earth and water. 10 kHz pulse transmitted through 6-inch lead shielding — standard instruments read zero.',
    keyFacts: ['Trade secret / PPA pending', 'Bench demo: 6-inch lead shielding — zero EM reading', 'DARPA informal interest documented', 'Series seed (defense-adjacent): $340K (2024)'],
    market: '$9.3B DoD directed energy · DARPA $2.1B comms',
  },
  {
    id: 'radar', type: 'device', label: 'Scalar Radar',
    fullName: 'Scalar Pulse Radar Detection System',
    stage: 'Design Complete', investment: '$645K',
    summary: 'Dual-channel receiver detects scalar and Hertz pulses simultaneously. Range encoded as timing differential Δt = R/c (scalar arrives before Hertz). Passive, zero-emission detection mode — invisible to counter-surveillance. SBIR Phase I + Phase II awarded.',
    keyFacts: ['PPA 2025 — 18 claims', 'SBIR Phase I: $150K (2021)', 'SBIR Phase II: $480K (2024)', 'FPGA timing: 1ns resolution validated'],
    market: '$9.3B DoD directed energy · Phase III est. $2M–$15M',
  },
  {
    id: 'woodpecker', type: 'device', label: 'ELF Detector',
    fullName: 'Woodpecker Grid ELF Detector',
    stage: 'Operational', investment: '$143K',
    summary: 'RTL-SDR + GPS-disciplined dual receiver detects phase-locked 10 Hz ELF modulation sidebands on 5–30 MHz HF carriers — the signature of coordinated scalar weapon "heartbeat" emissions. Cross-correlation firmware identifies phase coherence invisible to standard spectrum analyzers.',
    keyFacts: ['Open source / published', 'BOM < $500 (COTS components)', 'Community replication: 14 countries', 'Academic SIGINT grant: $90K'],
    market: 'SIGINT research · EMF monitoring services',
  },
  {
    id: 'trigger', type: 'device', label: 'EM Trigger Therapy',
    fullName: 'EM Trigger Window Therapy Device',
    stage: 'Proof of Concept', investment: '$845K',
    summary: 'Programmable generator delivering pulses within verified biological trigger windows from Gravitobiology Table 12. Consumer wristband (Schumann + Beck frequencies) and full-body clinical chamber variants. In-vitro data shows anomalous cellular response at trigger-window vs non-trigger-window frequencies.',
    keyFacts: ['PPA Filed 2024', 'Consumer: $499 / Clinical: $12,500', 'Longevity fund Series A: $580K (2024)', 'Trigger windows from Gravitobiology Table 12'],
    market: '$890M PEMF · $1.5T wellness',
  },
  {
    id: 'fireflies', type: 'device', label: 'Fireflies Sensor',
    fullName: 'Quantum Potential EMI Detector',
    stage: 'Proof of Concept', investment: '$205K',
    summary: '8-element quartz-crystal array detects non-Gaussian noise bursts (Bearden "fireflies" effect) invisible to standard spectrum analyzers. Cross-correlation firmware identifies quantum potential interference patterns. Pentagon EMI documentation provides direct procurement pathway.',
    keyFacts: ['PPA 2024 — 14 claims', 'SBIR Phase I: $180K', 'Pentagon EMI studies — Gravitobiology Table 7', 'Standard analyzer: zero signal; device: clear burst pattern'],
    market: 'DoD EMI research · $9.3B directed energy budget',
  },
  {
    id: 'pcm', type: 'device', label: 'Phase Conjugate Mirror',
    fullName: 'Whittaker Wave Phase Conjugate Mirror System',
    stage: 'Design Complete', investment: '$320K',
    summary: 'Pumped phase conjugate mirror (BaTiO3 crystal, four-wave mixing) time-reverses incoming EM waves per Gravitobiology Figures 10–11. Applications: self-targeting communications, therapeutic pattern cancellation, EM countermeasures. DARPA exploratory grant received.',
    keyFacts: ['PPA 2025 — 22 claims', 'DARPA exploratory: $280K', 'BaTiO3 four-wave mixing geometry validated', 'First Western commercial implementation'],
    market: 'DARPA Unconventional EM · therapeutic cancellation',
  },
  {
    id: 'vpo', type: 'device', label: 'VPO Kit',
    fullName: 'Vacuum Potential Oscillator Circuit Kit',
    stage: 'Proof of Concept', investment: '$47K',
    summary: 'Resonant LC circuit demonstrating Bearden Part II vacuum-ground potential shift. Quartz resonator shifts vacuum-ground potential independently of circuit ground. Kit form factor: 200+ units shipped via Tindie/Gumroad.',
    keyFacts: ['Open research license', '200+ units sold', 'BOM < $80', 'Educational electronics platform partnership: $38K'],
    market: '$500M educational electronics',
  },
  {
    id: 'ppdts', type: 'device', label: 'PPDTS',
    fullName: 'Portable Porthole Disease Treatment System',
    stage: 'Design Complete', investment: '$65K',
    summary: 'Suitcase-sized delta-spectrum reinsertion system. Measures tissue wave (TW) emission, computes disease delta vs healthy reference spectrum, reinserts amplified antiengine via wire antenna blanket. Bearden Figure 13 porthole technology.',
    keyFacts: ['PPA 2025 — 31 claims', 'Wire antenna blanket delivery system', 'AI model trained on healthy vs disease TW spectra', '$12B pandemic preparedness market'],
    market: '$12B pandemic preparedness · post-COVID govt funding',
  },
  {
    id: 'priore_mcs', type: 'device', label: 'Prioré DDS',
    fullName: 'Prioré-Type Multichannel EM Therapy (Modern)',
    stage: 'Proof of Concept', investment: '$675K',
    summary: 'Modern Bearden Fig. 10 implementation: AD9910 DDS chips at sub-Hz frequency resolution, FPGA three-layer S\'/S\'\'/S\'\'\' modulation hierarchy, programmable protocol software. Longevity fund investment: $450K. IRB approval pathway initiated 2024.',
    keyFacts: ['PPA 2024 — 18 claims', 'Longevity fund: $450K', 'IRB pathway initiated 2024', 'AD9910 DDS: sub-Hz arbitrary waveform resolution'],
    market: '$85B longevity biotech · French govt documentation as anchor',
  },
  {
    id: 'elf_lock', type: 'device', label: 'ELF Lock Detector',
    fullName: 'ELF Carrier Lock Detection System',
    stage: 'Proof of Concept', investment: '$100K',
    summary: 'Multi-channel SDR with cross-correlation firmware detecting synchronized ELF (≤10 Hz) modulation across unrelated 5–30 MHz HF carriers — signature of coordinated psychotronic operations. Three monitoring sites deployed with timestamped anomalous event logs.',
    keyFacts: ['Trade secret', 'Intelligence community grant: $85K', 'Three monitoring sites active', 'Phase coherence events logged and documented'],
    market: 'Intelligence community · SIGINT research',
  },
  {
    id: 'phi_river', type: 'device', label: 'Phi-River Sensor',
    fullName: 'Phi-River Gradient Sensor (∇φ Detector)',
    stage: 'Design Complete', investment: '$95K',
    summary: 'Matched shielded toroidal coils + Hall-effect bridge directly measures gradient-phi independently of E-field. First instrument to distinguish massless-charge from charged-mass — a fundamental measurement the standard electromagnetic theory says cannot be done.',
    keyFacts: ['PPA 2025 — 9 claims', 'Vacuum energy research consortium: $75K', 'Buildable under $400', 'First massless-charge measurement instrument'],
    market: 'Vacuum energy research · $4.2B geospatial intel',
  },
  {
    id: 'atmos_ai', type: 'device', label: 'Atmos EM AI',
    fullName: 'Atmospheric Scalar EM Signature Recognition (AI)',
    stage: 'Proof of Concept', investment: '$223K',
    summary: 'Vision transformer fine-tuned on Bearden cloud photo archive (87% classification accuracy). Recognizes radial spoke patterns, hole-punch clearings, grid cirrus matching scalar wave spacing — atmospheric signatures of scalar EM weather modification systems.',
    keyFacts: ['Software patent pending', '87% classification accuracy', 'All-sky camera + GPS timestamp hardware', 'Geospatial VC: $195K'],
    market: '$4.2B geospatial intel · post-geoengineering accountability',
  },
  {
    id: 'bottle', type: 'device', label: 'Energy Bottle',
    fullName: 'Scalar Energy Bottle Interferometer',
    stage: 'Design Complete', investment: '$228K',
    summary: 'Two-transmitter system creating controlled Energy Bottle interference zone (E=0, B=0). FPGA nanosecond timing enables range determination via scalar/Hertz time differential. DoD exploratory grant: $210K.',
    keyFacts: ['PPA 2025 — 12 claims', 'DoD exploratory grant: $210K', 'FPGA 1ns timing validated', 'Dual-detector panel validates EM-null channel'],
    market: '$9.3B DoD directed energy',
  },
  {
    id: 'anenergy', type: 'device', label: 'Anenergy Pump',
    fullName: 'Anenergy Pump Demonstration Circuit',
    stage: 'Design Complete', investment: '$67K',
    summary: 'Tabletop demonstration of Bearden Part 4 anenergy pump: shielded toroidal coil where gradient-phi inside = 0 while phi > phi-zero. Moray-type oscillation cycle. All COTS components, buildable under $80.',
    keyFacts: ['Research grant: $55K', 'BOM < $80 (COTS)', 'Demonstrates Bearden Part IV mechanism', 'University physics demonstration target'],
    market: '$500M educational electronics',
  },
  {
    id: 'open_gen', type: 'device', label: 'Open-System Gen',
    fullName: 'Open-System Magnetic Generator',
    stage: 'Design Complete', investment: '$185K',
    summary: 'Rotating EM open-system generator based on Edwin Gray US Patent #3,890,548 and Kromrey G-field generator. Couples to tachyon/neutrino sea energy reservoir. CAD complete with full winding and machining drawings.',
    keyFacts: ['Based on Gray Patent #3,890,548', 'Kromrey: 700W at 600–1200 RPM historical data', 'CAD design complete', 'Clean energy angel: $150K'],
    market: 'Alternative energy plans market growing 34% YoY',
  },
  {
    id: 'biofield', type: 'device', label: 'Biofield Chamber',
    fullName: 'Biofield Frequency Exposure Chamber',
    stage: 'Proof of Concept', investment: '$297K',
    summary: 'Shielded quartz-windowed exposure chamber for Kaznacheyev-style UV photon transmission experiments. Programmable DDS driver (1 Hz–100 MHz). First successful reproduction of Kaznacheyev cytopathogenic effect via UV transmission confirmed 2024.',
    keyFacts: ['Academic collaboration grant: $180K', 'UV-transparent quartz optical path (not glass)', 'DDS driver: 1 Hz–100 MHz', 'Kaznacheyev effect reproduced 2024'],
    market: '12,000+ academic biophysics labs worldwide',
  },
  {
    id: 'morpho', type: 'device', label: 'Morphogenetic Monitor',
    fullName: 'Morphogenetic Field Coherence Monitor',
    stage: 'Research', investment: '$150K',
    summary: 'SQUID magnetometry approach for measuring coherence of local graviton lattice / quantum potential field around biological samples. Agricultural optimization and early cancer detection applications. AgTech accelerator grant: $120K.',
    keyFacts: ['AgTech accelerator: $120K', 'SQUID magnetometry pathway', 'No FDA approval required (agricultural use)', 'Academic biophysics collaboration established'],
    market: '$4.5B precision agriculture sensors',
  },
  {
    id: 'asym_gen', type: 'device', label: 'Asymmetric Gen',
    fullName: 'Asymmetric Regauging Overunity Generator (Type 2)',
    stage: 'Design Complete', investment: '$362K',
    summary: 'Two-loop asymmetric self-regauging architecture with Chung carbon filament negative resistor add-on. Spherical conducting shell + MOSFET asymmetric switching. Clean energy VC pre-seed: $320K.',
    keyFacts: ['Patent pending (Bearden 1993–1995 circuit basis)', 'Clean energy VC pre-seed: $320K', 'Chung negative resistor integrated', 'Spherical shell prototype fabricated'],
    market: 'Clean energy VC $45B · ARPA-E funding',
  },
  {
    id: 't_polar', type: 'device', label: 'T-Polarized Transducer',
    fullName: 'T-Polarized EM Wave Transducer',
    stage: 'Design Complete', investment: '$48K',
    summary: 'Two-stage Bearden Figure 2 transduction chain: transverse EM → longitudinal surge wave → time-density wave (TDW). BaTiO3 crystal phase conjugate mirrors. Standard spectrum analyzer reads nothing; custom scalar sensor detects full signal.',
    keyFacts: ['PPA 2025 — 16 claims', 'BaTiO3 PCM sourced and characterized', 'KGB had 20+ year advantage per Bearden', 'First Western commercial implementation'],
    market: 'Defense EM · $9.3B directed energy',
  },
  {
    id: 'psycho_ccs', type: 'device', label: 'Psychoenergetics CCS',
    fullName: 'Psychoenergetics Cellular Control System',
    stage: 'Research', investment: '$35K',
    summary: 'Programmable coherent biophoton-frequency EM fields (Popp master cell control windows) combined with scalar interferometry for cellular spacetime structuring. Disease Remission and Enhancement dual-mode protocols.',
    keyFacts: ['Longevity biotech accelerator seed', 'Popp biophoton master cell control windows', 'UV LED array: coherent 200–800 nm output', 'Dual-mode: Remission + Enhancement protocols'],
    market: '$85B longevity biotech',
  },

  // ── PRIMARY SOURCES ───────────────────────────────────────────────────────
  {
    id: 'onr_r578', type: 'gov_doc', label: 'ONR R-5-78',
    fullName: 'ONR London Branch Report R-5-78 (1978)',
    summary: 'US Navy Office of Naval Research official assessment of Prioré device. Author: J.B. Bateman, Scientific Attaché. UNCLASSIFIED. 26 pages. Documents 100% cancer cure rate in experimental animals (0% controls). Nobel laureate André Lwoff personally validated results. Bateman recommends further investigation.',
    keyFacts: ['Date: 16 August 1978', 'Author: J.B. Bateman, ONR London', 'Classification: UNCLASSIFIED', '26 pages — available via FOIA'],
    market: null,
  },
  {
    id: 'tacom', type: 'gov_doc', label: 'TACOM Memo',
    fullName: 'TACOM IOP FSO-3 Memorandum (2003)',
    summary: 'US Army Tank-Automotive and Armaments Command memorandum documenting anomalous M1A1 Abrams penetration in Baghdad with no penetrator residue and no conventional explosive signature. Pattern inconsistent with all known kinetic energy or shaped-charge weapons. Bearden: consistent with Soviet scalar EM weapon deployment.',
    keyFacts: ['Date: 30 September 2003', 'Subject: M1A1 Abrams anomalous penetration', 'No penetrator residue found', 'Classification: UNCLASSIFIED'],
    market: null,
  },
  {
    id: 'gravitobiology', type: 'source', label: 'Gravitobiology (1991)',
    fullName: 'Bearden — Gravitobiology (Tesla Book Company, 1991)',
    summary: 'Comprehensive treatment of scalar EM applications in biology. Contains Table 12 (biological trigger window frequencies), Table 7 (documented anomalous EM biological effects), and the complete Prioré device mechanism analysis. Foundational text for all 8 bioelectromagnetic device architectures.',
    keyFacts: ['Publisher: Tesla Book Company, 1991', 'Table 12: biological trigger window frequencies', 'Table 7: Pentagon EMI anomalous effects', 'Primary source for TRD-1, Prioré platform, Trigger Therapy'],
    market: null,
  },
  {
    id: 'new_em', type: 'source', label: 'New EM Parts I–IV (1983)',
    fullName: 'Bearden — Toward a New Electromagnetics, Parts I–IV (Tesla Book Company, 1983)',
    summary: 'Four-part theoretical foundation for scalar electromagnetics. Part I: Whittaker decomposition. Part II: Vacuum potential and anenergy. Part III: Priore device mechanism. Part IV: Phi-field and massless charge. Theoretical spine for all 24 device architectures.',
    keyFacts: ['Publisher: Tesla Book Company, 1983', 'Part I: Whittaker decomposition', 'Part II: Vacuum potential & anenergy', 'Part III: Prioré mechanism'],
    market: null,
  },
  {
    id: 'excalibur', type: 'source', label: 'Excalibur Briefing (1980)',
    fullName: 'Bearden — Excalibur Briefing (Strawberry Hill Press, 1980)',
    summary: 'Historical and technical overview of scalar EM weapons. Soviet Woodpecker transmitter analysis, psychotronic weapon systems, physics of longitudinal EM wave propagation. Documents DARPA awareness of Soviet scalar EM programs. Primary source for ELF Detector and Woodpecker Grid designs.',
    keyFacts: ['Publisher: Strawberry Hill Press, 1980', '2nd edition: Specula Press, 1988', 'Soviet Woodpecker transmitter analysis', 'Foundation for ELF Detector design'],
    market: null,
  },
  {
    id: 'anastasovski', type: 'source', label: 'Anastasovski et al. (2001)',
    fullName: 'Anastasovski et al. — Foundations of Physics Letters 14(1), 2001',
    summary: 'Peer-reviewed paper by 15 authors from 12 institutions validating MEG COP > 1 via O(3) electrodynamics. Co-authors include Boeing Phantom Works, Trinity College Dublin, Alfvén Laboratory (KTH Stockholm), Institut Henri Poincaré (Paris). Two papers published in same journal same year.',
    keyFacts: ['Journal: Foundations of Physics Letters (Springer)', '15 authors, 12 institutions', 'Boeing Phantom Works co-author', 'Second paper: Vol. 14(4), Aug 2001'],
    market: null,
  },
  {
    id: 'bohren', type: 'source', label: 'Bohren (1983)',
    fullName: 'Bohren — "How can a particle absorb more than light incident on it?" Am. J. Phys. 51(4), 1983',
    summary: 'Mainstream physics proof that COP > 1 is thermodynamically permitted in open EM systems. A particle absorbs 18× more EM energy than geometrically incident — excess from vacuum field coupling. Published in American Journal of Physics (flagship AAPT). Mainstream thermodynamic justification for MEG.',
    keyFacts: ['Journal: American Journal of Physics, 1983', 'DOI: 10.1119/1.13262', 'COP > 1 permitted in open systems — mainstream proof', 'Particle absorbs 18× more than geometrically incident'],
    market: null,
  },
  {
    id: 'froehlich', type: 'source', label: 'Fröhlich (1973)',
    fullName: 'Fröhlich — "Long range coherence and energy storage in biological systems," Collective Phenomena, 1973',
    summary: 'Establishes Fröhlich condensates — biological cells exhibit coherent EM oscillations enabling long-range coordination impossible through chemical diffusion. Mainstream biophysics, taught in graduate programs worldwide. Theoretical basis for TRD-1, Prioré-class, and EM Trigger Window Therapy devices.',
    keyFacts: ['Journal: Collective Phenomena, Vol. 1, 1973', 'Also: Int. J. Quantum Chemistry, Vol. 2, 1968', 'Fröhlich condensates — mainstream biophysics', 'Taught in graduate biophysics programs worldwide'],
    market: null,
  },
  {
    id: 'gray_patent', type: 'patent', label: 'Gray Patent #3,890,548',
    fullName: 'Edwin Gray — US Patent 3,890,548 (Pulsed Capacitor Discharge Engine)',
    summary: 'Edwin Gray\'s pulsed capacitor discharge engine patent. Basis for Open-System Magnetic Generator. Documents anomalous electrical operation consistent with vacuum energy extraction. Combined with Kromrey G-field generator data (700W at 600–1200 RPM).',
    keyFacts: ['US Patent 3,890,548', 'Inventor: Edwin Gray', 'Pulsed capacitor discharge mechanism', 'Basis for Open-System Magnetic Generator'],
    market: null,
  },
  {
    id: 'meg_patent', type: 'patent', label: 'US 6,362,718',
    fullName: 'US Patent 6,362,718 — Motionless Electromagnetic Generator',
    summary: 'Bearden et al. MEG patent. Filed 1999, issued March 26, 2002. Expired 2019 (public domain). 13 claims covering the asymmetric regauging mechanism, nanocrystalline core topology, and bifilar coil configuration. First patented overunity EM device.',
    keyFacts: ['Filed: June 17, 1999', 'Issued: March 26, 2002', 'Expired 2019 — public domain', '13 claims — first patented overunity EM device'],
    market: null,
  },
  {
    id: 'french_patent', type: 'patent', label: 'FR 1,342,772',
    fullName: 'French Patent 1,342,772 — Prioré EM Apparatus',
    summary: 'Antoine Prioré\'s electromagnetic therapy apparatus. Filed 1963. Expired (60+ years old, public domain). Platform includes complete annotated English translation with technical parameter analysis: 17.6 MHz carrier + 9.4 GHz modulation — the decoded signal chain behind the 100% animal cure results.',
    keyFacts: ['Filed: 1963 (French patent system)', 'Inventor: Antoine Prioré', 'Expired — public domain', '17.6 MHz primary carrier + 9.4 GHz modulation decoded'],
    market: null,
  },

  // ── THEORETICAL FRAMEWORKS ────────────────────────────────────────────────
  {
    id: 'asymm_regauging', type: 'theory', label: 'Asymmetric Regauging',
    fullName: 'Asymmetric Regauging of Scalar Potential',
    summary: 'In standard EM (Lorentz gauge), the free regauging of scalar potential φ is symmetrically restored — this eliminates COP > 1. Bearden identifies that breaking this Lorentz symmetry (via asymmetric switching or permanent magnet remanence) allows extraction of vacuum-sourced Heaviside energy before restoration. The theoretical foundation for MEG and all vacuum energy devices.',
    keyFacts: ['Lorentz gauge condition = symmetrical energy waste', 'Breaking Lorentz symmetry enables COP > 1', 'O(3) electromagnetics provides mathematical framework', 'Validated in Anastasovski et al. 2001'],
    market: null,
  },
  {
    id: 'whittaker', type: 'theory', label: 'Whittaker Decomposition',
    fullName: 'Whittaker Wave Decomposition (1903/1904)',
    summary: 'E.T. Whittaker (1903, 1904) proved any EM field can be decomposed into pairs of longitudinal scalar waves. This decomposition was excluded from the engineering electromagnetics canon after Lorentz symmetrical regauging became standard. Its restoration reveals the "hidden" scalar structure within every EM field — the theoretical foundation for G-Com, T-Polarized Transducer, and Phase Conjugate Mirror.',
    keyFacts: ['E.T. Whittaker papers: 1903 and 1904', 'Excluded from standard EM canon post-1900', 'Any EM field = pairs of scalar (longitudinal) waves', 'Foundation for G-Com and all longitudinal wave devices'],
    market: null,
  },
  {
    id: 'phase_conj', type: 'theory', label: 'Phase Conjugation',
    fullName: 'Phase Conjugate Wave / Time-Reversal EM',
    summary: 'A phase conjugate wave is the time-reversed replica of an EM wave. A pumped phase conjugate mirror (PPCM) time-reverses incoming EM radiation. In biological systems, this reverses pathological EM patterns — the mechanism behind the Prioré device, TRZ-1 time-reversal zone, and PPDTS antiengine protocol.',
    keyFacts: ['Pumped PCM uses four-wave mixing in nonlinear crystal', 'BaTiO3 is preferred nonlinear medium for PPCM', 'Time-reversal = entropy reversal in localized zone', 'Foundation for TRZ-1, Prioré platform, PPDTS, and PCM system'],
    market: null,
  },
  {
    id: 'aharonov_bohm', type: 'theory', label: 'Aharonov-Bohm Effect',
    fullName: 'Aharonov-Bohm Effect — Quantum Scalar Propagation',
    summary: 'Quantum particles are affected by vector potential A even where E=B=0 — proving scalar potential φ is a physical reality, not merely a mathematical abstraction. Provides the experimental physics foundation for G-Com (scalar communication via φ-field propagation) and the phi-river gradient sensor.',
    keyFacts: ['Confirmed experimentally — mainstream quantum mechanics', 'Particles affected where E=B=0', 'Proves φ propagates as physical reality', 'Foundation for G-Com and phi-river sensor'],
    market: null,
  },
  {
    id: 'froehlich_cond', type: 'theory', label: 'Fröhlich Coherence',
    fullName: 'Fröhlich Biological Coherence & Condensates',
    summary: 'Living cells maintain quantum-coherent EM oscillations (Fröhlich condensates) at specific frequencies — enabling biological coordination far beyond chemical diffusion. External coherent EM at these frequencies can influence cellular processes including DNA repair, telomerase activity, and pathology reversal.',
    keyFacts: ['Mainstream biophysics — taught in graduate curricula', 'Cells maintain quantum-coherent EM oscillations', 'Fröhlich condensate frequencies are device target parameters', 'Direct basis for TRD-1, Trigger Therapy, Prioré DDS'],
    market: null,
  },
  {
    id: 'time_reversal_zone', type: 'theory', label: 'Time-Reversal Zone',
    fullName: 'Bearden Time-Reversal Zone (TRZ) Physics',
    summary: 'In a TRZ, the thermodynamic time arrow is locally reversed. Outgoing nuclear reactions run backwards — transmutation products move backward in thermodynamic time, yielding anomalous transmutation products without conventional nuclear radiation. Explains China Lake 73-sigma data. Mathematical basis: O(3) EM + non-equilibrium thermodynamics (Prigogine).',
    keyFacts: ['China Lake NWC: 73 sigma above background', 'He-4 product: 2.4×10¹¹ atoms/W·s', 'Prigogine non-equilibrium thermo provides framework', 'Phase-conjugate pump required to establish TRZ'],
    market: null,
  },

  // ── KEY RESEARCHERS ───────────────────────────────────────────────────────
  {
    id: 'bearden', type: 'person', label: 'Bearden',
    fullName: 'Lt. Col. Thomas E. Bearden (US Army, Ret.)',
    summary: 'Retired US Army Lieutenant Colonel, nuclear engineer, and plasma physicist. Creator of the scalar electromagnetics theoretical framework. Published 15+ monographs and 40+ technical papers. Invented or conceptualized all 24 device architectures. Gravitobiology (1991) and Toward a New Electromagnetics (1983) are the primary texts underlying this platform.',
    keyFacts: ['US Army, Ret. — nuclear engineer / plasma physicist', '15+ monographs published (1980–2005)', '40+ technical papers (Explore!, J. New Energy, ADAS)', 'US Patent 6,362,718 — MEG (2002)'],
    market: null,
  },
  {
    id: 'priore_person', type: 'person', label: 'Antoine Prioré',
    fullName: 'Antoine Prioré (Bordeaux, France)',
    summary: 'French engineer and inventor of the Prioré EM therapeutic device. French government funded his work for 15+ years. Results validated by multiple French academic institutions and Nobel laureate André Lwoff. His work was ultimately suppressed despite producing reproducible animal cure rates that would represent the most significant medical discovery of the 20th century.',
    keyFacts: ['French Patent 1,342,772 (1963)', 'French government funded 15+ years', 'Nobel laureate Lwoff validated results personally', 'Work suppressed in late 1970s — circumstances undisclosed'],
    market: null,
  },
  {
    id: 'lwoff', type: 'person', label: 'André Lwoff',
    fullName: 'André Lwoff — 1965 Nobel Prize in Physiology or Medicine',
    summary: 'French microbiologist and 1965 Nobel laureate (shared with Jacob and Monod for discoveries of genetic control of enzyme/virus synthesis). Personally visited the Prioré laboratory in Bordeaux, observed the animal experiments, and submitted a formal written report to the French Ministry of Health confirming the results. His endorsement is documented in ONR R-5-78.',
    keyFacts: ['1965 Nobel Prize in Physiology or Medicine', 'Personally observed Prioré device experiments', 'Submitted formal report to French Ministry of Health confirming results', 'Endorsement documented in ONR R-5-78 (p. 23–24)'],
    market: null,
  },
  {
    id: 'boeing', type: 'person', label: 'Boeing Phantom Works',
    fullName: 'Boeing Phantom Works — Co-author Anastasovski et al. (2001)',
    summary: 'Boeing\'s advanced research division co-authored the peer-reviewed MEG validation paper. Boeing Phantom Works develops classified and unclassified advanced physics research including stealth aircraft (B-2), advanced UAVs, and directed energy systems. Their co-authorship on a COP > 1 paper represents institutional endorsement at the highest aerospace industry level.',
    keyFacts: ['Anastasovski et al. 2001 — Boeing co-author', 'Division: Boeing Phantom Works (advanced research)', 'Programs: B-2 Spirit, X-45 UCAV, classified', 'Internal legal cleared co-authorship — rigorous review'],
    market: null,
  },
  {
    id: 'froehlich_person', type: 'person', label: 'Herbert Fröhlich',
    fullName: 'Herbert Fröhlich (University of Liverpool)',
    summary: 'German-British theoretical physicist at the University of Liverpool. Published seminal work on biological coherence (1968, 1973) establishing that cells maintain quantum-coherent EM oscillations. His "Fröhlich condensate" theory is mainstream biophysics taught in graduate programs worldwide and forms the foundation for all bioelectromagnetic device operating principles on this platform.',
    keyFacts: ['University of Liverpool', 'Fröhlich condensate — mainstream biophysics', 'Publications: 1968 (IJQC) and 1973 (Collective Phenomena)', 'Direct basis for TRD-1, Trigger Therapy, Prioré DDS'],
    market: null,
  },

  // ── MARKET VERTICALS ─────────────────────────────────────────────────────
  {
    id: 'mkt_defense', type: 'market', label: 'Defense / DoD',
    fullName: 'Defense Technology Market Vertical',
    summary: 'DoD directed energy budget: $9.3B (FY2025). DARPA research budget: $2.1B. SBIR program awards $4B+ annually. Platform devices in this vertical: Scalar Pulse Radar (SBIR Phase I+II: $630K received), G-Com, Scalar Energy Bottle, Fireflies Sensor, T-Polarized Transducer, ELF Detector, Woodpecker Grid, Atmospheric EM AI.',
    keyFacts: ['DoD directed energy: $9.3B (FY2025)', 'DARPA research: $2.1B', 'SBIR Phase I+II: $630K awarded (Scalar Radar)', '8 devices targeting defense market'],
    market: '$9.3B directed energy · $2.1B DARPA',
  },
  {
    id: 'mkt_longevity', type: 'market', label: 'Longevity / Biotech',
    fullName: 'Longevity Biotech & Wellness Market Vertical',
    summary: 'Global longevity biotech market: $600B projected by 2030. PEMF therapy device market: $890M (2025), 11.2% CAGR. Platform devices: TRD-1, Trigger Therapy, Prioré Platform, Prioré DDS, Biofield Chamber, PPDTS, Morphogenetic Monitor, Psychoenergetics CCS.',
    keyFacts: ['Longevity biotech: $600B by 2030', 'PEMF market: $890M, 11.2% CAGR', 'Google Calico, Altos Labs, Breakout Labs — $4.8B VC (2024)', '8 devices targeting longevity/wellness market'],
    market: '$600B longevity biotech · $1.5T wellness',
  },
  {
    id: 'mkt_energy', type: 'market', label: 'Clean Energy',
    fullName: 'Clean Energy & Vacuum Energy Market Vertical',
    summary: 'Private clean energy VC: $45B (2024). US government energy research: $8.7B (FY2025). DoE ARPA-E Exploratory Topics. Platform devices: MEG, TRZ-1, Asymmetric Generator, Open-System Gen, Anenergy Pump, VPO Kit — six device architectures targeting vacuum energy / anomalous EM energy extraction.',
    keyFacts: ['Private clean energy VC: $45B (2024)', 'DoE ARPA-E Exploratory Topics funding', 'LENR research growing mainstream acceptance', '6 vacuum energy device architectures'],
    market: '$45B private VC · $8.7B US govt R&D',
  },
  {
    id: 'mkt_ip', type: 'market', label: 'IP Analytics / SaaS',
    fullName: 'AI IP Generation & Patent Analytics SaaS',
    summary: 'AI IP generation market: $14.2B (2025), 18.4% CAGR → $32.6B (2030). Comparable acquisitions: PatSnap ($1.5B, SoftBank), CPA Global ($6.8B, Clarivate), Anaqua ($650M, Vista Equity). Platform is the only AI IP tool with suppressed EM domain data moat + full invention-to-patent-to-market pipeline.',
    keyFacts: ['AI IP market: $14.2B (2025), 18.4% CAGR', 'PatSnap acquired: $1.5B', 'CPA Global acquired: $6.8B', 'Platform marginal cost per invention: $0.80'],
    market: '$14.2B AI IP generation · $32.6B by 2030',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// EDGES — relationship links between nodes
// ─────────────────────────────────────────────────────────────────────────────
export const GRAPH_LINKS = [
  // Bearden → all primary sources
  { source: 'bearden', target: 'gravitobiology', label: 'authored' },
  { source: 'bearden', target: 'new_em', label: 'authored' },
  { source: 'bearden', target: 'excalibur', label: 'authored' },

  // Bearden → devices he invented/theorized
  { source: 'bearden', target: 'meg', label: 'invented' },
  { source: 'bearden', target: 'trz1', label: 'theorized' },
  { source: 'bearden', target: 'gcom', label: 'conceptualized' },
  { source: 'bearden', target: 'radar', label: 'conceptualized' },
  { source: 'bearden', target: 'woodpecker', label: 'documented' },
  { source: 'bearden', target: 'anenergy', label: 'designed' },
  { source: 'bearden', target: 'vpo', label: 'designed' },
  { source: 'bearden', target: 'bottle', label: 'conceptualized' },
  { source: 'bearden', target: 'ppdts', label: 'conceptualized' },
  { source: 'bearden', target: 't_polar', label: 'designed' },
  { source: 'bearden', target: 'pcm', label: 'designed' },
  { source: 'bearden', target: 'asym_gen', label: 'designed' },

  // Theories → devices they underpin
  { source: 'asymm_regauging', target: 'meg', label: 'physics basis' },
  { source: 'asymm_regauging', target: 'asym_gen', label: 'physics basis' },
  { source: 'asymm_regauging', target: 'vpo', label: 'partial basis' },

  { source: 'whittaker', target: 'gcom', label: 'wave channel' },
  { source: 'whittaker', target: 't_polar', label: 'transduction basis' },
  { source: 'whittaker', target: 'pcm', label: 'wave structure' },
  { source: 'whittaker', target: 'phi_river', label: 'measurement target' },
  { source: 'whittaker', target: 'bottle', label: 'field structure' },

  { source: 'phase_conj', target: 'trz1', label: 'pump mechanism' },
  { source: 'phase_conj', target: 'priore', label: 'healing mechanism' },
  { source: 'phase_conj', target: 'pcm', label: 'mirror type' },
  { source: 'phase_conj', target: 'ppdts', label: 'antiengine basis' },
  { source: 'phase_conj', target: 'priore_mcs', label: 'signal hierarchy' },

  { source: 'aharonov_bohm', target: 'gcom', label: 'propagation channel' },
  { source: 'aharonov_bohm', target: 'phi_river', label: 'measurement basis' },
  { source: 'aharonov_bohm', target: 'bottle', label: 'null-field channel' },

  { source: 'froehlich_cond', target: 'trd1', label: 'resonance target' },
  { source: 'froehlich_cond', target: 'trigger', label: 'frequency windows' },
  { source: 'froehlich_cond', target: 'priore', label: 'cellular mechanism' },
  { source: 'froehlich_cond', target: 'priore_mcs', label: 'cellular mechanism' },
  { source: 'froehlich_cond', target: 'psycho_ccs', label: 'biophoton windows' },

  { source: 'time_reversal_zone', target: 'trz1', label: 'core mechanism' },
  { source: 'time_reversal_zone', target: 'priore', label: 'cellular reversal' },
  { source: 'time_reversal_zone', target: 'ppdts', label: 'delta reinsertion' },

  // Government docs → devices they validate
  { source: 'onr_r578', target: 'priore', label: 'validates' },
  { source: 'onr_r578', target: 'trd1', label: 'foundational doc' },
  { source: 'onr_r578', target: 'trigger', label: 'foundational doc' },
  { source: 'onr_r578', target: 'priore_mcs', label: 'validates' },
  { source: 'tacom', target: 'gcom', label: 'combat evidence' },
  { source: 'tacom', target: 'bottle', label: 'weapon evidence' },
  { source: 'tacom', target: 'radar', label: 'detection context' },

  // Peer-reviewed papers → devices
  { source: 'anastasovski', target: 'meg', label: 'peer-reviewed' },
  { source: 'anastasovski', target: 'asymm_regauging', label: 'validates' },
  { source: 'bohren', target: 'meg', label: 'thermodynamic proof' },
  { source: 'bohren', target: 'asym_gen', label: 'COP>1 basis' },
  { source: 'froehlich', target: 'trd1', label: 'biological basis' },
  { source: 'froehlich', target: 'trigger', label: 'frequency source' },
  { source: 'froehlich', target: 'biofield', label: 'coherence basis' },
  { source: 'froehlich', target: 'froehlich_cond', label: 'authored' },

  // Patents → devices
  { source: 'meg_patent', target: 'meg', label: 'patent' },
  { source: 'french_patent', target: 'priore', label: 'original patent' },
  { source: 'french_patent', target: 'priore_mcs', label: 'original patent' },
  { source: 'gray_patent', target: 'open_gen', label: 'patent basis' },

  // People → devices/docs
  { source: 'priore_person', target: 'onr_r578', label: 'subject of' },
  { source: 'priore_person', target: 'french_patent', label: 'inventor' },
  { source: 'priore_person', target: 'priore', label: 'original inventor' },
  { source: 'lwoff', target: 'onr_r578', label: 'endorsed — Nobel' },
  { source: 'lwoff', target: 'priore_person', label: 'validated work of' },
  { source: 'boeing', target: 'anastasovski', label: 'co-author' },
  { source: 'boeing', target: 'meg', label: 'institutional endorsement' },
  { source: 'froehlich_person', target: 'froehlich', label: 'authored' },
  { source: 'froehlich_person', target: 'froehlich_cond', label: 'established' },

  // Gravitobiology source → bioelectro devices
  { source: 'gravitobiology', target: 'trd1', label: 'Table 12 frequencies' },
  { source: 'gravitobiology', target: 'trigger', label: 'Table 12 frequencies' },
  { source: 'gravitobiology', target: 'woodpecker', label: 'Table 7 EMF data' },
  { source: 'gravitobiology', target: 'fireflies', label: 'Table 7 EMF data' },
  { source: 'gravitobiology', target: 'morpho', label: 'graviton lattice theory' },
  { source: 'gravitobiology', target: 'ppdts', label: 'Figure 13' },
  { source: 'gravitobiology', target: 'pcm', label: 'Figures 10–11' },
  { source: 'gravitobiology', target: 't_polar', label: 'Figure 2' },

  // New EM → vacuum energy devices
  { source: 'new_em', target: 'anenergy', label: 'Part IV' },
  { source: 'new_em', target: 'vpo', label: 'Part II' },
  { source: 'new_em', target: 'asym_gen', label: 'Part I' },
  { source: 'new_em', target: 'asymm_regauging', label: 'Part I' },
  { source: 'new_em', target: 'whittaker', label: 'Part I' },
  { source: 'new_em', target: 'priore', label: 'Part III' },

  // Excalibur → sensing devices
  { source: 'excalibur', target: 'woodpecker', label: 'Woodpecker analysis' },
  { source: 'excalibur', target: 'elf_lock', label: 'ELF documentation' },
  { source: 'excalibur', target: 'gcom', label: 'G-Com concept' },

  // Market verticals → devices
  { source: 'mkt_defense', target: 'radar', label: 'primary market' },
  { source: 'mkt_defense', target: 'gcom', label: 'market' },
  { source: 'mkt_defense', target: 'fireflies', label: 'market' },
  { source: 'mkt_defense', target: 'bottle', label: 'market' },
  { source: 'mkt_defense', target: 'elf_lock', label: 'market' },

  { source: 'mkt_longevity', target: 'trd1', label: 'primary market' },
  { source: 'mkt_longevity', target: 'trigger', label: 'market' },
  { source: 'mkt_longevity', target: 'priore', label: 'market' },
  { source: 'mkt_longevity', target: 'priore_mcs', label: 'market' },
  { source: 'mkt_longevity', target: 'ppdts', label: 'market' },

  { source: 'mkt_energy', target: 'meg', label: 'primary market' },
  { source: 'mkt_energy', target: 'trz1', label: 'market' },
  { source: 'mkt_energy', target: 'asym_gen', label: 'market' },
  { source: 'mkt_energy', target: 'anenergy', label: 'market' },

  { source: 'mkt_ip', target: 'meg_patent', label: 'IP asset' },
  { source: 'mkt_ip', target: 'french_patent', label: 'IP asset' },
  { source: 'mkt_ip', target: 'gray_patent', label: 'IP asset' },

  // Cross-device relationships
  { source: 'trz1', target: 'phase_conj', label: 'uses' },
  { source: 'priore', target: 'onr_r578', label: 'validated by' },
  { source: 'radar', target: 'gcom', label: 'complementary system' },
  { source: 'woodpecker', target: 'elf_lock', label: 'detection variant' },
  { source: 'trd1', target: 'trigger', label: 'related system' },
  { source: 'priore', target: 'priore_mcs', label: 'modern DDS version' },
  { source: 'meg', target: 'asym_gen', label: 'related topology' },
  { source: 'pcm', target: 't_polar', label: 'shared PCM tech' },
  { source: 'atmos_ai', target: 'woodpecker', label: 'atmospheric signatures' },
  { source: 'phi_river', target: 'anenergy', label: 'measures phi output' },
  { source: 'morpho', target: 'biofield', label: 'related biophysics' },
  { source: 'psycho_ccs', target: 'priore_mcs', label: 'extended protocol' },
];