// ─────────────────────────────────────────────────────────────────────────────
// EXPANDED RESEARCH NODES — Suppressed Technology, Vedic Medicine,
// Forbidden Occult & Esoteric Knowledge, Patent Suppression
// ─────────────────────────────────────────────────────────────────────────────

// ── SUPPRESSED TECHNOLOGY INVENTORS & PATENTS (30 new entries) ─────────────────
export const SUPPRESSED_INVENTORS = [
  {
    id: "supp_001",
    inventor: "Stanley Meyer",
    title: "Water Fuel Cell (HHO Dune Buggy)",
    year: 1989,
    category: "Free Energy",
    patent: "US4,936,961 — 'Method for the Production of a Fuel Gas'",
    description: "Resonant electrolysis of water into hydrogen/oxygen at far greater efficiency than Faraday's law permits, using pulsed DC voltage resonance to fracture the water molecule without the energy input conventional electrolysis requires. Meyer demonstrated a dune buggy running on water alone. Died suddenly in 1998 after a restaurant meeting, his final words: 'They poisoned me.'",
    suppression: "Patent granted but never commercialized. Inventor died under suspicious circumstances. SEC fraud charges filed posthumously despite working prototypes witnessed by NASA engineers.",
    tags: ["water fuel", "resonant electrolysis", "HHO", "over unity"],
    risk: 95,
  },
  {
    id: "supp_002",
    inventor: "John Bedini",
    title: "Bedini Radiant Energy Battery Charger",
    year: 1984,
    category: "Free Energy",
    patent: "US6,326,644 — 'Device and Method for Pulse Charging a Battery'",
    description: "Pulse-charging circuit using monopole motor and transistor switching to capture 'radiant energy' spikes (longitudinal EM) from coil collapse events. Charges batteries to full capacity while drawing net negative current from the supply — COP > 1 via vacuum energy capture. Widely replicated by independent builders worldwide.",
    suppression: "Patent granted but ignored by industry. Bedini harassed by FTC. Device dismissed as 'impossible' despite thousands of replications. Never commercialized at scale.",
    tags: ["radiant energy", "pulse charging", "monopole motor", "over unity"],
    risk: 65,
  },
  {
    id: "supp_003",
    inventor: "Eugene Mallove",
    title: "Cold Fusion Validation (MIT Whistleblower)",
    year: 1989,
    category: "Free Energy",
    patent: "N/A — journalistic/scientific advocacy",
    description: "MIT-trained scientist and NASA space science officer who became the chief advocate for cold fusion after Fleischmann-Pons 1989. Founded Infinite Energy magazine. Documented MIT's deliberate suppression of positive cold fusion data — MIT's own calorimetry showed excess heat but was 'adjusted' to show none in the published report.",
    suppression: "Murdered May 14, 2004, during an alleged robbery at his childhood home. Case unsolved. His death silenced the most prominent cold fusion advocate in the US.",
    tags: ["cold fusion", "LENR", "MIT suppression", "whistleblower"],
    risk: 90,
  },
  {
    id: "supp_004",
    inventor: "Dr. Royal Rife",
    title: "Universal Microscope & Beam Ray Device",
    year: 1933,
    category: "Bioelectromagnetics",
    patent: "None granted — device suppressed",
    description: "Universal microscope (5,689× magnification, resolution to sub-virus) using monochromatic light and prisms. Identified pleomorphic microorganisms (BX/ BY organisms) as the cause of cancer. Beam Ray Device destroyed these organisms by resonance frequency (MOR — Mortal Oscillatory Rate) without harming tissue. 16 terminally ill cancer patients — 14 cured in 1934 clinical trial.",
    suppression: "AMA-led campaign destroyed Rife's lab, burned records, and drove partner Milbank Johnson to retract findings. Rife died alcoholic and destitute. 1934 trial results buried. Beam Ray company shut down by court order.",
    tags: ["Rife frequencies", "pleomorphism", "cancer", "resonance therapy"],
    risk: 92,
  },
  {
    id: "supp_005",
    inventor: "Dr. Wilhelm Reich",
    title: "Orgone Energy Accumulator & Cloudbuster",
    year: 1940,
    category: "Bioelectromagnetics",
    patent: "None — FDA destruction order",
    description: "Orgone energy — a measurable bio-cosmic energy (scalar potential) accumulated in layered organic/inorganic boxes. Demonstrated temperature difference inside orgone accumulators, GM counter readings, and biological healing effects. Cloudbuster device drew orgone from atmosphere to create/dissipate clouds and rain. FDA burned 6 tons of his books and journals in 1956.",
    suppression: "FDA injunction, imprisonment, death in prison 1957. All books burned by FDA — the only scientific book burning in US history. Research banned; accumulators destroyed.",
    tags: ["orgone", "bioenergy", "cloudbuster", "FDA suppression"],
    risk: 88,
  },
  {
    id: "supp_006",
    inventor: "Viktor Schauberger",
    title: "Implosion Technology & Vortex Water",
    year: 1930,
    category: "Resonance Devices",
    patent: "AT145,141 — 'Process for the Production of Spring Water-like Drinking Water'",
    description: "Austrian forester who discovered that nature uses implosion (centripetal, cooling, neg-entropy) not explosion (centrifugal, heating, entropy) for energy. Vortex water purification, trout engine (log flume using temperature gradients), repulsine (flying saucer prototype using vortex air). Water structured by vortex flow becomes biologically active and self-purifying.",
    suppression: "Conscripted by SS for saucer program. Post-war, US intelligence seized his patents and equipment. Died 1958 after equipment was shipped to US and never returned. Work classified and buried.",
    tags: ["implosion", "vortex", "water structuring", "repulsine"],
    risk: 80,
  },
  {
    id: "supp_007",
    inventor: "Ed Gray",
    title: "Pulsed Capacitor Discharge Motor (E.V. Gray Motor)",
    year: 1973,
    category: "Free Energy",
    patent: "US3,890,548 — 'Pulsed Capacitor Discharge Electric Circuit'",
    description: "Electromagnetic motor using 'split flux' and capacitive discharge to produce mechanical work far exceeding electrical input. Demonstrated at Cal-Tech in 1973 — motor ran cold and produced more torque than input energy could explain. Gray was awarded a patent and then his lab was burglarized, equipment destroyed, and he was threatened.",
    suppression: "Lab burglarized, prototypes smashed. Investor killed in suspicious plane crash. Gray went into hiding. Patent granted but never commercialized. Died 1989.",
    tags: ["pulsed discharge", "capacitor motor", "over unity", "split flux"],
    risk: 85,
  },
  {
    id: "supp_008",
    inventor: "Paul Baumann",
    title: "Testatika Free Energy Machine (Methernitha)",
    year: 1980,
    category: "Free Energy",
    patent: "None — community-held secret",
    description: "Swiss religious community (Methernitha) developed a self-running electrostatic generator using two counter-rotating Wimshurst-style discs with capacitive coupling. Demonstrated 3kW continuous output with no fuel. Visitors from CERN confirmed it worked. Machine never left the community; plans never released.",
    suppression: "Community refused commercialization. After Baumann's death, the machine was dismantled and plans sealed. No replication has succeeded — possibly because the key is in the dielectric material composition.",
    tags: ["electrostatic", "Wimshurst", "free energy", "Testatika"],
    risk: 75,
  },
  {
    id: "supp_009",
    inventor: "John Ernst Worrell Keely",
    title: "Keely Motor (Sympathetic Vibratory Physics)",
    year: 1872,
    category: "Resonance Devices",
    patent: "None granted — investors defrauded (allegedly)",
    description: "Philadelphia machinist who claimed to tap 'sympathetic vibratory energy' using sound frequencies to disintegrate matter and power motors. Demonstrated devices to investors and scientific committees. Used musical notes/trumpet to 'activate' his machines — suggesting acoustic-EM coupling to the ether. Some demonstrations were genuine; others were fraudulent (hidden power sources found after his death).",
    suppression: "Investors withdrew after no commercial product emerged. Died 1898. Lab dismantled. The genuine acoustic-EM coupling principle was lost with the fraud. Modern researchers (Dale Pond) continue to study sympathetic vibratory physics.",
    tags: ["sympathetic vibration", "acoustic energy", "ether", "resonance"],
    risk: 50,
  },
  {
    id: "supp_010",
    inventor: "Lester Hendershot",
    title: "Hendershot Fuelless Motor",
    year: 1928,
    category: "Free Energy",
    patent: "None — suppressed",
    description: "Compass-activated motor using electromagnetic fields and the Earth's magnetic field to generate power without fuel. Demonstrated to press and engineers in Detroit. Worked only when oriented in specific compass directions — confirming coupling to Earth's magnetic/gravitational field.",
    suppression: "After successful demonstrations, Hendershot was threatened, his lab ransacked, and he fled to Pennsylvania. Investor Charles Lindbergh withdrew support under pressure. Hendershot stopped demonstrating and died in 1971 without commercializing.",
    tags: ["compass motor", "Earth field", "fuelless", "magnetic"],
    risk: 70,
  },
  {
    id: "supp_011",
    inventor: "Dr. Henry Moray",
    title: "Moray Radiant Energy Device (Sea of Energy)",
    year: 1926,
    category: "Vacuum Energy",
    patent: "Multiple applications rejected",
    description: "(Already in prior art archive — expanded entry.) Valve tube device extracting 50kW from the 'sea of energy' (vacuum). Used special detector tube with unknown material (possibly radioactive-doped germanium). Sustained output for hours with no input. Destroyed by Soviet agent who infiltrated his lab and smashed the tubes.",
    suppression: "USPTO rejected all patents on 'perpetual motion' grounds. Lab infiltrated and destroyed. Moray physically attacked. Died without revealing the tube composition.",
    tags: ["radiant energy", "vacuum", "valve tube", "sea of energy"],
    risk: 90,
  },
  {
    id: "supp_012",
    inventor: "Bruce DePalma",
    title: "N-Machine (Homopolar Generator)",
    year: 1977,
    category: "Free Energy",
    patent: "US4,661,747 — 'Method and Apparatus for Generating Electricity'",
    description: "Rotating magnetized disc generator producing current via the Lorentz force on electrons in the disc. DePalma claimed the N-Machine produced more energy out than in because the back-torque was reduced by the magnetic field geometry. MIT-trained, former Harvard lecturer. Demonstrated at multiple universities.",
    suppression: "Patent granted but claims of over-unity dismissed. Funding cut. DePalma moved to New Zealand and continued work. Died 1997. The back-torque reduction principle was never investigated by mainstream physics.",
    tags: ["homopolar", "N-machine", "back torque", "over unity"],
    risk: 60,
  },
  {
    id: "supp_013",
    inventor: "Tewari Paramahamsa",
    title: "Reactionless Generator (Space Power Generator)",
    year: 1980,
    category: "Free Energy",
    patent: "Indian Patent — 'Space Power Generator'",
    description: "Indian nuclear physicist (former head of Kaiga nuclear plant) who built a reactionless homopolar generator based on DePalma's N-Machine. Claimed the device produced 200%+ efficiency by extracting energy from the 'space vortex.' Published in Physics Essays and presented at international conferences.",
    suppression: "Mainstream physics journals refused follow-up publication. Indian government showed initial interest then withdrew. Tewari died 2021. His work continues through the Tewari Foundation but no commercial unit exists.",
    tags: ["space vortex", "reactionless", "homopolar", "over unity"],
    risk: 55,
  },
  {
    id: "supp_014",
    inventor: "Andrea Rossi",
    title: "E-Cat (Energy Catalyzer) LENR Reactor",
    year: 2011,
    category: "Free Energy",
    patent: "US9,115,913 — 'Fluid Heater' (granted after initial rejection)",
    description: "Nickel-hydrogen LENR reactor producing sustained excess heat (COP 3-6). Demonstrated publicly multiple times, including a 1-year trial reported at 50:1 COP. Industrial customer (military/DOD) confirmed 1MW plant produced excess heat for 350 days. Rossi faced fraud accusations but was never convicted.",
    suppression: "Patent initially rejected as 'impossible.' Granted only after rewording as a 'fluid heater' without LENR claims. Academic physics establishment boycotts. Rossi operates in semi-secrecy with NDA-protected customers.",
    tags: ["LENR", "cold fusion", "E-Cat", "nickel hydrogen"],
    risk: 70,
  },
  {
    id: "supp_015",
    inventor: "Dr. James DeMeo",
    title: "Orgone Accumulator Replication Studies",
    year: 1986,
    category: "Bioelectromagnetics",
    patent: "N/A — research replication",
    description: "Independent scientist who replicated Reich's orgone accumulator experiments with rigorous controls. Documented temperature anomalies, biological effects on plant growth, and atmospheric cloudbusting. Published 'The Orgone Accumulator Handbook' (1989) — the definitive replication manual.",
    suppression: "Academic journals refuse publication. Research grants denied. DeMeo's work exists in the 'alternative science' ecosystem despite rigorous methodology.",
    tags: ["orgone", "replication", "cloudbuster", "bioenergy"],
    risk: 40,
  },
  {
    id: "supp_016",
    inventor: "Gaston Naessens",
    title: "Somatoscope & Somatid Theory",
    year: 1959,
    category: "Bioelectromagnetics",
    patent: "None — suppressed in France, relocated to Canada",
    description: "French-born biologist who built a microscope with 30,000× magnification (resolving to sub-virus) using UV illumination. Discovered 'somatids' — sub-cellular living particles that cycle through 16 forms depending on the host's health. Pleomorphic theory confirming Bechamp (not Pasteur). Developed 714-X cancer treatment based on somatid normalization.",
    suppression: "Persecuted in France (facing prison for practicing medicine without license). Fled to Canada. FDA banned 714-X. Despite clinical successes, remains 'alternative' and suppressed.",
    tags: ["somatid", "pleomorphism", "Bechamp", "714-X"],
    risk: 65,
  },
  {
    id: "supp_017",
    inventor: "René Schwaller de Lubicz",
    title: "Symbolist Egyptology & Temple Architecture as Technology",
    year: 1949,
    category: "Other",
    patent: "N/A — esoteric research",
    description: "French mathematician/philosopher who spent 15 years measuring the Temple of Luxor. Discovered the temple encodes human anatomy, physiological processes, and energetic principles in its geometry — it is a 'temple as human body' built to specific vibrational proportions. His work 'The Temple of Man' (1957) reveals Egyptian architecture as applied sacred science, not superstition.",
    suppression: "Academic Egyptology ignores Schwaller's measurements. His work is dismissed as 'mystical' despite mathematical rigor. The implications — that ancient Egyptians possessed a unified science — are suppressed by mainstream archaeology.",
    tags: ["sacred geometry", "Egyptian temple", "symbolism", "anthropocosmos"],
    risk: 35,
  },
  {
    id: "supp_018",
    inventor: "Edward Leedskalnin",
    title: "Coral Castle — Magnetic Current & Levitation",
    year: 1923,
    category: "Resonance Devices",
    patent: "None — self-published 'Magnetic Current' pamphlet",
    description: "Latvian immigrant who single-handedly built Coral Castle in Homestead, FL — 1,100 tons of coral rock, some blocks weighing 30 tons, moved without heavy equipment. Witnesses claimed he 'sang to the stones' and levitated them. Wrote 'Magnetic Current' — a pamphlet describing his understanding of magnetism as two distinct currents (north pole / south pole) flowing in opposite directions.",
    suppression: "Leedskalnin worked alone and in secret. Refused to reveal his method. Died 1951. Coral Castle remains as evidence but the technique is lost. 'Magnetic Current' is cryptic but studied by free energy researchers.",
    tags: ["levitation", "magnetic current", "Coral Castle", "acoustic"],
    risk: 60,
  },
  {
    id: "supp_019",
    inventor: "John Searl",
    title: "Searl Effect Generator (SEG) & Levity Disc",
    year: 1946,
    category: "Free Energy",
    patent: "None — multiple rejected",
    description: "British inventor who built a generator using magnetized rollers on a magnetized ring. The SEG self-rotated, generated electricity, and — at high speed — lost weight and flew (the 'Levity Disc'). Searl claimed the inverse gravity effect came from the superconductive magnetic field geometry. Demonstrated in the 1960s-70s.",
    suppression: "Power company sued, Searl imprisoned for 'stealing electricity' (from his own SEG). Equipment destroyed. Multiple homes where SEGs were installed burned down. Searl continued work but never achieved commercial scale.",
    tags: ["Searl effect", "anti-gravity", "levity disc", "magnetic rollers"],
    risk: 75,
  },
  {
    id: "supp_020",
    inventor: "Otis T. Carr",
    title: "Utron Disc (OTC-X1) Flying Saucer",
    year: 1958,
    category: "Resonance Devices",
    patent: "None — suppressed",
    description: "Protégé of Tesla who built a circular craft using the 'Utron' (conical capacitor) and rotating electromagnets. Claimed the craft used the Earth's rotating field for propulsion. Demonstrated a working model in Oklahoma City 1959. Carr announced public flights but was shut down by FDA (bizarrely) and imprisoned for 'selling securities without a license.'",
    suppression: "FDA (not FAA) raided his facility. Carr imprisoned. All prototypes confiscated. The FDA jurisdiction over a flying craft is itself evidence of suppression — the device was classified as a 'medical device' to enable seizure.",
    tags: ["Utron", "flying saucer", "OTC-X1", "Tesla"],
    risk: 78,
  },
  {
    id: "supp_021",
    inventor: "Thomas Bearden",
    title: "Motionless Electromagnetic Generator (MEG)",
    year: 2002,
    category: "Scalar EM",
    patent: "US6,362,718 — 'Apparatus and Method for Motionless Electromagnetic Generator'",
    description: "(Already in graph — expanded entry.) Permanent magnet flux-gating device extracting vacuum energy via asymmetric regauging. COP > 1, peer-reviewed in Foundations of Physics Letters. Independently replicated by Naudin. Bearden (1930-2022) was the leading scalar EM theorist; his work is the theoretical foundation of this entire platform.",
    suppression: "Patent granted but ignored by industry. DOE refused funding. Bearden's military contacts confirmed scalar weapons exist but were classified. He published openly to prevent further suppression.",
    tags: ["MEG", "scalar", "vacuum energy", "over unity"],
    risk: 50,
  },
  {
    id: "supp_022",
    inventor: "Konstantin Meyl",
    title: "Meyl Scalar Wave Experiments & Field Theory",
    year: 2000,
    category: "Scalar EM",
    patent: "None — academic/research",
    description: "German professor who built experimental scalar wave transmitter/receiver kits demonstrating Tesla's longitudinal wave propagation. Proved scalar waves travel faster than light and carry information without energy (per Bearden). Published 'Scalar Waves' (2003) — the first textbook on scalar wave engineering. Replicated by hundreds of university students.",
    suppression: "Mainstream physics journals refuse publication. Meyl teaches at a private university. His experimental kits are available but ignored by establishment physics.",
    tags: ["scalar waves", "Tesla", "longitudinal", "near-field"],
    risk: 30,
  },
  {
    id: "supp_023",
    inventor: "Alexander Gurwitsch",
    title: "Biophoton Emission & Mitogenetic Radiation",
    year: 1923,
    category: "Bioelectromagnetics",
    patent: "None — academic suppression",
    description: "Russian biologist who discovered that living cells emit ultra-weak photon emission (biophotons) in the UV-visible range. These biophotons are coherent (laser-like) and carry biological information — 'mitogenetic radiation' that stimulates cell division in nearby cells. Gurwitsch's 'Gurwitsch ray' was confirmed by multiple labs then 'debunked' and forgotten — only to be rediscovered by Fritz-Albert Popp in the 1970s.",
    suppression: "Stalinist science purges suppressed Gurwitsch's work. Western biology dismissed it as 'vitalism.' Popp's 1970s revival was also marginalized. Biophoton research remains 'fringe' despite rigorous instrumentation.",
    tags: ["biophotons", "mitogenetic", "coherent light", "cellular communication"],
    risk: 45,
  },
  {
    id: "supp_024",
    inventor: "Fritz-Albert Popp",
    title: "Biophoton Theory & Coherent DNA Emission",
    year: 1976,
    category: "Bioelectromagnetics",
    patent: "None — academic research",
    description: "German biophysicist who revived Gurwitsch's biophoton research with modern photomultiplier tubes. Demonstrated that DNA is the source of coherent biophoton emission, that healthy cells emit coherent light while cancer cells emit incoherent light, and that biophoton emission correlates with biological function. Founded the International Institute of Biophysics.",
    suppression: "Research grants denied. Popp lost his university position. The Institute operates on private funding. Mainstream biology ignores biophoton theory despite 40+ years of data.",
    tags: ["biophotons", "DNA", "coherence", "cancer"],
    risk: 40,
  },
  {
    id: "supp_025",
    inventor: "Cleve Backster",
    title: "Primary Perception (Plant Bio-Communication)",
    year: 1966,
    category: "Bioelectromagnetics",
    patent: "None — experimental research",
    description: "CIA polygraph expert who connected plants to galvanic skin response meters and discovered plants respond to human intention, to the death of other life forms (brine shrimp, bacteria), and to events at a distance — instantaneously. 'Primary perception' suggests a non-local bio-field connecting all life. Confirmed by multiple independent researchers.",
    suppression: "Mainstream science dismissed as 'pseudoscience.' Backster was a respected CIA interrogator but his plant research was ridiculed. The implications — non-local consciousness — are too threatening to establishment paradigms.",
    tags: ["primary perception", "plant consciousness", "bio-field", "non-local"],
    risk: 50,
  },
  {
    id: "supp_026",
    inventor: "Jacques Benveniste",
    title: "Water Memory & Digital Biology",
    year: 1988,
    category: "Bioelectromagnetics",
    patent: "None — Nature controversy",
    description: "French immunologist who discovered that water exposed to antibodies retains biological activity even after the antibodies are diluted to zero (Avogadro's limit). Published in Nature (1988). Then Nature sent a fraud investigation team (including magician James Randi) and 'debunked' the work despite no fraud found. Benveniste later transmitted molecular 'signatures' over telephone lines — 'digital biology.'",
    suppression: "Lost INSERM lab, funding, and reputation. Nature led a public campaign to destroy him. Died 2004. Water memory research continues (Luc Montagnier, Nobel laureate, confirmed electromagnetic signals from DNA in water).",
    tags: ["water memory", "homeopathy", "digital biology", "electromagnetic signature"],
    risk: 70,
  },
  {
    id: "supp_027",
    inventor: "Luc Montagnier",
    title: "DNA Electromagnetic Signals in Water",
    year: 2009,
    category: "Bioelectromagnetics",
    patent: "None — Nobel laureate's suppressed research",
    description: "Nobel Prize winner (2008, HIV discovery) who confirmed Benveniste's water memory: bacterial and viral DNA emits electromagnetic signals in water, detectable after dilution. These signals can be recorded, emailed, and used to reconstruct the DNA at a remote location. Published in Interdisciplinary Sciences: Computational Life Sciences.",
    suppression: "Nobel laureate attacked by scientific establishment. Forced to move his research to China (Shanghai Jiaotong University) because no Western lab would host him. Died 2022. His DNA signal research remains 'fringe' despite a Nobel laureate's validation.",
    tags: ["DNA signals", "water memory", "electromagnetic", "Nobel"],
    risk: 55,
  },
  {
    id: "supp_028",
    inventor: "Viktor Grebennikov",
    title: "Cavernous Structure Effect (CSE) & Anti-Gravity Platform",
    year: 1988,
    category: "Resonance Devices",
    patent: "None — Russian research",
    description: "Russian entomologist who discovered that certain insect chitin shells (beetle elytra) create a 'cavernous structure effect' — a measurable anti-gravity and biological effect from their geometric cavity arrangement. Built a 'gravitoplane' (flying platform) using CSE surfaces. Documented in 'My World' (1997). The effect is geometric — shape resonance with the vacuum.",
    suppression: "Russian scientific establishment ignored. Grebennikov died 2001. His platform and specimens are in a Novosibirsk museum but access is restricted. Western science unaware.",
    tags: ["CSE", "anti-gravity", "chitin", "cavity resonance"],
    risk: 65,
  },
  {
    id: "supp_029",
    inventor: "Alexander Chernetsky",
    title: "Self-Generating Discharge (SGD) Plasma Reactor",
    year: 1970,
    category: "Vacuum Energy",
    patent: "Soviet patents — classified",
    description: "Soviet physicist who built a plasma reactor that extracted energy from the physical vacuum via 'self-generating discharge' — a plasma vortex that draws in vacuum energy. Demonstrated 500W output with 100W input. The reactor ran cold and the plasma exhibited anomalous properties (negative entropy). Classified by Soviet military.",
    suppression: "Classified by Soviet/Russian military. Chernetsky died 2000. Work continues in restricted Russian labs. Western access denied.",
    tags: ["plasma", "vacuum", "self-generating", "negative entropy"],
    risk: 80,
  },
  {
    id: "supp_030",
    inventor: "Dr. Peter Gariaev",
    title: "Wave Genome & Linguistic DNA",
    year: 1994,
    category: "Bioelectromagnetics",
    patent: "Russian patents — 'Method of Wave Genetics'",
    description: "Russian biophysicist who demonstrated that DNA functions as a soliton hologram — it reads and writes itself using electromagnetic and acoustic waves. DNA has a 'linguistic' structure (follows Zipf's law of human language). Transmitted genetic information via modulated laser between organisms. 'Wave genome' theory — the genome is a wave biocomputer.",
    suppression: "Russian Academy of Sciences dismissed. Western journals refuse. Gariaev's lab was defunded. Died 2020. Wave genetics continues through a small group of researchers.",
    tags: ["wave genome", "linguistic DNA", "soliton", "genetic transmission"],
    risk: 60,
  },
];

// ── VEDIC MEDICINAL HEALING CONCEPTS (20 new entries) ─────────────────────────
export const VEDIC_HEALING_CONCEPTS = [
  {
    id: "vedic_001",
    concept: "Panchakarma: Five-Action Detoxification",
    source: "Charaka Samhita (c. 300 BCE); Sushruta Samhita",
    description: "The Ayurvedic master purification: Vamana (therapeutic emesis), Virechana (purgation), Basti (medicated enema), Nasya (nasal administration), Raktamokshana (bloodletting). Removes dosha imbalances at the root. Modern research confirms lipid-profile normalization, heavy metal clearance, and inflammatory marker reduction. Maps to Bearden's 'clearing the bioenergetic template' before impressing a new one.",
    application: "Integrative detox protocol combined with scalar-EM cellular clearing. Pre-treatment for Prioré-class therapy.",
    tags: ["detox", "Ayurveda", "purification", "dosha"],
  },
  {
    id: "vedic_002",
    concept: "Rasayana: Rejuvenation & Telomere Science",
    source: "Charaka Samhita, Chikitsa Sthana 1-2; Sushruta Samhita",
    description: "Rasayana — the Ayurvedic science of rejuvenation. Herbs (ashwagandha, shilajit, haritaki, amalaki, tulsi), metals/minerals (bhasmas — incinerated to nanoparticle ash), and lifestyle practices that reverse aging. Modern research: ashwagandha extends telomeres, shilajit upregulates mitochondria, amalaki (vitamin C complex) is the highest natural antioxidant. Rasayana IS the Vedic longevity protocol.",
    application: "Rasayana herbs + Prioré EM telomerase activation = accelerated biological age reversal. Core of TRD-1 protocol.",
    tags: ["rejuvenation", "telomere", "ashwagandha", "longevity"],
  },
  {
    id: "vedic_003",
    concept: "Marma Chikitsa: 107 Vital Point Therapy",
    source: "Sushruta Samhita, Sharira Sthana 6; Dhanvantari tradition",
    description: "107 marma points — vital energy junctions where prana concentrates. Stimulating marmas (pressure, oil, heat, light) releases blocked energy and heals organs/systems. Sushruta mapped them in 600 BCE — the world's first acupressure/acupuncture system (predates Chinese acupuncture by ~200 years). Each marma corresponds to a nadis junction and chakra sub-node.",
    application: "Marma point stimulation + PEMF coil array = targeted bioenergetic activation. Maps to acupuncture meridians + Bearden nadis network.",
    tags: ["marma", "acupressure", "vital points", "prana"],
  },
  {
    id: "vedic_004",
    concept: "Bhasma: Nanoparticle Metal Therapy",
    source: "Rasa Shastra (Vedic alchemy); Rasaratna Samuccaya",
    description: "Bhasmas — metals and minerals (gold, silver, iron, copper, mica) incinerated through repeated calcination (puta) with herbal juices until reduced to nanoparticle ash. Swarna Bhasma (gold) is the supreme rasayana — modern research confirms it is biocompatible gold nanoparticles that cross the blood-brain barrier and exhibit anti-inflammatory, nootropic, and anti-aging effects.",
    application: "Bhasma nanoparticle synthesis + scalar-EM activation = enhanced bioavailability. Gold bhasma + TRD-1 = telomere + cognitive restoration.",
    tags: ["bhasma", "nanoparticle", "alchemy", "gold"],
  },
  {
    id: "vedic_005",
    concept: "Shilajit: Mineral Pitch Fulvic Complex",
    source: "Sushruta Samhita; Charaka Samhita; Himalayan tradition",
    description: "Shilajit — a mineral-rich resin exuding from Himalayan rocks, formed by decomposition of plant matter over centuries. Contains fulvic acid (60-80%), dibenzo-alpha-pyrones, and 84+ minerals. Modern research: enhances mitochondrial function (CoQ10 pathway), upregulates Nrf2 (antioxidant), increases ATP production, chelates heavy metals. The Ayurvedic 'conqueror of mountains and destroyer of weakness.'",
    application: "Shilajit supplementation + mitochondrial PEMF = synergistic ATP restoration. Core supplement for bioenergetic therapy protocols.",
    tags: ["shilajit", "fulvic acid", "mitochondria", "ATP"],
  },
  {
    id: "vedic_006",
    concept: "Abhyanga: Daily Oil Massage & Lymphatic Clearing",
    source: "Charaka Samhita, Sutrasthana 5; Ashtanga Hridaya",
    description: "Daily warm oil massage with dosha-specific oils (sesame for vata, coconut for pitta, mustard for kita). Stimulates lymph flow, moves prana through nadis, calms the nervous system (parasympathetic dominance), and delivers transdermal herbal medicine. Modern research confirms lymphatic flow increase, cortisol reduction, and sleep quality improvement.",
    application: "Abhyanga + vibroacoustic therapy (VAT) = synergistic lymphatic + nervous system reset. Oil-soluble scalar-active herbs delivered transdermally during EM therapy.",
    tags: ["abhyanga", "oil massage", "lymphatic", "transdermal"],
  },
  {
    id: "vedic_007",
    concept: "Nadi Pariksha: Pulse Diagnosis",
    source: "Sarangadhara Samhita; Yoga Ratnakara",
    description: "Ayurvedic pulse diagnosis — reading the radial pulse at three depths (vata, pitta, kapha) to assess dosha imbalance, organ function, and disease prognosis. A master vaidya can detect disease before physical symptoms. Maps to Bearden's bioenergetic template reading — the pulse carries the body's scalar potential signature.",
    application: "Nadi pariksha + biophoton/biofield sensors = AI-assisted dosha + bioenergetic diagnosis. Digital pulse analysis for pre-symptomatic detection.",
    tags: ["pulse diagnosis", "nadi", "dosha", "diagnosis"],
  },
  {
    id: "vedic_008",
    concept: "Gandusha / Kavala: Oil Pulling Detox",
    source: "Charaka Samhita, Chikitsa Sthana; Kavala Graha",
    description: "Swishing medicated oil (sesame, coconut) in the mouth for 5-15 minutes daily. Draws toxins through the oral mucosa, reduces oral pathogens, and — per Ayurveda — pulls systemic dosha imbalances through the mouth-tongue-organ reflex. Modern research confirms reduction in oral bacteria, plaque, and inflammatory markers.",
    application: "Oil pulling + oral microbiome + scalar-EM oral rinse device = comprehensive oral-systemic detox. The mouth is the gateway to the nadis.",
    tags: ["oil pulling", "oral detox", "microbiome", "gandusha"],
  },
  {
    id: "vedic_009",
    concept: "Agnikarma: Thermal Cautery for Pain & Channel Opening",
    source: "Sushruta Samhita, Sutrasthana 12; Dhanvantari tradition",
    description: "Application of controlled heat (metal probe, gold, copper) to specific points for chronic pain, sciatica, arthritis, and channel blockages. The heat 'opens' blocked nadis and resets the local bioenergetic field. Modern research confirms efficacy for musculoskeletal pain comparable to steroid injection.",
    application: "Agnikarma points + targeted infrared (FIR) + scalar-EM = deep tissue bioenergetic reset. Maps to trigger point therapy + Prioré mechanism.",
    tags: ["agnikarma", "heat therapy", "pain", "nadi opening"],
  },
  {
    id: "vedic_010",
    concept: "Shirodhara: Third-Eye Oil Flow for Nervous System Reset",
    source: "Ashtanga Hridaya; Kerala Panchakarma tradition",
    description: "Continuous warm oil stream on the forehead (third eye / Ajna chakra) for 20-45 minutes. Induces alpha-theta brainwave state, resets the hypothalamic-pituitary axis, and normalizes cortisol/melatonin cycles. Modern research confirms significant reduction in anxiety, PTSD symptoms, and insomnia. The most powerful Ayurvedic nervous system reset.",
    application: "Shirodhara + cranial PEMF + binaural audio = deep nervous system reprogramming. Core therapy for stress-related bioenergetic depletion.",
    tags: ["shirodhara", "third eye", "nervous system", "alpha waves"],
  },
  {
    id: "vedic_011",
    concept: "Swedana: Herbal Steam Box Therapy",
    source: "Charaka Samhita, Sutrasthana 14; Panchakarma texts",
    description: "Medicated steam chamber where the patient's body (head excluded) is bathed in herb-infused steam. Induces sweating, opens channels (srotas), liquefies doshas, and prepares the body for purification. Modern research confirms vasodilation, toxin release through sweat, and enhanced transdermal herb absorption.",
    application: "Swedana + FIR sauna + scalar-EM chamber = multi-modal detox. The steam carries scalar-active herbal signatures transdermally.",
    tags: ["swedana", "steam", "detox", "srotas"],
  },
  {
    id: "vedic_012",
    concept: "Netra Basti: Eye Rejuvenation Therapy",
    source: "Sushruta Samhita, Uttara Tantra; Ayurvedic ophthalmology",
    description: "Warm medicated ghee (clarified butter) pooled over the eyes in a flour dam. Relieves eye strain, improves vision, treats dry eye, and — per Ayurveda — rejuvenates the optic nerve and Ajna chakra. Modern research confirms improvement in tear film, visual acuity, and intraocular pressure.",
    application: "Netra Basti + photobiomodulation (PBM, 670nm) + scalar-EM = accelerated optic nerve regeneration. Core for macular degeneration protocol.",
    tags: ["netra basti", "eye therapy", "ghee", "vision"],
  },
  {
    id: "vedic_013",
    concept: "Kati Basti: Localized Oil Pool for Spine/Joints",
    source: "Kerala Panchakarma tradition; Ashtanga Hridaya",
    description: "Warm medicated oil pooled over a specific body region (lower back, knee, neck) in a flour dam. Deep tissue penetration, dosha localization, and sustained heat. Modern research confirms efficacy for disc herniation, osteoarthritis, and chronic inflammation superior to NSAIDs.",
    application: "Kati Basti + targeted PEMF + ultrasound = deep joint/spine regeneration. Oil carries scalar-active herbs to the affected tissue.",
    tags: ["kati basti", "oil pool", "spine", "joint"],
  },
  {
    id: "vedic_014",
    concept: "Chyawanprash: Master Rasayana Formula",
    source: "Charaka Samhita; Mahabharata (Chyavana Rishi story)",
    description: "Amla (Indian gooseberry, 30x vitamin C of orange) based jam with 40+ herbs, ghee, sesame oil, and honey. The premier Ayurvedic rasayana — 2,000+ years of continuous use. Modern research: immunomodulatory, antioxidant, adaptogenic, cognitive enhancing, and telomere-protective. The original 'longevity formula.'",
    application: "Chyawanprash + TRD-1 telomerase activation = synergistic anti-aging. Daily rasayana for bioenergetic maintenance.",
    tags: ["chyawanprash", "amla", "rasayana", "longevity"],
  },
  {
    id: "vedic_015",
    concept: "Tulsi (Holy Basil): Adaptogenic Bio-Field Herb",
    source: "Padma Purana; Charaka Samhita",
    description: "Tulsi — 'The Incomparable One' — sacred to Vishnu. Adaptogen, immunomodulator, anti-inflammatory, antimicrobial, radioprotective. Modern research: lowers cortisol, balances blood sugar, protects against radiation (relevant to EMF exposure), and enhances cognitive function. Tulsi is the Ayurvedic answer to environmental stress — including EMF.",
    application: "Tulsi extract + EMF protection protocol = biological scalar shielding. Tulsi's radioprotective effect complements Faraday shielding.",
    tags: ["tulsi", "adaptogen", "radioprotective", "EMF"],
  },
  {
    id: "vedic_016",
    concept: "Brahmi & Shankhpushpi: Nootropic Brain Herbs",
    source: "Charaka Samhita; Bhavaprakasha Nighantu",
    description: "Brahmi (Bacopa monnieri) and Shankhpushpi (Convolvulus pluricaulis) — the Ayurvedic cognitive enhancers. Brahmi enhances memory, learning, and concentration; modern research confirms BDNF upregulation and hippocampal neurogenesis. Shankhpushpi reduces anxiety and improves cognitive function. Both are 'medhya rasayanas' — brain rejuvenators.",
    application: "Brahmi + Shankhpushpi + cranial PEMF + binaural frequencies = accelerated cognitive enhancement. Core for neural regeneration protocols.",
    tags: ["brahmi", "nootropic", "BDNF", "cognitive"],
  },
  {
    id: "vedic_017",
    concept: "Triphala: Three-Fruit Colon & Microbiome Tonic",
    source: "Charaka Samhita; Sushruta Samhita",
    description: "Amalaki (Emblica officinalis), Bibhitaki (Terminalia bellirica), Haritaki (Terminalia chebula) — three fruits combined. Gentle colon cleanser, microbiome balancer, and antioxidant. Modern research: prebiotic effect, anti-inflammatory, and gut-brain axis normalization. The most prescribed Ayurvedic formula.",
    application: "Triphala + microbiome PEMF + structured water = comprehensive gut restoration. The gut is the 'second brain' and the root of bioenergetic health.",
    tags: ["triphala", "colon", "microbiome", "gut-brain"],
  },
  {
    id: "vedic_018",
    concept: "Yoga Asana as Bioenergetic Circuit Posture",
    source: "Patanjali Yoga Sutras (c. 200 BCE); Hatha Yoga Pradipika",
    description: "Yoga postures (asanas) are not stretching — they are bioenergetic circuits. Each posture creates specific nadis flows, chakra activations, and organ stimulation. Modern research confirms: down-regulation of stress genes, upregulation of telomere-protective genes, vagal tone increase, and inflammatory marker reduction. Asana IS scalar-EM engineering of the body.",
    application: "Yoga asana + bioenergetic monitoring (BFAC) = real-time feedback on nadis/chakra activation. Postures prescribed per dosha + condition.",
    tags: ["yoga", "asana", "bioenergetic", "nadis"],
  },
  {
    id: "vedic_019",
    concept: "Pranayama: Breath as Scalar-EM Modulation",
    source: "Patanjali Yoga Sutras 2.49-2.53; Hatha Yoga Pradipika 2",
    description: "Breath control — Nadi Shodhana (alternate nostril), Bhastrika (bellows), Kapalabhati (skull shining), Ujjayi (victorious). Each technique modulates the vagus nerve, hemispheric brain balance, and the body's CO2/O2 ratio. Modern research: vagal tone enhancement, HRV improvement, nitric oxide production (nasal breathing), and parasympathetic dominance. Pranayama IS the directed modulation of the body's scalar field via breath.",
    application: "Pranayama + HRV biofeedback + scalar-EM breath coil = precise bioenergetic modulation. Breath as the control interface for the bio-field.",
    tags: ["pranayama", "breath", "vagus nerve", "HRV"],
  },
  {
    id: "vedic_020",
    concept: "Soma: Plant of Immortality & the Amrita Nectar",
    source: "Rig Veda (Mandala 9 — Soma Pavamana); Avesta (Haoma)",
    description: "Soma — the sacred plant/nectar of the Vedic tradition, consumed in ritual to achieve immortality (amrita), divine vision, and healing. The identity of Soma is lost (candidates: Ephedra, Amanita muscaria, Sarcostemma, Peganum harmala). The Rig Veda devotes an entire mandala (114 hymns) to Soma. Beyond the plant, Soma represents the 'nectar of immortality' — the bio-energetic substance that regenerates the body when the nadis are fully activated.",
    application: "Soma (as archetype) + rasayana herbs + kundalini activation = the Vedic immortality protocol. Maps to Bearden's 'kindled biopotential' that self-sustains.",
    tags: ["soma", "amrita", "immortality", "nectar"],
  },
];

// ── FORBIDDEN OCCULT & ESOTERIC KNOWLEDGE (20 new entries) ─────────────────────
export const OCCULT_ESOTERIC = [
  {
    id: "occ_001",
    concept: "Hermetic Principles (Kybalion) & the 7 Universal Laws",
    source: "The Kybalion (1908, William Walker Atkinson); attributed to Hermes Trismegistus",
    description: "Seven Hermetic laws: Mentalism (universe is mind), Correspondence (as above so below), Vibration (everything vibrates), Polarity (everything is dual), Rhythm (everything flows), Cause & Effect (nothing escapes law), Gender (everything has masculine/feminine). These are the philosophical precursors of scalar-EM principles — Vibration = scalar wave, Correspondence = fractal vacuum structure, Mentalism = consciousness as the substrate.",
    application: "Hermetic principles as the design philosophy for scalar-EM devices. Each law maps to an engineering principle.",
    tags: ["Hermetic", "Kybalion", "seven laws", "mentalism"],
  },
  {
    id: "occ_002",
    concept: "Sacred Geometry: Flower of Life, Metatron's Cube, Phi Ratio",
    source: "Ancient Egypt (Osirion); Euclid; Drunvalo Melchizedek 'The Ancient Secret of the Flower of Life'",
    description: "Geometric patterns (Flower of Life, Metatron's Cube, Fibonacci spiral, Golden Ratio, Platonic solids) encode the structure of the vacuum. These patterns appear in temple architecture, mandalas, and nature. Modern research: sacred geometry forms create measurable energy fields (e.g., the Merkaba/Star Tetrahedron correlates with toroidal scalar fields). The Phi ratio (1.618) appears in DNA, galaxies, and the human body.",
    application: "Sacred geometry coil winding patterns + scalar-EM resonators = enhanced vacuum coupling. Phi-ratio coils for optimal energy transfer.",
    tags: ["sacred geometry", "Flower of Life", "Phi", "Metatron"],
  },
  {
    id: "occ_003",
    concept: "Alchemy: The Great Work (Magnum Opus) & Transmutation",
    source: "Emerald Tablet of Hermes; Paracelsus; Fulcanelli",
    description: "Alchemy — the art of transmutation. The 'Great Work' (nigredo/blackening, albedo/whitening, citrinitas/yellowing, rubedo/reddening) describes both material transmutation (lead to gold) and spiritual transformation. Paracelsus (16th c.) practiced 'spagyrics' — plant alchemy still used in modern homeopathy. Fulcanelli (20th c.) revealed that Gothic cathedrals encode alchemical processes in stone.",
    application: "Alchemy + Kervran biological transmutation + scalar-EM = the unified transmutation theory. Bhasma preparation IS alchemy applied to medicine.",
    tags: ["alchemy", "transmutation", "Paracelsus", "Great Work"],
  },
  {
    id: "occ_004",
    concept: "Qabbalistic Tree of Life: 10 Sephirot as Energy Architecture",
    source: "Sefer Yetzirah (Book of Formation, c. 200 CE); Zohar",
    description: "The Tree of Life — 10 Sephirot (emanations) connected by 22 paths. Kether (crown) to Malkuth (kingdom). Maps the descent of divine energy into matter. Each Sephirah corresponds to a chakra, a planet, a color, and an archangel. The Tree is the universal energy architecture — the same structure appears in the chakra system, the 10 dimensions of string theory, and the 10-fold symmetry of the vacuum.",
    application: "Tree of Life geometry + chakra PEMF array = 10-node bioenergetic stimulation system. Each Sephirah = a scalar-EM node.",
    tags: ["Qabbalah", "Tree of Life", "Sephirot", "energy architecture"],
  },
  {
    id: "occ_005",
    concept: "Gnosticism: The Divine Spark & Archon Suppression",
    source: "Nag Hammadi Library (1945); Pistis Sophia",
    description: "Gnostic tradition: humanity carries a 'divine spark' (pneuma) trapped in matter by the Demiurge (ignorant creator god) and his Archons (rulers/authorities). Liberation comes through gnosis (direct knowledge). The Archons suppress knowledge to maintain control. Maps to the suppression of free energy, scalar-EM, and healing technologies by modern 'archons' (corporate/government entities).",
    application: "Gnostic framework as the philosophical model for technology suppression. The 'divine spark' = the scalar potential in every human.",
    tags: ["Gnostic", "Archons", "Demiurge", "gnosis"],
  },
  {
    id: "occ_006",
    concept: "Enochian Magic: John Dee's Angelic Language & Aetheric Keys",
    source: "John Dee & Edward Kelley (1582-1589); Liber Logaeth",
    description: "Dr. John Dee (Queen Elizabeth I's astrologer) and Edward Kelley received the 'Enochian' language and 19 Calls (keys) from angelic entities via scrying. The Enochian language is a complete, internally consistent language with its own grammar. The 30 Aethyrs (aetheric regions) and 91 Governors describe a structured access system to non-physical dimensions. Modern researchers note parallels to scalar-EM frequency keys.",
    application: "Enochian Calls as scalar-EM frequency templates. The 'angelic language' may be a structured longitudinal wave code for vacuum access.",
    tags: ["Enochian", "John Dee", "angelic", "aether"],
  },
  {
    id: "occ_007",
    concept: "Vril Energy: The Coming Race & Subterranean Power",
    source: "Edward Bulwer-Lytton 'The Coming Race' (1871); Vril Society",
    description: "Vril — a mysterious energy described in Bulwer-Lytton's novel, later adopted by the Vril Society (early 20th c. German occult group). Vril is the life-force of a subterranean race, used for healing, propulsion, and destruction. The Vril Society influenced early German saucer research. Vril maps to orgone, prana, and scalar potential — the same bio-cosmic energy under different names.",
    application: "Vril (as orgone/prana equivalent) + scalar-EM = unified bio-cosmic energy theory. The 'Vril motor' may be a scalar-EM device.",
    tags: ["Vril", "subterranean", "bio-cosmic", "occult"],
  },
  {
    id: "occ_008",
    concept: "Od Force: Baron von Reichenbach's Life Energy",
    source: "Karl von Reichenbach 'Researches on the Dynamics of Magnetism' (1850)",
    description: "Baron Carl von Reichenbach (German chemist, discoverer of creosote and paraffin) spent 30 years studying 'Od' — a life-force energy emitted by magnets, crystals, sunlight, and living things. Sensitive subjects perceived Od as a blue flame at the north pole and red at the south. Od flows through wires, accumulates in bodies, and affects the nervous system. Od IS orgone/prana — Reichenbach was the first Western scientist to systematically study it.",
    application: "Od force = orgone = prana = scalar potential. Reichenbach's experimental protocols are directly applicable to scalar-EM detection.",
    tags: ["Od", "Reichenbach", "life force", "magnetism"],
  },
  {
    id: "occ_009",
    concept: "Mesmerism: Animal Magnetism & the First Bio-Field Therapy",
    source: "Franz Anton Mesmer (1766); 'Mémoire sur la découverte du magnétisme animal'",
    description: "Franz Anton Mesmer — 18th c. Austrian physician — discovered 'animal magnetism' (a bio-field energy). He healed patients by passing magnets over their bodies, or by 'magnetic passes' of his hands. His 'mesmeric trance' was the first hypnosis. The French Academy (commissioned by Louis XVI, including Benjamin Franklin) 'debunked' him in 1784 — but the commission only tested whether the effect came from magnets, not whether it existed. Mesmerism survived as hypnosis; the bio-field aspect was suppressed.",
    application: "Mesmer's magnetic passes + PEMF = the original bio-field therapy. Mesmer's techniques are the precursors of modern energy medicine.",
    tags: ["Mesmer", "animal magnetism", "bio-field", "hypnosis"],
  },
  {
    id: "occ_010",
    concept: "Runes & Galdr: Norse Vibrational Magic",
    source: "Elder Futhark (c. 150 CE); Havamal; Sigdrifumal",
    description: "Runes — 24 symbols of the Elder Futhark — are not merely an alphabet but vibrational operators. 'Galdr' (rune singing) is the chanting of rune names as incantations. Each rune has a specific meaning (Fehu = wealth/fire, Uruz = strength/aurochs, Thurisaz = thorn/giants) and a specific sound. Like Sanskrit bija mantras, runes are longitudinal wave operators that structure the local field. Odin hung from Yggdrasil for 9 days to receive the runes — a shamanic initiation to access the vibrational code of reality.",
    application: "Runes + Sanskrit mantras = cross-cultural vibrational engineering. Rune frequencies mapped to scalar-EM resonance windows.",
    tags: ["runes", "galdr", "Norse", "vibrational"],
  },
  {
    id: "occ_011",
    concept: "I Ching: 64 Hexagrams & the Genetic Code",
    source: "I Ching (Book of Changes, c. 1000 BCE); King Wen sequence",
    description: "The I Ching — 64 hexagrams (6-line figures of yin/yang) — is the world's oldest oracle and a complete binary system (predates Leibniz by 2,600 years). The 64 hexagrams correspond exactly to the 64 codons of the genetic code (DNA triplets). This correspondence (discovered by Martin Schönberger 1973) suggests the I Ching encodes the same binary structure as life itself. The I Ching is a bio-information system.",
    application: "I Ching hexagrams + DNA codons + scalar-EM frequency templates = the binary code of life. 64-frequency scalar templates for genetic regulation.",
    tags: ["I Ching", "hexagram", "DNA", "binary"],
  },
  {
    id: "occ_012",
    concept: "Solfeggio Frequencies & the Gregorian Chant Codes",
    source: "Guido of Arezzo (11th c.); rediscovered by Dr. Joseph Puleo (1990s)",
    description: "The Solfeggio frequencies (396 Hz, 417 Hz, 528 Hz, 639 Hz, 741 Hz, 852 Hz, 963 Hz) — encoded in the Gregorian chant 'Ut Queant Laxis.' Each frequency has a specific biological effect: 528 Hz (DNA repair), 396 Hz (fear release), 741 Hz (cellular awakening). Dr. Joseph Puleo rediscovered them via numerological analysis of the I Ching. Modern research (Glen Rein) confirms 528 Hz increases UV absorption in DNA (marker of repair).",
    application: "Solfeggio frequencies + Prioré EM + vibroacoustic therapy = precise frequency-targeted healing. 528 Hz as the core DNA repair frequency.",
    tags: ["Solfeggio", "528 Hz", "Gregorian", "DNA repair"],
  },
  {
    id: "occ_013",
    concept: "Anthroposophical Medicine: Rudolf Steiner's Spiritual Science",
    source: "Rudolf Steiner (1861-1925); 'Fundamentals of Therapy' (1924)",
    description: "Rudolf Steiner's medical system — treats the human as a fourfold being (physical, etheric, astral, ego). Uses potentized remedies (similar to homeopathy), mistletoe therapy for cancer, and rhythmic massage. Steiner also designed the first biodynamic agriculture and the Waldorf education system. His medical insights include: the heart is not a pump (it's a hydraulic ram — blood moves by levity), and cancer is a 'warmth organism' that needs to be re-spiritualized.",
    application: "Anthroposophical medicine + scalar-EM = the fourfold bioenergetic model. Steiner's etheric body = Bearden's bioenergetic template.",
    tags: ["Steiner", "anthroposophy", "etheric body", "mistletoe"],
  },
  {
    id: "occ_014",
    concept: "Egyptian Book of the Dead & the Afterlife Technology",
    source: "Papyrus of Ani (c. 1500 BCE); Pyramid Texts (c. 2400 BCE)",
    description: "The Egyptian Book of the Dead (Pert em Hru — 'Coming Forth by Day') is a technical manual for navigating the afterlife — specific spells, passwords, and amulets for each stage. The 42 Negative Confessions (weighing of the heart against Maat's feather). This is not superstition but a technology of consciousness — the Egyptians mapped the non-physical dimensions and the soul's journey with engineering precision. The pyramids were not tombs but resonance chambers for this transition.",
    application: "Egyptian afterlife technology + scalar-EM = consciousness engineering. The pyramid geometry as a scalar-EM resonance chamber.",
    tags: ["Egyptian", "Book of the Dead", "afterlife", "pyramid"],
  },
  {
    id: "occ_015",
    concept: "Dowsing & Radionics: Radiesthesia as Scalar Detection",
    source: "Abbé Mermet (20th c.); Dr. Ruth Drown; Malcolm Rae",
    description: "Dowsing (radiesthesia) — detecting subtle energies with pendulum, rods, or bare hands. Radionics — Dr. Ruth Drown (1920s) built devices to detect and broadcast healing frequencies at a distance using blood spot + rates. Malcolm Rae developed 'simulated card' radionics. These are scalar-EM detection and broadcast systems — the 'rates' are frequency codes. Modern research (Tiller, Rein) confirms intention-imprinted electronic devices produce measurable biological effects.",
    application: "Radionics + scalar-EM = remote healing technology. Dowsing as a bio-field detection skill. Radionic rates as scalar frequency templates.",
    tags: ["dowsing", "radionics", "radiesthesia", "remote healing"],
  },
  {
    id: "occ_016",
    concept: "Astrological Correspondences & Bio-Cosmic Timing",
    source: "Babylonian (c. 2000 BCE); Vedic Jyotish; Hellenistic astrology",
    description: "Astrology — the correlation of celestial positions with terrestrial and biological events. Beyond fortune-telling, medical astrology (iatromathematics) prescribes treatment timing based on planetary hours, lunar phases, and zodiacal signs. Modern research: Michel Gauquelin's 'Mars effect' (statistically significant correlation of Mars position with athletic champions); lunar cycle effects on biological rhythms. The mechanism may be scalar-EM — the planets modulate the solar wind, which modulates Earth's ionosphere, which modulates the bio-field.",
    application: "Medical astrology + scalar-EM timing = optimal therapy scheduling. Planetary hours as scalar-field density windows.",
    tags: ["astrology", "medical astrology", "timing", "cosmic"],
  },
  {
    id: "occ_017",
    concept: "Voodoo & Hoodoo: African Diasporic Energy Medicine",
    source: "West African (Yoruba, Fon, Ewe); New Orleans Voodoo; Haitian Vodou",
    description: "Voodoo/Vodou — African diasporic traditions combining ancestor veneration, spirit possession, herbal medicine, and energy work. 'Voodoo dolls' are not for cursing but for sympathetic magic — directing energy to a person via a symbolic representation. The 'loa' (spirits) are archetypal energies. Haitian Vodou preserved more of the original African energy science than any other diasporic tradition. The 'zombie' phenomenon is real (tetrodotoxin + dissociatives) and demonstrates the pharmacological control of the bio-field.",
    application: "Voodoo sympathetic magic + scalar-EM = the principle of non-local bio-field influence. The 'doll' as a scalar-EM target proxy.",
    tags: ["Voodoo", "sympathetic magic", "ancestor", "bio-field"],
  },
  {
    id: "occ_018",
    concept: "Shamanic Journeying & Soul Retrieval",
    source: "Siberian, Amazonian, Celtic, Native American traditions",
    description: "Shamanism — the world's oldest spiritual technology (30,000+ years). The shaman enters non-ordinary reality via drumming (4-7 Hz theta rhythm), journeys to upper/middle/lower worlds, retrieves lost 'soul parts' (fragments of consciousness split off by trauma), and removes intrusive energies. Soul retrieval is the shamanic equivalent of re-integrating the bioenergetic template. The drumming frequency (4-7 Hz) is the Earth's Schumann resonance and the theta brainwave band — the shaman is tuning to the planetary scalar field.",
    application: "Shamanic drumming + theta binaural + scalar-EM = consciousness-state induction for bio-field reintegration. Soul retrieval as template repair.",
    tags: ["shamanism", "soul retrieval", "drumming", "theta"],
  },
  {
    id: "occ_019",
    concept: "Wim Hof Method: Conscious Control of Autonomic System",
    source: "Wim Hof 'The Iceman'; 'The Wim Hof Method' (2020)",
    description: "Wim Hof — Dutch athlete who demonstrated conscious control of the autonomic nervous system, immune response, and body temperature. His method (cold exposure + breathing + mindset) has been scientifically validated: voluntary immune system modulation (endotoxin study, Radboud University), reduced inflammatory markers, and epinephrine/norepinephrine release on command. Hof has climbed Everest in shorts, run marathons in the desert without water, and sat in ice water for 2 hours. His method proves the mind-body connection is directly controllable — the bio-field responds to intention.",
    application: "Wim Hof Method + scalar-EM + breath biofeedback = conscious bio-field modulation. The method as the modern pranayama + kundalini activation.",
    tags: ["Wim Hof", "autonomic", "cold exposure", "breathing"],
  },
  {
    id: "occ_020",
    concept: "Plant Spirit Medicine & Ayahuasca as Bio-Field Teacher",
    source: "Amazonian traditions; Shipibo-Conibo; Santo Daime; UDV",
    description: "Ayahuasca — the Amazonian plant medicine (Banisteriopsis caapi + Psychotria viridis) used for millennia. The vine teaches, heals, and reveals — including the 'ikaros' (healing songs) that the shaman learns directly from the plant. Modern research: ayahuasca shows efficacy for treatment-resistant depression, PTSD, and addiction. The mechanism is not just pharmacological (DMT + MAOI) but bio-energetic — the plant restructures the bio-field. The 'visions' are the conscious perception of the scalar template being rewritten.",
    application: "Ayahuasca (as bio-field teacher) + scalar-EM integration therapy = accelerated trauma release and template repair. Post-ceremony EM therapy to consolidate the new template.",
    tags: ["ayahuasca", "plant spirit", "DMT", "bio-field"],
  },
];

// ── PATENT SUPPRESSION CASES (15 new entries) ────────────────────────────────
export const PATENT_SUPPRESSION = [
  {
    id: "pat_sup_001",
    title: "USPTO Secrecy Order (Invention Secrecy Act 1951)",
    description: "The US Invention Secrecy Act of 1951 allows the USPTO to issue 'secrecy orders' on patent applications deemed detrimental to national security. Over 6,000 secrecy orders are currently in effect. Inventors whose patents are classified cannot publish, commercialize, or even discuss their invention — under penalty of imprisonment. Many free energy and scalar-EM patents have been classified under this act.",
    impact: "Thousands of energy and healing technologies locked away. Inventors gagged for life.",
    tags: ["secrecy order", "USPTO", "Invention Secrecy Act", "classified"],
  },
  {
    id: "pat_sup_002",
    title: "Section 101 Rejections: 'Impossible' Energy Patents",
    description: "USPTO examiners reject energy patents under 35 USC 101 (utility) by declaring them 'impossible' or 'perpetual motion' — without testing. Moray, Newman, Gray, and hundreds of others were rejected on these grounds. The examiner assumes the current physics paradigm is complete and any claim exceeding it is 'impossible.' This is not scientific review — it is paradigm enforcement.",
    impact: "Legitimate vacuum energy inventions rejected without examination. The patent office as gatekeeper of the old paradigm.",
    tags: ["Section 101", "perpetual motion", "rejection", "paradigm"],
  },
  {
    id: "pat_sup_003",
    title: "National Security Letter (NSL) Gag Orders on Inventors",
    description: "When secrecy orders are insufficient, the government can issue National Security Letters — secret orders that prevent any disclosure. The inventor cannot tell anyone, including family, that they received an NSL. This has been used on multiple free energy inventors who were then 'disappeared' from the public sphere.",
    impact: "Inventors silenced completely. No legal recourse. The technology exists but is locked.",
    tags: ["NSL", "gag order", "national security", "silenced"],
  },
  {
    id: "pat_sup_004",
    title: "Corporate Patent Acquisition & Shelving",
    description: "Major corporations (oil, pharma, defense) acquire patents not to develop them but to shelve them. Chevron, Exxon, Pfizer, and others have thousands of shelved patents. The strategy: buy the invention, bury it, maintain the existing business model. This is legal and standard practice.",
    impact: "Thousands of disruptive technologies bought and buried. The market selects against its own disruption.",
    tags: ["corporate", "shelving", "acquisition", "suppression"],
  },
  {
    id: "pat_sup_005",
    title: "FDA/FTC Enforcement Against Healing Devices",
    description: "The FDA and FTC have shut down dozens of legitimate healing device companies (Rife, Reich, Hulda Clark, Bob Beck, Royal Rife successors) by declaring the devices 'unproven medical devices.' The standard: if it works but doesn't fit the pharmaceutical model, it's illegal. The FDA has never approved a single energy medicine device for cancer treatment — despite 60+ years of positive data.",
    impact: "Healing technology companies destroyed. Practitioners imprisoned. Patients denied access.",
    tags: ["FDA", "FTC", "healing devices", "medical suppression"],
  },
  {
    id: "pat_sup_006",
    title: "Academic Blackballing of Free Energy Researchers",
    description: "University researchers who study free energy, cold fusion, or scalar-EM are denied tenure, publication, and funding. Dr. Eugene Mallove (MIT), Dr. John Bockris (Texas A&M cold fusion), Dr. Martin Fleischmann (Southampton) — all blackballed. The academic publication system (peer review) enforces the paradigm. 'Extraordinary claims require extraordinary evidence' is weaponized to mean 'impossible claims require no examination.'",
    impact: "The best researchers driven from academia. The peer-review system as paradigm enforcement.",
    tags: ["academic", "blackball", "peer review", "tenure"],
  },
  {
    id: "pat_sup_007",
    title: "Media Discreditation Campaigns",
    description: "When inventors go public, media campaigns discredit them as 'frauds,' 'pseudoscientists,' or 'conspiracy theorists.' Stanley Meyer, John Searl, Andrea Rossi, and dozens of others were systematically ridiculed. The pattern: legitimate demonstration → media attack → 'debunking' by a magician (James Randi) or a non-expert → public dismissal. The goal: make the technology socially unacceptable to discuss.",
    impact: "Public perception managed. Legitimate inventors framed as cranks. Social suppression as effective as legal suppression.",
    tags: ["media", "discreditation", "debunking", "social suppression"],
  },
  {
    id: "pat_sup_008",
    title: "Suspicious Deaths of Free Energy Inventors",
    description: "A pattern of suspicious deaths: Stanley Meyer (1998, 'They poisoned me'), Eugene Mallove (2004, unsolved murder), Dr. Andrew Moulden (2013, heart attack after announcing vaccine-autism evidence), Dr. Jeff Bradstreet (2015, 'suicide' after GcMAF cancer treatment breakthrough), Dr. Nicholas Gonzalez (2015, 'heart attack'). These are documented; many more are suspected. The pattern: inventor announces breakthrough → threat → death.",
    impact: "The ultimate suppression. Inventors silenced permanently. Others intimidated into silence.",
    tags: ["suspicious deaths", "Meyer", "Mallove", "intimidation"],
  },
  {
    id: "pat_sup_009",
    title: "Defense Advanced Research Projects (DARPA) Classification",
    description: "DARPA and the DoD classify technologies that could be weaponized — including free energy (which enables directed energy weapons), scalar-EM (which enables scalar weapons), and healing devices (which enable biological warfare countermeasures). The 1951 Invention Secrecy Act is the legal basis. Many 'suppressed' inventions are actually classified — they exist, work, and are used by the military, but are denied to civilians.",
    impact: "Dual-use technologies classified. The public denied energy independence and advanced medicine while the military uses them.",
    tags: ["DARPA", "classification", "dual-use", "military"],
  },
  {
    id: "pat_sup_010",
    title: "International Patent Treaty Suppression (PCT)",
    description: "The Patent Cooperation Treaty (PCT) allows international rejection of patents based on a single country's rejection. If the USPTO rejects a free energy patent, other countries can cite the US rejection. This creates a global suppression network — one paradigm-enforcing jurisdiction blocks worldwide protection.",
    impact: "Global suppression via treaty. One rejection blocks all countries.",
    tags: ["PCT", "international", "treaty", "global suppression"],
  },
  {
    id: "pat_sup_011",
    title: "Energy Patent 'National Security' Classification (DoE)",
    description: "The Department of Energy has the authority to classify energy patents under 'national security.' This has been used on nuclear, fusion, and — allegedly — free energy patents. The DoE's own Office of Classification has stated that energy inventions 'with significant weapons potential' are classified. This includes any technology that could enable directed energy weapons — which includes most free energy devices.",
    impact: "Energy independence denied. The 'national security' umbrella covers the entire energy sector.",
    tags: ["DoE", "energy", "classification", "national security"],
  },
  {
    id: "pat_sup_012",
    title: "Pharmaceutical Industry Suppression of Non-Drug Therapies",
    description: "The pharmaceutical industry (Big Pharma) systematically suppresses non-drug therapies that threaten drug revenue. Energy medicine, frequency therapy, nutritional therapy, and plant medicine are attacked via: FDA raids, media discreditation, academic blackballing, and 'quackbuster' websites (operated by PR firms). The opioid crisis is the visible result of the drug-first model; the invisible result is the suppression of alternatives.",
    impact: "Non-drug healing suppressed. Drug revenue protected. Patients denied effective, safe, cheap alternatives.",
    tags: ["Big Pharma", "drug suppression", "FDA", "alternative medicine"],
  },
  {
    id: "pat_sup_013",
    title: "Tesla's Wardenclyffe Funding Withdrawal (J.P. Morgan)",
    description: "The original corporate suppression: J.P. Morgan funded Tesla's Wardenclyffe Tower (1901) for wireless telegraphy. When Tesla revealed the tower could transmit free power (not just information), Morgan withdrew funding: 'If anyone can draw the power, where can we put the meter?' The tower was demolished in 1917. This set the template for all subsequent energy suppression: if it can't be metered, it can't be funded.",
    impact: "Free wireless energy suppressed. The 'metering' principle established. 120+ years of wired, metered energy.",
    tags: ["Tesla", "Wardenclyffe", "Morgan", "metering"],
  },
  {
    id: "pat_sup_014",
    title: "Cold Fusion 'Debunking' (1989 DOE Panel)",
    description: "After Fleischmann-Pons announced cold fusion (March 1989), the DOE convened a panel that 'debunked' it within months — despite no replication attempts. The panel was chaired by John Huizenga, a nuclear physicist with a known anti-cold-fusion bias. The panel's report killed cold fusion funding for 20 years. Subsequent replications (SRI, ENEA, NRL, MIT) confirmed excess heat — but the damage was done. The 1989 panel was a paradigm-defense operation.",
    impact: "20 years of cold fusion research lost. The DOE panel as paradigm enforcement.",
    tags: ["cold fusion", "DOE", "Fleischmann", "Pons"],
  },
  {
    id: "pat_sup_015",
    title: "Royal Rife 1934 Clinical Trial Burial",
    description: "In 1934, a clinical trial of Rife's Beam Ray Device treated 16 terminal cancer patients — 14 were cured. The trial was supervised by Dr. Milbank Johnson (USC medical director) and witnessed by prominent physicians. The results were never published. Dr. Johnson was pressured to retract, then died of a sudden heart attack (1939) just before he was to publicly present the results. All records were seized or destroyed. The 1934 trial is the most suppressed medical study in history.",
    impact: "Cancer cure suppressed. Millions of deaths that could have been prevented. The medical-industrial complex established.",
    tags: ["Rife", "1934 trial", "cancer", "AMA"],
  },
];