export const VETTED_INVESTORS = [
  // ─── Research Foundations ──────────────────────────────────────
  {
    id: "foresight_001",
    name: "Foresight Institute",
    type: "Foundation",
    location: "Palo Alto, CA",
    focus: ["breakthrough physics", "nanotechnology", "long-term science", "unconventional research"],
    categories: ["Vacuum Energy", "Scalar EM", "Resonance Devices", "Free Energy"],
    stage_preference: ["Concept", "Prototype", "Patent Filed"],
    check_size_min: 10000,
    check_size_max: 250000,
    alignment_score: 98,
    suppression_risk: "very_low",
    anonymity_friendly: true,
    description: "Non-profit supporting transformative technologies including breakthrough energy and advanced physics. Actively funds heterodox science through fellowships and grants. No agenda alignment required beyond scientific merit.",
    contact_approach: "Fellowship application or direct email to programs team. Anonymous disclosures accepted at initial stage.",
    tags: ["heterodox science", "breakthrough physics", "fellowship", "no NDA required"],
    logo_emoji: "🔬",
    color: "#3b82f6",
  },
  {
    id: "emergent_001",
    name: "Emergent Ventures (Mercatus Center)",
    type: "Grant Program",
    location: "Arlington, VA",
    focus: ["moonshot ideas", "heterodox research", "unconventional scientists", "breakthrough technology"],
    categories: ["Vacuum Energy", "Scalar EM", "Bioelectromagnetics", "Free Energy", "Health Technology"],
    stage_preference: ["Concept", "Prototype"],
    check_size_min: 5000,
    check_size_max: 100000,
    alignment_score: 95,
    suppression_risk: "very_low",
    anonymity_friendly: true,
    description: "Tyler Cowen's fast-moving grant program explicitly targeting contrarian thinkers with potentially civilization-changing ideas. No bureaucracy, decisions in days not months. Welcomes fringe-but-rigorous science.",
    contact_approach: "Single-page application. Anonymous applications reviewed; identity disclosed only after initial screening.",
    tags: ["moonshots", "contrarian", "fast grants", "Tyler Cowen", "civilization-level"],
    logo_emoji: "🌱",
    color: "#22c55e",
  },
  {
    id: "vitadao_001",
    name: "VitaDAO",
    type: "Research DAO",
    location: "Decentralized",
    focus: ["longevity science", "bioelectromagnetics", "health extension", "open-source biology"],
    categories: ["Bioelectromagnetics", "Health Technology", "Resonance Devices"],
    stage_preference: ["Concept", "Prototype", "Patent Filed"],
    check_size_min: 25000,
    check_size_max: 500000,
    alignment_score: 90,
    suppression_risk: "very_low",
    anonymity_friendly: true,
    description: "Decentralized autonomous organization funding longevity and health research. No single point of censorship — governance distributed across token holders. IP-NFT model means research IP can be owned collectively, preventing suppression by single actor.",
    contact_approach: "Submit research proposal to VitaDAO forum. Pseudonymous submissions accepted. Community votes on funding.",
    tags: ["DAO", "decentralized", "longevity", "IP-NFT", "censorship-resistant"],
    logo_emoji: "💊",
    color: "#a855f7",
  },
  {
    id: "labdao_001",
    name: "LabDAO / DeSci Foundation",
    type: "Research DAO",
    location: "Decentralized",
    focus: ["open science", "decentralized research", "unconventional physics", "reproducibility"],
    categories: ["Vacuum Energy", "Scalar EM", "Resonance Devices", "Free Energy", "Bioelectromagnetics"],
    stage_preference: ["Concept", "Prototype", "Patent Filed"],
    check_size_min: 5000,
    check_size_max: 150000,
    alignment_score: 92,
    suppression_risk: "very_low",
    anonymity_friendly: true,
    description: "Decentralized science infrastructure funding open research with no institutional gatekeeping. Smart contract-based grants release funds on milestone completion, not committee approval. Particularly receptive to suppressed-but-documented prior art.",
    contact_approach: "GitHub proposal + forum post. Pseudonymous identity supported throughout process. Milestone-based smart contract funding.",
    tags: ["DeSci", "open source", "milestone-based", "smart contracts", "no gatekeeping"],
    logo_emoji: "🧪",
    color: "#06b6d4",
  },
  // ─── Angel Investors ──────────────────────────────────────────
  {
    id: "angel_001",
    name: "Peter Thiel Foundation / Thiel Fellowship",
    type: "Angel / Foundation",
    location: "San Francisco, CA",
    focus: ["contrarian bets", "definite optimism", "breakthrough technology", "anti-establishment science"],
    categories: ["Vacuum Energy", "Free Energy", "Scalar EM", "Defense Technology", "Health Technology"],
    stage_preference: ["Concept", "Prototype", "Patent Filed"],
    check_size_min: 100000,
    check_size_max: 5000000,
    alignment_score: 85,
    suppression_risk: "low",
    anonymity_friendly: false,
    description: "Peter Thiel's investment philosophy centers on breakthrough technology others dismiss. Explicitly anti-consensus, pro-definite-optimism. Has funded multiple technologies mainstream VCs rejected. Thiel Fellowship provides $100K for under-22 inventors to skip college and build.",
    contact_approach: "Warm introduction strongly preferred. Identity required at term sheet stage but early conversations can be exploratory.",
    tags: ["contrarian", "anti-consensus", "large checks", "Thiel Fellows", "breakthrough"],
    logo_emoji: "⚡",
    color: "#f59e0b",
  },
  {
    id: "angel_002",
    name: "Helion Energy / Sam Altman Circle",
    type: "Angel Network",
    location: "Redmond, WA",
    focus: ["clean energy", "advanced physics", "fusion adjacent", "energy breakthrough"],
    categories: ["Vacuum Energy", "Free Energy", "Resonance Devices", "Scalar EM"],
    stage_preference: ["Prototype", "Patent Filed", "Patent Granted", "Pre-Revenue"],
    check_size_min: 500000,
    check_size_max: 50000000,
    alignment_score: 70,
    suppression_risk: "medium",
    anonymity_friendly: false,
    description: "The Sam Altman / Y Combinator energy-focused investment circle. Funded Helion at $3B valuation. Interested in breakthrough energy. Institutional enough to require full identity disclosure but mission-aligned on energy abundance.",
    contact_approach: "YC application or warm intro via YC alumni network. Full identity and team disclosure required.",
    tags: ["clean energy", "YC", "large checks", "mainstream-adjacent", "fusion"],
    logo_emoji: "🔋",
    color: "#ef4444",
  },
  {
    id: "angel_003",
    name: "Skoll Foundation",
    type: "Foundation",
    location: "Palo Alto, CA",
    focus: ["social entrepreneurs", "civilizational impact", "health innovation", "suppressed solutions"],
    categories: ["Bioelectromagnetics", "Health Technology", "Free Energy"],
    stage_preference: ["Prototype", "Patent Filed", "Patent Granted", "Pre-Revenue"],
    check_size_min: 50000,
    check_size_max: 2000000,
    alignment_score: 80,
    suppression_risk: "low",
    anonymity_friendly: false,
    description: "Jeff Skoll's foundation funding social entrepreneurs solving humanity's most critical problems. Framed around planetary-scale impact. Health technology and energy access are core focus areas. Values mission alignment over profit maximization.",
    contact_approach: "Applications through Skoll Foundation programs. Identity required. Framing around global health impact increases odds.",
    tags: ["social impact", "health", "civilizational", "mission-aligned", "Skoll"],
    logo_emoji: "🌍",
    color: "#22c55e",
  },
  {
    id: "angel_004",
    name: "ARPA-E Alumni Angels (Ex-DARPA/DOE)",
    type: "Angel Network",
    location: "Washington, DC",
    focus: ["energy breakthrough", "defense physics", "scalar EM adjacent", "suppressed government research"],
    categories: ["Vacuum Energy", "Scalar EM", "Defense Technology", "Free Energy", "Resonance Devices"],
    stage_preference: ["Concept", "Prototype", "Patent Filed"],
    check_size_min: 25000,
    check_size_max: 1000000,
    alignment_score: 88,
    suppression_risk: "low",
    anonymity_friendly: true,
    description: "Informal network of former ARPA-E, DARPA, and DOE researchers who became angel investors. Uniquely positioned to evaluate unconventional energy claims — they've seen classified research that validates what mainstream physics denies. Several members have personal knowledge of suppressed programs.",
    contact_approach: "Introduction through defense technology networks. Many are comfortable with anonymous initial disclosures due to personal experience with classified research.",
    tags: ["DARPA", "DOE", "defense", "classified-adjacent", "government alumni"],
    logo_emoji: "🎖️",
    color: "#8b5cf6",
  },
  {
    id: "angel_005",
    name: "Protocol Labs / Juan Benet Network",
    type: "Angel / Crypto Fund",
    location: "San Francisco, CA",
    focus: ["decentralized infrastructure", "censorship-resistant knowledge", "open science", "Web3 research funding"],
    categories: ["Vacuum Energy", "Scalar EM", "Bioelectromagnetics", "Free Energy", "Other"],
    stage_preference: ["Concept", "Prototype", "Patent Filed"],
    check_size_min: 50000,
    check_size_max: 5000000,
    alignment_score: 87,
    suppression_risk: "very_low",
    anonymity_friendly: true,
    description: "Protocol Labs (IPFS/Filecoin) founder Juan Benet and network fund research that decentralizes knowledge and prevents suppression. Philosophical alignment with open, uncensorable science. Web3 grant structures support pseudonymous researchers.",
    contact_approach: "DeSci community channels or Protocol Labs research grants. Pseudonymous applications fully supported.",
    tags: ["IPFS", "decentralized", "censorship-resistant", "Web3", "open science"],
    logo_emoji: "🌐",
    color: "#06b6d4",
  },
  {
    id: "angel_006",
    name: "Balaji Srinivasan / Network State Investors",
    type: "Angel Network",
    location: "San Francisco / Remote",
    focus: ["sovereignty technology", "exit from legacy institutions", "decentralized science", "anti-censorship"],
    categories: ["Vacuum Energy", "Free Energy", "Scalar EM", "Health Technology", "Defense Technology"],
    stage_preference: ["Concept", "Prototype"],
    check_size_min: 50000,
    check_size_max: 2000000,
    alignment_score: 92,
    suppression_risk: "very_low",
    anonymity_friendly: true,
    description: "Balaji Srinivasan and his network of 'network state' aligned investors specifically seeking technology that works around suppressive institutions. His thesis is that breakthrough technology must be developed outside legacy regulatory/IP capture systems. Extremely favorable to anonymous-first disclosure.",
    contact_approach: "Crypto-native channels. Bitcoin/ETH payment accepted for services. Pseudonymous identity supported end-to-end.",
    tags: ["network state", "sovereignty", "anti-suppression", "crypto-native", "pseudonymous"],
    logo_emoji: "🏴",
    color: "#f59e0b",
  },
  {
    id: "angel_007",
    name: "Long-Term Future Fund (LTFF / EA Funds)",
    type: "Foundation / EA Fund",
    location: "Global (UK registered)",
    focus: ["existential risk reduction", "humanity-saving technology", "breakthrough science", "long-horizon impact"],
    categories: ["Bioelectromagnetics", "Health Technology", "Free Energy", "Vacuum Energy"],
    stage_preference: ["Concept", "Prototype", "Patent Filed"],
    check_size_min: 5000,
    check_size_max: 500000,
    alignment_score: 82,
    suppression_risk: "very_low",
    anonymity_friendly: true,
    description: "Effective Altruism-adjacent fund focused on existential risk and humanity-scale positive impact. If your research genuinely addresses large-scale human health or energy crises, this fund is philosophically aligned. Fast turnaround, small team, research-friendly.",
    contact_approach: "Online application. Anonymous applications reviewed; framing around humanity-scale positive impact increases probability.",
    tags: ["EA", "existential risk", "long-term", "humanity-scale", "fast grants"],
    logo_emoji: "🌱",
    color: "#22c55e",
  },
  {
    id: "angel_008",
    name: "Cascade Energy Ventures",
    type: "VC Fund",
    location: "Seattle, WA",
    focus: ["breakthrough energy", "advanced materials", "quantum effects", "unconventional physics"],
    categories: ["Vacuum Energy", "Free Energy", "Resonance Devices", "Scalar EM"],
    stage_preference: ["Prototype", "Patent Filed", "Patent Granted", "Pre-Revenue"],
    check_size_min: 500000,
    check_size_max: 10000000,
    alignment_score: 75,
    suppression_risk: "low",
    anonymity_friendly: false,
    description: "Pacific Northwest VC fund with several partners who have academic backgrounds in advanced physics. More receptive than typical VCs to unconventional energy claims. Require working prototype demonstration but evaluate mechanism on its physics merit, not mainstream consensus.",
    contact_approach: "Warm introduction through Pacific Northwest tech networks. Identity required at first meeting. Prototype demo expected within 60 days of term sheet.",
    tags: ["energy VC", "advanced physics", "prototype required", "Pacific Northwest"],
    logo_emoji: "⚡",
    color: "#3b82f6",
  },
];

export const INVESTOR_TYPES = ["All", "Foundation", "Angel / Foundation", "Research DAO", "Grant Program", "Angel / Crypto Fund", "Angel Network", "VC Fund"];
export const SUPPRESSION_RISK_COLORS = {
  very_low: { text: "text-green-400", label: "Very Low", bg: "bg-green-900/30" },
  low: { text: "text-blue-400", label: "Low", bg: "bg-blue-900/30" },
  medium: { text: "text-yellow-400", label: "Medium", bg: "bg-yellow-900/30" },
  high: { text: "text-red-400", label: "High", bg: "bg-red-900/30" },
};