export const INVESTORS = [
  {
    id: "foresight_01",
    name: "Foresight Institute",
    type: "Research Foundation",
    logo: "🔬",
    focus: ["Vacuum Energy", "Scalar EM", "Nanotechnology", "Physics Breakthrough"],
    alignment: ["open_science", "long_horizon", "suppressed_tech", "existential_benefit"],
    check_range: [25000, 500000],
    stage_fit: ["Concept", "Prototype", "Patent Pending"],
    description: "Non-profit funding breakthrough science that mainstream institutions won't touch. Deep alignment with unconventional physics, long time horizons. Founded 1986. Grants + fellowship programs.",
    website: "https://foresight.org",
    contact_method: "Grant application portal",
    risk_tolerance: "high",
    anonymity_respected: true,
    geography: "Global",
    tags: ["nanotechnology", "physics", "breakthrough", "open science", "longevity"],
  },
  {
    id: "emergent_01",
    name: "Emergent Ventures (Tyler Cowen / Mercatus)",
    type: "Angel Program",
    logo: "💡",
    focus: ["Breakthrough Technology", "Energy", "Physics", "Heterodox Science"],
    alignment: ["heterodox", "long_horizon", "decentralized", "anti_establishment"],
    check_range: [10000, 100000],
    stage_fit: ["Concept", "Prototype"],
    description: "Fast grants for talented individuals working on ambitious, often contrarian projects. Tyler Cowen personally reviews. No bureaucracy — 2-page application, fast decision. Explicitly funds ideas mainstream academia rejects.",
    website: "https://marginalrevolution.com/emergentventures",
    contact_method: "2-page application, personal review",
    risk_tolerance: "very_high",
    anonymity_respected: true,
    geography: "Global",
    tags: ["contrarian", "fast grant", "individual", "ambitious", "heterodox"],
  },
  {
    id: "vitadao_01",
    name: "VitaDAO",
    type: "Decentralized Research DAO",
    logo: "🧬",
    focus: ["Bioelectromagnetics", "Longevity", "Anti-aging", "Health Technology"],
    alignment: ["decentralized", "open_science", "longevity", "existential_benefit"],
    check_range: [50000, 300000],
    stage_fit: ["Concept", "Prototype", "Patent Pending"],
    description: "Community-owned longevity research DAO. Funds bioelectromagnetic health technologies, unconventional therapies, and anti-aging science. IP-NFT model means no single party can suppress your research.",
    website: "https://www.vitadao.com",
    contact_method: "DAO governance proposal",
    risk_tolerance: "high",
    anonymity_respected: true,
    geography: "Global (Decentralized)",
    tags: ["longevity", "DAO", "bioelectromagnetics", "health", "IP-NFT", "decentralized"],
  },
  {
    id: "labdao_01",
    name: "LabDAO",
    type: "Decentralized Science DAO",
    logo: "⚗️",
    focus: ["Open Science", "Scalar EM", "Physics", "Research Infrastructure"],
    alignment: ["open_science", "decentralized", "suppressed_tech"],
    check_range: [5000, 150000],
    stage_fit: ["Concept", "Prototype", "Patent Pending", "Patent Granted"],
    description: "Decentralized laboratory and research funding network. Runs compute and wet-lab jobs peer-to-peer. Ideal for inventors who need lab resources without exposing themselves to institutional gatekeepers.",
    website: "https://www.labdao.xyz",
    contact_method: "Protocol grant",
    risk_tolerance: "high",
    anonymity_respected: true,
    geography: "Global (Decentralized)",
    tags: ["open science", "decentralized", "lab access", "peer-to-peer", "research"],
  },
  {
    id: "thiel_01",
    name: "Thiel Foundation / 20 Under 20",
    type: "Angel Foundation",
    logo: "🎯",
    focus: ["Breakthrough Energy", "Physics", "Technology Contrarianism"],
    alignment: ["anti_establishment", "long_horizon", "heterodox", "decentralized"],
    check_range: [100000, 1000000],
    stage_fit: ["Prototype", "Patent Pending", "Patent Granted"],
    description: "Peter Thiel explicitly funds technology that governments and mainstream institutions suppress. Deep scepticism of regulatory capture. Portfolio includes several energy and physics companies mainstream VCs refused. Expects unconventional ideas.",
    website: "https://thielfoundation.org",
    contact_method: "Fellowship application or warm intro",
    risk_tolerance: "very_high",
    anonymity_respected: false,
    geography: "US / Global",
    tags: ["contrarian", "anti-establishment", "breakthrough", "energy", "physics"],
  },
  {
    id: "darpex_01",
    name: "ARPA-E (DOE Advanced Research)",
    type: "Government Research Grant",
    logo: "⚡",
    focus: ["Vacuum Energy", "Advanced Energy", "Physics Breakthrough"],
    alignment: ["long_horizon", "existential_benefit"],
    check_range: [500000, 10000000],
    stage_fit: ["Prototype", "Patent Pending", "Patent Granted", "Seeking Funding"],
    description: "DOE's high-risk, high-reward energy research agency. Explicitly funds ideas too risky for private investors. Has funded unconventional approaches to energy extraction. Requires prototype demonstration.",
    website: "https://arpa-e.energy.gov",
    contact_method: "ARPA-E OPEN solicitation",
    risk_tolerance: "high",
    anonymity_respected: false,
    geography: "US only",
    tags: ["government", "energy", "high risk", "large grants", "prototype required"],
  },
  {
    id: "longevity_01",
    name: "Longevity Fund (Laura Deming)",
    type: "Venture Fund",
    logo: "🌿",
    focus: ["Bioelectromagnetics", "Health Technology", "Longevity"],
    alignment: ["longevity", "existential_benefit", "long_horizon"],
    check_range: [500000, 5000000],
    stage_fit: ["Prototype", "Patent Pending", "Patent Granted"],
    description: "Early stage longevity fund backing science-driven health technology. Laura Deming has publicly backed unconventional approaches to aging and health. Strong alignment with bioelectromagnetic therapeutic applications.",
    website: "https://www.longevity.vc",
    contact_method: "Cold email with data",
    risk_tolerance: "high",
    anonymity_respected: false,
    geography: "US / Global",
    tags: ["longevity", "health", "bioelectromagnetics", "VC", "science-driven"],
  },
  {
    id: "breakout_01",
    name: "Breakout Labs (Thiel Foundation)",
    type: "Fellowship Program",
    logo: "🔓",
    focus: ["Vacuum Energy", "Scalar EM", "Radical Science"],
    alignment: ["anti_establishment", "heterodox", "long_horizon"],
    check_range: [350000, 350000],
    stage_fit: ["Concept", "Prototype"],
    description: "Breakout Labs specifically funds companies doing science so radical that no traditional funding source will touch it. Fixed $350K grants for early-stage radical science companies. Has funded energy and materials breakthroughs.",
    website: "https://www.breakoutlabs.org",
    contact_method: "Application + scientific review",
    risk_tolerance: "very_high",
    anonymity_respected: true,
    geography: "US",
    tags: ["radical science", "no traditional funding", "energy", "early stage"],
  },
  {
    id: "resonance_01",
    name: "Resonance Science Foundation",
    type: "Research Foundation",
    logo: "🌀",
    focus: ["Scalar EM", "Unified Physics", "Resonance Devices", "Vacuum Energy"],
    alignment: ["open_science", "suppressed_tech", "long_horizon", "existential_benefit"],
    check_range: [10000, 200000],
    stage_fit: ["Concept", "Prototype", "Patent Pending"],
    description: "Non-profit researching unified physics and field resonance. Nassim Haramein's group — deep alignment with scalar field theory, vacuum energy, and consciousness research. Community of 30,000+ researchers globally.",
    website: "https://www.resonancescience.org",
    contact_method: "Research collaboration proposal",
    risk_tolerance: "very_high",
    anonymity_respected: true,
    geography: "Global",
    tags: ["unified physics", "scalar field", "vacuum", "community", "non-profit"],
  },
  {
    id: "openphil_01",
    name: "Open Philanthropy",
    type: "Research Foundation",
    logo: "🌍",
    focus: ["Existential Risk", "Advanced Technology", "Bioelectromagnetics", "Energy"],
    alignment: ["existential_benefit", "long_horizon", "open_science"],
    check_range: [100000, 5000000],
    stage_fit: ["Concept", "Prototype", "Patent Pending", "Patent Granted"],
    description: "GiveWell's sister org funding high-impact, high-uncertainty science. Has funded unconventional health and technology research. Strong case for scalar EM as existential risk mitigation (EMF damage reduction).",
    website: "https://www.openphilanthropy.org",
    contact_method: "Expression of interest form",
    risk_tolerance: "high",
    anonymity_respected: true,
    geography: "Global",
    tags: ["existential risk", "high impact", "health", "energy", "large grants"],
  },
  {
    id: "gitcoin_01",
    name: "Gitcoin Grants (DeSci Round)",
    type: "Crowdfunding DAO",
    logo: "🪙",
    focus: ["Open Science", "Decentralized Research", "Energy", "Health Technology"],
    alignment: ["decentralized", "open_science", "anti_establishment"],
    check_range: [1000, 50000],
    stage_fit: ["Concept", "Prototype"],
    description: "Quadratic funding rounds for open science. Decentralized Science (DeSci) rounds specifically fund unconventional research that institutional gatekeepers reject. Funds proportional to community interest — viral support amplifies grants.",
    website: "https://gitcoin.co",
    contact_method: "Grant application in DeSci round",
    risk_tolerance: "very_high",
    anonymity_respected: true,
    geography: "Global (Decentralized)",
    tags: ["crowdfunding", "quadratic", "open source", "DeSci", "decentralized"],
  },
  {
    id: "molecule_01",
    name: "Molecule Protocol (IP-NFT)",
    type: "Decentralized Research DAO",
    logo: "💊",
    focus: ["Bioelectromagnetics", "Health Technology", "Longevity", "Therapeutic Devices"],
    alignment: ["decentralized", "open_science", "longevity"],
    check_range: [100000, 1000000],
    stage_fit: ["Patent Pending", "Patent Granted"],
    description: "Blockchain-based IP ownership and research funding. Converts patents into IP-NFTs, enabling decentralized community ownership of research IP. Once your invention is an IP-NFT, no single investor can buy it and shelve it.",
    website: "https://www.molecule.to",
    contact_method: "IP-NFT minting proposal",
    risk_tolerance: "high",
    anonymity_respected: true,
    geography: "Global (Decentralized)",
    tags: ["IP-NFT", "blockchain", "decentralized IP", "community ownership", "health"],
  },
];

export const ALIGNMENT_FLAGS = [
  { id: "open_science", label: "Open Science", color: "#3b82f6", desc: "Committed to public knowledge sharing" },
  { id: "long_horizon", label: "Long Time Horizon", color: "#a855f7", desc: "5–20+ year investment patience" },
  { id: "suppressed_tech", label: "Suppressed Tech", color: "#ef4444", desc: "Accepts historically suppressed technologies" },
  { id: "existential_benefit", label: "Existential Benefit", color: "#22c55e", desc: "Prioritizes humanity-level impact" },
  { id: "decentralized", label: "Decentralized", color: "#f59e0b", desc: "No single point of control or suppression" },
  { id: "heterodox", label: "Heterodox Science", color: "#06b6d4", desc: "Funds ideas mainstream rejects" },
  { id: "anti_establishment", label: "Anti-Establishment", color: "#ec4899", desc: "Explicitly counter-institutional" },
  { id: "longevity", label: "Longevity / Health", color: "#84cc16", desc: "Health and lifespan extension focus" },
];

export const INVESTOR_CATEGORIES = ["All", "Research Foundation", "Angel Program", "Decentralized Research DAO", "Venture Fund", "Fellowship Program", "Government Research Grant", "Crowdfunding DAO"];