export const PRIOR_ART_ARCHIVE = [
  // ─── TESLA ──────────────────────────────────────────────────────
  {
    id: "tesla_001",
    title: "Tesla Magnifying Transmitter (Wardenclyffe Tower)",
    inventor: "Nikola Tesla",
    year: 1901,
    category: "Scalar EM",
    outcome: "Suppressed",
    patent_numbers: "US645576, US649621",
    source_document: "Tesla Patent Archives; Bearden 'Comments on New Tesla EM' (1982)",
    description: "Resonant cavity transmitter using Earth as conductor to transmit power and scalar waves globally. Ground wave propagation without conventional EM radiation. Morgan withdrew funding after realizing metered electricity was impossible.",
    key_claims: ["longitudinal wave propagation through Earth", "resonant cavity excitation", "wireless energy transmission without Hertzian radiation", "ground current utilization"],
    failure_reasons: "Investor suppression (J.P. Morgan), funding withdrawal 1904. Physical plant demolished 1917. No patent rejection — suppressed at deployment stage.",
    rejection_grounds: "N/A — never submitted for rejection; commercial suppression",
    tags: ["longitudinal waves", "ground transmission", "resonant cavity", "wireless power", "scalar"],
    risk_score: 85,
  },
  {
    id: "tesla_002",
    title: "Tesla Radiant Energy Collector",
    inventor: "Nikola Tesla",
    year: 1901,
    category: "Free Energy",
    outcome: "Patent Granted",
    patent_numbers: "US685957",
    source_document: "Tesla Patent US685957 (1901); Bearden anenergy pump analysis",
    description: "System for utilizing radiant solar and cosmic radiation. Insulated elevated plate collects charge potential from space, discharging through circuit. Bearden interprets as early anenergy pump demonstration.",
    key_claims: ["elevated insulated collector plate", "cosmic radiation charge accumulation", "capacitive discharge circuit", "free-space energy collection"],
    failure_reasons: "Patent granted but never commercialized. Output insufficient for commercial application at contemporary efficiencies.",
    rejection_grounds: "N/A — patent granted",
    tags: ["radiant energy", "cosmic rays", "capacitive collection", "anenergy"],
    risk_score: 30,
  },
  {
    id: "tesla_003",
    title: "Tesla Oscillating Transformer (Tesla Coil)",
    inventor: "Nikola Tesla",
    year: 1891,
    category: "Resonance Devices",
    outcome: "Patent Granted",
    patent_numbers: "US454622, US462418",
    source_document: "Tesla Patent US454622; Bearden scalar wave analysis of Tesla coil secondary",
    description: "Resonant air-core transformer producing high-voltage high-frequency oscillations. Bearden argues the secondary output is partially scalar (phi-field) in nature, explaining anomalous biological and energetic effects not predicted by standard transformer theory.",
    key_claims: ["air-core resonant transformer", "high-frequency oscillation", "displacement current dominance", "standing wave formation in secondary coil"],
    failure_reasons: "Patent granted; device works as claimed but scalar aspects unrecognized in filing.",
    rejection_grounds: "N/A — patent granted",
    tags: ["resonant transformer", "high voltage", "standing waves", "displacement current"],
    risk_score: 20,
  },
  // ─── MORAY ──────────────────────────────────────────────────────
  {
    id: "moray_001",
    title: "T.H. Moray Sea-of-Energy Vacuum Extraction Device",
    inventor: "Thomas Henry Moray",
    year: 1926,
    category: "Vacuum Energy",
    outcome: "Suppressed",
    patent_numbers: "None granted (multiple rejected)",
    source_document: "Bearden Part 4 (1983); Moray 'The Sea of Energy in Which the Earth Swims' (1960)",
    description: "Valve/tube device demonstrated at 50kW output with no external power source. Multiple independent witnesses signed affidavits. Device destroyed by Soviet agent infiltrating Moray's laboratory. USPTO rejected patent applications due to impossibility of claimed output exceeding input.",
    key_claims: ["vacuum zero-point energy extraction", "sea-of-energy tapping mechanism", "valve tube resonant coupling to vacuum", "50kW sustained output from ambient"],
    failure_reasons: "Physical device destroyed. Patent applications rejected by USPTO on 101/102 grounds. Inventor died without replication documentation.",
    rejection_grounds: "USPTO rejection: claimed perpetual motion / output exceeds input — violates known energy conservation laws. No independent replication submitted.",
    tags: ["zero point energy", "vacuum extraction", "valve tube", "sea of energy", "over unity"],
    risk_score: 90,
  },
  // ─── PRIORE ─────────────────────────────────────────────────────
  {
    id: "priore_001",
    title: "Prioré Multichannel EM Therapeutic Device",
    inventor: "Antoine Prioré",
    year: 1963,
    category: "Bioelectromagnetics",
    outcome: "Suppressed",
    patent_numbers: "FR1,342,772 (French patent granted 1963)",
    source_document: "Bearden Excalibur Briefing Fig. 10; French CNRS documentation 1964–1974",
    description: "Multichannel rotating magnetic field device with plasma tube. French government funded; documented cancer remissions in laboratory animals. S'/S''/S''' hyperspatial modulation architecture. Research terminated after Prioré's death and political changes at CNRS.",
    key_claims: ["multichannel modulated EM field therapy", "rotating magnetic field biological interaction", "plasma tube EM emission with nested modulation", "cancer regression via EM template reversal"],
    failure_reasons: "French patent granted. Research terminated on political/funding grounds post-1974, not technical failure. No regulatory (FDA equivalent) approval path pursued.",
    rejection_grounds: "N/A in France — patent granted. Would face FDA 510(k) / PMA pathway in US; mechanism of action not explained in classical physics terms.",
    tags: ["EM therapy", "cancer", "rotating magnetic field", "plasma", "France", "hyperspatial modulation"],
    risk_score: 60,
  },
  // ─── RIFE ────────────────────────────────────────────────────────
  {
    id: "rife_001",
    title: "Royal Rife Universal Microscope & Mortal Oscillatory Rate",
    inventor: "Royal Raymond Rife",
    year: 1934,
    category: "Bioelectromagnetics",
    outcome: "Suppressed",
    patent_numbers: "None — no patent filed",
    source_document: "Bearden 'Gravitobiology' (1988/1991); Barry Lynes 'The Cancer Cure That Worked'",
    description: "Prismatic microscope with magnification exceeding 50,000× without electron beam. Identified Mortal Oscillatory Rate (MOR) — specific resonant frequencies destroying pathogens without harming surrounding tissue. Demonstrated cancer regression. AMA suppressed clinical trials 1939.",
    key_claims: ["biological resonant frequency pathogen destruction", "MOR-specific frequency targeting", "optical microscopy beyond Abbe diffraction limit", "selective cytotoxic resonance"],
    failure_reasons: "No patent filed. AMA legal and professional pressure forced all clinical collaborators to recant. Microscope blueprints lost. No frequency-verified replication completed.",
    rejection_grounds: "N/A — no patent filed. Modern replications face FDA Class III device classification requiring clinical trial data AMA actively suppressed.",
    tags: ["MOR", "resonant frequency", "pathogen", "microscopy", "cancer", "AMA suppression"],
    risk_score: 70,
  },
  // ─── SCHAUBERGER ─────────────────────────────────────────────────
  {
    id: "schauberger_001",
    title: "Viktor Schauberger Implosion Vortex Generator",
    inventor: "Viktor Schauberger",
    year: 1940,
    category: "Free Energy",
    outcome: "Suppressed",
    patent_numbers: "AT145141, AT196680 (Austrian patents)",
    source_document: "Callum Coats 'Living Energies'; Schauberger archives Vienna",
    description: "Vortex motion water turbine exploiting implosion rather than explosion physics. Claimed levitation and over-unity output. Nazi regime confiscated designs; later US government debriefed Schauberger at Los Alamos. All papers classified.",
    key_claims: ["implosion vortex motion", "counter-rotating fluid dynamics", "diamagnetic levitation", "over-unity water turbine"],
    failure_reasons: "Patents granted in Austria but classified by governments. Inventor died shortly after US government took all physical models and documents under NDAs. No public replication.",
    rejection_grounds: "Austrian patents granted. US patent applications — unknown (classified). Modern filings risk 102 rejection citing Austrian prior art.",
    tags: ["implosion", "vortex", "over-unity", "levitation", "classified"],
    risk_score: 65,
  },
  // ─── BEARDEN ─────────────────────────────────────────────────────
  {
    id: "bearden_001",
    title: "Anenergy Pump — Shielded Toroid Vacuum Energy Extraction",
    inventor: "Thomas E. Bearden",
    year: 1983,
    category: "Vacuum Energy",
    outcome: "Unknown",
    patent_numbers: "None filed (published as open research)",
    source_document: "Bearden 'Toward a New Electromagnetics Part 4' (1983)",
    description: "Theoretical circuit for tapping vacuum energy via shielded toroidal geometry where internal gradient-phi = 0 while phi > phi-zero maintained. Massless charge extraction without V=IR mass current. Based on Aharonov-Bohm effect extended to energy extraction.",
    key_claims: ["shielded toroidal coil with zero internal gradient-phi", "vacuum potential oscillation", "massless charge extraction circuit", "non-Ohmic energy source"],
    failure_reasons: "Published as theory; no physical prototype documented. No patent filed — published openly. Replication attempts not independently verified.",
    rejection_grounds: "USPTO would reject under 35 USC 101 (operability) — must demonstrate working prototype with independent measurement. Energy output claims require certified lab replication.",
    tags: ["anenergy", "toroid", "massless charge", "vacuum potential", "Aharonov-Bohm"],
    risk_score: 88,
  },
  {
    id: "bearden_002",
    title: "Energy Bottle — Zero-Vector EM Interference Zone",
    inventor: "Thomas E. Bearden",
    year: 1983,
    category: "Scalar EM",
    outcome: "Unknown",
    patent_numbers: "None filed",
    source_document: "Bearden 'Toward a New Electromagnetics Part 4' (1983)",
    description: "Two-transmitter system creating interference zone where E=0 and B=0 but phi-field is non-zero. Energy is trapped in the zone with no radiation. Scalar pulse arrives instantaneously; Hertz pulse delayed by c·Δt — enables new radar modality.",
    key_claims: ["zero-vector EM interference zone", "scalar pulse instantaneous ranging", "E=0 B=0 energy bottle", "two-transmitter phase-cancel geometry"],
    failure_reasons: "Theoretical; no documented physical prototype. Scalar pulse timing claims would require nanosecond independent lab verification.",
    rejection_grounds: "102 rejection possible citing Aharonov-Bohm effect (1959, Physical Review). 112 rejection if insufficient enablement — examiner would require working prototype data.",
    tags: ["energy bottle", "scalar pulse", "zero vector", "ranging", "interference zone"],
    risk_score: 75,
  },
  {
    id: "bearden_003",
    title: "Whittaker Scalar Potential Decomposition — EM Communications",
    inventor: "Thomas E. Bearden",
    year: 1988,
    category: "Scalar EM",
    outcome: "Unknown",
    patent_numbers: "None filed",
    source_document: "Bearden 'Gravitobiology' (1988); E.T. Whittaker 'On the Partial Differential Equations of Mathematical Physics' (1903)",
    description: "Whittaker (1903) proved any scalar potential can be decomposed into two counterpropagating EM waves. Bearden extends this to propose hidden-variable EM communications channel — modulation inside the scalar potential propagates faster-than-light between phase-conjugate mirror pairs.",
    key_claims: ["Whittaker potential decomposition communications", "phase conjugate mirror pair channel", "scalar potential hidden-variable modulation", "FTL information channel via vacuum potential"],
    failure_reasons: "Prior art: Whittaker 1903 mathematical proof in public domain. FTL claims face extreme patent office skepticism and physics community rejection.",
    rejection_grounds: "101 rejection (non-operative / violates special relativity for FTL claims). 102 citing Whittaker 1903. Strong 103 obviousness given Aharonov-Bohm and quantum non-locality literature.",
    tags: ["Whittaker", "scalar potential", "phase conjugate", "FTL", "communications", "hidden variable"],
    risk_score: 92,
  },
  // ─── SEARL ────────────────────────────────────────────────────────
  {
    id: "searl_001",
    title: "Searl Effect Generator (SEG) — Levity Disc",
    inventor: "John R.R. Searl",
    year: 1952,
    category: "Free Energy",
    outcome: "Partial Success",
    patent_numbers: "UK Patents (expired/disputed)",
    source_document: "Schaffranke 'Overture to a New Age Technology' (1984); Bearden Tesla Book Co. survey",
    description: "Segmented rollers rotating on concentric rings of neodymium alloy, self-accelerating via room-temperature electron avalanche. Claimed levitation at 10,000 RPM. Multiple witnesses documented levitation events 1960s–1980s. Schaffranke survey included as corroboration in Bearden (1984).",
    key_claims: ["self-accelerating magnetic roller system", "room temperature electron avalanche", "electromagnetic levitation at resonant RPM", "over-unity electrical output during levitation"],
    failure_reasons: "Claimed devices built but independent witness verification disputed. No certified lab measurement of output. UK patents not maintained. Modern SEG Foundation replications show normal motor behavior, not levitation.",
    rejection_grounds: "102 rejection on original Searl UK patent prior art. 101 rejection for levitation/over-unity claims without certified independent data.",
    tags: ["levitation", "magnetic rollers", "self-acceleration", "over-unity", "SEG"],
    risk_score: 80,
  },
  // ─── FLOYD SWEET ──────────────────────────────────────────────────
  {
    id: "sweet_001",
    title: "Floyd Sweet Vacuum Triode Amplifier (VTA)",
    inventor: "Floyd Sweet",
    year: 1985,
    category: "Vacuum Energy",
    outcome: "Unknown",
    patent_numbers: "None filed",
    source_document: "Bearden co-authored 'The Vacuum Triode Amplifier' (1991); Sweet private communications",
    description: "Conditioned barium ferrite magnets producing anomalous output. Sweet and Bearden co-authored analysis claiming vacuum triode mechanism — barium ferrite lattice couples to vacuum scalar field, amplifying input. Tom Bearden witnessed 500W output from small input. No independent replication.",
    key_claims: ["conditioned barium ferrite vacuum coupling", "magnetic domain scalar lattice interaction", "vacuum amplification of EM signal", "over-unity magnetic device"],
    failure_reasons: "No patent filed. Device died with Sweet. No independent certified measurement. Sweet refused third-party testing claiming personal safety concerns.",
    rejection_grounds: "N/A — no patent filed. USPTO would require certified independent laboratory measurement of output exceeding input with calibrated instruments.",
    tags: ["barium ferrite", "vacuum triode", "conditioned magnets", "over-unity"],
    risk_score: 85,
  },
  // ─── KROMREY ──────────────────────────────────────────────────────
  {
    id: "kromrey_001",
    title: "Kromrey G-Field Generator (700W at >100% Efficiency)",
    inventor: "R. Kromrey",
    year: 1978,
    category: "Free Energy",
    outcome: "Partial Success",
    patent_numbers: "German/Swiss patent (Schaffranke reference)",
    source_document: "Schaffranke 'Overture to a New Age Technology' (1984) — included in Bearden Tesla Book Co. (1984)",
    description: "French-German-Swiss gravity-field generator delivering 700W at reported >100% COP. Schaffranke included it in his international survey of documented over-unity prototypes. European patent granted but never commercialized. Details sparse in public record.",
    key_claims: ["gravity field coupling to electrical output", "700W demonstrated output", "coefficient of performance > 1.0", "European patent-protected design"],
    failure_reasons: "European patent granted but no commercialization. Schaffranke's survey is secondary source. No peer-reviewed independent measurement found in accessible literature.",
    rejection_grounds: "US 101 rejection risk: COP > 1.0 requires certified independent lab data. European grant does not bind USPTO examiners.",
    tags: ["G-field", "gravity coupling", "COP > 1", "European patent", "over-unity"],
    risk_score: 72,
  },
  // ─── MODERN ────────────────────────────────────────────────────────
  {
    id: "hutchison_001",
    title: "Hutchison Effect — Anomalous Material Phenomena",
    inventor: "John Hutchison",
    year: 1979,
    category: "Scalar EM",
    outcome: "Partial Success",
    patent_numbers: "None granted",
    source_document: "Hutchison video archives; multiple independent witness documentation",
    description: "Overlapping Tesla coil and RF fields producing anomalous material effects: levitation of heavy objects, jellification of metals, fusion of dissimilar materials at room temperature. Multiple documented video recordings. Canadian government and military investigated.",
    key_claims: ["overlapping EM field material anomalies", "room-temperature metal jellification", "object levitation via EM field interaction", "matter-field coupling at resonance"],
    failure_reasons: "Non-reproducible on demand. No systematic theory enabling independent replication. Effects appear stochastic. No patent filed.",
    rejection_grounds: "112 enablement rejection — cannot specify conditions enabling reproduction. 101 rejection without deterministic replication protocol.",
    tags: ["levitation", "jellification", "RF fields", "Tesla coil", "anomalous", "stochastic"],
    risk_score: 88,
  },
  {
    id: "mills_001",
    title: "Randell Mills Hydrino Theory (BlackLight Power / BrLP)",
    inventor: "Randell Mills",
    year: 1991,
    category: "Free Energy",
    outcome: "Patent Granted",
    patent_numbers: "US7,188,033 and others",
    source_document: "Mills 'The Grand Unified Theory of Classical Quantum Mechanics'; BrLP corporate filings",
    description: "Hydrogen atoms transition to sub-ground-state 'hydrino' configurations releasing energy exceeding normal combustion. Classical quantum mechanics model replaces standard QM. Multiple patents granted; SunCell device under development. Contested by mainstream physics but patents issued.",
    key_claims: ["sub-ground-state hydrogen energy transition", "hydrino formation catalysis", "plasma energy release from hydrogen", "SunCell thermal energy generation"],
    failure_reasons: "Patent granted but physics community disputes mechanism. No peer-reviewed independent calorimetric verification of anomalous excess heat. Commercial deployment delayed 30+ years.",
    rejection_grounds: "Patents granted — but vulnerable to 101 attack if hydrino existence disproven. DOE and mainstream physics reject the mechanism.",
    tags: ["hydrino", "hydrogen", "sub-ground-state", "plasma", "SunCell", "contested"],
    risk_score: 45,
  },
  {
    id: "rossi_001",
    title: "Andrea Rossi E-Cat (Energy Catalyzer) — LENR",
    inventor: "Andrea Rossi",
    year: 2011,
    category: "Free Energy",
    outcome: "Patent Granted",
    patent_numbers: "US9,115,913",
    source_document: "USPTO US9115913; Lugano Report (2014); multiple independent calorimetric tests",
    description: "Low Energy Nuclear Reaction (LENR) device using nickel-hydrogen fuel producing anomalous heat (COP 3–11 claimed). US patent granted 2015 after examiner required working prototype demonstration. Multiple independent measurement teams report excess heat. Rossi fraud conviction in Italy complicates IP picture.",
    key_claims: ["nickel-hydrogen LENR reaction", "anomalous heat production", "nuclear transmutation at low temperature", "energy catalyzer thermal output"],
    failure_reasons: "Patent granted but Rossi credibility severely damaged by fraud conviction and failed industrial heat partnership lawsuit. Independent measurement teams split on whether anomalous heat is real.",
    rejection_grounds: "Patents granted after prototype demo. Future continuation patents face 112 written description issues if mechanism not fully disclosed.",
    tags: ["LENR", "cold fusion", "nickel hydrogen", "anomalous heat", "LENR", "E-Cat"],
    risk_score: 40,
  },
];

export const CATEGORIES = [
  "All",
  "Vacuum Energy",
  "Scalar EM",
  "Bioelectromagnetics",
  "Phase Conjugation",
  "Resonance Devices",
  "Atmospheric EM",
  "Free Energy",
  "Tesla Technology",
  "Other",
];

export const OUTCOMES = [
  "All",
  "Success (demonstrated)",
  "Suppressed",
  "Partial Success",
  "Failed",
  "Patent Granted",
  "Patent Denied",
  "Unknown",
];

export const OUTCOME_COLORS = {
  "Success (demonstrated)": { bg: "bg-green-900/40", text: "text-green-300", border: "border-green-700" },
  "Suppressed": { bg: "bg-red-900/40", text: "text-red-300", border: "border-red-700" },
  "Partial Success": { bg: "bg-yellow-900/40", text: "text-yellow-300", border: "border-yellow-700" },
  "Failed": { bg: "bg-gray-800", text: "text-gray-400", border: "border-gray-600" },
  "Patent Granted": { bg: "bg-blue-900/40", text: "text-blue-300", border: "border-blue-700" },
  "Patent Denied": { bg: "bg-orange-900/40", text: "text-orange-300", border: "border-orange-700" },
  "Unknown": { bg: "bg-purple-900/40", text: "text-purple-300", border: "border-purple-700" },
};