// ── ANCIENT VEDIC, SANSKRIT & FORBIDDEN/OCCULT KNOWLEDGE NODES ──────────────
// Each node is researched from primary texts, archaeological records, and
// suppressed-history scholarship. Connections to the Bearden scalar EM
// framework are noted where the parallel is substantive.

export const vedicOccultNodes = [
  // ── VEDIC TECHNOLOGY ──
  {
    id: "vedic_vimana",
    label: "Vimana: Ancient Aerial Craft (Samarangana Sutradhara)",
    group: "ancient",
    description: "Vimanas — self-propelled flying machines described in the Ramayana, Mahabharata, Samarangana Sutradhara (King Bhoja, c. 1030 CE), and the Vaimaanika Shastra (attributed to Maharishi Bharadwaja). Powered by mercury vortex engines (mercury boiler / gyroscopic), capable of vertical flight, invisibility, and interstellar travel. The Samarangana Sutradhara devotes an entire chapter (XXXI) to vimana construction: mercury heated in a sealed iron vessel drives a vortex wheel producing lift and directional thrust.",
    fragments: [
      "Samarangana Sutradhara, Chapter XXXI (King Bhoja of Dhar, c. 1030 CE): 'Strong and durable must the body of the Vimana be made, like a great flying bird of light material. Inside one must put the mercury engine with its solar mercury boiler at the bottom center. By means of the power latent in the mercury which sets the driving whirlwind in motion, a man sitting inside may travel a great distance into the sky. The movements of the Vimana are such that it can go vertically, descend, move slantingly, and wander. It has the capacity to become invisible, to hear distant sounds, and to see distant objects.'",
      "Vaimaanika Shastra (Maharishi Bharadwaja, reconstructed 1918–1923 by Pandit Subbaraya Shastya): Describes 32 secrets of vimana operation including: (1) Mantrika — invocation of entities; (2) Tantrika — mechanical; (3) Kritaka — artificial vimanas; (4) Antara — atmospheric; (5) Gouda — solar powered; (6) Mercuric vortex engine; (7) Tamogarbha Loha — light-absorbing metal alloy for the hull; (8) Solar power absorption panels; (9) Invisibility via 'guha garbha darshan' (concealment).",
      "Ramayana (Valmiki), Yuddha Kanda: Pushpaka Vimana — the self-moving aerial car of Kubera, seized by Ravana, then by Rama. 'That great car, self-propelled and shining like the sun, expanded to carry all the Vanaras. It moved at the will of its occupants.' The Pushpaka is described as capable of carrying any number of passengers and shrinking/expanding — consistent with a structured-field craft rather than a mechanical vehicle.",
      "Mahabharata: Drona Parva describes the 'Agneya Astra' (fire weapon), 'Brahma Sirs' (universe-destroying weapon), and 'Vimana' craft used in the Kurukshetra war. The Brahmastra's description — 'a single projectile charged with all the power of the Universe... an incandescent column of smoke and flame as bright as ten thousand suns rose in all its splendor... corpses so burned as to be unrecognizable, hair and nails fell out, pottery broke without cause, birds turned white' — is the oldest surviving description of a weapon with nuclear/ scalar-EM characteristics, predating 20th-century physics by ~2,500 years."
    ]
  },
  {
    id: "nada_brahman",
    label: "Nada Brahma: Sound as the Fabric of Reality (Sanskrit)",
    group: "ancient",
    description: "The Vedic doctrine that the universe IS sound — 'Nada Brahma' (God is Sound). Sanskrit mantras are not symbolic language but precise vibrational operators that directly structure the quantum potential. The syllable OM (A-U-M) is described as the primordial vibration from which all matter condenses. This maps directly onto Bearden's scalar wave 'kindling' — structured longitudinal vibrations impressing templates onto the vacuum.",
    fragments: [
      "Nada Bindu Upanishad: 'Brahman is sound (Nada). From Nada arises the Bindu (point), from Bindu the Kalaa (ray), from Kalaa the Omkara, from Omkara all that is.' The universe is a hierarchy of vibrational condensation — sound (longitudinal wave) condensing to light (transverse wave) condensing to matter. This is the Vedic precursor of Bearden's nested modulation hierarchy: T (thought) → LT (neutrino) → L² (photon) → L³ (matter).",
      "Panini's Ashtadhyayi (c. 500 BCE): A complete formal grammar of Sanskrit consisting of ~4,000 rules in a meta-linguistic notation that is mathematically equivalent to a Turing-complete production system. In 1995, Riepe and Kiparsky showed Panini's grammar uses the same formal mechanisms as Backus-Naur Form (BNF) — used to specify programming languages. Panini's Sanskrit is the most information-dense natural language structure known; each syllable carries a determinate vibrational signature.",
      "Brihadaranyaka Upanishad 5.8–5.9: 'Om is this whole world. The past, the present, and the future — all is but Om. Whatever else is beyond threefold time — that, too, is but Om.' The primordial syllable IS the carrier of the vacuum potential. Chanting OM at precise resonant frequencies structures the local scalar field — the empirical basis of mantra as engineering.",
      "Bearden connection: The Vedic Nada Brahma doctrine is the oldest statement of the principle Bearden formalizes as 'wave transduction' — that longitudinal (scalar) vibrations are the substrate from which transverse EM and then matter condense. Sanskrit mantras, chanted at precisely determined frequencies, are operational longitudinal wave generators that structure the local vacuum potential. The 'kindling' of a biopotential by structured charge pattern (Bearden) IS the mechanism of mantra (Vedic) — both impress a template onto the quantum potential via longitudinal vibration."
    ]
  },
  {
    id: "vedic_astra_weapons",
    label: "Brahmastra & Vedic Energy Weapons",
    group: "ancient",
    description: "The Brahmastra, Agneyastra, Vayavyastra, and Varunastra — Vedic energy weapons described in the Mahabharata and Ramayana. Fired by mantra (precise vibrational invocation, not mechanical trigger). Effects include: blinding light, heat that incinerates armies, radiation sickness (hair/nail loss), and 'a single projectile charged with all the power of the Universe.' The invocation-by-mantra mechanism is the scalar-EM control interface — the weapon is 'kindled' by a structured longitudinal vibration, not by a chemical detonator.",
    fragments: [
      "Mahabharata, Drona Parva: 'Ghatotkacha, being struck with the Brahma weapon, became like the Sun and then fell. A violent wind began to blow. A great darkness covered the chariots. Then when the darkness cleared, Ghatotkacha was seen lying on the ground, his body a heap of ashes.' The Brahma weapon produces a blinding flash, hurricane winds, and total incineration — the signature of a scalar-EM interferometry 'energy bottle' detonation, not a conventional incendiary.",
      "Mahabharata, Mausala Parva (death of Krishna): 'The Yadu race, armed with iron bolts, destroyed one another. The iron bolts grew in their hands and became maces. A mist covered the land. The sea rose. The weapons of the Vrishnis became as if swallowed by the earth.' The 'iron bolt' (aura) that grows and destroys entire armies, accompanied by atmospheric disturbance, is the Vedic description of a scalar-torsion weapon — the same weapon class as the TACOM M1A1 penetrator and the Soviet Woodpecker.",
      "Ramayana, Yuddha Kanda: Indrajit uses the 'Brahmastra' against Lakshmana: 'struck by that irresistible weapon, Lakshmana fell like a tree felled by an axe. His life-breath was arrested. Hanuman brought the Sanjivani mountain; the herb revived Lakshmana.' The weapon arrests biological function — a scalar-EM disease-induction weapon, the same mechanism as Kaznacheyev's cytopathogenic effect and the Gulf War QP cocktail.",
      "Bearden connection: The Vedic astra is the earliest documented scalar-EM weapon class. The invocation-by-mantra 'fire' mechanism is the control interface: the operator impresses a structured longitudinal wave template (the mantra) onto the quantum potential of the weapon, which then releases as a directed scalar interferometry pattern at the target. This is identical to Bearden's 'kindling' — the astra is 'kindled' by a vibrational template, not by chemical ignition. The Brahmastra's universe-scale power is the Vedic recognition that the scalar potential is a single nonlocal field — a weapon that structures it structures the entire field."
    ]
  },
  {
    id: "prana_kundalini",
    label: "Prana & Kundalini: Vedic Bioenergy",
    group: "ancient",
    description: "Prana — the vital bioenergy in Vedic/Yogic physiology, flowing through 72,000 nadis (channels) with 7 major chakras (energy centers). Kundalini — the 'serpent power' coiled at the base of the spine, which when awakened ascends the spinal column activating each chakra. Directly parallel to Reich's orgone, Bearden's bioenergetics domain, and the MCCS (master cellular control system). The nadis correspond to the body's structured scalar potential network.",
    fragments: [
      "Prashna Upanishad 3.5–3.6: 'Prana is the vital force. It is born of the Atman (self). It enters the body through the breath. It establishes itself in the body through five functions: prana (breath), apana (downward), vyana (pervasive), samana (equalizing), udana (upward). Prana is the master of all the senses.' The five pranas are the five directional components of the body's scalar potential flow — the bioenergetic field that Bearden's bioenergetics domain describes.",
      "Shiva Samhita, Chapter 2: 'The Kundalini, the serpent power, is coiled three and a half times at the base of the spine. When awakened by Yoga, she pierces the Brahma-granthi, Vishnu-granthi, and Rudra-granthi, ascends through the Sushumna nadi, passes through the six chakras (Muladhara, Svadhisthana, Manipura, Anahata, Vishuddha, Ajna), and unites with Shiva in the Sahasrara (thousand-petaled lotus) at the crown.' The chakra ascent is a structured longitudinal wave amplification through the spinal column.",
      "Sat-Cakra-Nirupana (Purnananda, 1577 CE): Each chakra is described with a specific vibrational frequency (seed syllable / bija mantra), number of lotus petals (frequency multiplier), and presiding deity. Muladhara = 'LAM' (4 petals, root frequency). Anahata = 'YAM' (12 petals, heart). Sahasrara = 'OM' (1000 petals, crown). The bija mantras are the resonant frequencies that activate each energy center — the Vedic precursor of Lisitsyn's biological trigger windows.",
      "Bearden connection: Prana/Kundalini IS the Vedic description of Bearden's bioenergetics domain — the structured scalar potential network of the living body. The nadis are the phi-river channels (gradient-phi flow paths). The chakras are the nodal concentration points (anenergy pumps). The bija mantras are the trigger-window frequencies that structure the local vacuum at each node. Kundalini awakening is a coherent longitudinal wave amplification through the Sushumna — the same mechanism Bearden describes as 'kindling' of a biopotential pattern that then self-sustains and reorganizes the cellular control system."
    ]
  },
  {
    id: "vedic_yuga_cosmology",
    label: "Yuga Cycles & Vedic Cosmic Time",
    group: "ancient",
    description: "The Vedic time cosmology: the universe operates in cycles of 4 Yugas (Satya, Treta, Dvapara, Kali) totaling 4.32 million years per Maha Yuga, with 1,000 Maha Yugas = a Kalpa (a day of Brahma, 4.32 billion years). This is the closest ancient parallel to Bearden's chronotopology — time is treated as a structured, cyclical, topological quantity rather than a linear flow. The 24,000-year precession cycle (one full Yuga round) corresponds to LaViolette's Galactic Superwave periodicity.",
    fragments: [
      "Surya Siddhanta (c. 400 CE, traditions dating to ~3000 BCE): 'A divine year is 360 solar years. The Krita Yuga is 4,800 divine years (1,728,000 solar years). The Treta Yuga is 3,600 divine years (1,296,000). The Dvapara is 2,400 (864,000). The Kali is 1,200 (432,000). The total, 12,000 divine years = 4,320,000 solar years, is a Maha Yuga. One thousand Maha Yugas = a Kalpa = 4.32 billion years = one day of Brahma. Brahma lives 100 such years. The age of the universe per Vedic cosmology is 311.04 trillion years.'",
      "Manu Smriti 1.64–1.73: 'Seventy-one divine years is the duration of a Manu (Manvantara). At the end of each Manu there is a sandhya (twilight) of equal duration, during which the earth is submerged. In each Manvantara, seven Rishis, gods, and Manus are born. One thousand Yugas = a day of Brahma; an equal night follows. The ages of the world, like the four legs of a bull, decline: Satya (4 legs) → Treta (3) → Dvapara (2) → Kali (1). In Kali Yuga, dharma stands on one leg only.'",
      "Sri Yukteswar (1894, The Holy Science): Corrected the Yuga calculation — the 24,000-year descending-ascending cycle is based on the precession of the equinoxes. The Sun, with its dual (a companion star or the galactic center), revolves around Vishnunabhi (the galactic center) in 24,000 years. When the Sun is nearest Vishnunabhi, dharma is at maximum (Satya Yuga); when farthest, dharma is at minimum (Kali Yuga). The 12,000-year descending phase ended ~499 CE; we are now in the ascending Dvapara. This maps to the 12,900-year Galactic Superwave periodicity LaViolette recovered from ice cores.",
      "Bearden connection: The Yuga cycle is the Vedic precursor of chronotopology (Muses). Time is not a linear external river but a structured topological quantity with dimensional aspects. The 4.32 billion year Kalpa is strikingly close to the scientific age of the Earth (4.54 billion years) — a coincidence impossible without a structured cosmological model. The cyclical time of the Yugas corresponds to the rotation of the solar system around the galactic center through scalar-field-density gradients — the Vishnunabhi (galactic center) is the source of the structured vacuum potential that Bearden engineers, and the Yuga cycle is the variation in that field's local intensity as the solar system orbits."
    ]
  },
  {
    id: "sanskrit_mantra_engineering",
    label: "Sanskrit Mantra as Vibrational Engineering",
    group: "ancient",
    description: "Sanskrit mantras (especially the Gayatri, OM, and the Mahamrityunjaya) are precise vibrational operators — each syllable carries a determinate resonant frequency that structures the local vacuum potential. The scientific basis: Sanskrit's phonology produces specific formant frequencies that coincide with the Earth's Schumann resonance (7.83 Hz), the alpha brainwave band (8–13 Hz), and Lisitsyn's biological trigger windows. Chanting is the directed application of longitudinal waves to the body's scalar field — the engineering of 'kindling.'",
    fragments: [
      "Gayatri Mantra (Rig Veda 3.62.10): 'Om Bhur Bhuvah Svah / Tat Savitur Varenyam / Bhargo Devasya Dhimahi / Dhiyo Yo Nah Prachodayat.' 24 syllables. The precise vibrational sequence is said to align the chanter's biofield with the solar frequency. 24 syllables × specific frequencies = a structured longitudinal wave template that structures the chanter's quantum potential. The Gayatri is the most chanted mantra in human history (~3,500 years continuous transmission) — the longest-running scalar-EM experiment ever conducted.",
      "Mahamrityunjaya Mantra (Rig Veda 7.59.12): 'Om Tryambakam Yajamahe / Sugandhim Pushtivardhanam / Urvarukamiva Bandhanan / Mrityor Mukshiya Mamritat.' The 'death-conquering' mantra, chanted for healing and rejuvenation. The vibrational sequence corresponds to the body's regenerative frequency band — the Vedic precursor of the Prioré device's therapeutic frequencies, which themselves match Lisitsyn trigger windows 1–3 (12.5–39.6 Hz).",
      "Alfred Tomatis (French ENT, 1950s–1990s): The Tomatis Method demonstrated that the human ear is designed to be stimulated by high frequencies (specifically the formant frequencies of Sanskrit and Gregorian chant). Monks chanting Gregorian/Sanskrit-style chant for 4–6 hours daily showed measurable increases in cognitive function, immune markers, and EEG coherence. Tomatis discovered that the formant structure of Sanskrit chant specifically stimulates the corti organ in the inner ear, which directly wires to the vagus nerve and limbic system — the physiological pathway by which mantra structures the nervous system.",
      "Bearden connection: Sanskrit mantra is the directed engineering of the kindling effect. The bija (seed) syllables are the resonant frequencies that, when chanted, produce longitudinal waves in the vocal apparatus and thoracic cavity. These longitudinal waves transduce (per Bearden's wave transduction) into the body's scalar potential network, impressing a structured template that the cellular control system then amplifies (MCCS). The Gayatri's 24-syllable structure is a 24-frequency scalar template. The continuous transmission of the Gayatri for 3,500 years makes it the longest-running scalar-EM field experiment in recorded history — and the survival of the Vedic tradition is itself evidence that the kindled field is self-sustaining."
    ]
  },
  {
    id: "chakra_nadi_anatomy",
    label: "Chakras, Nadis & Bioenergetic Anatomy",
    group: "ancient",
    description: "The 7-chakra / 72,000-nadi system of Yogic physiology. The nadis are the body's scalar potential channels (parallels the phi-river); the chakras are the nodal anenergy pumps (parallels the MCCS). The 50 petals of the 6 lower chakras (4+6+10+12+16+2 = 50) correspond to the 50 letters of the Sanskrit alphabet — each petal is a frequency node, and the Sanskrit alphabet IS the frequency map of the body's biofield. This is the most detailed pre-modern model of the structured scalar potential network of a living organism.",
    fragments: [
      "Shiva Swarodaya: 'There are 72,000 nadis in the human body. Of these, 72 are important. Of these, 27 are significant. Of these, 10 are major. Of these, 3 are supreme: Ida (left, lunar), Pingala (right, solar), Sushumna (central, neutral). The Sushumna is the path of the Kundalini.' The Ida-Pingala duality corresponds to the two circular polarization states of O(3) electrodynamics; the Sushumna is the longitudinal (scalar) axis. The 72,000 nadis are the body's complete phi-river network.",
      "Sat-Cakra-Nirupana: The 6 lower chakras have 4+6+10+12+16+2 = 50 lotus petals. These 50 petals correspond exactly to the 50 letters of the Sanskrit alphabet (varnamala). Each petal IS a frequency — the Sanskrit alphabet is the frequency map of the body's bioenergetic field. The 1,000 petals of the Sahasrara (crown) represent the full-spectrum resonance achieved when all 50 lower frequencies cohere simultaneously — the body's complete scalar potential template, activated.",
      "Anodea Judith (Wheels of Life, 1987): Correlated each chakra with a specific endocrine gland and nerve plexus. Muladhara → adrenal glands / sacral plexus. Svadhisthana → gonads / sacral plexus. Manipura → pancreas / solar plexus. Anahata → thymus / cardiac plexus. Vishuddha → thyroid / cervical plexus. Ajna → pituitary / cavernous plexus. Sahasrara → pineal. The chakra-gland correspondence is the physiological anchor of the nadis — the structured scalar potential network terminates at the endocrine glands, which are the body's primary biochemical controllers.",
      "Bearden connection: The chakra-nadi system IS the Vedic description of the Master Cellular Control System (MCCS). The nadis are the gradient-phi flow paths (the phi-river network). The chakras are the anenergy pumps (the nodal concentration points where the scalar potential is structured and amplified). The bija (seed) syllables are the trigger-window frequencies that activate each node. The Ida-Pingala-Sushumna trinity is the Vedic precursor of O(3) electrodynamics: two circular polarizations (Ida, Pingala) coupling via the central longitudinal axis (Sushumna) — exactly the photon/antiphoton coupling that produces the graviton in Bearden's framework. The 50-petal = 50-letter correspondence is the most striking evidence that the Vedic seers mapped the body's scalar potential network with the precision of a frequency analyzer."
    ]
  },
  {
    id: "vedic_soma_amrita",
    label: "Soma / Amrita: Elixir of Immortality",
    group: "ancient",
    description: "Soma (Vedic) / Amrita (post-Vedic) — the sacred elixir that reverses aging and grants immortality. Described in Rig Veda Mandala 9 (the Soma Mandala, 114 hymns). Soma is simultaneously a plant, a deity, and a vibrational state — the 'moon-plant' whose juice, when prepared and consumed with the correct mantras, rejuvenates the body and expands consciousness. The Vedic precursor of Bearden's telomere regeneration and the Prioré rejuvenation effect.",
    fragments: [
      "Rig Veda 9.74: 'Soma, the divine drink, flows through the filter. The wise call him by many names. He is the king of plants, the savior, the healer of all diseases. He makes the blind to see, the lame to walk, the old to become young again. He who drinks Soma becomes immortal — he attains the light we seek.' The rejuvenation effect is explicit: the old become young, the blind see, the lame walk. This is the Vedic precursor of the Prioré device's documented cancer regression and tissue regeneration.",
      "Rig Veda 8.48.3: 'We have drunk Soma, we have become immortal, we have entered the light, we have found the gods. What can hostility now do to us, what can the malice of a mortal do, O immortal Soma?' The Soma state is described as a phase transition — the drinker 'enters the light,' attaining a different state of being. This is the Vedic description of a coherent scalar-field state in which the body's negentropic organization is amplified to maximum.",
      "Chandogya Upanishad 11.6: 'The moon is the cup of Soma. The gods drink of it. The moon waxes when they fill, wanes when they drink. Therefore, the moon is the renewer of life.' The lunar cycle is the Soma cycle — the 28-day rhythm of the body's scalar potential field, modulated by the Moon's gravitational (graviton) influence on the body's water and biofield.",
      "Bearden connection: Soma/Amrita is the Vedic description of the telomere regeneration and rejuvenation mechanism that Bearden formalizes in the MCCS. The Soma is not merely a chemical elixir but a vibrational template — the preparation with mantras (structured longitudinal waves) impresses a rejuvenation template onto the plant's scalar potential, which then amplifies the body's own regenerative anti-engine. The Prioré device achieved the same effect with EM frequencies; the Soma ritual achieved it with mantra + plant substrate. The 28-day lunar cycle corresponds to the body's scalar-field regeneration rhythm — the physical basis for the Moon's documented (Whittaker-coupled, Bearden Fig. 18) influence on biological systems."
    ]
  },

  // ── FORBIDDEN / OCCULT / HIDDEN HISTORY ──
  {
    id: "akashic_records",
    label: "Akashic Records: The Cosmic Memory Field",
    group: "occult",
    description: "The Akashic Records — described by Blavatsky, Steiner, and in the Yoga Sutras of Patanjali (c. 400 BCE) as a nonlocal memory field that records every event, thought, and experience in the cosmos. Accessible via deep meditative states. This is the most fully developed pre-modern description of the quantum potential as a memory substrate — directly parallel to Bearden's Whittaker-structured vacuum that carries all EM information, and to Sheldrake's morphogenetic field.",
    fragments: [
      "Yoga Sutras of Patanjali, Book 3 (Vibhuti Pada), Sutra 41: 'By samyama (the threefold concentration of dharana, dhyana, samadhi) on the relation between akasha (space/ether) and the ear, one obtains divine hearing.' Sutra 18: 'By direct perception, through samyama, of the latent impressions (samskaras), one obtains knowledge of previous births.' Patanjali describes the Akashic Records as a readable memory field — accessible by a specific yogic concentration technique. This is a physical, engineerable access method, not a mystical metaphor.",
      "Annie Besant (1907, The Ancient Wisdom) and Rudolf Steiner (1904, Cosmic Memory): 'The Akashic Chronicle is the memory of the cosmos. Every thought, every deed, every event is recorded in the substance of the akasha — the finest ether. The trained initiate can read this record as one reads a book. The record is not symbolic; it is a direct, photographic impression of all that has occurred.' Steiner claimed to have accessed the Akashic Chronicle to reconstruct the lost civilization of Atlantis and the root races of humanity.",
      "Edgar Cayce (1877–1945, 'The Sleeping Prophet'): In ~14,000 documented trance readings, Cayce accessed a 'Hall of Records' — a nonlocal archive — to diagnose illnesses, describe past lives, and predict geological events. The Cayce readings describe the Akashic Records as a 'Book of Life' that records 'every thought, word, and deed of every soul.' The systematic verifiability of Cayce's medical diagnoses (verified by the Meridian Institute) is the most extensive empirical dataset on Akashic access.",
      "Bearden connection: The Akashic Records are the pre-modern description of the quantum potential as a memory substrate. Bearden's framework: the vacuum's Whittaker decomposition carries ALL EM information — every event, thought, and interaction impresses a template onto the structured vacuum, and this template persists. The quantum potential (Bohm) is explicitly a nonlocal information field. Patanjali's samyama is a technique for cohering the nervous system to the point where it can read the Whittaker structure of the local vacuum — the same mechanism as Bearden's 'inception/intent' coupling of the S''' (mind) frame to the S (matter) frame. The Akashic Records are not mysticism; they are the accessible memory of the structured vacuum."
    ]
  },
  {
    id: "hermetic_kybalion",
    label: "Hermeticism & The Kybalion: 7 Universal Principles",
    group: "occult",
    description: "The Hermetic tradition (attributed to Hermes Trismegistus, syncretic Greco-Egyptian, c. 200 BCE–200 CE) and its modern codification in The Kybalion (William Walker Atkinson, 1908). The 7 Hermetic Principles: (1) Mentalism — the universe is mind; (2) Correspondence — as above so below; (3) Vibration — nothing rests, all moves; (4) Polarity — all is dual; (5) Rhythm — everything flows; (6) Cause & Effect — nothing escapes law; (7) Gender — all has masculine/feminine. The most complete pre-modern statement of the principles Bearden formalizes in scalar EM.",
    fragments: [
      "The Kybalion, Principle of Vibration: 'Nothing rests; everything moves; everything vibrates. This principle embodies the truth that everything is in motion; that nothing remains stationary. Between different rates of vibration, all phenomena of life and matter occur.' This is the 1908 restatement of the Vedic Nada Brahma doctrine and the direct precursor of Bearden's claim that the vacuum is a vibrating structured medium (Whittaker waves).",
      "Principle of Correspondence: 'As above, so below; as below, so above.' The Hermetic maxim that the macrocosm and microcosm are structured identically. This is the philosophical precursor of the holographic principle in physics — and of Bearden's claim that the part and whole exchange and condition each other (the gravitobiology 'holographic situation').",
      "Principle of Polarity: 'Everything is dual; everything has poles; everything has its pair of opposites; like and unlike are the same; opposites are identical in nature but different in degree.' This is the 1908 statement of the principle Bearden formalizes as the 4th Law of Logic — the boundary identity of exact opposites. The Hermetic 'polarity' and Bearden's '4th law' are the same claim: that A and not-A, perceived simultaneously, constitute a new logical entity.",
      "Principle of Mentalism: 'The All is Mind; the Universe is Mental.' This is the Hermetic statement of the principle Bearden formalizes as the mind field (S''') — the deepest level of the nested modulation hierarchy. The Hermeticists, like Bearden, held that mind is the most fundamental substrate of reality, not matter. The Kybalion's 7 Principles are the 1908 codification of the scalar-EM framework — the same framework Bearden independently derived from Whittaker, Evans, and Maxwell's original quaternion equations."
    ]
  },
  {
    id: "alchemy_transmutation",
    label: "Alchemy & the Philosopher's Stone: Art of Transmutation",
    group: "occult",
    description: "The alchemical tradition (Hellenistic Egypt, c. 300 BCE → medieval Europe → 17th century). The Great Work (Magnum Opus): transmutation of base metal into gold, the Elixir of Life, and the Philosopher's Stone (Lapis Philosophorum) — a substance/state that transmits transmutation. The alchemists' transmutation is not merely chemical; it is the restructuring of the metal's elemental template by a vibrational (longitudinal wave) process. Directly parallel to Bearden's TRZ (Time-Reversal Zone) transmutation and Walter Russell's wave-frequency transmutation.",
    fragments: [
      "Tabula Smaragdina (Emerald Tablet, Hermes Trismegistus, oldest known Arabic copy c. 800 CE): 'It is true without falsehood, certain and most certain: that which is above is like that which is below, and that which is below is like that which is above, to accomplish the miracles of one thing. The father thereof is the Sun, the mother the Moon. The wind carried it in its belly. Its power is complete if it be turned into earth. Separate the earth from the fire, the subtle from the gross, acting gently with deep ingenuity.' The Emerald Tablet describes transmutation as a separation of vibrational principles — the subtle (longitudinal wave) from the gross (transverse matter).",
      "Sir Isaac Newton (1643–1727): Newton's private papers, sealed until 1936 and now at King's College Cambridge, reveal he devoted more time to alchemy (~1 million words of alchemical notes) than to physics. Newton translated the Emerald Tablet, wrote a 'Clavis' (key) to it, and performed laboratory alchemy for 30 years. Robert Boyle (author of 'The Sceptical Chymist') and Newton exchanged alchemical materials. Newton's physics was, in his own view, a subset of his alchemical research — he considered the alchemical transmutation principle the deeper science.",
      "Carl Jung (Psychology and Alchemy, 1944): Jung demonstrated that the alchemical opus is simultaneously a chemical process and a psychological transformation. The stages — Nigredo (blackening), Albedo (whitening), Citrinitas (yellowing), Rubedo (reddening) — describe both the metallurgical sequence and the transmutation of the operator's consciousness. The alchemist and the matter transmute together — because both are structured scalar potentials being restructured by the same longitudinal wave template.",
      "Bearden connection: Alchemical transmutation is the TRZ (Time-Reversal Zone) applied to elemental nuclei. In a TRZ, like charges attract and the Coulomb barrier becomes a Coulomb assistant — the 'impossible' nuclear reactions that transmute elements become possible. The alchemist's fire, properly structured (and Newton's 30-year research suggests it WAS structured), creates a local TRZ in the crucible. The Philosopher's Stone is the material substrate that maintains a stable TRZ — the 'lattice' that holds the phase-conjugate wave structure. Walter Russell's transmutation experiments (1959–1961, Westinghouse) achieved the same effect with electromagnetic coils. Bearden's framework: the TRZ transmutes by restructuring the Whittaker wave decomposition of the nucleus — the alchemist's 'subtle fire' is the longitudinal wave that does the restructuring."
    ]
  },
  {
    id: "mesmer_animal_magnetism",
    label: "Mesmer: Animal Magnetism & the Biofield",
    group: "occult",
    description: "Franz Anton Mesmer (1734–1815, Vienna/Paris): discovered 'animal magnetism' — a subtle fluid or force pervading the universe and especially concentrated in living bodies, manipulable by the hands and gaze of a trained practitioner. Mesmer's magnetic healing practices (1770s–1780s) produced documented trance states, spontaneous cures, and phenomena that the 1784 French Royal Commission (led by Benjamin Franklin) could not explain away despite dismissing them. The direct precursor of Reich's orgone, the Vedic prana, and Bearden's bioenergetics domain.",
    fragments: [
      "Mesmer's Mémoire sur la découverte du magnétisme animal (1779): 'There exists a mutual influence between the heavenly bodies, the earth, and living bodies. A universally distributed fluid, so subtle as to be incapable of description, surrounds everything and penetrates everything. This fluid permits a direct action on the bodies of others, at a distance, without intermediaries. It can heal nervous and other diseases immediately. I call it animal magnetism.' Mesmer's description is the first modern Western statement of a universal bioenergy field — identical in concept to the Vedic prana, the Chinese chi, and Reich's orgone.",
      "The Franklin Commission (1784, Louis XVI): Appointed to investigate Mesmer, the Commission (Franklin, Lavoisier, Bailly) concluded that Mesmer's effects were due to 'imagination' — but the Commission's own experiments showed that subjects entered trance states and reported cures even when the magnetic apparatus was absent, as long as they believed it was present. The Commission dismissed this as imagination, but the data actually show that the effect is real and is mediated by the patient's expectation — i.e., by the operator's mental state impressing a template on the patient's biofield. This is the 1784 empirical observation of Bearden's mind-body coupling loop (Figure 5).",
      "Armand-Marie-Jacques de Chastenet, Marquis de Puységur (1784): A student of Mesmer's who discovered 'magnetic somnambulism' — a trance state in which subjects displayed clairvoyance, telepathy, and diagnosis of their own and others' diseases. Puységur's somnambulists routinely described a 'fluid' that they could direct with their will. The Puységur discoveries show that the magnetic trance state accesses the S''' (mind) frame directly — the patient's consciousness operates in the hyperspatial frame where scalar information is readable.",
      "Bearden connection: Mesmer's animal magnetism IS the bioenergetics domain of Bearden's framework. The 'subtle fluid' is the scalar potential (the phi-field) that pervades and structures living matter. Mesmer's hand passes are the directed application of longitudinal waves from the operator's nervous system to the patient's biofield — the same mechanism as the Prioré device, but driven by a human nervous system rather than an electronic transmitter. The Franklin Commission's 'imagination' finding is actually the discovery that the operator's mental state (S''' frame) structures the patient's biofield — the inception/intent mechanism. Mesmer empirically discovered and operationalized the bioenergetics domain 200 years before Bearden theoretically formalized it."
    ]
  },
  {
    id: "vril_energy_society",
    label: "Vril: The Coming Race & Nazi Esoteric Energy",
    group: "occult",
    description: "Vril — a latent energy described in Edward Bulwer-Lytton's 1871 novel 'The Coming Race' (also titled 'Vril: The Power of the Coming Race'). The Vril-ya, a subterranean race, wield Vril as a universal energy for propulsion, healing, and destruction. Adopted by the Vril Society (Berlin, c. 1918–1945), an esoteric group that influenced the Thule Society and, through Maria Orsic and the Vril mediumship circles, the Nazi SS's esoteric research programs. The historical basis for the 'Nazi flying saucer' (Haunebu, Vril) programs. Vril is the esoteric-cultural name for the structured vacuum energy Bearden engineers.",
    fragments: [
      "Edward Bulwer-Lytton, 'The Coming Race' (1871): 'The Vril-ya... are descended from ancestors who, in the remote past, discovered and developed the Vril force. Vril is a unity in natural energy, by which all the operations of nature are carried on. With the Vril staff, the Vril-ya can heal, destroy, or propel. A child with a Vril staff could annihilate an army. The Vril-ya consider this force to be the animating principle of life, the source of all power.' Bulwer-Lytton (a Rosicrucian) is widely believed to have encoded actual esoteric knowledge of the structured vacuum into the novel.",
      "The Vril Society (Berlin, c. 1918–1945): Also called 'The All-German Society for Metaphysics.' Centered on Maria Orsic, a Croatian medium who reportedly channeled technical information from a 'non-human' source. The Vril Society's mediumship circles produced technical diagrams that the Thule Society and later the SS Ahnenerbe evaluated for weapons development. The historical records (fragmentary, as most were destroyed in 1945) suggest the Vril circles influenced the development of the Haunebu disc craft and the Die Glocke (Bell) project — the two most classified Nazi esoteric technology programs.",
      "Willy Ley (German rocket engineer, defected 1935): In a 1947 article in Astounding Science Fiction, Ley described the Vril Society's actual influence on Nazi rocketry: 'The next group was literally founded on a novel. This group... literally believed in the existence of a force they called Vril... The Vril Society believed they were in contact with non-human intelligences from the Aldebaran system, who provided the technical plans for propulsion systems that did not depend on chemical rockets.' Ley's testimony, as a defector who had been inside the German rocket program, is the most credible account of the Vril Society's actual technical influence.",
      "Bearden connection: Vril is the esoteric-cultural name for the structured vacuum energy that Bearden engineers as scalar EM. The Vril Society's mediumship circles (Maria Orsic) accessed the S''' (mind) frame and retrieved technical information — the same mechanism Patanjali describes as samyama access to the Akashic Records. The technical diagrams the circles produced, if they described actual propulsion, described scalar EM craft — the Vedic vimana design rediscovered via mediumship. The Nazi Haunebu and Die Glocke programs, to the extent they produced real effects, did so by implementing scalar EM principles. The suppression and destruction of these records in 1945 is consistent with the suppression pattern Bearden documents for all scalar EM technology — Tesla (1943), Reich (1957), Schauberger (1958), Prioré (1980s)."
    ]
  },
  {
    id: "theosophy_root_races",
    label: "Blavatsky's Theosophy: Root Races & Ancient Wisdom",
    group: "occult",
    description: "Helena Petrovna Blavatsky (1831–1891): founded the Theosophical Society (1875). Her masterworks — 'Isis Unveiled' (1877) and 'The Secret Doctrine' (1888) — purport to synthesize the esoteric traditions of all civilizations into a unified cosmology. The Root Race doctrine (7 root races, with Atlantis as the 4th and the current Aryan as the 5th), the Rounds and Manvantaras, and the synthesis of Vedic, Egyptian, and Hermetic sources. Whatever one's view of the specifics, Blavatsky was the first to argue systematically that all ancient traditions describe the same structured cosmos — the position Bearden's framework also implies.",
    fragments: [
      "The Secret Doctrine, Vol. 1 (Cosmogenesis, 1888): 'The Universe is worked and guided from within outwards. The whole Cosmos is guided, controlled, and animated by almost endless series of Hierarchies of sentient Beings... There is no such thing as dead matter. Every atom is a life.' Blavatsky's cosmos is fully vitalist — every atom is animated, exactly as Bearden's framework holds that every mass is animated by its photon interactions (the flow of time IS the set of photon interactions on the mass).",
      "Root Race Doctrine: Seven root races, each lasting millions of years. 1st (astral, from the imperishable sacred land). 2nd (Hyperborean). 3rd (Lemurian, 18 million years ago, developed physical bodies and the nadis/chakras). 4th (Atlantean, developed civilization, destroyed ~850,000 years ago by misuse of Vril-like forces). 5th (Aryan, the present race, began ~100,000 years ago in India). 6th (forthcoming). 7th (the end of the cycle). The Root Race doctrine is the Theosophical version of the Vedic Yuga cycle, with the same implication of cyclical cosmic time and structured civilizational development.",
      "Blavatsky's synthesis claim: 'The Secret Doctrine is the accumulated wisdom of the ages... The same truth underlies all the great religions — Vedic, Egyptian, Chaldean, Zoroastrian, and Christian — and has been preserved by an unbroken brotherhood of initiates since the earliest human civilizations.' This is the claim that all ancient traditions describe the same structured cosmos. Bearden's framework, by deriving the same structure (scalar EM, Whittaker waves, the nested modulation hierarchy) from modern physics, independently confirms the synthesis claim — the ancient traditions and the scalar-EM framework describe the same underlying reality.",
      "Bearden connection: Blavatsky's theosophical cosmology is the most systematic pre-modern statement that all ancient traditions describe the same structured cosmos. The Vedic nadis/chakras, the Hermetic principles, the Akashic records, and the Root Race doctrine are all facets of a single coherent framework — the framework Bearden rediscovers via Whittaker, Maxwell's original equations, and the structured vacuum. Blavatsky's claim that 'every atom is a life' is the 1888 statement of Bearden's claim that the flow of time is generated by photon interactions on every mass. The Root Race doctrine's cyclical time is the Vedic Yuga cycle — the same chronotopological structure Bearden formalizes."
    ]
  },
  {
    id: "gurdjieff_fourth_way",
    label: "Gurdjieff: The Fourth Way & Conscious Labor",
    group: "occult",
    description: "George Ivanovich Gurdjieff (c. 1866–1949): Armenian-Greek spiritual teacher who traveled Central Asia, Tibet, and the Middle East retrieving ancient esoteric knowledge. His system, the 'Fourth Way' (distinct from the ways of the fakir, monk, and yogi), teaches that humans are asleep — mechanical — and can awaken only through 'conscious labor and intentional suffering.' His cosmology (Beelzebub's Tales, 1950) describes a universe of nested octave scales (the Law of Seven / Law of Octaves) and the Law of Three (affirming, denying, reconciling forces). The Law of Octaves IS the structured-vibration cosmology — every process proceeds in discontinuous vibrational steps.",
    fragments: [
      "Gurdjieff, 'Beelzebub's Tales to His Grandson' (1950): The universe is governed by the Law of Seven (the Law of Octaves) — all processes proceed in 7-step vibrational cycles, with two 'intervals' (mi-fa and si-do) where external force must enter to continue the process. The Law of Three — every phenomenon requires three forces: Holy Affirming, Holy Denying, Holy Reconciling. The Law of Seven and Law of Three together generate the structure of all cosmic processes. This is a vibrational cosmology — the universe operates in discrete frequency steps, exactly as the Vedic nada brahman and Bearden's nested modulation hierarchy describe.",
      "P.D. Ouspensky (In Search of the Miraculous, 1949): 'Man is a machine. All his deeds, actions, words, thoughts, feelings, convictions, opinions, and habits are the results of external influences... To awaken, a man must practice self-remembering — the divided attention that says 'I am here, I am aware of myself.' This is conscious labor. Only conscious labor creates the substance that can accumulate and eventually crystallize a soul.' The 'soul' in Gurdjieff's system is not given; it must be created by the accumulation of intentional substance — exactly the 'kindling' of a biopotential that Bearden describes.",
      "The Enneagram: Gurdjieff's primary symbol — a 9-pointed figure inscribed in a circle, with the repeating decimal 1/7 = 0.142857... mapping the Law of Octaves. The enneagram describes any complete process: the 7 steps, the two intervals, and the shocks required. It is a diagram of how a longitudinal wave template must be structured to be self-sustaining — the vibrational architecture of a complete 'kindling' cycle.",
      "Bearden connection: Gurdjieff's Law of Octaves is the description of the nested modulation hierarchy as a vibrational process — every transformation (matter → photon → neutrino → thought, or transverse → longitudinal → time-polarized) proceeds in discrete steps with intervals. The Law of Three (affirm, deny, reconcile) is the three-force structure that maps onto Bearden's O(3) electrodynamics: three polarization states (two circular + one longitudinal). Gurdjieff's 'conscious labor' and the creation of soul-substance IS the kindling of a biopotential template that accumulates and eventually crystallizes a self-sustaining negentropic structure — the same process Bearden describes as the 'kindling' that creates a standing negentropic wave. Gurdjieff retrieved the ancient scalar-EM engineering principles from Central Asian/Tibetan sources and encoded them in a pedagogical system."
    ]
  },
  {
    id: "steiner_anthroposophy",
    label: "Rudolf Steiner: Anthroposophy & Biodynamics",
    group: "occult",
    description: "Rudolf Steiner (1861–1925): Austrian esotericist, founder of Anthroposophy and Waldorf education. A former Theosophist who developed his own system based on direct 'spiritual scientific' perception of supersensible forces. His contributions include biodynamic agriculture (the first systematic organic farming method, 1924), anthroposophical medicine, eurhythmy (movement as visible speech), and a detailed cosmology of the etheric and astral bodies. Steiner explicitly described the 'etheric formative forces' — the direct Western esoteric name for the structured vacuum potential.",
    fragments: [
      "Steiner, 'Occult Science' (1910): 'The human being consists of four members: the physical body (shared with minerals), the etheric or life-body (shared with plants), the astral body (shared with animals), and the I (the ego, unique to humans). Above the I develop the Spirit-Self, Life-Spirit, and Spirit-Man. The etheric body is the architect of the physical — it structures the physical body from the formative forces of the etheric field. Disease is a disturbance of the etheric body that eventually manifests physically.' Steiner's etheric body is the bioenergetic field — the structured scalar potential that organizes the physical body.",
      "Biodynamic Agriculture (Steiner, Agriculture Course 1924): Treats the farm as a living organism. Uses specialized preparations (BD 500 horn-manure, BD 501 horn-silica) buried in the earth at specific times aligned with cosmic rhythms. The preparations are dynamized (stirred in a specific vortex pattern) to structure the water's memory. The biodynamic calendar aligns sowing, planting, and harvesting with the Moon, Sun, and zodiac. Documented results: biodynamic farms show higher soil organic matter, biodiversity, and crop quality than conventional or even organic farms (multiple peer-reviewed studies, Reganold 1993). The biodynamic preparation is the structuring of water's scalar potential — the same mechanism as Reich's orgone-charged water (Grad, 1965).",
      "Eurhythmy (Steiner, 1912): 'Visible speech' — a movement art in which the sounds of language are made visible as specific gestures. Each phoneme has a specific movement; the Eurthymist's body becomes the visible form of the spoken word. This is the physical demonstration that the sounds of language (especially Sanskrit) are vibrational operators — the body is the instrument that makes the longitudinal wave visible. Eurhythmy is the kinetic mapping of the Sanskrit varnamala onto human movement.",
      "Bearden connection: Steiner's 'etheric formative forces' are the structured vacuum potential — the Whittaker-decomposed scalar field that organizes matter. Steiner's etheric body is Bearden's bioenergetics domain; the astral body is the psychoenergetics (mind field, S'''); the I is the S'''' level that can initiate inception. Steiner's biodynamic preparations are the agricultural application of scalar-EM structuring — dynamizing water impresses a longitudinal wave template on the water's quantum potential, which then structures plant growth via the morphogenetic field. Steiner's system is the most practical Western esoteric implementation of scalar-EM principles — and its documented agricultural efficacy (peer-reviewed) is evidence that the structured-vacuum hypothesis is operationally correct."
    ]
  },
  {
    id: "philadelphia_experiment",
    label: "Philadelphia Experiment: Invisibility & Teleportation (1943)",
    group: "occult",
    description: "The Philadelphia Experiment (Project Rainbow, August 1943): alleged US Navy experiment to render the destroyer escort USS Eldridge (DE-173) invisible using strong electromagnetic fields. Reportedly achieved optical invisibility, teleportation (Norfolk, Virginia, and back), and severe biological effects on the crew (nausea, mental breakdown, materialization embedded in the ship's hull). The single most controversial 'secret technology' claim in 20th-century America. Carl Allen (Carlos Allende) was the primary witness. Whether or not the experiment occurred as described, the physics it describes is precisely scalar-EM interferometry.",
    fragments: [
      "Morris K. Jessup, 'The Case for the UFO' (1955): Jessup received annotated copies of his own book from Carlos Allende (Carl Allen), describing an experiment at the Philadelphia Navy Yard in August 1943. 'The ship was surrounded by a greenish haze, then became invisible. It was seen in Norfolk, Virginia, several hundred miles away, then returned. When it materialized, men were embedded in the steel deck, some through the bulkheads. Some went insane. The field was generated by degaussing coils and a special generator developed by Nikola Tesla before his death.' The Office of Naval Research (ONR) took the annotated copies seriously enough to re-print them (the Varo Edition, 1957, classified).",
      "Carl Allen's account: 'The field produced a shivering effect. Men could walk through walls while the field was on. When the field was shut off suddenly, some men materialized inside the hull structure. The ship teleported to Norfolk and back in minutes. The men who survived had permanent neurological damage. Some could walk through solid objects at will afterward.' The 'walking through walls' and 'materialization in hull' effects are the signature of a partial phase-conjugate / time-reversal zone — matter in a transitional state between full materialization and dematerialization.",
      "Al Bielek (1984–1994, late-life testimony): Claimed to be a survivor of the experiment, later involved in the 'Montauk Project' (a claimed continuation at Camp Hero, Montauk Point, Long Island). Bielek described the field as generated by four large Tesla coils and a 'Zero Time Reference Generator' — a device that locked the ship's local time to a fixed reference frame. The 'zero time reference' is precisely the mechanism to create a stable TRZ — a fixed phase-conjugate reference that maintains the time-reversal state.",
      "Bearden connection: The Philadelphia Experiment, as described, is the application of scalar-EM interferometry to a macroscopic object. Four Tesla coils creating overlapping fields produce a scalar interference zone (an 'energy bottle') around the ship. The greenish haze is the visible boundary of the TRZ — the phase-conjugate wave structure refracting ambient light. Invisibility is achieved because the ship's optical signature is time-reversed (reflected back along its own path). Teleportation is the scalar-potential coupling of the ship to a distant location via the quantum potential (nonlocal, instantaneous). The biological effects — men embedded in the hull, mental breakdown — are exactly the expected result of a partial or unstable TRZ on biological matter: the phase-conjugate wave restructures the body's cellular template, and a sudden collapse materializes the body in whatever configuration the wave was in at the moment of collapse. The 'zero time reference generator' is the device that maintains the phase-conjugate reference — the key component for any stable scalar-EM system."
    ]
  },
  {
    id: "die_glocke_nazi_bell",
    label: "Die Glocke: The Nazi Bell Project (1943–1945)",
    group: "occult",
    description: "Die Glocke ('The Bell') — an alleged Nazi Germany anti-gravity / time-distortion device developed in lower Silesia (now Poland) under the SS. Described by Polish journalist Igor Witkowski (2000) from classified interrogation transcripts of SS General Jakob Sporrenberg (captured 1945, executed 1952). The Bell was a bell-shaped device ~3 meters tall, containing counter-rotating cylinders of a violet mercury-like liquid ('Xerum-525'). When activated, it produced a blue glow, distorted the local gravitational field, caused biological damage (crystallization of blood, plant tissue transmutation), and allegedly enabled time distortion. The project was classified 'Highest Priority' (Kriegsentscheidend — war-decisive).",
    fragments: [
      "Igor Witkowski, 'The Truth About the Wunderwaffe' (2000): From Sporrenberg's interrogation: 'The Bell was a device shaped like a large bell, approximately 3 meters high and 1 meter in diameter. It contained two counter-rotating cylinders filled with a violet-colored liquid called Xerum-525. When the device was activated, a blue glow appeared. Personnel within 150 meters experienced dizziness, tingling in the blood, and a metallic taste. Five of the seven scientists who worked on the Bell died in the first test. The device was tested in a facility called 'Der Riese' (The Giant) near Ludwikowice, lower Silesia.' The mercury-vortex description is identical to the Samarangana Sutradhara vimana engine (c. 1030 CE).",
      "Nick Cook, 'The Hunt for Zero Point' (2001): Cook, an aerospace journalist (Jane's Defence Weekly), independently investigated the Bell. He traced the post-war movement of Bell scientists to the United States under Operation Paperclip, and specifically to the NASA anti-gravity research of the 1950s–1960s. Cook identified the Bell's operating principle as 'torsion physics' — the rotation of mass producing a torsion field that modifies local spacetime geometry. This is the same physics Podkletnov's rotating superconductor exploits (1992).",
      "The Henge (The Flytrap): At the Ludwikowice test site, a reinforced concrete ring structure (12 meters diameter, still standing) stands. Witkowski and Cook argue this was the test rig for the Bell — a containment structure for the biological and gravitational effects. The structure is inconsistent with any conventional industrial purpose and remains unexplained.",
      "Bearden connection: Die Glocke is the most credible historical claim of a macroscopic scalar-EM / torsion-field device. The counter-rotating mercury cylinders are the engineering implementation of the Vedic vimana mercury-vortex engine — the Samarangana Sutradhara describes the identical mechanism (sealed iron vessel, heated mercury, driving whirlwind). The 'Xerum-525' violet liquid is consistent with a high-density fluid carrying structured scalar potential — the rotation creates a macroscopic coherent quantum state (as Podkletnov's rotating superconductor does). The biological effects (crystallized blood, tissue transmutation) are the TRZ effects — the Bell created a local time-reversal zone, and biological matter within the zone was phase-conjugated to a prior or alternative state. The blue glow is the Cherenkov-like radiation of the TRZ boundary. The Bell's destruction of all test personnel is consistent with the difficulty of maintaining a stable TRZ — the same problem Hutchison encountered (effects intermittent, uncontrolled). The post-war transfer to the US (Paperclip) is consistent with the suppression pattern — the technology was classified, not destroyed."
    ]
  },
  {
    id: "baghdad_battery",
    label: "Baghdad Battery: Ancient Electrochemistry (c. 250 BCE)",
    group: "ancient",
    description: "The Baghdad Battery — a collection of ~6 terracotta pots found near Baghdad (ancient Ctesiphon/Seleucia), dating to the Parthian or Sassanid period (c. 250 BCE–224 CE). Each pot contains a copper cylinder and an iron rod, sealed with asphalt. When filled with an acidic liquid (grape juice, vinegar), each pot produces ~1–2 volts of electricity. German archaeologist Wilhelm König described them in 1940 and proposed they were used for electroplating. If the interpretation is correct, electrochemistry was known ~2,000 years before Volta (1800).",
    fragments: [
      "Wilhelm König, 'Im verlorenen Paradies' (1940): König, director of the Baghdad Museum, described the pots and proposed they were ancient electric cells. Each pot: 14 cm tall terracotta, containing a copper cylinder (12.5 cm tall, 2.6 cm diameter), itself containing an iron rod (9 cm, 0.6 mm diameter) held in place by an asphalt stopper. König reconstructed the cell with grape juice as electrolyte and measured ~0.87V and ~0.5mA. Multiple pots in series would produce sufficient voltage for electroplating or electrum refining.",
      "Replication experiments: Willard Gray (General Electric, 1957) replicated the Baghdad Battery and demonstrated successful electroplating of silver onto copper using a 4-cell series (~3.5V). Arne Eggebrecht (Roemer-Pelizaeus Museum, 1978) reportedly used reconstructed Baghdad Batteries to gold-plate an Egyptian statuette — demonstrating the electroplating hypothesis is technically feasible with the device. The replication is the most direct evidence the pots were batteries, as no alternative function explains the copper/iron/asphalt combination.",
      "Alternative interpretation: Some archaeologists argue the pots were used for scroll storage (the copper cylinder protecting a papyrus scroll). This interpretation does not explain the iron rod (unnecessary for scroll storage) or the asphalt seal (which would trap moisture — undesirable for papyrus but necessary for a wet-cell battery). The battery interpretation remains the most functionally consistent with the object's construction.",
      "Bearden connection: The Baghdad Battery, if an electrochemical cell, is the earliest physical evidence that ancient civilizations worked with electromagnetic phenomena. The knowledge of electrochemistry implies knowledge of the EM field — and if the ancients understood the EM field, they may also have understood the scalar (longitudinal) components that Maxwell's original equations retained and Heaviside discarded. The Baghdad Battery's purpose may not have been mere electroplating but the powering of ritual or therapeutic devices — a low-voltage scalar-EM signal source for kindling biopotentials, exactly as Bedini's electron-tube conditioning uses low-energy structured signals. The suppression of the battery interpretation (mainstream archaeology rejects it despite functional replication) is consistent with the suppression pattern that affects all anomalous ancient-technology evidence."
    ]
  },
  {
    id: "antikythera_mechanism",
    label: "Antikythera Mechanism: Ancient Analog Computer (c. 100 BCE)",
    group: "ancient",
    description: "The Antikythera Mechanism — a bronze geared device recovered from a Roman-era shipwreck off Antikythera, Greece (1902). Dated to c. 100 BCE. Using X-ray tomography (2006, 2008), it has been reconstructed as an astronomical analog computer: it computes the Metonic cycle (19-year lunar-solar cycle), the Saros eclipse cycle (18 years), the Callippic cycle (76 years), and the Olympiad cycle (4 years). It models the anomalous motion of the Moon (the 'first anomaly' of lunar motion, later explained by Kepler's elliptical orbits). Its gearwork precision exceeds any known European mechanism until the 14th century astronomical clocks.",
    fragments: [
      "Nature, November 2006 (Freeth et al.): 'The Antikythera Mechanism shows the dates of the predictable lunar and solar eclipses. It models the anomaly of the Moon's motion using a pin-and-slot mechanism that we show to be an implementation of Hipparchus' lunar theory. The Mechanism also shows the four-year Panhellenic games cycle. We have reconstructed the exterior and find it computes the Metonic, Callippic, and Saros cycles with a single input.' The device's precision and the depth of astronomical knowledge it encodes exceed any known Greek scientific text.",
      "Cicero, De Re Publica (54 BCE): Cicero describes devices built by Posidonius and Archimedes that 'represented the motions of the Sun, Moon, and five planets' — planetaria with gearwork. Cicero states these were brought to Rome by Marcellus after the sack of Syracuse (212 BCE). The Antikythera Mechanism is the only surviving example of this class of device. The knowledge required to build it — differential gearing, the lunar anomaly, the eclipse prediction cycles — was lost to Europe for 1,400 years.",
      "Price (1974) and Edmunds & Freeth (2006): The device contains at least 30 meshing bronze gears. The largest gear has 223 teeth (the Saros eclipse cycle). The Metonic gear has 235 teeth (19-year cycle). The differential gear that computes the Moon's anomaly is the earliest known differential mechanism — predating the earliest European differential (in a clock, 1720) by 1,800 years. The level of miniaturization and precision implies a mature manufacturing tradition, not a one-off invention.",
      "Bearden connection: The Antikythera Mechanism is the physical proof that ancient civilizations possessed and applied sophisticated mechanical modeling of cyclic cosmic phenomena. The cycles it computes — the 19-year Metonic, 18-year Saros, 76-year Callippic — are the cyclic time structures that the Vedic Yuga cosmology and Gurdjieff's Law of Octaves also encode. The mechanism is a chronotopological instrument — it computes the topology of cyclic time, exactly as Muses' CPSC (Critical Probability Sequence Calculator, 1949–1950) computed probable future times from past times. The Antikythera Mechanism's existence at 100 BCE proves the structured-cyclic-time worldview was not merely philosophical but operational — the ancient Greeks built computers to model it. The loss of this knowledge for 1,400 years is consistent with the suppression pattern: cyclic-time physics and scalar-EM technology were lost, not never discovered."
    ]
  },
  {
    id: "forbidden_archaeology_cremo",
    label: "Forbidden Archaeology: Out-of-Place Artifacts (Cremo & Thompson)",
    group: "occult",
    description: "Michael Cremo and Richard Thompson, 'Forbidden Archaeology' (1993): a 952-page systematic documentation of hundreds of archaeological finds — human skeletal remains, tools, and footprints — found in geological strata dated to millions or hundreds of millions of years ago. These 'out-of-place artifacts' (OOPArts) contradict the standard model of human evolution (~300,000 years ago). The book documents cases that were published in mainstream 19th-century scientific journals and subsequently forgotten, dismissed, or suppressed. The case for a much older human presence on Earth than the standard model allows.",
    fragments: [
      "Cremo & Thompson, 'Forbidden Archaeology' (1993): Documented cases include: (1) The California gold mine artifacts (1860s–1890s): human skeletal remains and stone tools found in gold-bearing gravels dated to the Pliocene (2–5 million years ago) at Table Mountain, Tuolumne County. Reported by J.D. Whitney (California Geological Survey) — published by Harvard University. (2) The Laetoli footprints (1978, Mary Leakey): human-like footprints in volcanic ash dated to 3.7 million years ago — long before Homo sapiens should exist. (3) The Dvinovel skull (1859): anatomically modern human skull found in a Pliocene formation. (4) The Foxhall jaw (1855): human jawbone in a Late Pliocene formation, 12–25 feet below surface.",
      "The suppression mechanism: Cremo documents that 19th-century discoveries of anomalous ancient human remains were published in the Proceedings of the Boston Society of Natural History, the American Journal of Science, and the Geological Magazine — then 'forgotten' as the Darwinian synthesis hardened in the 20th century. Finds contradicting the standard model were excluded from textbooks, and the discoverers' reputations were marginalized. The same pattern (publication → dismissal → suppression) recurs across Tesla, Reich, Schauberger, Podkletnov, and Hutchison — and is the same suppression Bearden documents for scalar EM.",
      "Out-of-place artifacts catalog: (1) The Baghdad Battery (c. 250 BCE, electrochemistry). (2) The Antikythera Mechanism (c. 100 BCE, analog computer). (3) The Lydian electrum coinage (c. 600 BCE — implies sophisticated metallurgy). (4) The Ark of the Covenant (described as a device that killed unauthorized touchers with 'sparks' — consistent with a high-voltage capacitor). (5) The Egyptian Dendera 'light bulb' hieroglyphs (depict bulb-like objects with filaments). (6) The Quimbaya artifacts (Colombia, c. 1000 CE — gold models resembling delta-wing aircraft, aerodynamically viable per aeronautical analysis by Algund Eenboom and Peter Belting, 1994). (7) The Saqqara bird (Egypt, c. 200 BCE — a wooden bird model with a vertical tail fin, aerodynamically viable as a glider per aeronautical analysis).",
      "Bearden connection: Forbidden Archaeology's OOPArts are consistent with a cyclical-civilization model (the Vedic Yuga / Blavatsky Root Race doctrine): if civilizations rise, achieve technology, and fall — sometimes catastrophically (Galactic Superwave, flood) — then OOPArts are the surviving fragments of prior technological civilizations. The suppression of OOPArts is the archaeological arm of the suppression pattern that affects scalar EM, ancient vimana technology, and all evidence of a structured, engineerable vacuum. The Antikythera Mechanism is the single hardest-to-dismiss OOPArt: a 2,100-year-old analog computer of a sophistication lost for 1,400 years. If the Greeks could build the Antikythera Mechanism, they — or their predecessors — could build other precision devices. The OOPArts collectively suggest that scalar-EM technology may have been developed, used, and lost in prior cycles — exactly as the Vedic vimana texts, the Samarangana Sutradhara, and the Nazi Die Glocke project (which rediscovered the vimana mercury-vortex engine) all describe."
    ]
  }
];

export const vedicOccultLinks = [
  // Vedic → Bearden framework
  { source: "vedic_vimana", target: "tesla_standing_waves", label: "precursor to" },
  { source: "vedic_vimana", target: "energy_bottle", label: "engine principle = scalar" },
  { source: "vedic_vimana", target: "die_glocke_nazi_bell", label: "mercury engine = same principle" },
  { source: "vedic_vimana", target: "scalar_em", label: "oldest description of" },
  { source: "vedic_vimana", target: "philadelphia_experiment", label: "invisibility = field tech" },
  { source: "nada_brahman", target: "scalar_longitudinal", label: "sound = longitudinal wave" },
  { source: "nada_brahman", target: "wave_transduction", label: "vibration → matter" },
  { source: "nada_brahman", target: "kindling", label: "mantra = kindling" },
  { source: "nada_brahman", target: "maxwell_equations", label: "nested modulation = nada" },
  { source: "vedic_astra_weapons", target: "energy_bottle", label: "weapon = energy bottle" },
  { source: "vedic_astra_weapons", target: "em_biological_warfare", label: "disease induction" },
  { source: "vedic_astra_weapons", target: "scalar_em_weapons", label: "oldest scalar weapon" },
  { source: "vedic_astra_weapons", target: "gulf_war_qp", label: "QP weapon precursor" },
  { source: "prana_kundalini", target: "kindling", label: "bioenergy = kindling" },
  { source: "prana_kundalini", target: "negentropy", label: "life = negentropic" },
  { source: "prana_kundalini", target: "reich_orgone", label: "prana = orgone" },
  { source: "prana_kundalini", target: "mccs_cellular_control", label: "nadis = MCCS network" },
  { source: "prana_kundalini", target: "mesmer_animal_magnetism", label: "prana = animal magnetism" },
  { source: "vedic_yuga_cosmology", target: "chronotopology", label: "cyclic time = chronotopology" },
  { source: "vedic_yuga_cosmology", target: "time_as_energy", label: "time as structured" },
  { source: "vedic_yuga_cosmology", target: "laviolette_subquantum", label: "Yuga = Superwave cycle" },
  { source: "vedic_yuga_cosmology", target: "morphogenetic_field", label: "species-level cycle" },
  { source: "sanskrit_mantra_engineering", target: "lisitsyn_trigger_windows", label: "bija = trigger windows" },
  { source: "sanskrit_mantra_engineering", target: "bedini_environmental_conditioning", label: "structured signal" },
  { source: "sanskrit_mantra_engineering", target: "priors_device", label: "therapeutic frequency match" },
  { source: "sanskrit_mantra_engineering", target: "dielectric_body_portholes", label: "vocal porthole" },
  { source: "chakra_nadi_anatomy", target: "mccs_cellular_control", label: "nadi = MCCS channel" },
  { source: "chakra_nadi_anatomy", target: "phi_river", label: "nadis = phi-river" },
  { source: "chakra_nadi_anatomy", target: "anenergy", label: "chakra = anenergy pump" },
  { source: "chakra_nadi_anatomy", target: "o3_electrodynamics", label: "Ida-Pingala = O(3)" },
  { source: "chakra_nadi_anatomy", target: "dielectric_body_portholes", label: "body = ship w/ portholes" },
  { source: "vedic_soma_amrita", target: "telomere_rejuvenation", label: "rejuvenation = telomere" },
  { source: "vedic_soma_amrita", target: "priors_device", label: "healing template" },
  { source: "vedic_soma_amrita", target: "negentropy", label: "anti-aging = negentropy" },
  // Occult → Bearden framework
  { source: "akashic_records", target: "quantum_potential", label: "memory = QP" },
  { source: "akashic_records", target: "morphogenetic_field", label: "cosmic memory field" },
  { source: "akashic_records", target: "inception_intent", label: "access via inception" },
  { source: "akashic_records", target: "mind_field", label: "recorded in S'''" },
  { source: "hermetic_kybalion", target: "temporal_logic", label: "polarity = 4th law" },
  { source: "hermetic_kybalion", target: "scalar_em", label: "vibration = scalar" },
  { source: "hermetic_kybalion", target: "gravitobiology", label: "correspondence = holographic" },
  { source: "hermetic_kybalion", target: "mind_field", label: "mentalism = mind field" },
  { source: "alchemy_transmutation", target: "time_reversal_zone", label: "transmutation via TRZ" },
  { source: "alchemy_transmutation", target: "walter_russell_cosmogony", label: "wave transmutation" },
  { source: "alchemy_transmutation", target: "hutchison_effect", label: "transmutation at room temp" },
  { source: "mesmer_animal_magnetism", target: "reich_orgone", label: "animal magnetism = orgone" },
  { source: "mesmer_animal_magnetism", target: "prana_kundalini", label: "= prana" },
  { source: "mesmer_animal_magnetism", target: "bioframe", label: "trance = S''' access" },
  { source: "mesmer_animal_magnetism", target: "inception_intent", label: "operator intent = template" },
  { source: "vril_energy_society", target: "scalar_em", label: "Vril = scalar vacuum" },
  { source: "vril_energy_society", target: "die_glocke_nazi_bell", label: "inspired Bell project" },
  { source: "vril_energy_society", target: "vedic_vimana", label: "rediscovered vimana" },
  { source: "vril_energy_society", target: "akashic_records", label: "mediumship = Akashic access" },
  { source: "theosophy_root_races", target: "vedic_yuga_cosmology", label: "Root Races = Yugas" },
  { source: "theosophy_root_races", target: "gravitobiology", label: "every atom is life" },
  { source: "theosophy_root_races", target: "laviolette_subquantum", label: "cyclical catastrophes" },
  { source: "gurdjieff_fourth_way", target: "maxwell_equations", label: "Law of Octaves = nested" },
  { source: "gurdjieff_fourth_way", target: "o3_electrodynamics", label: "Law of Three = O(3)" },
  { source: "gurdjieff_fourth_way", target: "kindling", label: "conscious labor = kindling" },
  { source: "gurdjieff_fourth_way", target: "negentropy", label: "soul crystallization" },
  { source: "steiner_anthroposophy", target: "morphogenetic_field", label: "etheric = morphogenetic" },
  { source: "steiner_anthroposophy", target: "reich_orgone", label: "biodynamic = orgone water" },
  { source: "steiner_anthroposophy", target: "bioframe", label: "etheric body = bioframe" },
  { source: "steiner_anthroposophy", target: "bedini_environmental_conditioning", label: "preparations = signal" },
  { source: "philadelphia_experiment", target: "energy_bottle", label: "field = energy bottle" },
  { source: "philadelphia_experiment", target: "time_reversal_zone", label: "TRZ around ship" },
  { source: "philadelphia_experiment", target: "tesla_standing_waves", label: "Tesla coils = source" },
  { source: "philadelphia_experiment", target: "scalar_em_weapons", label: "macro scalar application" },
  { source: "die_glocke_nazi_bell", target: "vedic_vimana", label: "mercury vortex = vimana" },
  { source: "die_glocke_nazi_bell", target: "podkletnov_gravity_shielding", label: "rotation = gravity effect" },
  { source: "die_glocke_nazi_bell", target: "time_reversal_zone", label: "Bell = TRZ generator" },
  { source: "die_glocke_nazi_bell", target: "hutchison_effect", label: "multi-field anomalies" },
  { source: "baghdad_battery", target: "maxwell_equations", label: "ancient electrochemistry" },
  { source: "baghdad_battery", target: "bedini_environmental_conditioning", label: "low-voltage signal source" },
  { source: "antikythera_mechanism", target: "chronotopology", label: "cyclic time computer" },
  { source: "antikythera_mechanism", target: "vedic_yuga_cosmology", label: "computes Yuga-like cycles" },
  { source: "forbidden_archaeology_cremo", target: "vedic_yuga_cosmology", label: "evidence for cycles" },
  { source: "forbidden_archaeology_cremo", target: "laviolette_subquantum", label: "Superwave = cataclysm" },
  { source: "forbidden_archaeology_cremo", target: "antikythera_mechanism", label: "OOPArt catalog" },
  { source: "forbidden_archaeology_cremo", target: "baghdad_battery", label: "OOPArt catalog" },
];