import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// NDA document text
const NDA_TEXT = `CONFIDENTIALITY AND NON-DISCLOSURE AGREEMENT

Zenith Apex Research Platform — C.O.D.E.X.T.E.C.H.
Effective Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
Agreement Version: 1.0

PARTIES & SCOPE
This Confidentiality and Non-Disclosure Agreement ("Agreement") is entered into by and between the owner and operator of the Zenith Apex Research Platform ("Disclosing Party") and the individual accessing this platform ("Recipient"). This Agreement governs all content, data, research frameworks, conceptual models, source text fragments, visualizations, business models, pitch materials, and any derivative works contained within or generated by this application ("Confidential Information").

CONFIDENTIAL INFORMATION INCLUDES:
- All annotated research data relating to scalar electromagnetics and gravitobiology
- Original analytical frameworks, concept node structures, and relational graph data
- Business models, pitch deck outlines, revenue projections, and product roadmaps
- Source text fragments, commentary, and interpretive analysis
- Timeline analyses, geopolitical assessments, and technical feasibility studies
- Any AI-generated summaries, expansions, or derivative content produced within this platform
- The platform architecture, data structures, and visual design methodology

OBLIGATIONS OF RECIPIENT:
- Hold all Confidential Information in strict confidence
- Not copy, screenshot, reproduce, publish, share, transmit, or distribute any content from this platform in whole or in part
- Not use any Confidential Information for commercial purposes without express written consent
- Not share access credentials or grant third-party access to this platform
- Not input, upload, or transmit any Confidential Information into any AI system, machine learning model, LLM, or automated data extraction tool
- Immediately notify the Disclosing Party of any unauthorized disclosure or suspected breach
- Return or destroy all Confidential Information upon termination of access

PROHIBITION ON AI INGESTION & AUTOMATED SCRAPING:
No content from this platform shall be input into any AI or LLM system (including ChatGPT, Claude, Gemini, Copilot, or any proprietary model) for training, fine-tuning, or analysis beyond personal use; scraped, crawled, or harvested by any automated bot, spider, or data mining tool; used to create competing datasets, knowledge graphs, or derivative analytical platforms; or transmitted to any third-party AI service, API, or data broker. Violation constitutes unauthorized access under the Computer Fraud and Abuse Act (18 U.S.C. § 1030) and similar international statutes.

INTELLECTUAL PROPERTY:
All platform-original content, including organizational frameworks, analytical commentary, concept graphs, business models, and AI-generated synthesis, is the exclusive intellectual property of the Disclosing Party. Access grants no license, ownership right, or interest in any Confidential Information.

REMEDIES & LIQUIDATED DAMAGES:
- $50,000 per incident of unauthorized disclosure or distribution
- $250,000 per incident of unauthorized AI ingestion or commercial exploitation

TERM & SURVIVAL:
This Agreement is effective upon first access to the platform and remains in effect indefinitely. The confidentiality obligations survive any termination of access. This Agreement shall be governed by the laws of the United States of America.

By signing below, the Recipient confirms they have read, understood, and agree to be legally bound by all terms herein. Electronic acceptance constitutes a valid and binding signature under the Electronic Signatures in Global and National Commerce Act (E-SIGN).

______________________________
Recipient Signature

______________________________
Printed Name

______________________________
Date
`;

async function getDocuSignToken() {
  const integrationKey = Deno.env.get('DOCUSIGN_INTEGRATION_KEY');
  const userId = Deno.env.get('DOCUSIGN_USER_ID');
  const privateKeyPem = Deno.env.get('DOCUSIGN_PRIVATE_KEY');
  const baseUrl = Deno.env.get('DOCUSIGN_BASE_URL') || 'https://account.docusign.com';

  if (!integrationKey || !userId || !privateKeyPem) {
    throw new Error('Missing DocuSign credentials');
  }

  // Build JWT
  const now = Math.floor(Date.now() / 1000);
  const header = { alg: 'RS256', typ: 'JWT' };
  const payload = {
    iss: integrationKey,
    sub: userId,
    aud: baseUrl.replace('https://', '').replace('http://', ''),
    iat: now,
    exp: now + 3600,
    scope: 'signature impersonation',
  };

  const encode = (obj) => btoa(JSON.stringify(obj)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
  const signingInput = `${encode(header)}.${encode(payload)}`;

  // Import RSA private key
  const pemContent = privateKeyPem
    .replace(/-----BEGIN RSA PRIVATE KEY-----/, '')
    .replace(/-----END RSA PRIVATE KEY-----/, '')
    .replace(/-----BEGIN PRIVATE KEY-----/, '')
    .replace(/-----END PRIVATE KEY-----/, '')
    .replace(/\s/g, '');

  const binaryDer = Uint8Array.from(atob(pemContent), c => c.charCodeAt(0));
  const cryptoKey = await crypto.subtle.importKey(
    'pkcs8',
    binaryDer,
    { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' },
    false,
    ['sign']
  );

  const signature = await crypto.subtle.sign(
    'RSASSA-PKCS1-v1_5',
    cryptoKey,
    new TextEncoder().encode(signingInput)
  );

  const sigB64 = btoa(String.fromCharCode(...new Uint8Array(signature)))
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');

  const jwt = `${signingInput}.${sigB64}`;

  // Exchange JWT for access token
  const tokenUrl = `${baseUrl}/oauth/token`;
  const tokenRes = await fetch(tokenUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=${jwt}`,
  });

  if (!tokenRes.ok) {
    const err = await tokenRes.text();
    throw new Error(`DocuSign token error: ${err}`);
  }

  const tokenData = await tokenRes.json();
  return tokenData.access_token;
}

Deno.serve(async (req) => {
  try {
    if (req.method !== 'POST') {
      return Response.json({ error: 'Method not allowed' }, { status: 405 });
    }

    const base44 = createClientFromRequest(req);
    const body = await req.json();
    const { full_name, email, company } = body;

    if (!full_name || !email) {
      return Response.json({ error: 'full_name and email are required' }, { status: 400 });
    }

    const accountId = Deno.env.get('DOCUSIGN_ACCOUNT_ID');
    const baseUrl = Deno.env.get('DOCUSIGN_BASE_URL') || 'https://na4.docusign.net';

    if (!accountId) {
      return Response.json({ error: 'DOCUSIGN_ACCOUNT_ID not configured' }, { status: 500 });
    }

    // Get access token
    const accessToken = await getDocuSignToken();

    // Convert NDA text to base64
    const ndaBase64 = btoa(unescape(encodeURIComponent(NDA_TEXT)));

    // Create envelope with embedded signing
    const appUrl = req.headers.get('origin') || 'https://app.base44.com';

    const envelopeBody = {
      emailSubject: 'Please sign the C.O.D.E.X.T.E.C.H. Non-Disclosure Agreement',
      emailBlurb: `Dear ${full_name}, please sign the attached NDA to access the Zenith Apex Research Platform vault.`,
      documents: [
        {
          documentBase64: ndaBase64,
          name: 'CODEXTECH_NDA.txt',
          fileExtension: 'txt',
          documentId: '1',
        },
      ],
      recipients: {
        signers: [
          {
            email,
            name: full_name,
            recipientId: '1',
            routingOrder: '1',
            tabs: {
              signHereTabs: [
                {
                  documentId: '1',
                  pageNumber: '1',
                  xPosition: '100',
                  yPosition: '700',
                },
              ],
              fullNameTabs: [
                {
                  documentId: '1',
                  pageNumber: '1',
                  xPosition: '100',
                  yPosition: '730',
                },
              ],
              dateTabs: [
                {
                  documentId: '1',
                  pageNumber: '1',
                  xPosition: '100',
                  yPosition: '760',
                },
              ],
            },
          },
        ],
      },
      status: 'sent',
    };

    const apiBase = `${baseUrl}/restapi/v2.1/accounts/${accountId}`;

    const createRes = await fetch(`${apiBase}/envelopes`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(envelopeBody),
    });

    if (!createRes.ok) {
      const err = await createRes.text();
      console.error('DocuSign envelope error:', err);
      return Response.json({ error: 'Failed to create DocuSign envelope', details: err }, { status: 500 });
    }

    const envelope = await createRes.json();
    const envelopeId = envelope.envelopeId;

    // Store pending NDA record
    const ip = req.headers.get('x-forwarded-for') || req.headers.get('cf-connecting-ip') || 'unknown';
    await base44.asServiceRole.entities.NDASignature.create({
      full_name,
      email,
      company: company || 'Not provided',
      signature_data: `docusign_envelope:${envelopeId}`,
      accepted_terms: false, // will be true when DocuSign webhook fires
      ip_address: ip,
      user_agent: req.headers.get('user-agent') || 'unknown',
      signed_at: new Date().toISOString(),
    });

    // Notify admin
    const adminEmail = Deno.env.get('ADMIN_EMAIL') || 'admin@codextech.io';
    await base44.integrations.Core.SendEmail({
      to: adminEmail,
      subject: `📋 NDA Sent for Signature — ${full_name}`,
      body: `NDA signature request sent via DocuSign.\n\nName: ${full_name}\nEmail: ${email}\nCompany: ${company || 'N/A'}\nEnvelope ID: ${envelopeId}\n\nThe signed copy will be stored automatically when they complete signing.`,
    });

    return Response.json({
      success: true,
      envelopeId,
      message: 'NDA sent to your email via DocuSign. Please check your inbox and sign to gain vault access.',
    });
  } catch (error) {
    console.error('sendNdaDocusign error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});