import { Link } from "react-router-dom";
import {
  FileText, Zap, Users, Brain, BarChart3, BookOpen,
  ShoppingBag, Cpu, Video, FlaskConical, TrendingUp, Shield
} from "lucide-react";

const FEATURES = [
  {
    icon: Brain,
    label: "AI Patent Attorney",
    desc: "Chat with an AI attorney trained on 40+ EM patents. Draft provisional applications, independent claims, and FTO analysis in minutes — not months.",
    neon: "#00ccff",
    href: "/patent-attorney-chat",
    badge: "TOP EARNER",
  },
  {
    icon: FileText,
    label: "Invention Dossier Suite",
    desc: "Full IP empire in a click: patent strategy, claims draft, $5M–$150M valuation, 12-month commercialization roadmap. Auto-generated. Ready for investors.",
    neon: "#cc00ff",
    href: "/invention-dossier",
    badge: "BEST VALUE",
  },
  {
    icon: Video,
    label: "Pitch Deck Builder",
    desc: "3D-rendered, investor-grade pitch decks generated by AI. TAM analysis, IP valuation, team bios, competitive moat — slide-ready in under 5 minutes.",
    neon: "#ff6600",
    href: "/pitch-deck-builder",
    badge: "HOT",
  },
  {
    icon: Zap,
    label: "Build Device Plans",
    desc: "21+ electromagnetic device build plans with complete BOMs, schematics, video guides, and step-by-step assembly. From MEG to Kapanadze.",
    neon: "#00ff66",
    href: "/invention-plans",
    badge: "21+ PLANS",
  },
  {
    icon: BookOpen,
    label: "Structured Courses",
    desc: "8 modules from scalar EM fundamentals to MEG replication masterclass to bioelectromagnetics clinical data. Includes lab protocols & problem sets.",
    neon: "#ffcc00",
    href: "/courses",
    badge: "8 MODULES",
  },
  {
    icon: TrendingUp,
    label: "Bearden Concept Graph",
    desc: "Interactive 3D knowledge graph of 100+ electromagnetic devices, patent cross-references, and technology maturity scores. Navigate the field visually.",
    neon: "#00ccff",
    href: "/device-graph",
    badge: "UNIQUE",
  },
  {
    icon: FlaskConical,
    label: "Scalar Wave Lab",
    desc: "Real-time browser-based scalar wave simulator. Adjust frequency, phase, amplitude. Visualize interference patterns. Validate theoretical designs.",
    neon: "#00ff66",
    href: "/scalar-lab",
    badge: "INTERACTIVE",
  },
  {
    icon: Users,
    label: "IP Marketplace",
    desc: "Anonymous inventor & investor matching. Browse live IP deals, submit LOIs, negotiate term sheets, and close deals — ZAT takes 5% on success.",
    neon: "#ff3366",
    href: "/ip-marketplace",
    badge: "MARKETPLACE",
  },
  {
    icon: BarChart3,
    label: "FTO Analysis Engine",
    desc: "Freedom-to-operate analysis powered by AI. Prior art search, claim mapping, risk scoring, and design-around strategy generation.",
    neon: "#cc00ff",
    href: "/fto-analysis",
    badge: "PRO TOOL",
  },
  {
    icon: Cpu,
    label: "IoT Telemetry Dashboard",
    desc: "Connect your electromagnetic prototypes. Stream sensor data in real time, visualize waveforms, and set threshold alerts for your builds.",
    neon: "#00ccff",
    href: "/iot-dashboard",
    badge: "LIVE DATA",
  },
  {
    icon: Shield,
    label: "EMF Protection Shop",
    desc: "Curated EMF shielding products — grounding mats, Faraday fabric, scalar pendants, and measurement devices. All vetted for effectiveness.",
    neon: "#ff6600",
    href: "/emf-shop",
    badge: "SHOP",
  },
  {
    icon: ShoppingBag,
    label: "Build Supplies Shop",
    desc: "Pre-sourced component kits for every device in the catalogue. MEG parts kit, TRZ reactor components, scalar resonators — shipped to your door.",
    neon: "#00ff66",
    href: "/build-supplies-shop",
    badge: "KITS",
  },
];

function FeatureCard({ f }) {
  const Icon = f.icon;
  return (
    <Link
      to={f.href}
      style={{
        background: "#000",
        border: `2px solid ${f.neon}44`,
        borderRadius: "14px",
        padding: "20px",
        display: "flex",
        flexDirection: "column",
        gap: "10px",
        position: "relative",
        overflow: "hidden",
        textDecoration: "none",
        transition: "border-color 0.2s, box-shadow 0.2s, transform 0.2s",
      }}
      onMouseEnter={e => {
        e.currentTarget.style.borderColor = f.neon;
        e.currentTarget.style.boxShadow = `0 0 30px ${f.neon}44`;
        e.currentTarget.style.transform = "translateY(-2px)";
      }}
      onMouseLeave={e => {
        e.currentTarget.style.borderColor = `${f.neon}44`;
        e.currentTarget.style.boxShadow = "none";
        e.currentTarget.style.transform = "translateY(0)";
      }}
    >
      {/* Glow top line */}
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: "1px", background: `linear-gradient(90deg, transparent, ${f.neon}88, transparent)` }} />

      {/* Badge */}
      <div style={{ position: "absolute", top: "12px", right: "12px" }}>
        <span style={{
          fontSize: "8px", fontWeight: "900", padding: "2px 7px", borderRadius: "5px",
          background: `${f.neon}15`, border: `1px solid ${f.neon}`, color: f.neon,
          letterSpacing: "0.1em",
        }}>
          {f.badge}
        </span>
      </div>

      {/* Icon */}
      <div style={{
        width: "44px", height: "44px", borderRadius: "10px",
        background: `${f.neon}12`, border: `1.5px solid ${f.neon}`,
        display: "flex", alignItems: "center", justifyContent: "center",
      }}>
        <Icon size={22} style={{ color: f.neon }} />
      </div>

      <h3 style={{ color: "#fff", fontWeight: "900", fontSize: "15px", paddingRight: "60px" }}>{f.label}</h3>
      <p style={{ color: "rgba(255,255,255,0.55)", fontSize: "12px", lineHeight: "1.65" }}>{f.desc}</p>

      <span style={{ color: f.neon, fontSize: "11px", fontWeight: "900", marginTop: "4px" }}>
        Explore → 
      </span>
    </Link>
  );
}

export default function PlatformShowcase() {
  return (
    <section
      className="px-6 py-20 border-b border-white/10"
      style={{ background: "linear-gradient(180deg, #000 0%, #020208 100%)" }}
    >
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <div
            className="inline-flex items-center gap-2 px-5 py-2 rounded-full mb-5"
            style={{
              border: "2px solid #00ccff",
              background: "rgba(0,200,255,0.07)",
              boxShadow: "0 0 24px rgba(0,200,255,0.25)",
            }}
          >
            <Cpu size={13} style={{ color: "#00ccff" }} />
            <span className="text-xs font-black tracking-widest" style={{ color: "#00ccff" }}>
              FULL PLATFORM SUITE — 12 TOOLS
            </span>
          </div>
          <h2
            className="text-4xl font-black mb-4"
            style={{
              background: "linear-gradient(135deg, #00ccff, #00ff66)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            Everything an Inventor Needs.
          </h2>
          <p className="text-gray-400 text-base max-w-2xl mx-auto">
            From first spark of an idea to patent grant, investor pitch, device build, and commercialization — ZAT covers every step of the IP journey.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {FEATURES.map((f, i) => <FeatureCard key={i} f={f} />)}
        </div>
      </div>
    </section>
  );
}