import { useState } from "react";
import { ShieldAlert, Lock, Eye, FileText, AlertTriangle, CheckCircle2 } from "lucide-react";
import { base44 } from "@/api/base44Client";

const AGREEMENT_VERSION = "1.0";
const EFFECTIVE_DATE = "April 1, 2026";

export default function LegalAgreement() {
  const [checked1, setChecked1] = useState(false);
  const [checked2, setChecked2] = useState(false);
  const [checked3, setChecked3] = useState(false);

  const allChecked = checked1 && checked2 && checked3;

  const handleAccept = () => {
    if (!allChecked) return;
    const record = {
      accepted: true,
      version: AGREEMENT_VERSION,
      timestamp: new Date().toISOString(),
      userAgent: navigator.userAgent,
    };
    localStorage.setItem("bearden_nda_accepted", JSON.stringify(record));
    window.location.href = "/";
  };

  return (
    <div className="fixed inset-0 overflow-y-auto z-50" style={{backgroundColor: "#030712"}}>
    <div className="min-h-full flex flex-col items-center justify-center px-4 py-12">
      <div className="w-full max-w-3xl">

        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-4">
            <ShieldAlert className="text-red-500" size={36} />
            <Lock className="text-yellow-500" size={28} />
          </div>
          <h1 className="text-white font-bold text-3xl mb-2 tracking-tight">
            Confidentiality & Non-Disclosure Agreement
          </h1>
          <p className="text-gray-400 text-sm">
            <strong className="text-yellow-400">RESTRICTED ACCESS — READ CAREFULLY BEFORE PROCEEDING</strong>
          </p>
          <p className="text-gray-600 text-xs mt-1">Agreement Version {AGREEMENT_VERSION} · Effective {EFFECTIVE_DATE}</p>
        </div>

        {/* Agreement body */}
        <div className="bg-gray-900 border border-gray-700 rounded-2xl overflow-hidden mb-6">

          {/* Warning banner */}
          <div className="bg-red-950 border-b border-red-900 px-6 py-4 flex items-start gap-3">
            <AlertTriangle className="text-red-400 flex-shrink-0 mt-0.5" size={18} />
            <p className="text-red-300 text-sm leading-relaxed">
              <strong>THIS PLATFORM CONTAINS PROPRIETARY RESEARCH AND CLASSIFIED THEORETICAL FRAMEWORKS.</strong>{" "}
              Access is conditioned upon your full acceptance of the terms below. Unauthorized disclosure, reproduction, or AI ingestion of any content is a violation of this agreement and may result in civil and criminal liability.
            </p>
          </div>

          {/* Main agreement text */}
          <div className="px-6 py-6 space-y-6 text-gray-300 text-sm leading-relaxed overflow-y-auto max-h-[50vh]">

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">1.</span> PARTIES & SCOPE
              </h2>
              <p>
                This Confidentiality and Non-Disclosure Agreement ("Agreement") is entered into by and between the owner and operator of the Bearden Concept Network platform ("Disclosing Party") and the individual accessing this platform ("Recipient"). This Agreement governs all content, data, research frameworks, conceptual models, source text fragments, visualizations, business models, pitch materials, and any derivative works contained within or generated by this application ("Confidential Information").
              </p>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">2.</span> CONFIDENTIAL INFORMATION
              </h2>
              <p>Confidential Information includes, but is not limited to:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-gray-400">
                <li>All annotated research data relating to scalar electromagnetics and gravitobiology</li>
                <li>Original analytical frameworks, concept node structures, and relational graph data</li>
                <li>Business models, pitch deck outlines, revenue projections, and product roadmaps</li>
                <li>Source text fragments, commentary, and interpretive analysis</li>
                <li>Timeline analyses, geopolitical assessments, and technical feasibility studies</li>
                <li>Any AI-generated summaries, expansions, or derivative content produced within this platform</li>
                <li>The platform architecture, data structures, and visual design methodology</li>
              </ul>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">3.</span> OBLIGATIONS OF RECIPIENT
              </h2>
              <p>The Recipient agrees to:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-gray-400">
                <li>Hold all Confidential Information in strict confidence</li>
                <li>Not copy, screenshot, reproduce, publish, share, transmit, or distribute any content from this platform in whole or in part</li>
                <li>Not use any Confidential Information for commercial purposes without express written consent</li>
                <li>Not share access credentials or grant third-party access to this platform</li>
                <li>Not input, upload, or transmit any Confidential Information into any artificial intelligence system, machine learning model, large language model, or automated data extraction tool</li>
                <li>Immediately notify the Disclosing Party of any unauthorized disclosure or suspected breach</li>
                <li>Return or destroy all Confidential Information upon termination of access</li>
              </ul>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">4.</span> PROHIBITION ON AI INGESTION & AUTOMATED SCRAPING
              </h2>
              <div className="bg-red-950/40 border border-red-900/50 rounded-lg p-4">
                <p className="text-red-300 font-semibold mb-2">⚠ STRICT PROHIBITION</p>
                <p>The Recipient expressly agrees that no content from this platform shall be:</p>
                <ul className="list-disc list-inside space-y-1 mt-2 text-gray-400">
                  <li>Input into any AI or LLM system (including but not limited to ChatGPT, Claude, Gemini, Copilot, or any proprietary model) for training, fine-tuning, summarization, or analysis beyond personal use</li>
                  <li>Scraped, crawled, or harvested by any automated bot, spider, or data mining tool</li>
                  <li>Used to create competing datasets, knowledge graphs, or derivative analytical platforms</li>
                  <li>Transmitted to any third-party AI service, API, or data broker</li>
                </ul>
                <p className="text-red-400 text-xs mt-3 font-semibold">
                  Violation of this section constitutes unauthorized access under the Computer Fraud and Abuse Act (18 U.S.C. § 1030) and similar international statutes.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">5.</span> INTELLECTUAL PROPERTY
              </h2>
              <p>
                All platform-original content — including but not limited to organizational frameworks, analytical commentary, concept graphs, business models, and AI-generated synthesis — is the exclusive intellectual property of the Disclosing Party. Access to this platform grants no license, ownership right, or interest in any Confidential Information. The underlying research of Lt. Col. Thomas E. Bearden is used under scholarly fair use principles for archival and analytical purposes.
              </p>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">6.</span> MONITORING & ENFORCEMENT
              </h2>
              <p>
                The Disclosing Party reserves the right to monitor access patterns, audit usage logs, and employ technical measures to detect unauthorized copying, scraping, or data exfiltration. Access timestamps, user agent strings, and behavioral fingerprints may be recorded for security purposes. The Disclosing Party may terminate access at any time without notice upon suspected violation.
              </p>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">7.</span> REMEDIES & LIQUIDATED DAMAGES
              </h2>
              <p>
                The Recipient acknowledges that any breach of this Agreement would cause irreparable harm for which monetary damages would be inadequate. The Disclosing Party shall be entitled to seek injunctive relief, specific performance, and any other equitable or legal remedy. In addition to actual damages, Recipient agrees to pay liquidated damages of <strong className="text-white">$50,000 USD per incident</strong> of unauthorized disclosure or distribution, and <strong className="text-white">$250,000 USD per incident</strong> of unauthorized AI ingestion or commercial exploitation.
              </p>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">8.</span> TERM & SURVIVAL
              </h2>
              <p>
                This Agreement is effective upon first access to the platform and remains in effect indefinitely. The confidentiality obligations survive any termination of access. This Agreement shall be governed by the laws of the United States of America.
              </p>
            </section>

            <section>
              <h2 className="text-white font-bold text-base mb-2 flex items-center gap-2">
                <span className="text-yellow-400">9.</span> ENTIRE AGREEMENT
              </h2>
              <p>
                This Agreement constitutes the entire understanding between the parties regarding confidentiality of the platform's content and supersedes all prior discussions. By clicking "I Agree" below, the Recipient represents that they have read, understood, and agree to be legally bound by all terms of this Agreement. Electronic acceptance constitutes a valid and binding signature under the Electronic Signatures in Global and National Commerce Act (E-SIGN).
              </p>
            </section>

          </div>
        </div>

        {/* Checkboxes */}
        <div className="bg-gray-900 border border-gray-700 rounded-xl p-5 mb-5 space-y-4">
          <p className="text-gray-400 text-xs uppercase tracking-widest font-semibold mb-3 flex items-center gap-2">
            <Eye size={13} /> Required Acknowledgements
          </p>

          {[
            {
              id: "c1", checked: checked1, setChecked: setChecked1,
              text: "I have read and fully understand this Confidentiality & Non-Disclosure Agreement, and I agree to be legally bound by its terms."
            },
            {
              id: "c2", checked: checked2, setChecked: setChecked2,
              text: "I will NOT copy, screenshot, reproduce, share, publish, or distribute any content from this platform, and I will NOT input any content into any AI system for training or analysis."
            },
            {
              id: "c3", checked: checked3, setChecked: setChecked3,
              text: "I understand that violations of this agreement may result in civil liability including liquidated damages up to $250,000 per incident, and potential criminal prosecution."
            },
          ].map(({ id, checked, setChecked, text }) => (
            <label key={id} className="flex items-start gap-3 cursor-pointer group">
              <div
                onClick={() => setChecked(c => !c)}
                className={`w-5 h-5 rounded border-2 flex-shrink-0 flex items-center justify-center mt-0.5 transition-colors ${
                  checked ? "bg-green-600 border-green-500" : "bg-gray-800 border-gray-600 group-hover:border-gray-400"
                }`}
              >
                {checked && <CheckCircle2 size={13} className="text-white" />}
              </div>
              <span className="text-gray-300 text-sm leading-relaxed">{text}</span>
            </label>
          ))}
        </div>

        {/* Accept button */}
        <div className="flex flex-col items-center gap-3">
          <button
            onClick={handleAccept}
            disabled={!allChecked}
            className={`w-full py-4 rounded-xl font-bold text-base transition-all ${
              allChecked
                ? "bg-green-700 hover:bg-green-600 text-white shadow-lg shadow-green-900/40"
                : "bg-gray-800 text-gray-600 cursor-not-allowed"
            }`}
          >
            {allChecked ? "✓ I Accept — Enter Platform" : "Check all boxes above to continue"}
          </button>
          <p className="text-gray-600 text-xs text-center">
            Your acceptance is timestamped and recorded. By proceeding you confirm you are at least 18 years old and have authority to enter this agreement.
          </p>
          <button
            onClick={() => base44.auth.redirectToLogin(window.location.href)}
            className="text-yellow-600 hover:text-yellow-400 text-xs underline transition-colors mt-1"
          >
            🔐 Admin? Sign in here to bypass this agreement
          </button>
        </div>

      </div>
    </div>
    </div>
  );
}