import { useState } from "react";
import { Shield, Lock, Eye, AlertTriangle, CheckCircle2, ShieldCheck, Fingerprint, ChevronRight } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { startTrialPass } from "@/hooks/useTrialPass";

const AGREEMENT_VERSION = "1.0";
const EFFECTIVE_DATE = "April 1, 2026";

const SECTIONS = [
  {
    num: "01",
    title: "Parties & Scope",
    content: "This Confidentiality and Non-Disclosure Agreement ('Agreement') is entered into by and between the owner and operator of the Zenith Apex Research Platform ('Disclosing Party') and the individual accessing this platform ('Recipient'). This Agreement governs all content, data, research frameworks, conceptual models, source text fragments, visualizations, business models, pitch materials, and any derivative works contained within or generated by this application ('Confidential Information').",
  },
  {
    num: "02",
    title: "Confidential Information",
    bullets: [
      "All annotated research data relating to scalar electromagnetics and gravitobiology",
      "Original analytical frameworks, concept node structures, and relational graph data",
      "Business models, pitch deck outlines, revenue projections, and product roadmaps",
      "Source text fragments, commentary, and interpretive analysis",
      "Timeline analyses, geopolitical assessments, and technical feasibility studies",
      "Any AI-generated summaries, expansions, or derivative content produced within this platform",
      "The platform architecture, data structures, and visual design methodology",
    ],
  },
  {
    num: "03",
    title: "Obligations of Recipient",
    bullets: [
      "Hold all Confidential Information in strict confidence",
      "Not copy, screenshot, reproduce, publish, share, transmit, or distribute any content from this platform in whole or in part",
      "Not use any Confidential Information for commercial purposes without express written consent",
      "Not share access credentials or grant third-party access to this platform",
      "Not input, upload, or transmit any Confidential Information into any AI system, machine learning model, LLM, or automated data extraction tool",
      "Immediately notify the Disclosing Party of any unauthorized disclosure or suspected breach",
      "Return or destroy all Confidential Information upon termination of access",
    ],
  },
  {
    num: "04",
    title: "Prohibition on AI Ingestion & Automated Scraping",
    alert: true,
    bullets: [
      "Input into any AI or LLM system (including ChatGPT, Claude, Gemini, Copilot, or any proprietary model) for training, fine-tuning, or analysis beyond personal use",
      "Scraped, crawled, or harvested by any automated bot, spider, or data mining tool",
      "Used to create competing datasets, knowledge graphs, or derivative analytical platforms",
      "Transmitted to any third-party AI service, API, or data broker",
    ],
    footer: "Violation constitutes unauthorized access under the Computer Fraud and Abuse Act (18 U.S.C. § 1030) and similar international statutes.",
  },
  {
    num: "05",
    title: "Intellectual Property",
    content: "All platform-original content, including organizational frameworks, analytical commentary, concept graphs, business models, and AI-generated synthesis, is the exclusive intellectual property of the Disclosing Party. Access grants no license, ownership right, or interest in any Confidential Information. The underlying research of Lt. Col. Thomas E. Bearden is used under scholarly fair use principles for archival and analytical purposes.",
  },
  {
    num: "06",
    title: "Monitoring & Enforcement",
    content: "The Disclosing Party reserves the right to monitor access patterns, audit usage logs, and employ technical measures to detect unauthorized copying, scraping, or data exfiltration. Access timestamps, user agent strings, and behavioral fingerprints may be recorded for security purposes. Access may be terminated at any time without notice upon suspected violation.",
  },
  {
    num: "07",
    title: "Remedies & Liquidated Damages",
    content: null,
    damages: true,
  },
  {
    num: "08",
    title: "Term & Survival",
    content: "This Agreement is effective upon first access to the platform and remains in effect indefinitely. The confidentiality obligations survive any termination of access. This Agreement shall be governed by the laws of the United States of America.",
  },
  {
    num: "09",
    title: "Entire Agreement",
    content: "This Agreement constitutes the entire understanding between the parties regarding confidentiality and supersedes all prior discussions. By proceeding, the Recipient represents that they have read, understood, and agree to be legally bound by all terms. Electronic acceptance constitutes a valid and binding signature under the Electronic Signatures in Global and National Commerce Act (E-SIGN).",
  },
];

function SectionBlock({ s }) {
  return (
    <div className="border-b border-slate-700/50 pb-5 last:border-0 last:pb-0">
      <div className="flex items-start gap-4">
        <span className="text-cyan-500 font-mono text-xs font-bold mt-0.5 flex-shrink-0 w-6">{s.num}</span>
        <div className="flex-1 min-w-0">
          <h3 className="text-white font-semibold text-sm mb-2">{s.title}</h3>

          {s.alert && (
            <div className="mb-3 flex items-start gap-2 bg-red-950/40 border border-red-700/50 rounded-lg px-3 py-2">
              <AlertTriangle size={12} className="text-red-400 flex-shrink-0 mt-0.5" />
              <p className="text-red-300 text-xs font-semibold">No content from this platform shall be:</p>
            </div>
          )}

          {s.content && (
            <p className="text-slate-400 text-xs leading-relaxed">{s.content}</p>
          )}

          {s.bullets && (
            <ul className="space-y-1.5">
              {s.bullets.map((b, i) => (
                <li key={i} className="flex items-start gap-2">
                  <ChevronRight size={11} className="text-cyan-600 flex-shrink-0 mt-0.5" />
                  <span className="text-slate-400 text-xs leading-relaxed">{b}</span>
                </li>
              ))}
            </ul>
          )}

          {s.footer && (
            <p className="mt-3 text-red-400 text-xs font-semibold">{s.footer}</p>
          )}

          {s.damages && (
            <div className="grid grid-cols-2 gap-3">
              <div className="bg-slate-800/60 border border-slate-600/40 rounded-xl p-4 text-center">
                <p className="text-white font-black text-lg">$50,000</p>
                <p className="text-slate-400 text-xs mt-1">per incident of unauthorized disclosure or distribution</p>
              </div>
              <div className="bg-slate-800/60 border border-red-700/30 rounded-xl p-4 text-center">
                <p className="text-red-300 font-black text-lg">$250,000</p>
                <p className="text-slate-400 text-xs mt-1">per incident of unauthorized AI ingestion or commercial exploitation</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function LegalAgreement() {
  const [checked1, setChecked1] = useState(false);
  const [checked2, setChecked2] = useState(false);
  const [checked3, setChecked3] = useState(false);

  const allChecked = checked1 && checked2 && checked3;
  const checkedCount = [checked1, checked2, checked3].filter(Boolean).length;

  const handleAccept = () => {
    if (!allChecked) return;
    const record = {
      accepted: true,
      version: AGREEMENT_VERSION,
      timestamp: new Date().toISOString(),
      userAgent: navigator.userAgent,
    };
    localStorage.setItem("bearden_nda_accepted", JSON.stringify(record));
    // Start 24-hour trial pass
    startTrialPass();
    window.location.href = "/";
  };

  return (
    <div
      className="fixed inset-0 overflow-y-auto"
      style={{ backgroundColor: "#0F172A", fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', system-ui, sans-serif" }}
    >
      {/* Subtle grid background */}
      <div
        className="fixed inset-0 pointer-events-none"
        style={{
          backgroundImage: "linear-gradient(rgba(14,165,233,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(14,165,233,0.03) 1px, transparent 1px)",
          backgroundSize: "40px 40px",
        }}
      />

      <div className="relative min-h-full flex flex-col items-center justify-start px-4 py-10">
        <div className="w-full max-w-4xl">

          {/* Top status bar */}
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse" />
              <span className="text-cyan-400 text-xs font-mono font-bold tracking-widest uppercase">Secure Connection Established</span>
            </div>
            <div className="text-slate-500 text-xs font-mono">TLS 1.3 · AES-256 · ZARP-NDA-{AGREEMENT_VERSION}</div>
          </div>

          {/* Header card */}
          <div
            className="rounded-2xl border mb-6 overflow-hidden"
            style={{ background: "linear-gradient(135deg, #1E293B 0%, #162032 100%)", borderColor: "#334155" }}
          >
            {/* Accent top stripe */}
            <div style={{ background: "linear-gradient(90deg, #0EA5E9, #10B981)", height: 3 }} />

            <div className="px-8 py-7 flex items-start gap-6">
              {/* Icon cluster */}
              <div className="flex-shrink-0">
                <div
                  className="w-16 h-16 rounded-2xl flex items-center justify-center"
                  style={{ background: "linear-gradient(135deg, rgba(14,165,233,0.15), rgba(16,185,129,0.1))", border: "1px solid rgba(14,165,233,0.3)" }}
                >
                  <ShieldCheck size={28} className="text-cyan-400" />
                </div>
              </div>

              <div className="flex-1">
                <div className="flex items-center gap-3 mb-1 flex-wrap">
                  <span
                    className="text-xs font-mono font-bold px-2 py-0.5 rounded tracking-widest"
                    style={{ background: "rgba(14,165,233,0.1)", color: "#0EA5E9", border: "1px solid rgba(14,165,233,0.2)" }}
                  >
                    RESTRICTED ACCESS
                  </span>
                  <span className="text-slate-500 text-xs font-mono">v{AGREEMENT_VERSION} · {EFFECTIVE_DATE}</span>
                </div>
                <h1 className="text-white font-bold text-2xl leading-tight mb-1">
                  Non-Disclosure Agreement
                </h1>
                <p className="text-slate-400 text-sm">
                  Zenith Apex Research Platform · Confidentiality & Access Control Agreement
                </p>
              </div>

              <div className="flex-shrink-0 text-right hidden md:block">
                <Fingerprint size={20} className="text-slate-600 mb-1 ml-auto" />
                <p className="text-slate-600 text-xs font-mono">Identity<br/>Verification</p>
              </div>
            </div>

            {/* Warning strip */}
            <div
              className="px-8 py-3 flex items-center gap-3"
              style={{ background: "rgba(239,68,68,0.08)", borderTop: "1px solid rgba(239,68,68,0.2)" }}
            >
              <AlertTriangle size={14} className="text-red-400 flex-shrink-0" />
              <p className="text-red-300 text-xs leading-relaxed">
                <strong className="text-red-200">LEGAL NOTICE:</strong> This platform contains proprietary research and classified theoretical frameworks. Unauthorized disclosure, reproduction, or AI ingestion of any content constitutes a violation of this agreement and applicable federal law.
              </p>
            </div>
          </div>

          {/* Main content — 2 column layout */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">

            {/* Left: Agreement text (2/3) */}
            <div
              className="lg:col-span-2 rounded-2xl border overflow-hidden"
              style={{ background: "#1E293B", borderColor: "#334155" }}
            >
              <div
                className="px-6 py-3 flex items-center justify-between"
                style={{ borderBottom: "1px solid #334155", background: "#162032" }}
              >
                <div className="flex items-center gap-2">
                  <Eye size={13} className="text-cyan-500" />
                  <span className="text-white text-xs font-semibold">Agreement Terms</span>
                </div>
                <span className="text-slate-500 text-xs font-mono">9 sections</span>
              </div>

              <div className="px-6 py-5 space-y-5 overflow-y-auto" style={{ maxHeight: "55vh" }}>
                {SECTIONS.map(s => <SectionBlock key={s.num} s={s} />)}
              </div>
            </div>

            {/* Right: Progress + Acknowledgements (1/3) */}
            <div className="flex flex-col gap-4">

              {/* Access level card */}
              <div
                className="rounded-2xl border p-5"
                style={{ background: "#1E293B", borderColor: "#334155" }}
              >
                <p className="text-slate-400 text-xs font-semibold uppercase tracking-widest mb-4">Access Level</p>
                <div className="space-y-2">
                  {[
                    { label: "Research Access", color: "#10B981", active: true },
                    { label: "IP & Patents", color: "#0EA5E9", active: true },
                    { label: "Classified Frameworks", color: "#F59E0B", active: true },
                    { label: "Defense Applications", color: "#EF4444", active: false },
                  ].map((item, i) => (
                    <div key={i} className="flex items-center justify-between">
                      <span className="text-slate-300 text-xs">{item.label}</span>
                      <div className="flex items-center gap-1.5">
                        <div
                          className="w-1.5 h-1.5 rounded-full"
                          style={{ background: item.active ? item.color : "#334155" }}
                        />
                        <span className="text-xs font-mono" style={{ color: item.active ? item.color : "#475569" }}>
                          {item.active ? "GRANTED" : "RESTRICTED"}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Acceptance progress */}
              <div
                className="rounded-2xl border p-5"
                style={{ background: "#1E293B", borderColor: "#334155" }}
              >
                <div className="flex items-center justify-between mb-3">
                  <p className="text-slate-400 text-xs font-semibold uppercase tracking-widest">Authorization</p>
                  <span className="text-cyan-400 font-mono text-xs font-bold">{checkedCount}/3</span>
                </div>

                {/* Progress bar */}
                <div className="h-1.5 bg-slate-700 rounded-full mb-5 overflow-hidden">
                  <div
                    className="h-full rounded-full transition-all duration-500"
                    style={{
                      width: `${(checkedCount / 3) * 100}%`,
                      background: allChecked ? "linear-gradient(90deg, #0EA5E9, #10B981)" : "linear-gradient(90deg, #0EA5E9, #06B6D4)"
                    }}
                  />
                </div>

                <div className="space-y-3">
                  {[
                    { checked: checked1, setChecked: setChecked1, text: "I have read and fully understand this NDA and agree to be legally bound by its terms." },
                    { checked: checked2, setChecked: setChecked2, text: "I will NOT copy, share, or input any content into any AI system for training or analysis." },
                    { checked: checked3, setChecked: setChecked3, text: "I understand violations may result in liquidated damages up to $250,000 per incident." },
                  ].map(({ checked, setChecked, text }, i) => (
                    <label key={i} className="flex items-start gap-3 cursor-pointer group">
                      <div
                        onClick={() => setChecked(c => !c)}
                        className="w-5 h-5 rounded flex-shrink-0 flex items-center justify-center mt-0.5 transition-all"
                        style={{
                          background: checked ? "linear-gradient(135deg, #0EA5E9, #10B981)" : "transparent",
                          border: checked ? "none" : "1px solid #475569",
                        }}
                      >
                        {checked && <CheckCircle2 size={13} className="text-white" />}
                      </div>
                      <span className="text-slate-300 text-xs leading-relaxed">{text}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Accept button */}
              <button
                onClick={handleAccept}
                disabled={!allChecked}
                className="w-full py-4 rounded-2xl font-bold text-sm transition-all flex items-center justify-center gap-2"
                style={{
                  background: allChecked
                    ? "linear-gradient(135deg, #0EA5E9, #10B981)"
                    : "#1E293B",
                  color: allChecked ? "#fff" : "#475569",
                  border: allChecked ? "none" : "1px solid #334155",
                  boxShadow: allChecked ? "0 4px 24px rgba(14,165,233,0.3)" : "none",
                  cursor: allChecked ? "pointer" : "not-allowed",
                }}
              >
                <Lock size={15} />
                {allChecked ? "Authorize Access — Enter Platform" : "Complete all acknowledgements"}
              </button>

              <p className="text-slate-600 text-xs text-center leading-relaxed px-2">
                Your acceptance is timestamped and recorded. By proceeding you confirm you are at least 18 years old and have authority to enter this agreement.
              </p>

              <button
                onClick={() => base44.auth.redirectToLogin(window.location.href)}
                className="text-slate-500 hover:text-cyan-400 text-xs text-center transition-colors flex items-center justify-center gap-1.5"
              >
                <Fingerprint size={12} />
                Admin biometric sign-in
              </button>
            </div>
          </div>

          {/* Footer */}
          <div className="flex items-center justify-between text-slate-600 text-xs font-mono pb-4">
            <span>ZARP-NDA-v{AGREEMENT_VERSION} · E-SIGN Act Compliant · Governed by U.S. Federal Law</span>
            <span>{EFFECTIVE_DATE}</span>
          </div>

        </div>
      </div>
    </div>
  );
}