import { AlertTriangle } from "lucide-react";

export default function ExportLegalFooter() {
  return (
    <div className="mt-8 rounded-xl border border-amber-900/40 bg-amber-950/10 px-5 py-4">
      <div className="flex items-start gap-3">
        <AlertTriangle size={14} className="text-amber-400 flex-shrink-0 mt-0.5" />
        <p className="text-amber-200/60 text-[11px] leading-relaxed">
          <span className="font-bold text-amber-300">Disclaimer:</span> Documents generated by the ZARP Export Center are for IP development, investor communication, and research purposes only. They do not constitute medical advice, legal advice, securities offerings, or final product designs. All device-related content is conceptual and subject to manufacturer validation. All IP documentation is for attorney review only.
          <br className="mt-1" />
          <span className="text-amber-200/40">© 2026 Aethon Apex IP Holdings LLC — Henderson, NV 89002.</span>
        </p>
      </div>
    </div>
  );
}