import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { node, aiSummary } = await req.json();
    if (!node) return Response.json({ error: 'No node data provided' }, { status: 400 });

    const { accessToken } = await base44.asServiceRole.connectors.getConnection("googledocs");

    const title = `Research Summary: ${node.label}`;

    // Create the document
    const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ title }),
    });
    const doc = await createRes.json();
    if (!doc.documentId) {
      console.error("Doc creation failed:", JSON.stringify(doc));
      return Response.json({ error: 'Failed to create document' }, { status: 500 });
    }

    const docId = doc.documentId;

    // Build the document content as batchUpdate requests
    const fragmentsText = node.fragments.map((f, i) => `Fragment ${i + 1}:\n"${f}"`).join('\n\n');

    const bodyText = [
      title,
      '\n',
      `Category: ${node.group}`,
      `Generated: ${new Date().toUTCString()}`,
      '\n',
      'DESCRIPTION',
      node.description,
      '\n',
      ...(aiSummary ? ['AI SYNTHESIS', aiSummary, '\n'] : []),
      'SOURCE FRAGMENTS',
      fragmentsText,
      '\n',
      '---',
      'Generated by Bearden Concept Network',
    ].join('\n');

    // Insert text at end of document
    await fetch(`https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: bodyText,
            },
          },
        ],
      }),
    });

    const docUrl = `https://docs.google.com/document/d/${docId}/edit`;
    console.log("Doc created:", docUrl);
    return Response.json({ url: docUrl, title });
  } catch (error) {
    console.error("generateResearchDoc error:", error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
});